.changeset/wet-clouds-exist.md
packages/generator/generators/base-generator/modern.config.js
packages/generator/generators/bff-generator/modern.config.js
packages/generator/generators/changeset-generator/modern.config.js
packages/generator/generators/dependence-generator/modern.config.js
packages/generator/generators/entry-generator/modern.config.js
packages/generator/generators/eslint-generator/modern.config.js
packages/generator/generators/generator-generator/modern.config.js
packages/generator/generators/generator-generator/templates/js-template/modern.config.js.handlebars
packages/generator/generators/generator-generator/templates/ts-template/modern.config.ts.handlebars
packages/generator/generators/module-generator/modern.config.js
packages/generator/generators/monorepo-generator/modern.config.js
packages/generator/generators/mwa-generator/modern.config.js
packages/generator/generators/repo-generator/modern.config.js
packages/generator/generators/router-legacy-generator/modern.config.js
packages/generator/generators/server-generator/modern.config.js
packages/generator/generators/ssg-generator/modern.config.js
packages/generator/generators/storybook-generator/modern.config.js
packages/generator/generators/tailwindcss-generator/modern.config.js
packages/generator/generators/test-generator/modern.config.js
packages/generator/generators/upgrade-generator/modern.config.js
packages/generator/plugins/generator-plugin/modern.config.js
packages/generator/plugins/generator-plugin/src/index.ts
packages/toolkit/create/modern.config.js
packages/toolkit/upgrade/modern.config.js

fix: generator bundle

---

.changeset/big-cherries-kiss.md
packages/builder/builder-webpack-provider/src/plugins/fileSize.ts
packages/solutions/app-tools/src/commands/build.ts
packages/solutions/app-tools/src/commands/dev.ts
packages/solutions/app-tools/src/utils/createCompiler.ts
packages/solutions/app-tools/src/utils/printInstructions.ts

Improve build logs of dev and build command.
Dev:
Build:

feat(app-tools): improve build logs of dev and build command

---

.changeset/fast-timers-double.md
packages/solutions/app-tools/src/builder/createToolsConfig.ts

fix: repeat register `babel-plugin-lodash`

fix: repeat register babel-plugin-lodash

---

.changeset/clean-humans-turn.md
packages/runtime/plugin-garfish/src/runtime/plugin.tsx
packages/runtime/plugin-garfish/src/runtime/utils/MApp.tsx

fix(garfish): fix reRender issue when use apps and Garfish.run with activeWhen parameter
provide active and deactive methods to avoid auto render <img width="526" alt="image" src="https://user-images.githubusercontent.com/65393845/199921439-ff553539-9c16-450b-852c-bf79c09f84bf.png">

fix(garfish): fix reRender issue when use apps and Garfish.run with activeWhen parameter

---

.changeset/lazy-numbers-knock.md
packages/builder/builder-webpack-provider/package.json

Fix incorrect ModuleFilenameHelpers path

fix(builder): incorrect ModuleFilenameHelpers path

---

.changeset/twelve-toes-walk.md
packages/solutions/app-tools/src/builder/builderPlugins/compatModern.ts
tests/e2e/webpack-builder/inspect-config/package.json
tests/integration/ssg/fixtures/simple/package.json
tests/integration/ssg/fixtures/web-server/package.json

Compat legacy resolve behavior, resolve package from `<appDirectory>/node_modules/`.

fix(app-tools): compat legacy resolve behavior

---

tests/integration/alias-set/test/index.test.js
tests/integration/runtime/test/index.test.js
tests/integration/runtime/test/router-legacy.test.js
tests/integration/ssr/test/index.test.js
tests/jest-puppeteer.config.js
tests/utils/setup.js

fix: puppeteer params

---

.changeset/fluffy-peaches-speak.md
packages/solutions/app-tools/src/builder/index.ts
tests/integration/css-modules/test/index.test.js
tests/integration/css/test/css.test.js
tests/utils/modernTestUtils.js

fix: add framework tag & fix css integration test

---

.changeset/dirty-tigers-unite.md
packages/cli/plugin-bff/src/cli.ts
packages/cli/plugin-bff/tests/cli.test.ts
packages/toolkit/utils/src/chainId.ts

fix: bff api loader should run before babel loader

---

.changeset/young-papayas-retire.md
packages/generator/generator-common/src/common/solution.ts
packages/generator/generators/module-generator/src/index.ts
packages/generator/generators/monorepo-generator/package.json
packages/generator/generators/monorepo-generator/src/index.ts
packages/generator/generators/mwa-generator/package.json
packages/generator/generators/mwa-generator/src/index.ts
packages/generator/generators/packages-generator/.eslintrc.js
packages/generator/generators/packages-generator/README.md
packages/generator/generators/packages-generator/modern.config.js
packages/generator/generators/packages-generator/package.json
packages/generator/generators/packages-generator/src/index.ts
packages/generator/generators/packages-generator/src/modern-app-env.d.ts
packages/generator/generators/packages-generator/tsconfig.json
packages/toolkit/create/src/createAction.ts
packages/toolkit/create/src/index.ts
packages/toolkit/create/src/locale/en.ts
packages/toolkit/create/src/locale/zh.ts
pnpm-lock.yaml
tests/generator/.eslintrc.js
tests/generator/module.ts
tests/generator/monorepo.ts
tests/generator/mwa.ts
tests/generator/utils/command.ts
tests/generator/utils/prepare.ts
tests/generator/utils/tools.ts
tests/package.json

feat: add generator test

---

tests/integration/css-modules/test/index.test.js

暂时忽略掉  css module composes 测试 case .

fix: ignore the css module composes test case

---

.changeset/dry-glasses-burn.md
packages/builder/builder-doc/en/config/tools/minifyCss.md
packages/builder/builder-doc/zh/config/tools/minifyCss.md
packages/builder/builder-webpack-provider/src/plugins/css.ts
packages/builder/builder-webpack-provider/src/plugins/minimize.ts
packages/builder/builder-webpack-provider/src/types/thirdParty/index.ts
packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/minimize.test.ts.snap

Disable mergeLonghand option of cssnano, see https://github.com/cssnano/cssnano/issues/803 https://github.com/cssnano/cssnano/issues/967

fix(builder): disable mergeLonghand option of cssnano

---

website/builder/src/en/guide/faq/exceptions.md
website/builder/src/zh/guide/faq/exceptions.md

docs: add compile TypeError into FAQ

---

tests/integration/garfish/dashboard/src/App.tsx
tests/integration/garfish/dashboard/src/modern-app-env.d.ts
tests/integration/garfish/main/src/App.tsx
tests/integration/garfish/main/src/modern-app-env.d.ts
tests/integration/garfish/table/src/App.tsx
tests/integration/garfish/table/src/modern-app-env.d.ts
tests/package.json

fix(garfish-next): fix e2e test

---

tests/integration/routes/modern.config.ts

test: disable ssr for routes case

---

packages/runtime/plugin-runtime/package.json
packages/runtime/plugin-testing/package.json

fix:  react version in peerDependencies

---

tests/integration/module-tools/test/build-bundleless.test.js

chore: skip module-tools test

---

tests/integration/css/test/css.test.js

fix: skip css test

---

packages/solutions/app-tools/src/commands/dev.ts
packages/solutions/app-tools/src/utils/createCompiler.ts
tests/integration/module-tools/test/build-bundleless.test.js
tests/integration/ssg/test/index.test.js

fix: print log after build success

---

.changeset/shaggy-days-count.md
packages/builder/builder-webpack-provider/src/core/build.ts
packages/builder/builder-webpack-provider/src/types/hooks.ts
packages/solutions/app-tools/src/commands/build.ts
packages/solutions/app-tools/src/hooks.ts
packages/solutions/app-tools/src/utils/createCompiler.ts

> localtion: packages/builder/builder-webpack-provider/src/types/hooks.ts  line: 32 
- before
- after

feat(builder): add builderConfigs params for beforeBuild hook

---

.changeset/loud-doors-happen.md
packages/toolkit/compiler/style/src/resolves/sass.ts

fix: add missing 'file' field

---

packages/runtime/plugin-testing/src/cli/index.ts

fix: add test alias

---

.changeset/two-jars-act.md
packages/solutions/app-tools/src/builder/builderPlugins/compatModern.ts

fix: builder 插件在 setup 阶段无法拿到 config

fix: builder config init order error

---

packages/builder/builder-doc/zh/config/performance/bundleAnalyze.md
website/builder/src/.vuepress/config.ts
website/builder/src/en/guide/advanced/build-performance.md
website/builder/src/zh/guide/advanced/build-performance.md

Add improve build performance chapter.
TODO: add plugin-swc/plugin-esbuild links.

docs(Builder): add improve build performance chapter

---

tests/integration/server-prod/test/index.test.js

fix: builder copy config/icon.png to dist/media/icon.png

---

packages/runtime/plugin-testing/src/cli/index.ts

fix: testing error

---

.changeset/giant-cups-wink.md
packages/generator/generators/mwa-generator/templates/base-template/package.json.handlebars

fix: mwa generator remove build in prepare command

---

packages/cli/plugin-ssg/package.json
pnpm-lock.yaml

fix: ssg plugin react-router-dom dependence

---

.changeset/fast-files-relax.md
packages/builder/plugin-swc/src/plugin.ts
packages/builder/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
packages/builder/plugin-swc/tests/fixtures/browserslist/chrome104/expected.js
packages/builder/plugin-swc/tests/fixtures/browserslist/ie11/expected.js
packages/builder/plugin-swc/tests/fixtures/compat/cjs-no-preserve-dyn-import/expected.js
packages/builder/plugin-swc/tests/fixtures/compat/cjs-preserve-dyn-import/expected.js
packages/builder/plugin-swc/tests/fixtures/polyfill/ie_11_entry/expected.js
packages/builder/plugin-swc/tests/fixtures/polyfill/ie_11_entry_exclude/expected.js
pnpm-lock.yaml

fix(builder-plugin-swc): fix minify plugin includes css

---

.github/workflows/build-main-website.yml

fix: change output path to /build

---

website/main/docusaurus.config.js

feat: next website add v2 prefix

---

.github/workflows/build-main-website.yml

chore: add v2/** to clean exclude

---

.changeset/plenty-crabs-look.md
packages/server/utils/package.json
pnpm-lock.yaml

Fix incorrect babel-compiler version.

fix(server-utils): incorrect babel-compiler version

---

.changeset/purple-gorillas-notice.md
packages/builder/builder-doc/en/config/tools/webpack.md
packages/builder/builder-doc/en/config/tools/webpackChain.md
packages/builder/builder-doc/zh/config/tools/webpack.md
packages/builder/builder-doc/zh/config/tools/webpackChain.md
packages/builder/builder-webpack-provider/src/core/webpackConfig.ts
packages/builder/builder-webpack-provider/src/plugins/css.ts
packages/builder/builder-webpack-provider/src/plugins/hmr.ts
packages/builder/builder-webpack-provider/src/types/config/tools.ts
packages/builder/builder-webpack-provider/src/types/hooks.ts
packages/builder/builder-webpack-provider/tests/__snapshots__/webpackConfig.test.ts.snap
packages/builder/builder-webpack-provider/tests/webpackConfig.test.ts
packages/cli/core/src/config/types/index.ts
packages/cli/webpack/src/config/base.ts
packages/solutions/app-tools/src/builder/createToolsConfig.ts
packages/solutions/app-tools/tests/builder/createToolsConfig.test.ts

Complete utils of tools.webpack, add following methods or properties:
- addRules
- appendPlugins
- prependPlugins
- removePlugin
- HtmlWebpackPlugin
- name (marked as deprecated)

feat(builder): complete utils of tools.webpack

---

.changeset/twelve-trainers-know.md
packages/server/server/src/server/dev-server.ts

chore: dev server default cross origin

---

packages/generator/generator-utils/src/index.ts
packages/generator/generators/bff-generator/src/index.ts
packages/generator/generators/module-generator/src/index.ts
packages/generator/generators/monorepo-generator/src/index.ts
packages/generator/generators/mwa-generator/src/index.ts
packages/generator/generators/server-generator/src/index.ts
packages/generator/generators/storybook-generator/src/index.ts
packages/generator/generators/upgrade-generator/src/index.ts
packages/generator/new-action/src/module.ts
packages/generator/new-action/src/mwa.ts

feat: generator support distTag params

---

website/builder/src/.vuepress/config.ts
website/builder/src/en/guide/basic/alias.md
website/builder/src/zh/guide/basic/alias.md

chore: add alias doc

---

.github/workflows/release-pull-request.yml
.github/workflows/release.yml

feat: support release v1 tag

---

.github/workflows/release-pull-request.yml
.github/workflows/release.yml

feat: support release beta

---

packages/generator/generators/base-generator/src/index.ts
packages/generator/generators/module-generator/src/index.ts
packages/generator/generators/monorepo-generator/src/index.ts
packages/generator/generators/mwa-generator/src/index.ts

fix: generator compile error

---

.changeset/wudong-devserver-fix.md
packages/toolkit/utils/src/is/index.ts

fix(dev-server): isDepsExists add non pkgPath judege

---

.changeset/nervous-buttons-serve.md
packages/solutions/module-tools/package.json
pnpm-lock.yaml

fix(module-tools): update speedy-core version to fix sass resolve error

---

.changeset/odd-months-drop.md
packages/solutions/app-tools/src/builder/builderPlugins/compatModern.ts
packages/solutions/app-tools/src/builder/webpackPlugins/htmlAsyncChunkPlugin.ts
packages/toolkit/utils/src/chainId.ts

Defer JS chunks cannot be used with Streaming SSR, since it would break the selective hydration. This PR applies async JS chunks when running in Streaming SSR mode. 
Refer to: https://github.com/reactwg/react-18/discussions/114

feat: inject async js chunk in Streaming SSR

---

website/builder/src/.vuepress/config.ts
website/builder/src/en/guide/basic/builder-config.md
website/builder/src/zh/api/config-output.md
website/builder/src/zh/api/config-performance.md
website/builder/src/zh/guide/basic/builder-config.md

docs(builder): add builder config document

---

website/main/docusaurus.config.js
website/main/package.json

fix: fix website assets bug

---

tests/integration/alias-set/package.json
tests/integration/server-prod/test/index.test.js

fix: windows test

---

tests/e2e/builder/fixtures/output/externals/src/App.jsx
tests/e2e/builder/fixtures/output/externals/src/ex.js
tests/e2e/builder/fixtures/output/externals/src/index.js
tests/e2e/builder/fixtures/tools/pug/src/App.tsx
tests/e2e/builder/fixtures/tools/pug/src/index.ts
tests/e2e/builder/fixtures/tools/pug/static/index.pug
tests/e2e/builder/fixtures/tools/pug/tsconfig.json
tests/e2e/builder/tests/output.test.ts
tests/e2e/builder/tests/tools.test.ts

chore:  add builder e2e test case

---

.github/workflows/release-pull-request.yml
.github/workflows/release.yml

feat: release workflow support modern-1

---

packages/builder/builder-shared/src/types/config/output.ts

chore(builder): shared output config add assetsRetry

---

packages/builder/builder-doc/en/config/dev/assetPrefix.md
packages/builder/builder-doc/en/config/output/assetPrefix.md
packages/builder/builder-doc/en/config/output/assetsRetry.md
packages/builder/builder-doc/en/config/output/cssModuleLocalIdentName.md
packages/builder/builder-doc/en/config/output/dataUriLimit.md
packages/builder/builder-doc/en/config/output/distPath.md
packages/builder/builder-doc/en/config/output/filename.md
packages/builder/builder-doc/en/config/output/svgDefaultExport.md
website/builder/src/.vuepress/config.ts
website/builder/src/.vuepress/styles/index.styl
website/builder/src/en/guide/advanced/split-chunk.md
website/builder/src/en/guide/basic/static-assets.md
website/builder/src/en/guide/features.md
website/builder/src/en/guide/introduction.md
website/builder/src/en/plugins/introduction.md
website/builder/src/zh/guide/advanced/split-chunk.md
website/builder/src/zh/guide/basic/static-assets.md
website/builder/src/zh/guide/features.md
website/builder/src/zh/guide/introduction.md
website/builder/src/zh/plugins/introduction.md

- Add static assets chapter.
- Fix some broken links.

docs(builder): add static assets chapter

---

.changeset/tender-eggs-know.md
packages/solutions/app-tools/src/builder/index.ts

Fix dev.assetPrefix config not work.

fix(app-tools): dev.assetPrefix not work

---

.gitattributes
.husky/post-checkout

chore: avoid conflicts in lockfile

---

.changeset/afraid-queens-appear.md
packages/runtime/plugin-runtime/src/core/compatible.tsx

`root` and `ReactDOM` params for `bootstrap`  are not the required params.

fix: bootstrap function params type define

---

.changeset/grumpy-queens-stare.md
packages/server/bff-core/src/router/utils.ts

fix: esbuild should not handle js files

---

packages/builder/plugin-swc/package.json

Fix builder-plugin-swc build script

fix: correct plugin swc build script

---

.changeset/curly-seas-talk.md
packages/runtime/plugin-runtime/src/ssr/serverRender/loadable.ts

fix: extname bug fix

---

packages/builder/plugin-swc/src/plugin.ts
packages/builder/plugin-swc/tests/browserslist.ts
packages/builder/plugin-swc/tests/utils.ts
scripts/vitest-run-all.js

fix(plugin-swc): fix plugin-swc CI failure

---

.changeset/hip-keys-carry.md
packages/runtime/plugin-runtime/src/core/compatible.tsx

Fix ssg failure due to lack of Web Response API.

fix: fix ssg failure

---

.changeset/tender-maps-sparkle.md
packages/runtime/plugin-garfish/src/runtime/utils/apps.tsx

fix: loadApp when dom is mount

fix: loadApp when dom is mount

---

packages/generator/generators/entry-generator/src/utils/index.ts

feat: single entry add routes dir

---

.changeset/fluffy-swans-own.md
packages/server/prod-server/package.json
packages/server/prod-server/src/libs/route/matcher.ts
packages/server/prod-server/src/utils.ts
packages/server/prod-server/src/worker-server.ts

- [] New feature (non-breaking change which adds functionality)

feat: export createHandler for cloudflare worker

---

packages/runtime/plugin-runtime/src/state/runtime/plugin.tsx

fix: state init function not return

---

.changeset/wet-mirrors-repair.md
packages/runtime/plugin-runtime/src/state/runtime/plugin.tsx

fix: state runtime plugin init hook not return next function

---

.github/workflows/check-changeset.yml
.github/workflows/cypress-test.yml
.github/workflows/integration-test-Windows.yml
.github/workflows/integration-test-macOS.yml
.github/workflows/test-macOS.yml

Upgrade node version in github actions to 16.x.

ci: upgrade node version

---

packages/toolkit/main-doc/zh/guides/advanced-features/custom-app.md
packages/toolkit/main-doc/zh/guides/concept/entries.md
packages/toolkit/main-doc/zh/guides/concept/integrated.md
packages/toolkit/main-doc/zh/guides/concept/lifecycle.md
packages/toolkit/main-doc/zh/guides/concept/solutions.md
packages/toolkit/main-doc/zh/guides/get-started/quick-start.md
packages/toolkit/main-doc/zh/guides/get-started/upgrade.md
website/main/src/css/dyte/font.css
website/main/src/css/dyte/md.css
website/main/src/css/dyte/root.css

feat: add quick start doc

---

tests/integration/ssr/fixtures/streaming/package.json

fix: package private field

---

website/builder/src/.vuepress/config.ts
website/builder/src/en/guide/advanced/custom-webpack-config.md
website/builder/src/zh/guide/advanced/custom-webpack-config.md

feat: add custom webpack config doc

---

packages/generator/generators/generator-generator/src/index.ts
packages/generator/generators/generator-generator/templates/js-template/src/index.js.handlebars
packages/generator/generators/generator-generator/templates/ts-template/src/index.ts.handlebars
packages/toolkit/main-doc/zh/guides/topic-detail/generator/codesmith/api/_category_.json
packages/toolkit/main-doc/zh/guides/topic-detail/generator/codesmith/api/app.md
packages/toolkit/main-doc/zh/guides/topic-detail/generator/codesmith/api/ejs.md
packages/toolkit/main-doc/zh/guides/topic-detail/generator/codesmith/api/fs.md
packages/toolkit/main-doc/zh/guides/topic-detail/generator/codesmith/api/git.md
packages/toolkit/main-doc/zh/guides/topic-detail/generator/codesmith/api/handlebars.md
packages/toolkit/main-doc/zh/guides/topic-detail/generator/codesmith/api/json.md
packages/toolkit/main-doc/zh/guides/topic-detail/generator/codesmith/api/npm.md
packages/toolkit/main-doc/zh/guides/topic-detail/generator/codesmith/develop.md
packages/toolkit/main-doc/zh/guides/topic-detail/generator/codesmith/introduce.md
packages/toolkit/main-doc/zh/guides/topic-detail/generator/codesmith/run-in-js.md
packages/toolkit/main-doc/zh/guides/topic-detail/generator/codesmith/structure.md
packages/toolkit/main-doc/zh/guides/topic-detail/generator/plugin/develop.md
website/main/src/css/dyte/md.css

feat: codesmith doc

---

.changeset/chilled-taxis-love.md
packages/generator/generator-utils/src/index.ts

fix: generator utils get plugin version

---

.changeset/rich-coats-double.md
packages/server/utils/package.json
packages/server/utils/src/compilers/typescript/tsconfig-paths-plugin.ts
pnpm-lock.yaml

Using the pre-bundled `tsconfig-paths` package.

chore(server-utils): using pre-bundled tsconfig-paths

---

.changeset/shiny-badgers-brush.md
packages/solutions/app-tools/src/commands/build.ts
packages/solutions/app-tools/src/commands/dev.ts

Fix `modern dev --analyze` and `modern build --analyze` not work.

fix(app-tools): cli --analyze option not work

---

packages/toolkit/main-doc/zh/guides/basic-features/data-fetch.md
packages/toolkit/main-doc/zh/guides/basic-features/env-vars.md
packages/toolkit/main-doc/zh/guides/basic-features/routes.md

feat: add routes doc

---

.changeset/rare-flies-dance.md
packages/builder/builder-doc/en/config/output/overrideBrowserslist.md
packages/builder/builder-doc/en/config/source/resolveExtensionPrefix.md
packages/builder/builder-doc/en/config/source/resolveMainFields.md
packages/builder/builder-doc/zh/config/output/overrideBrowserslist.md
packages/builder/builder-doc/zh/config/source/resolveExtensionPrefix.md
packages/builder/builder-doc/zh/config/source/resolveMainFields.md
packages/builder/builder-rspack-provider/src/plugins/resolve.ts
packages/builder/builder-rspack-provider/tests/plugins/resolve.test.ts
packages/builder/builder-shared/src/config.ts
packages/builder/builder-shared/src/getBrowserslist.ts
packages/builder/builder-shared/src/types/config/output.ts
packages/builder/builder-shared/src/types/config/source.ts
packages/builder/builder-shared/tests/config.test.ts
packages/builder/builder-shared/tests/getBrowserslist.test.ts
packages/builder/builder-webpack-provider/src/plugins/resolve.ts
packages/builder/builder-webpack-provider/tests/plugins/resolve.test.ts
pnpm-lock.yaml

Allow to set `overrideBrowserslist` `resolveMainFields` `resolveExtensionPrefix` by target.

feat(Builder): allow to set some configs by target

---

.changeset/honest-bugs-notice.md
packages/generator/generators/upgrade-generator/src/index.ts

fix: upgrade command update husky error

---

.changeset/fast-ants-accept.md
packages/runtime/plugin-runtime/src/core/compatible.tsx

fix: bootstrap func ReactDOM params type when use react18

---

packages/builder/builder-rspack-provider/src/plugins/devtool.ts
packages/builder/builder-rspack-provider/src/plugins/hmr.ts
packages/builder/builder-rspack-provider/src/plugins/react.ts
packages/builder/builder-rspack-provider/src/shared/plugin.ts

feat(rspack-provider): add rspack some dev plugins

---

.jest/setEnvVars.js
jest.config.js
packages/runtime/plugin-runtime/jest.config.js
packages/runtime/plugin-runtime/package.json
packages/runtime/plugin-runtime/src/core/compatible.tsx
packages/runtime/plugin-runtime/src/core/plugin.ts
packages/runtime/plugin-runtime/tests/core/bootstrap.test.tsx

fix: bootstrap type

---

packages/generator/generator-utils/src/index.ts
packages/generator/generators/bff-generator/src/index.ts
packages/generator/generators/server-generator/src/index.ts
packages/generator/generators/storybook-generator/src/index.ts
packages/generator/new-action/src/module.ts
packages/generator/new-action/src/mwa.ts
tests/generator/module.ts
tests/generator/monorepo.ts
tests/generator/mwa.ts
tests/generator/utils/command.ts

fix: generator test

---

.changeset/fast-planets-grab.md
packages/server/server/src/dev-tools/register/index.ts
packages/server/utils/src/common/index.ts
packages/server/utils/src/compilers/babel/index.ts
packages/server/utils/tests/__snapshots__/babel.test.ts.snap
packages/solutions/app-tools/src/config/default.ts
pnpm-lock.yaml

fix: modernjs dev server can not start normaly

---

packages/toolkit/main-doc/zh/configure/app/output/ssg.md
packages/toolkit/main-doc/zh/configure/app/server/ssr.md
packages/toolkit/main-doc/zh/guides/advanced-features/ssg.md
packages/toolkit/main-doc/zh/guides/advanced-features/ssr.md
packages/toolkit/main-doc/zh/guides/basic-features/routes.md

feat: add ssr & ssg doc

---

packages/builder/builder-rspack-provider/package.json
packages/builder/builder-rspack-provider/src/module.d.ts
packages/builder/builder-rspack-provider/src/plugins/css.ts
packages/builder/builder-rspack-provider/src/shared/plugin.ts
packages/builder/builder-rspack-provider/src/types/config/tools.ts
packages/builder/builder-rspack-provider/src/types/thirdParty/css.ts
packages/builder/builder-rspack-provider/src/types/thirdParty/index.ts
packages/builder/builder-rspack-provider/tests/plugins/__snapshots__/css.test.ts.snap
packages/builder/builder-rspack-provider/tests/plugins/__snapshots__/default.test.ts.snap
packages/builder/builder-rspack-provider/tests/plugins/css.test.ts
pnpm-lock.yaml

feat(rspack-provider): css plugin support

---

website/builder/src/en/guide/basic/typescript.md
website/builder/src/zh/guide/basic/typescript.md

chore(docs/ts): correct some chinese syntax

---

tests/integration/alias-set/test/index.test.js
tests/integration/app-document/tests/index.test.js
tests/integration/css/fixtures/exclude-less/package.json
tests/integration/mwa-app/tests/index.test.js

应用项目构建默认将不会自动生成 `asset-manifest.json` 文件，可以通过 output.enableAssetManifest 开启

fix: integration test -- remove asset-manifest.json file 

---

website/builder/src/en/plugins/plugin-swc.md
website/builder/src/zh/plugins/plugin-swc.md

fix(docs): type

---

packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/apis/app/runtime/model/create-app.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/apis/app/runtime/model/use-store.md
packages/toolkit/main-doc/zh/apis/app/runtime/model/create-app.md
packages/toolkit/main-doc/zh/apis/app/runtime/model/use-store.md

Remove incorrect example of `useStore`.

docs: reduck `useStore`

---

packages/builder/builder-doc/en/config/tools/babel.md
packages/builder/builder-doc/en/config/tools/postcss.md
packages/builder/builder-doc/zh/config/tools/babel.md
packages/builder/builder-doc/zh/config/tools/postcss.md

Add tools.babel and tools.postcss object.assign notice.

docs(Builder): add tools.babel object.assign notice

---

packages/builder/builder-doc/en/config/source/include.md
packages/builder/builder-doc/en/config/tools/babel.md
packages/builder/builder-doc/en/config/tools/webpack.md
packages/builder/builder-doc/en/config/tools/webpackChain.md
packages/builder/builder-doc/zh/config/source/include.md
packages/builder/builder-doc/zh/config/tools/babel.md
packages/builder/builder-doc/zh/config/tools/webpackChain.md
tests/integration/mwa-app/modern.config.ts
website/builder/src/.vuepress/config.ts
website/builder/src/en/guide/faq/exceptions.md
website/builder/src/zh/guide/faq/exceptions.md

docs(Builder): add some babel FAQ

---

.changeset/ten-eggs-brush.md
packages/runtime/plugin-runtime/src/ssr/cli/index.ts
packages/toolkit/main-doc/zh/guides/advanced-features/ssr.md
packages/toolkit/main-doc/zh/guides/basic-features/env-vars.md

In some cases, the code needs to distinguish between SSR and CSR in order to remove environment-related code.
```tsx
const App = () => {
if (process.env.MODERN_TARGET === 'browser') {
const safeGet = require('lodash.get');
const o = { a: 'x' };
console.log(safeGet(o, 'a'));
// or some sdk only run in browser.
};
};
export default App;
```
Unlike `context.isBrowser`, this env var removes useless code after production bundle.
`context.isBrowser` can be used in most cases to differentiate logic at runtime.
But in some cases, such as files with side effects, or logic outside the component, you need to do it through this environment variables：
```ts
logDevice(window.innerHeight);
```
We also recommend using environment variables instead of the runtime, as this will make the application package …

feat: support internal metaName_TARGET env vars

---

packages/toolkit/main-doc/zh/configure/app/experiments/_category_.json
packages/toolkit/main-doc/zh/configure/app/html/_category_.json
packages/toolkit/main-doc/zh/configure/app/performance/_category_.json
packages/toolkit/main-doc/zh/configure/app/security/_category_.json

feat: add category

---

packages/runtime/plugin-runtime/src/router/runtime/plugin.node.tsx
packages/runtime/plugin-runtime/src/router/runtime/plugin.tsx

fix(next): wrap router while has custom createRoutes

---

packages/cli/plugin-swc/package.json
pnpm-lock.yaml

fix: plugin-swc missing dep typescript

---

.changeset/wet-socks-own.md
packages/cli/core/package.json
packages/cli/core/src/runBin.ts
packages/solutions/app-tools/bin/modern.js
packages/solutions/app-tools/package.json
packages/solutions/doc-tools/bin/modern.js
packages/solutions/module-tools-v2/bin/modern.js
packages/solutions/module-tools-v2/package.json
packages/solutions/module-tools/bin/modern.js
packages/solutions/module-tools/package.json
packages/toolkit/utils/src/constants.ts

Add a `runBin` function to app/module/doctools, and configure the internal plugin constants in the app/module/doc tools

feat: add runBin and internal plugins constants in all tools

---

tests/integration/ssr/test/streaming.test.js

fix: fix ssr testcases

---

.changeset/smart-bees-dress.md
packages/solutions/app-tools/lib/types.d.ts
packages/solutions/app-tools/src/commands/dev.ts
tests/integration/api-service-koa/api/modern-app-env.d.ts

fix: builder should not be checked when apiOnly is true

---

.changeset/gold-eggs-remember.md
packages/solutions/app-tools/package.json
packages/solutions/app-tools/src/analyze/generateCode.ts
pnpm-lock.yaml

Add "esbuild" to dependencies and replace default import to named import

fix: add esbuild to dependencies

---

codecov.yml

chore: change the codecov to target 55

---

.changeset/fair-peas-think.md
packages/runtime/plugin-runtime/package.json

fix: miss export document cli

---

.changeset/stupid-chicken-join.md
packages/solutions/app-tools/src/analyze/nestedRoutes.ts
packages/solutions/app-tools/src/analyze/templates.ts
packages/toolkit/utils/src/test-utils.ts

fix: fix generateCode logic for windows

---

packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/configure/app/tools/esbuild.md
packages/toolkit/main-doc/zh/configure/app/tools/esbuild.md
website/builder/src/en/plugins/plugin-esbuild.md
website/builder/src/zh/plugins/plugin-esbuild.md

Update the esbuild document in Modern.js and Modern.js Builder.

docs(Builder): update esbuild document

---

.changeset/old-turkeys-wait.md
packages/cli/plugin-storybook/src/features/build.ts
packages/cli/plugin-storybook/src/features/dev.ts

fix(storybook): catch & log dev error， fix build config error

fix(storybook): catch & log dev error

---

.changeset/funny-planets-behave.md
packages/runtime/plugin-runtime/src/document/cli/index.ts

fix: document not hmr

---

.changeset/cold-books-count.md
packages/builder/builder-webpack-provider/src/plugins/tsChecker.ts

Fix failed to resolve "typescript" in some cases.

fix(Builder): failed to resolve typescript in some cases

---

packages/solutions/app-tools/src/analyze/index.ts
packages/solutions/app-tools/src/builder/index.ts
packages/toolkit/main-doc/zh/components/global-proxy.md
packages/toolkit/main-doc/zh/guides/advanced-features/ssr.md
packages/toolkit/main-doc/zh/guides/basic-features/proxy.md

feat: add ssr docs for data loader

---

.changeset/rude-jokes-fail.md
packages/server/server/package.json

Mark `ts-node` and `ts-config-paths` as optional peer dependencies, remove peer dependencies warning.

fix(server): remove peer dependencies warning

---

.changeset/nasty-books-join.md
packages/runtime/plugin-runtime/src/state/runtime/plugin.tsx

fix: fix state plugin config

---

.changeset/rare-geckos-appear.md
packages/solutions/app-tools/src/builder/builderPlugins/compatModern.ts

fix: router config maybe not defined

---

packages/generator/generators/module-generator/src/index.ts
packages/generator/generators/mwa-generator/src/index.ts

fix: @types/react version

---

.changeset/fluffy-pears-tickle.md
packages/solutions/app-tools/src/analyze/getBundleEntry.ts

fix: support set entry with file-system based router

---

packages/generator/generators/module-generator/templates/base-template/package.json.handlebars

fix: generator template

---

.changeset/nervous-boxes-sit.md
packages/solutions/module-tools/package.json
packages/solutions/module-tools/src/builder/build.ts
packages/solutions/module-tools/tests/__snapshots__/decorator.test.ts.snap
packages/solutions/module-tools/tests/__snapshots__/format.test.ts.snap
packages/solutions/module-tools/tests/__snapshots__/sourcemap.test.ts.snap
packages/solutions/module-tools/tests/__snapshots__/umdGlobals.test.ts.snap
packages/solutions/module-tools/tests/format.test.ts
pnpm-lock.yaml

feat: upgrade libuild version and remove warning log

---

packages/cli/core/package.json

feat: bump core version

---

.changeset/nine-scissors-lick.md
packages/cli/webpack/src/config/features/copy.ts
tests/integration/copy-assets/fixtures/copy-public-html/config/public/demo.html
tests/integration/copy-assets/test/__snapshots__/index.test.ts.snap

Fix failed to replace assetPrefix.

fix(webpack): failed to replace assetPrefix

---

packages/generator/generators/module-generator/templates/base-template/package.json.handlebars
tests/integration/copy-assets/fixtures/copy-public-html/package.json

feat: module template

---

.changeset/hot-dryers-tie.md
packages/builder/builder-webpack-provider/src/plugins/copy.ts
packages/solutions/app-tools/src/builder/share.ts
tests/integration/copy-assets/fixtures/copy-public-html/config/public/demo.html
tests/integration/copy-assets/test/__snapshots__/index.test.ts.snap

Fix failed to copy public assets.

fix(app-tools): failed to copy public assets

---

.changeset/nervous-tools-design.md
packages/runtime/plugin-testing/src/cli/index.ts

add `@` alias to plugin-testing

fix: testing alias

---

packages/generator/generator-cases/tests/index.test.ts
packages/generator/generator-common/src/locale/en.ts
packages/generator/generator-common/src/locale/zh.ts
packages/generator/generator-common/src/newAction/common/index.ts
packages/generator/generator-common/src/newAction/mwa/index.ts
packages/generator/generator-common/tests/new-action.test.ts

feat: support new swc compile

---

packages/generator/generators/repo-generator/modern.config.js
packages/generator/plugins/generator-plugin/modern.config.js
packages/generator/plugins/generator-plugin/src/index.ts
packages/generator/plugins/generator-plugin/templates/modern.config.js.handlebars
packages/generator/plugins/generator-plugin/templates/modern.config.ts.handlebars

fix: generator plugin config

---

packages/toolkit/types/server/hook.d.ts

fix: status is optional in route.redirect

---

packages/server/prod-server/src/libs/hook-api/index.ts
packages/toolkit/main-doc/zh/apis/app/runtime/web-server/hook.md
packages/toolkit/main-doc/zh/apis/app/runtime/web-server/middleware.md
packages/toolkit/types/server/hook.d.ts

feat: add context.url for custom web server

---

packages/solutions/app-tools/src/builder/index.ts
packages/solutions/app-tools/src/config/default.ts
packages/solutions/app-tools/src/config/initial/createOutputConfig.ts
packages/solutions/app-tools/src/config/initial/createSourceConfig.ts
packages/solutions/app-tools/src/config/initial/transformNormalizedConfig.ts
packages/solutions/app-tools/tests/builder/__snapshots__/index.test.ts.snap

Adjust config default value:
- disableNodePolyfill: `true` by default，`false` in compat mode.
- resolveExtensionPrefix: empty by default，`{ web: '.web', node: '.node' }` in compat mode.
- removeMomentLocale: `false` by default，`true` in compat mode.

fix(app-tools): adjust config default value

---

packages/server/prod-server/src/libs/hook-api/index.ts
packages/toolkit/types/server/hook.d.ts

fix: fix web server api type

---

.changeset/tasty-geckos-repair.md
packages/builder/plugin-swc/src/loader.ts
packages/builder/plugin-swc/src/plugin.ts
packages/builder/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
website/builder/src/en/plugins/plugin-swc.md
website/builder/src/zh/plugins/plugin-swc.md

feat: determine react runtime based on user tsConfig

---

packages/server/plugin-server/src/server.ts
tests/integration/server-hook/request/test/index.test.ts

fix: fixt test case

---

.vscode/extensions.json
.vscode/settings.json
monorepo.code-workspace
packages/generator/generators/base-generator/templates/base-templates/.vscode/extensions.json
packages/generator/generators/base-generator/templates/base-templates/.vscode/settings.json
packages/generator/generators/monorepo-generator/templates/base-template/monorepo.code-workspace

Simplify default vscode settings, merge the formatter config, remove some recommendations extensions.

chore(generator): simplify default vscode settings

---

tests/integration/asset-prefix/test/index.test.ts
tests/integration/mwa-app/modern.config.ts

chore: fix integration tests

---

modern.config.js

fix: bump version error

---

packages/cli/plugin-bff/package.json
packages/runtime/plugin-testing/package.json
packages/server/plugin-express/package.json
packages/server/plugin-koa/package.json
packages/server/plugin-polyfill/package.json
packages/server/plugin-server/package.json

fix: export type

---

packages/toolkit/main-doc/zh/components/prerequisites.md
packages/toolkit/main-doc/zh/tutorials/first-app/c01-start.md
packages/toolkit/main-doc/zh/tutorials/first-app/c03-css.md
packages/toolkit/main-doc/zh/tutorials/first-app/c04-routes.md
packages/toolkit/main-doc/zh/tutorials/first-app/c05-loader.md
packages/toolkit/main-doc/zh/tutorials/first-app/c06-model.md
packages/toolkit/main-doc/zh/tutorials/first-app/c07-container.md
packages/toolkit/main-doc/zh/tutorials/first-app/c08-entries.md

fix: tutorials doc

---

website/module-tools/docs/.island/config.ts

docs: fix island config

---

packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/apis/app/runtime/core/bootstrap.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/apis/app/runtime/core/create-app.md
packages/toolkit/main-doc/zh/apis/app/runtime/core/bootstrap.md
packages/toolkit/main-doc/zh/apis/app/runtime/core/create-app.md
packages/toolkit/main-doc/zh/apis/app/runtime/core/use-module-apps.md
packages/toolkit/main-doc/zh/configure/app/deploy/microFrontend.md
packages/toolkit/main-doc/zh/configure/app/runtime/master-app.md

fix: api doc

---

packages/solutions/app-tools/src/analyze/generateCode.ts
packages/solutions/app-tools/src/analyze/index.ts
packages/solutions/app-tools/src/index.ts
packages/solutions/app-tools/src/initialize/index.ts
packages/solutions/app-tools/src/utils/commands.ts
tests/integration/routes/src/modern-app-env.d.ts

fix: add start command to dev commands

---

packages/solutions/app-tools/src/analyze/generateCode.ts
tests/integration/app-document/modern.config.ts
tests/integration/garfish/dashboard/modern.config.js
tests/integration/garfish/main/modern.config.js
tests/integration/garfish/table/modern.config.js
tests/integration/runtime/fixtures/file-based-router/modern.config.ts
tests/integration/runtime/fixtures/file-based-router/src/home/pages/users/[userName]/index.jsx

fix: router-v5 test cases

---

packages/builder/plugin-image-compress/src/types/index.ts
packages/toolkit/utils/src/chainId.ts

feat: prepare plugin imagex

---

packages/builder/builder-webpack-provider/src/index.ts
pnpm-lock.yaml

Export ModifyWebpackChainUtils and ModifyWebpackConfigUtils types.

feat(Builder): export webpack utils type

---

tests/integration/app-document/src/modern-app-env.d.ts

fix: router test

---

packages/solutions/app-tools/src/index.ts

fix: app tools runtime type

---

website/builder/src/en/guide/advanced/browserslist.md
website/builder/src/zh/guide/advanced/browserslist.md

Improve browserslist document.

docs(Builder): improve browserslist document

---

packages/cli/core/package.json

feat: bump beta version

---

packages/builder/builder-webpack-provider/src/plugins/splitChunks.ts
packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/default.test.ts.snap
packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/splitChunks.test.ts.snap
packages/builder/builder-webpack-provider/tests/plugins/splitChunks.test.ts

Configure too much cache groups may slow down the build time.
This PR adds some detects for the cache group, only attach some cache groups when the corespponding package is installed.

feat(Builder): optimize cache groups

---

packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/components/global-proxy.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/guides/basic-features/alias.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/guides/basic-features/env-vars.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/guides/basic-features/html.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/guides/basic-features/mock.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/guides/basic-features/proxy.md
packages/toolkit/main-doc/zh/guides/basic-features/alias.md
packages/toolkit/main-doc/zh/guides/basic-features/env-vars.md
packages/toolkit/main-doc/zh/guides/basic-features/mock.md
packages/toolkit/main-doc/zh/guides/basic-features/proxy.md

feat: add basic features en docs

---

packages/runtime/plugin-runtime/src/router/runtime/index.ts
packages/solutions/app-tools/src/analyze/getBundleEntry.ts
packages/solutions/app-tools/src/schema/index.ts
packages/solutions/app-tools/src/schema/legacy.ts
packages/solutions/app-tools/src/types/config/source.ts
packages/solutions/app-tools/src/types/legacyConfig/source.ts
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/configure/app/source/entries.md
packages/toolkit/main-doc/zh/configure/app/source/entries.md

fix: remove the enableFileSystemRoutes configuration

---

packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/guides/get-started/quick-start.md
packages/toolkit/main-doc/zh/components/debug-app.md
packages/toolkit/main-doc/zh/guides/get-started/quick-start.md
packages/toolkit/main-doc/zh/guides/topic-detail/micro-frontend/c02-development.md

docs: fix invalid ip and image url

---

packages/toolkit/upgrade/modern.config.js
packages/toolkit/upgrade/package.json
pnpm-lock.yaml

目前 upgrade 包会 bundle 所有依赖，导致包体积较大（2.9MB）：
由于这些依赖在 app-tools 里默认就会引用，所以改为 external，这样可以复用依赖，减少包体积，调整后包体积降低至 4KB：

feat(upgrade): reduce install size

---

packages/toolkit/main-doc/zh/guides/topic-detail/framework-plugin/implement.md

docs(main): modern.js plugin implement

---

.changeset/brave-kangaroos-wait.md
packages/generator/generator-common/src/newAction/module/index.ts
packages/generator/generators/module-generator/templates/base-template/package.json.handlebars
packages/generator/generators/module-generator/templates/base-template/tests/index.test.language.handlebars
packages/generator/generators/module-generator/templates/js-template/modern.config.js.handlebars
packages/generator/generators/module-generator/templates/js-template/tests/.eslintrc.js.handlebars
packages/generator/generators/module-generator/templates/ts-template/modern.config.ts.handlebars
packages/generator/generators/module-generator/templates/ts-template/tests/.eslintrc.js.handlebars
packages/generator/generators/module-generator/templates/ts-template/tests/tsconfig.json.handlebars
packages/generator/generators/module-generator/templates/ts-template/tsconfig.json.handlebars

feat: change module-tools generator

---

packages/generator/generators/router-v5-generator/src/locale/zh.ts
packages/runtime/plugin-garfish/src/cli/index.ts
packages/runtime/plugin-garfish/src/cli/types.ts
packages/runtime/plugin-garfish/type.d.ts
packages/toolkit/main-doc/zh/configure/app/deploy/microFrontend.md
tests/generator/module.ts

fix garfish type && fix doc link && fix generator module test

---

packages/builder/builder-webpack-provider/src/plugins/rem.ts
website/builder/src/en/guide/advanced/rem.md
website/builder/src/zh/guide/advanced/rem.md

chore: enable rem in stylus and update doc

---

packages/builder/plugin-swc/src/plugin.ts

Using webpack persistent cache for SWC minify.

feat(swc): using webpack persistent cache for minify

---

packages/generator/generator-common/src/newAction/mwa/index.ts
packages/generator/generators/ssg-generator/.eslintrc.js
packages/generator/generators/ssg-generator/LICENSE
packages/generator/generators/ssg-generator/README.md
packages/generator/generators/ssg-generator/jest.config.js
packages/generator/generators/ssg-generator/modern.config.js
packages/generator/generators/ssg-generator/package.json
packages/generator/generators/ssg-generator/src/index.ts
packages/generator/generators/ssg-generator/src/locale/en.ts
packages/generator/generators/ssg-generator/src/locale/index.ts
packages/generator/generators/ssg-generator/src/locale/zh.ts
packages/generator/generators/ssg-generator/tsconfig.json
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/guides/advanced-features/ssg.md
packages/toolkit/main-doc/zh/guides/advanced-features/ssg.md
pnpm-lock.yaml
tests/generator/mwa.ts

Fix ssg generator

---

tests/generator/utils/prepare.ts

fix: module generator test

---

.changeset/silent-bottles-whisper.md
packages/cli/doc-plugin-auto-sidebar/package.json
pnpm-lock.yaml

fix: fix dependency version

---

packages/cli/doc-core/src/node/mdx/remarkPlugins/link.ts
packages/cli/doc-core/src/runtime/utils.ts
packages/cli/doc-core/src/shared/utils/index.ts
packages/cli/doc-core/src/theme-default/logic/usePrevNextPage.ts
packages/cli/doc-plugin-auto-sidebar/package.json
packages/cli/doc-plugin-auto-sidebar/src/index.ts
pnpm-lock.yaml

fix: doc-tools prev-next invalid

---

packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/guides/topic-detail/generator/config/common.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/guides/topic-detail/generator/config/module.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/guides/topic-detail/generator/config/mwa.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/guides/topic-detail/generator/project.md
packages/toolkit/main-doc/zh/guides/topic-detail/generator/config/module.md
packages/toolkit/main-doc/zh/guides/topic-detail/generator/config/mwa.md

fix: doc detail

---

.changeset/silent-bottles-whisper.md
packages/cli/doc-core/package.json
packages/cli/doc-plugin-auto-sidebar/package.json
packages/cli/plugin-module-babel/package.json
packages/cli/plugin-module-main-fields/package.json
packages/cli/plugin-module-polyfill/package.json
packages/cli/plugin-module-target/package.json
packages/toolkit/main-doc/package.json
pnpm-lock.yaml

Fix peer dep

---

packages/cli/doc-core/src/shared/types/attributify-shims.d.ts
packages/cli/doc-core/src/shared/types/default-theme.ts
packages/cli/doc-core/src/theme-default/components/Aside/index.tsx
packages/cli/doc-core/src/theme-default/components/DocFooter/index.tsx
packages/cli/doc-core/src/theme-default/components/HomeFeatures/index.tsx
packages/cli/doc-core/src/theme-default/components/HomeFooter/index.tsx
packages/cli/doc-core/src/theme-default/components/LocalSideBar/index.tsx
packages/cli/doc-core/src/theme-default/components/Nav/NavMenuGroup.tsx
packages/cli/doc-core/src/theme-default/components/Nav/index.tsx
packages/cli/doc-core/src/theme-default/components/NavScreenMenuGroup/NavScreenMenuGroup.tsx
packages/cli/doc-core/src/theme-default/components/Overview/index.tsx
packages/cli/doc-core/src/theme-default/components/Search/index.tsx
packages/cli/doc-core/src/theme-default/components/Siderbar/index.tsx
packages/cli/doc-core/src/theme-default/components/SocialLinks/HiddenLinks.tsx
packages/cli/doc-core/src/theme-default/components/SocialLinks/LinkContent.tsx
packages/cli/doc-core/src/theme-default/components/SocialLinks/index.tsx
packages/cli/doc-core/src/theme-default/components/Tabs/index.tsx
packages/cli/doc-core/src/theme-default/layout/DocLayout/index.tsx
packages/cli/doc-core/src/theme-default/layout/NotFountLayout/index.tsx
packages/cli/doc-plugin-auto-sidebar/src/index.ts

由于 WindiCSS 的 attributify 字段仅为 Unocss 的子集， 迁移到 WindiCSS 后遇到部分字段会有类型报错问题，此 PR 进行逐个修复。

fix: doc-tools type error in default theme

---

.changeset/smart-scissors-hunt.md
packages/solutions/module-tools/src/constants/build.ts
packages/solutions/module-tools/tests/fixtures/svgr/default.config.ts
website/module-tools/docs/en/api/build-config.md
website/module-tools/docs/zh/api/build-config.md

feat(module-tools): close svgr default

---

.changeset/slimy-wolves-know.md
packages/cli/plugin-storybook/package.json
packages/cli/plugin-storybook/src/config/schema.ts
packages/cli/plugin-storybook/src/features/build.ts
packages/cli/plugin-storybook/src/features/dev.ts
packages/cli/plugin-storybook/src/features/utils/genConfigDir.ts
packages/cli/plugin-storybook/src/features/utils/webpackConfig.ts
packages/cli/plugin-storybook/src/index.ts
packages/cli/plugin-storybook/src/runtime-addon/components/modern.tsx
packages/cli/plugin-storybook/src/types/index.ts
packages/cli/plugin-storybook/template/main.tmpl
packages/runtime/plugin-runtime/src/config.ts
packages/runtime/plugin-runtime/src/index.ts
packages/runtime/plugin-runtime/types/index.d.ts
packages/runtime/plugin-runtime/types/router.d.ts
packages/solutions/module-tools/package.json
packages/solutions/module-tools/src/types/config/index.ts
packages/toolkit/utils/src/constants.ts
pnpm-lock.yaml

update storybook support runtime API.

feat: storybook runtime

---

packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/configure/app/runtime/master-app.md
packages/toolkit/main-doc/zh/configure/app/runtime/master-app.md

fix: synchronize Garfish en doc

---

packages/cli/plugin-data-loader/package.json
packages/cli/plugin-data-loader/src/cli/create-request.ts
packages/cli/plugin-data-loader/src/common/constants.ts
packages/cli/plugin-data-loader/src/server/index.ts
packages/cli/plugin-data-loader/tests/request.test.ts
packages/cli/plugin-data-loader/tests/server.test.ts

feat: rename request param

---

packages/server/core/src/types/config/server.ts
packages/server/plugin-express/src/plugin.ts
packages/server/plugin-express/tests/webServer.test.ts
packages/server/plugin-koa/src/plugin.ts
packages/server/plugin-koa/tests/webServer.test.ts
packages/solutions/app-tools/src/schema/index.ts
packages/solutions/app-tools/src/schema/legacy.ts
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/configure/app/server/enable-framework-ext.md
packages/toolkit/main-doc/zh/configure/app/server/enable-framework-ext.md
packages/toolkit/main-doc/zh/configure/app/server/port.md

Disable framework extension in web server by default.
change `server.disableFrameworkExt` to `server.enableFrameworkExt`, by default `false`.
config as follow to enable framework extension syntax.
before:
```ts
import { Middleware } from '@modern-js/runtime/server';
export const middleware: Middleware = (ctx, next) => {  
console.log(ctx.request.url);
next();
}
```
after config, example for `@modern-js/plugin-express`:
```ts
import { RequestHandler } from '@modern-js/runtime/express';
export const middleware: RequestHandler = (req, res, next) => {  
console.log(req.url);
next();
}
```

chore: change disableFrameworkExt to enableFrameworkExt

---

packages/cli/doc-core/index.html
packages/cli/doc-core/package.json
packages/cli/doc-core/src/node/build.ts
packages/cli/doc-core/src/node/constants.ts
packages/cli/doc-core/src/node/createBuilder.ts
packages/cli/doc-core/src/node/mdx/index.ts
packages/cli/doc-core/src/node/mdx/remarkPlugins/link.ts
packages/cli/doc-core/src/node/plugins/replace.ts
packages/cli/doc-core/src/node/utils/applyReplaceRules.ts
packages/cli/doc-core/src/node/virtualModule/siteData.ts
packages/cli/doc-core/src/node/windiOptions.ts
packages/cli/doc-core/src/runtime/ssrEntry.tsx
packages/cli/doc-core/src/shared/types/index.ts
packages/cli/doc-core/src/theme-default/components/Search/index.tsx
packages/cli/doc-core/src/theme-default/components/Siderbar/index.tsx
packages/cli/doc-core/src/theme-default/layout/DocLayout/index.tsx
packages/cli/doc-core/src/theme-default/layout/Layout/index.tsx
packages/cli/doc-core/vitest.config.ts
pnpm-lock.yaml

Doc Tools 更新:
Feat:
- 给文档内链接自动带上对应的语言前缀
Bug Fix:
1. collpasible 不生效
2. 页面 title 配置无效
3. 搜索内容未经 replaceRules 替换
4. 搜索内容出现 import 语句
5. 增加 vite 开发依赖，避免 vitest 找不到 peerDepencies 导致的报错

fix: collpasible not work & search content optimize

---

packages/generator/generators/module-generator/src/index.ts
packages/generator/generators/mwa-generator/src/index.ts
tests/cypress/support/e2e.js
tests/integration/garfish/main-router-v6/src/routes/user/layout.tsx

fix: generator dep and garfish path error

---

packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/tutorials/first-app/_category_.json
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/tutorials/first-app/c01-start.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/tutorials/first-app/c02-component.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/tutorials/first-app/c03-css.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/tutorials/first-app/c04-routes.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/tutorials/first-app/c05-loader.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/tutorials/first-app/c06-model.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/tutorials/first-app/c07-container.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/tutorials/first-app/c08-entries.md

feat: tutorials en doc

---

.changeset/many-kings-pump.md

fix: module tools v2.0.0 bad version

---

.changeset/perfect-pens-add.md
packages/generator/generator-common/src/newAction/module/index.ts

fix: module test plugin dep

---

scripts/check-changeset/src/index.ts

feat: remove special changeset check

---

.changeset/chilled-seals-switch.md
packages/solutions/app-tools/src/index.ts
packages/solutions/app-tools/src/locale/en.ts
packages/solutions/app-tools/src/locale/zh.ts
packages/solutions/module-tools/src/command.ts
packages/solutions/module-tools/src/locale/en.ts
packages/solutions/module-tools/src/locale/zh.ts
packages/solutions/monorepo-tools/src/cli/new.ts
packages/solutions/monorepo-tools/src/locale/en.ts
packages/solutions/monorepo-tools/src/locale/zh.ts

new command run support `--lang` params

feat: new command support --lang params

---

.github/workflows/build-module-website.yml
website/module-tools/docs/en/guide/basic/test-your-project.mdx

fix: module tools doc deploy

---

website/module-tools/docs/zh/api/config/build-config.md
website/module-tools/docs/zh/index.md
website/module-tools/modern.config.ts

docs: change title and add svgr tip

---

packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current.json
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/apis/app/runtime/model/Provider.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/components/debug-app.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/components/prerequisites.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/configure/app/runtime/router.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/guides/basic-features/css/less-sass.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/guides/basic-features/css/tailwindcss.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/guides/get-started/quick-start.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/tutorials/first-app/c01-start.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/tutorials/first-app/c02-component.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/tutorials/first-app/c03-css.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/tutorials/first-app/c04-routes.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/tutorials/first-app/c05-loader.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/tutorials/first-app/c06-model.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/tutorials/first-app/c07-container.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/tutorials/first-app/c08-entries.md

feat: tutorials doc

---

packages/cli/doc-core/package.json
packages/cli/doc-core/src/node/mdx/index.ts
packages/cli/doc-plugin-auto-sidebar/src/index.ts
pnpm-lock.yaml

1. 避免零值被 || 所忽略
2. external link 增加 target: '_blank'

chore: auto sidebar plugin sort

---

packages/builder/builder-doc/CHANGELOG.md
packages/builder/builder-rspack-provider/CHANGELOG.md
packages/builder/builder-shared/CHANGELOG.md
packages/builder/builder-webpack-provider/CHANGELOG.md
packages/builder/builder/CHANGELOG.md
packages/builder/plugin-esbuild/CHANGELOG.md
packages/builder/plugin-image-compress/CHANGELOG.md
packages/builder/plugin-node-polyfill/CHANGELOG.md
packages/builder/plugin-stylus/CHANGELOG.md
packages/builder/plugin-swc/CHANGELOG.md

add CHANGELOG.md of Builder packages, let changeset write the changelog to these files.

docs(builder): add CHANGELOG.md files

---

.changeset/slimy-apples-search.md
packages/builder/builder-doc/en/config/tools/htmlPlugin.md
packages/builder/builder-doc/zh/config/tools/htmlPlugin.md
packages/builder/builder-rspack-provider/tests/plugins/__snapshots__/html.test.ts.snap
packages/builder/builder-shared/src/config.ts
packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/html.test.ts.snap
packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/inlineChunk.test.ts.snap
packages/solutions/app-tools/src/config/initial/inits.ts

No longer remove comments of HTML, because the comments may be useful for upper-level frameworks.

fix(builder): no longer remove comments of HTML

---

packages/cli/doc-core/package.json
packages/cli/doc-core/src/node/build.ts
packages/cli/doc-core/src/node/route/RouteService.ts
packages/cli/doc-core/src/node/utils/getPageKey.ts
packages/cli/doc-core/src/runtime/hooks.ts
pnpm-lock.yaml

1. 修复 withBase API 重复执行的问题
2. 给 a 标签增加 href 的属性

fix: doc tools withBase api

---

.changeset/wicked-donkeys-greet.md
packages/cli/core/src/config/mergeConfig.ts
packages/solutions/module-tools/src/types.ts

feat(module-tools): export type UserConfig and fix type ToolsConfig

---

packages/cli/doc-core/src/node/mdx/remarkPlugins/normalizeLink.ts
packages/cli/doc-core/src/theme-default/components/Aside/index.tsx

fix: normalize link hash

---

packages/cli/doc-core/src/node/createBuilder.ts
packages/cli/doc-core/src/node/windiOptions.ts
packages/cli/doc-core/src/shared/utils/index.ts
packages/cli/doc-core/src/theme-default/components/Link/index.tsx
packages/cli/doc-core/src/theme-default/components/Nav/index.tsx
packages/cli/doc-core/src/theme-default/components/Search/index.tsx
packages/cli/doc-core/src/theme-default/components/Search/logic/util.ts
packages/cli/doc-core/src/theme-default/components/Siderbar/index.tsx
packages/cli/doc-core/src/theme-default/layout/DocLayout/index.tsx
packages/cli/doc-core/src/theme-default/styles/base.css
packages/cli/doc-core/src/theme-default/styles/vars.css
packages/toolkit/remark-container/src/index.ts
packages/toolkit/remark-container/tests/__snapshots__/index.test.ts.snap
packages/toolkit/remark-container/tests/index.test.ts

修复如下问题:
1. 带有 base 路径时切换语言出现 404 页面
2. 侧边栏标题太长会造成高度撑不开
3. 搜索结果中标题太长会出现样式错乱
4. Info 高亮框背景应调整为蓝色，而不是灰色
5. SSR 构建缓存不生效
6. 兼容模块工程文档出现的 :::tip{title=xxx} 不加引号的写法

fix: path error when change the language

---

tests/integration/garfish/main/src/App.tsx
tests/integration/garfish/main/src/modern-app-env.d.ts

* fix: garfish plugin e2e test failure

fix: garfish plugin e2e test failure

---

.changeset/tall-hounds-mix.md
packages/generator/generator-common/src/newAction/module/index.ts
packages/generator/generator-common/src/newAction/mwa/index.ts

Optimize the capitalization of plugin names when run new command to enable function.

chore: optimize the capitalization of new command plugin names

---

.changeset/happy-elephants-beg.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/configure/app/auto-load-plugin.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/configure/app/tools/swc.md
packages/toolkit/main-doc/zh/configure/app/auto-load-plugin.md
packages/toolkit/main-doc/zh/configure/app/tools/swc.md
pnpm-lock.yaml

Add registration guide of SWC plugin.

docs(swc-plugin): add registration guide

---

packages/cli/doc-core/src/theme-default/components/HomeHero/index.tsx
packages/toolkit/remark-container/src/index.ts

修复 remark-container 在遇到 :::tip{title=xxx} 用法时的边界问题。

fix: remark container plugin title

---

.changeset/funny-rivers-cross.md
packages/runtime/plugin-runtime/src/router/runtime/utils.tsx
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/guides/basic-features/routes.md
packages/toolkit/main-doc/zh/guides/basic-features/routes.md
packages/toolkit/types/cli/index.d.ts

fix: loadable component should not be wrapped in suspense

---

.changeset/tidy-coats-laugh.md
packages/cli/doc-core/src/node/constants.ts
packages/cli/doc-core/src/node/mdx/remarkPlugins/checkDeadLink.ts
packages/cli/doc-core/src/node/mdx/remarkPlugins/normalizeLink.ts
packages/cli/doc-core/src/shared/utils/index.ts

文档框架支持引入静态图片资源，有两种方式:
- 绝对路径引入(从根目录 public 寻找)
- 相对路径引入

feat: doc-tools support static image

---

.changeset/fuzzy-files-fix.md
packages/builder/plugin-swc/src/plugin.ts
packages/builder/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
packages/cli/babel-preset-app/src/common.ts
packages/cli/babel-preset-app/tests/common.test.ts
packages/toolkit/utils/src/index.ts
packages/toolkit/utils/src/react.ts
pnpm-lock.yaml
website/builder/src/en/plugins/plugin-swc.md
website/builder/src/zh/plugins/plugin-swc.md

取消 swc 插件探测 tsconfig 逻辑，并和现有默认 babel 行为保持一致

fix(builder-plugin-swc): disable detect tsconfig.json

---

.changeset/chilled-steaks-explain.md
website/builder/src/zh/plugins/plugin-swc.md

fix: fix doc description

---

.changeset/giant-fireants-hope.md
packages/generator/generators/module-generator/templates/ts-template/tsconfig.json.handlebars

chore: update module ts-template

---

.changeset/slow-walls-compare.md
packages/generator/generators/storybook-generator/src/index.ts

fix: storybook template update tsconfig not work

---

.changeset/rare-teachers-jump.md
packages/generator/new-action/src/module.ts
packages/generator/new-action/src/monorepo.ts
packages/generator/new-action/src/mwa.ts
tests/generator/utils/command.ts

fix: new action dist tag version

---

.changeset/orange-apricots-listen.md
packages/solutions/app-tools/src/analyze/constants.ts
packages/solutions/app-tools/src/analyze/templates.ts
packages/solutions/app-tools/tests/analyze/__snapshots__/templates.test.ts.snap
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/guides/basic-features/routes.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/guides/topic-detail/micro-frontend/c05-mixed-stack.md
packages/toolkit/main-doc/zh/components/enable-bff.md
packages/toolkit/main-doc/zh/configure/app/runtime/intro.md
packages/toolkit/main-doc/zh/guides/basic-features/routes.md
packages/toolkit/main-doc/zh/guides/topic-detail/micro-frontend/c05-mixed-stack.md
pnpm-lock.yaml
tests/integration/routes/src/four/routes/layout.tsx

docs: add docs for config and init

---

tests/integration/garfish/main-router-v6/package.json

fix: test pkg name duplicate

---

.changeset/friendly-points-enjoy.md
packages/generator/generator-utils/src/index.ts
packages/generator/generators/storybook-generator/src/index.ts
packages/generator/new-action/src/module.ts
packages/generator/new-action/src/mwa.ts
tests/generator/utils/prepare.ts

fix: module solution new command install plugin version

---

packages/builder/builder-doc/docs/en/config/output/dataUriLimit.md
packages/builder/builder-doc/docs/en/guide/optimization/inline-assets.md
packages/builder/builder-doc/docs/zh/config/output/dataUriLimit.md
packages/builder/builder-doc/docs/zh/guide/optimization/inline-assets.md

docs: fix asset not inline

---

.changeset/thin-avocados-move.md
packages/runtime/plugin-runtime/package.json
pnpm-lock.yaml

fix: add missing esbuild

---

packages/cli/doc-core/package.json
pnpm-lock.yaml

chore: use workspace instead of specific version

---

.changeset/purple-beds-hide.md
packages/server/server/src/dev-tools/dev-middleware/dev-server-plugin.ts
packages/toolkit/types/server/devServer.d.ts

chore: client protocol configurable in v1

---

.changeset/new-maps-warn.md
packages/cli/doc-core/src/shared/utils/index.test.ts
packages/cli/doc-core/src/shared/utils/index.ts

优化 withBase API，避免重复添加 base 路径

feat: optimize withBase api

---

.changeset/violet-years-beg.md
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/tutorials/first-app/c05-loader.md
packages/toolkit/main-doc/zh/tutorials/first-app/c05-loader.md

docs: modify data loader usage in the tutorial

---

.changeset/fifty-rivers-sing.md
packages/cli/doc-core/src/theme-default/logic/usePrevNextPage.ts

fix: prev-next data empty

---

.changeset/empty-kangaroos-flow.md
.changeset/two-onions-change.md
packages/generator/generators/module-generator/templates/base-template/package.json.handlebars
packages/generator/generators/monorepo-generator/templates/base-template/package.json.handlebars
packages/generator/generators/mwa-generator/templates/base-template/package.json.handlebars

feat: generator template upgrade node version to 16

---

.changeset/shiny-jobs-rule.md
packages/generator/generators/generator-generator/templates/js-template/modern.config.js.handlebars
packages/generator/generators/generator-generator/templates/ts-template/modern.config.ts.handlebars
packages/generator/plugins/generator-plugin/modern.config.js
packages/generator/plugins/generator-plugin/templates/modern.config.js.handlebars
packages/generator/plugins/generator-plugin/templates/modern.config.ts.handlebars
packages/toolkit/create/modern.config.js

fix: micro generator template

---

.changeset/wet-pumpkins-explode.md
packages/solutions/app-tools/src/analyze/nestedRoutes.ts
packages/solutions/app-tools/tests/analyze/fixtures/nested-routes/user/components/index.tsx
packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/configure/app/output/ssg.md
packages/toolkit/types/cli/index.d.ts

fix: an empty layout should not be created

---

PULL_REQUEST_TEMPLATE.md

Current pull request template is too complex, most contributors do not finish the full template, so I simplified the template to make it easier to complete.

chore: simplify Pull Request Template

---

.changeset/few-jokes-run.md
.changeset/lemon-toes-learn.md
packages/cli/plugin-module-babel/package.json
packages/solutions/module-tools/src/cli.ts
packages/solutions/module-tools/src/config/defineConfig.ts
packages/solutions/module-tools/src/config/legacy-schema.ts
packages/solutions/module-tools/src/config/normalize.ts
packages/solutions/module-tools/src/config/schema.ts
packages/solutions/module-tools/src/config/transform-legacy-config.ts
packages/solutions/module-tools/src/constants/build-presets.ts
packages/solutions/module-tools/src/constants/legacy-build-presets.ts
packages/solutions/module-tools/src/index.ts
packages/solutions/module-tools/src/types/index.ts
packages/solutions/module-tools/src/types/legacyConfig/index.ts
packages/solutions/module-tools/src/types/legacyConfig/output.ts
packages/solutions/module-tools/src/types/legacyConfig/source.ts
packages/solutions/module-tools/src/types/legacyConfig/tools.ts
packages/solutions/module-tools/src/utils/config.ts

add defineLegacyConfig function

feat: add defineLegacyConfig function

---

packages/builder/builder-shared/src/types/builder.ts

chore: builderInstance add onDevCompileDone type

---

.changeset/polite-candles-do.md
packages/builder/builder-shared/src/openBrowser.ts
packages/builder/builder-shared/src/openChrome.applescript

fix(builder): add openChrome applescript for openBrowser

---

.changeset/tough-suns-eat.md
packages/cli/doc-core/src/node/virtualModule/siteData.ts
packages/cli/doc-core/src/shared/types/index.ts
website/main/src/pages/index.tsx

1. 优化 doc-tools 打包后的 js bundle 体积 （主站首屏 JS 产物 800+ KB -> 200 KB ）
2. 修复 modern 主站打包错误 `window is not defined`

feat: optimize js bundle in doc

---

.changeset/perfect-cows-kick.md
packages/builder/builder-webpack-provider/src/plugins/define.ts

Refer to https://github.com/modern-js-dev/modern.js/issues/2692

feat: plugin define accept `undefined`

---

.changeset/sweet-numbers-fry.md
jest.config.js
package.json
packages/runtime/plugin-garfish/package.json
packages/runtime/plugin-router-v5/package.json
packages/runtime/plugin-runtime/jest.config.js
packages/runtime/plugin-runtime/package.json
packages/runtime/plugin-runtime/src/router/cli/index.ts
packages/runtime/plugin-runtime/src/router/runtime/plugin.node.tsx
packages/runtime/plugin-runtime/src/ssr/cli/index.ts
packages/server/create-request/package.json
pnpm-lock.yaml

all runtime package use /treeshaking instead /node for ssr bundle.

feat: use treeshaking production for ssr bundle

---

tests/generator/monorepo.ts
tests/generator/mwa.ts

feat: generator test support custom node version

---

packages/builder/builder-doc/docs/en/api/builder-core.mdx
packages/builder/builder-doc/docs/en/api/plugin-hooks.mdx
packages/builder/builder-doc/docs/en/guide/faq/general.md
packages/builder/builder-doc/docs/en/guide/glossary.mdx
packages/builder/builder-doc/docs/en/guide/introduction.mdx
packages/builder/builder-doc/docs/en/guide/quick-start.mdx
packages/builder/builder-doc/docs/en/plugins/introduction.md
packages/builder/builder-doc/docs/zh/api/builder-core.mdx
packages/builder/builder-doc/docs/zh/api/plugin-hooks.mdx
packages/builder/builder-doc/docs/zh/guide/faq/general.md
packages/builder/builder-doc/docs/zh/guide/glossary.mdx
packages/builder/builder-doc/docs/zh/guide/introduction.mdx
packages/builder/builder-doc/docs/zh/plugins/introduction.md
packages/cli/doc-core/src/theme-default/components/Overview/index.tsx
packages/cli/doc-core/src/theme-default/layout/DocLayout/index.module.scss
packages/toolkit/main-doc/en/guides/basic-features/builder.mdx
packages/toolkit/main-doc/zh/guides/basic-features/builder.mdx

- Improve Rspack spelling (Rspack, not rspack)
- Adjust description of Turbopack.

docs(Builder): improve Rspack spelling

---

.changeset/sour-cooks-wink.md
website/module-tools/docs/en/guide/advance/in-depth-about-dev-command.md
website/module-tools/docs/en/guide/basic/before-getting-started.md
website/module-tools/docs/en/guide/basic/command-preview.md
website/module-tools/docs/en/guide/basic/modify-output-product.md
website/module-tools/docs/en/guide/basic/use-micro-generator.md
website/module-tools/docs/en/guide/basic/using-storybook.mdx
website/module-tools/docs/en/guide/intro/getting-started.md
website/module-tools/docs/zh/guide/advance/in-depth-about-dev-command.md
website/module-tools/docs/zh/guide/basic/before-getting-started.md
website/module-tools/docs/zh/guide/basic/command-preview.md
website/module-tools/docs/zh/guide/basic/modify-output-product.md
website/module-tools/docs/zh/guide/basic/publish-your-project.md
website/module-tools/docs/zh/guide/basic/test-your-project.mdx
website/module-tools/docs/zh/guide/basic/use-micro-generator.md
website/module-tools/docs/zh/guide/basic/using-storybook.mdx
website/module-tools/docs/zh/guide/intro/getting-started.md

Docs module content optimiz

---

packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/default.test.ts.snap
packages/builder/builder-webpack-provider/tests/plugins/default.test.ts

chore: add snapshot for webpack provider

---

.changeset/hungry-gorillas-destroy.md
packages/solutions/module-tools/package.json
pnpm-lock.yaml

chore: update version

---

.changeset/tender-jeans-eat.md
packages/server/server/src/dev-tools/dev-middleware/hmr-client/createSocketUrl.ts

fix: protocol set error in v1

---

.changeset/tender-jeans-provide.md
packages/server/server/src/dev-tools/dev-middleware/hmr-client/createSocketUrl.ts

fix: protocol set error

---

.changeset/three-moles-confess.md
packages/toolkit/module-doc/docs/en/plugins/guide/getting-started.mdx
packages/toolkit/module-doc/docs/zh/plugins/guide/getting-started.mdx

docs: fix code symbols error

---

packages/builder/builder-doc/docs/en/plugins/plugin-stylus.mdx
packages/toolkit/module-doc/docs/en/guide/intro/getting-started.md
packages/toolkit/module-doc/docs/en/index.md
packages/toolkit/module-doc/docs/zh/index.md

- Fix welcome link in english document
- Add Quick Start button

docs(module): fix welcome link in english document

---

.changeset/three-ducks-try.md
packages/generator/generator-utils/src/index.ts

fix: use yarn not get right package version

---

.changeset/rotten-taxis-relax.md
packages/solutions/module-tools/src/constants/colors.ts
packages/solutions/module-tools/src/dev.ts

feat: change dev log color

---

.github/workflows/build-builder-website.yml
.github/workflows/build-module-website.yml

Fix failed to build module-tools website:
https://github.com/modern-js-dev/modern.js/actions/runs/4073836545/jobs/7018240543

chore(module-tools): fix failed to build website

---

packages/toolkit/main-doc/en/guides/advanced-features/ssr.mdx
packages/toolkit/main-doc/zh/guides/advanced-features/ssr.mdx
packages/toolkit/main-doc/zh/guides/topic-detail/generator/plugin/develop.mdx
pnpm-lock.yaml

fix: compat doc

---

.changeset/funny-swans-shop.md
packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/default.test.ts.snap
packages/builder/builder/src/plugins/devtool.ts
pnpm-lock.yaml

feat: use 'devtool: source-map' for ssr webpack bundle

---

.changeset/modern-pears-buy.md
packages/generator/generator-common/src/locale/en.ts
packages/generator/generators/entry-generator/CHANGELOG.md
packages/solutions/app-tools/src/locale/zh.ts
packages/toolkit/create/src/locale/zh.ts
packages/toolkit/main-doc/en/components/init-app.mdx
packages/toolkit/main-doc/en/guides/topic-detail/generator/config/app.mdx
packages/toolkit/main-doc/en/guides/topic-detail/generator/plugin/api/new/createElement.mdx
packages/toolkit/main-doc/en/guides/topic-detail/generator/plugin/api/new/enableFunc.mdx
packages/toolkit/main-doc/en/guides/topic-detail/generator/plugin/api/new/introduce.mdx
packages/toolkit/main-doc/en/guides/topic-detail/generator/plugin/develop.mdx
packages/toolkit/main-doc/zh/guides/topic-detail/generator/config/app.mdx
packages/toolkit/main-doc/zh/guides/topic-detail/generator/plugin/api/new/createElement.mdx
packages/toolkit/main-doc/zh/guides/topic-detail/generator/plugin/api/new/enableFunc.mdx
packages/toolkit/main-doc/zh/guides/topic-detail/generator/plugin/api/new/introduce.mdx
tests/integration/garfish/dashboard-router-v6/README.md
tests/integration/garfish/main-router-v6/README.md

`MWA` may confuses users, `Web App` will be clearer.

chore: rename MWA to Web App

---

.changeset/dull-hornets-learn.md
packages/generator/generator-utils/src/index.ts
packages/generator/generators/bff-generator/src/index.ts
packages/generator/generators/bff-generator/src/locale/en.ts
packages/generator/generators/bff-generator/src/locale/zh.ts
packages/generator/generators/dependence-generator/src/index.ts
packages/generator/generators/dependence-generator/src/locale/en.ts
packages/generator/generators/dependence-generator/src/locale/zh.ts
packages/generator/generators/module-test-generator/src/locale/en.ts
packages/generator/generators/module-test-generator/src/locale/zh.ts
packages/generator/generators/router-v5-generator/src/index.ts
packages/generator/generators/router-v5-generator/src/locale/en.ts
packages/generator/generators/router-v5-generator/src/locale/zh.ts
packages/generator/generators/ssg-generator/src/index.ts
packages/generator/generators/ssg-generator/src/locale/en.ts
packages/generator/generators/ssg-generator/src/locale/zh.ts
packages/generator/generators/storybook-generator/src/locale/en.ts
packages/generator/generators/storybook-generator/src/locale/zh.ts
packages/generator/generators/test-generator/src/locale/en.ts
packages/generator/generators/test-generator/src/locale/zh.ts
packages/generator/new-action/src/test.ts
pnpm-lock.yaml
tests/integration/load-config/fixtures/async-config-function/package.json
tests/integration/routes/tests/index.test.ts
tests/integration/routes/tsconfig.json

feat: new command code tooltip highlight

---

packages/builder/builder-doc/docs/en/plugins/plugin-swc.mdx
packages/builder/builder-doc/docs/zh/plugins/plugin-swc.mdx

Fix CI failure because of dead links.

docs(plugin-swc): fix dead links

---

.changeset/soft-moose-perform.md
packages/cli/doc-core/package.json
packages/cli/doc-core/src/node/virtualModule/globalStyles.ts
packages/cli/doc-core/src/node/virtualModule/index.ts
packages/cli/doc-core/src/shared/types/global.d.ts
packages/cli/doc-core/src/shared/types/index.ts
packages/cli/doc-core/src/theme-default/layout/Layout/index.tsx

feat(doc-core): support global styles

---

packages/builder/plugin-swc/package.json
pnpm-lock.yaml

chore: update

---

packages/builder/builder-doc/docs/en/plugins/plugin-swc.mdx
packages/builder/builder-doc/docs/zh/plugins/plugin-swc.mdx
packages/builder/builder-rspack-provider/src/config/validate/dev.ts
packages/builder/builder-rspack-provider/src/config/validate/html.ts
packages/builder/builder-rspack-provider/src/config/validate/index.ts
packages/builder/builder-rspack-provider/src/config/validate/output.ts
packages/builder/builder-rspack-provider/src/config/validate/performance.ts
packages/builder/builder-rspack-provider/src/config/validate/source.ts
packages/builder/builder-rspack-provider/src/config/validate/tools.ts
packages/builder/builder-rspack-provider/src/core/createContext.ts
packages/builder/builder-rspack-provider/tests/core/validate.test.ts
packages/builder/builder-shared/src/schema/index.ts
packages/builder/builder-shared/src/schema/performance.ts
packages/builder/builder-shared/src/schema/source.ts
packages/builder/builder-shared/src/schema/tools.ts
packages/builder/builder-webpack-provider/src/config/validate/tools.ts

feat: add schema validator for rspack provider

---

.changeset/hungry-humans-hope.md
packages/cli/doc-core/src/theme-default/components/Siderbar/index.tsx
packages/toolkit/main-doc/en/guides/advanced-features/_category_.json
packages/toolkit/main-doc/en/guides/basic-features/_category_.json
packages/toolkit/main-doc/en/guides/concept/_category_.json
packages/toolkit/main-doc/en/guides/get-started/_category_.json
website/main/src/pages/index.tsx

fix: modernjs 2.0 doc

---

.github/workflows/build-main-website.yml
website/main/blog/2022-11.01-release.md
website/main/docusaurus.config.js
website/main/i18n/zh-cn/docusaurus-plugin-content-docs/current.json
website/main/navbar.js

- Deploy v1 website to `https://modernjs.dev/v1/`
- Add version links to header nav.

docs: deploy v1 website

---

.changeset/clever-beds-notice.md
packages/builder/builder-rspack-provider/src/plugins/resolve.ts
packages/builder/builder-rspack-provider/tests/plugins/__snapshots__/default.test.ts.snap
packages/builder/builder-shared/src/apply/index.ts
packages/builder/builder-shared/src/apply/resolve.ts
packages/builder/builder-webpack-provider/src/plugins/resolve.ts
packages/builder/builder-webpack-provider/tests/plugins/resolve.test.ts
packages/solutions/app-tools/src/builder/builder-rspack/index.ts
packages/solutions/app-tools/src/builder/builder-webpack/index.ts
packages/solutions/app-tools/src/builder/generator/createBuilderProviderConfig.ts
packages/solutions/app-tools/src/builder/generator/index.ts
packages/solutions/app-tools/tests/builder/__snapshots__/index.test.ts.snap
tests/integration/builder-rspack/tests/index.test.ts

fix: the builder resolve plugin
1. Sink builder resolve login into builder shared
2. Modify bundlerConfig by `bundlerChain`
3. Make the framework using builder more convenient

fix: change the builder resolve plugin

---

packages/runtime/plugin-runtime/src/document/Body.tsx
packages/runtime/plugin-runtime/src/document/DocumentStructureContext.tsx
packages/runtime/plugin-runtime/src/document/Head.tsx
packages/runtime/plugin-runtime/src/document/Html.tsx
packages/runtime/plugin-runtime/src/document/index.ts

fix: typo of @piajs/plugin-runtime/document

---

.changeset/bright-garlics-join.md
README.md
packages/server/server/src/dev-tools/dev-middleware/hmr-client/index.ts

Add HMR connected log, notify users that the HMR has successfully connected.

feat(hmr-client): add HMR connected log

---

tests/e2e/builder/scripts/shared.ts
tests/e2e/builder/tests/performance.test.ts

fix: port conflict error when execute builder test cases in parallel

---

.changeset/nervous-dolls-develop.md
packages/cli/doc-core/src/node/mdx/remarkPlugins/toc.ts

feat: optimize doc bundle

---

.changeset/nervous-dolls-develop.md
packages/cli/doc-core/src/node/mdx/remarkPlugins/toc.ts

fix(doc-core): restore title in toc plugin

---

packages/builder/builder-rspack-provider/src/core/build.ts

fix: stats check

---

.changeset/tidy-fans-cover.md
packages/builder/builder-rspack-provider/src/plugins/basic.ts
packages/builder/builder-rspack-provider/src/plugins/less.ts
packages/builder/builder-rspack-provider/src/types/hooks.ts
packages/builder/builder-shared/src/apply/basic.ts
packages/builder/builder-shared/src/apply/index.ts
packages/builder/builder-shared/src/types/bundlerConfig.ts
packages/builder/builder-shared/src/types/config/index.ts
packages/builder/builder-shared/src/types/hooks.ts
packages/builder/builder-webpack-provider/src/plugins/basic.ts
packages/builder/builder-webpack-provider/src/plugins/css.ts
packages/builder/builder-webpack-provider/src/plugins/less.ts
packages/builder/builder-webpack-provider/src/plugins/sass.ts
packages/builder/builder-webpack-provider/src/types/hooks.ts
packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/default.test.ts.snap

feat: more use bunlder chain to modify bundler config

refactor: more use bundler chain to modify bundler config 

---

.changeset/big-hornets-remember.md
packages/solutions/module-tools/src/builder/build.ts
packages/solutions/module-tools/src/builder/dts/rollup.ts
packages/solutions/module-tools/src/builder/dts/tsc.ts
packages/solutions/module-tools/src/builder/index.ts
packages/solutions/module-tools/src/constants/log.ts
packages/solutions/module-tools/src/utils/print.ts

```bash
cd packages/solutions/doc-tools 
pnpm run  build
```
You will see

feat(module-tools): report size and info after build

---

tests/integration/server-hook/router/test/index.test.ts

fix: server hook test

---

.github/workflows/integration-test-Windows.yml
.github/workflows/integration-test-macOS.yml
.github/workflows/test-Windows.yml
.github/workflows/test-macOS.yml
.github/workflows/type-check.yml
scripts/skip-docs-change.js

Revert "chore(CI): ignore test when only change doc (#2810)"

---

.github/workflows/test-macOS.yml
packages/builder/builder-doc/docs/zh/index.md
scripts/skip-docs-change.js

- Update skip docs change folders.
- Fix macOS CI failure when updating docs:

chore(CI): update skip docs change folders

---

.github/workflows/lint-Linux.yml
.github/workflows/test-Windows.yml
.github/workflows/test-macOS.yml
.github/workflows/type-check.yml

Add merge_group as trigger to use the merge queue.

chore(CI): add merge_group as trigger

---

packages/toolkit/main-doc/en/tutorials/foundations/introduction.mdx
packages/toolkit/main-doc/zh/tutorials/foundations/introduction.mdx
website/main/src/i18n/en-US.ts
website/main/src/i18n/zh-CN.ts
website/main/src/theme/Footer/index.tsx

Remove Lark link from Modern.js website.

docs: remove Lark link

---

.changeset/few-jeans-mix.md
packages/cli/doc-core/src/theme-default/components/HomeFeatures/index.tsx
packages/cli/doc-core/src/theme-default/components/HomeFooter/index.tsx
packages/cli/doc-core/src/theme-default/components/HomeHero/index.tsx

feat: optimize home layout

---

packages/server/plugin-worker/package.json

fix: plugin worker types path

---

packages/solutions/app-tools/src/types/config/tools.ts

fix: RsBuilderToolsConfig type

---

packages/runtime/plugin-router-v5/src/runtime/plugin.tsx

before: 
```ts
const Main = ({ children }) => {
return <>{children}<>
}
```
after:
```ts
const Main = ({ Component }) => {
return <Component {...otherParams} />
}
```

feat: change createRoutes return React.Component

---

.changeset/light-dragons-occur.md
packages/cli/doc-core/src/node/build.ts
packages/cli/doc-core/src/node/createBuilder.ts
packages/cli/doc-core/src/node/dev.ts
packages/cli/doc-core/src/node/hooks.ts
packages/cli/doc-core/src/shared/types/Plugin.ts

feat: add beforeBuild and afterBuild in doc plugin

---

.changeset/spicy-years-learn.md
packages/server/server/src/dev-tools/register/index.ts

fix: ts-node should compile scopeDir only

---

.changeset/khaki-owls-press.md
packages/runtime/plugin-garfish/src/cli/utils.ts

fix(garfish): pass basename as props to root component

---

packages/toolkit/main-doc/zh/guides/topic-detail/micro-frontend/c02-development.mdx

docs(garfish): add manual for what garfish plugin doing

---

packages/toolkit/module-doc/docs/en/guide/intro/getting-started.md
packages/toolkit/module-doc/docs/zh/guide/intro/getting-started.md

docs: fix getting-started

---

.changeset/thick-lobsters-walk.md
packages/cli/doc-core/src/node/createBuilder.ts
packages/cli/doc-core/src/node/mdx/remarkPlugins/normalizeLink.ts
packages/cli/doc-core/src/theme-default/components/HomeFeatures/index.tsx
packages/cli/doc-core/src/theme-default/components/Overview/index.tsx
packages/cli/doc-core/src/theme-default/components/Siderbar/index.tsx

修复问题:
1. normalizeLink 插件中哈希经过 slugger 处理，可能会追加 `-1`、`-2` 等后缀，导致锚点无法正常跳转
2. 解决部分情况下 Overview 页面不展示的问题
3. 优化部分样式

fix(doc-core): hash error

---

.changeset/long-dogs-count.md
packages/builder/builder-doc/package.json
packages/cli/doc-core/src/node/build.ts
packages/cli/doc-core/src/node/constants.ts
packages/cli/doc-core/src/node/createBuilder.ts
packages/cli/doc-core/src/runtime/index.ts
packages/cli/doc-core/src/theme-default/components/Search/index.tsx
packages/cli/doc-core/src/theme-default/logic/useAppearance.ts
packages/toolkit/module-doc/package.json
website/main/package.json
website/main/src/pages/index.tsx

主要功能: 
- 优化 polyfill bundle 体积，由 182 KB -> 66 KB，减少 116 KB 产物体积(gzip 压缩前)
- 暴露 Helmet 的 runtime API，用于自定义 html 标签内容
修复问题:
- 避免首屏加载 search_index 文件，点击搜索框进行按需加载
- 修复 Modern.js 官网导航栏闪烁及主题切换按钮无法隐藏的问题

feat: optimzie polyfill bundle

---

packages/toolkit/main-doc/en/apis/app/commands/new.mdx
packages/toolkit/main-doc/en/apis/app/runtime/core/use-module-apps.mdx
packages/toolkit/main-doc/en/apis/app/runtime/model/connect.mdx
packages/toolkit/main-doc/en/apis/app/runtime/model/handle-effect.mdx
packages/toolkit/main-doc/en/apis/app/runtime/web-server/hook.mdx
packages/toolkit/main-doc/en/apis/app/runtime/web-server/middleware.mdx
packages/toolkit/main-doc/en/configure/app/runtime/intro.mdx
packages/toolkit/main-doc/en/configure/app/server/base-url.mdx
packages/toolkit/main-doc/en/guides/advanced-features/bff/frameworks.mdx
packages/toolkit/main-doc/en/guides/advanced-features/compatibility.mdx
packages/toolkit/main-doc/en/guides/advanced-features/ssg.mdx
packages/toolkit/main-doc/en/guides/advanced-features/testing.mdx
packages/toolkit/main-doc/en/guides/basic-features/data-fetch.mdx
packages/toolkit/main-doc/en/guides/basic-features/routes.mdx

Fix some missing translations.

docs: fix some missing translations

---

.changeset/two-berries-chew.md
packages/cli/doc-core/src/runtime/App.tsx

Fix failed to custom `Theme.Layout`.
```ts
// src/index.ts
import Theme from '@modern-js/doc-tools/theme';
import Layout from './MyLayout';
...Theme,
Layout,
};
```

fix(doc-core): failed to custom Theme.Layout

---

.changeset/curvy-queens-fetch.md
packages/cli/doc-core/src/node/searchIndex.ts
packages/cli/doc-core/src/node/utils/createHash.ts
packages/cli/doc-core/src/node/utils/index.ts
packages/cli/doc-core/src/node/virtualModule/siteData.ts
packages/cli/doc-core/src/shared/types/global.d.ts
packages/cli/doc-core/src/shared/utils/index.ts
packages/cli/doc-core/src/theme-default/components/Search/logic/providers/LocalProvider.ts

feat: add hash for search index file

---

packages/runtime/plugin-runtime/src/ssr/cli/index.ts
packages/runtime/plugin-runtime/src/ssr/serverRender/renderToStream/renderToPipe.worker.ts

fix: loadable plugin

---

.changeset/serious-boats-sparkle.md
packages/cli/doc-core/src/node/virtualModule/siteData.ts
packages/cli/doc-core/src/runtime/hooks.ts

feat(doc-core): useLang hook

---

packages/builder/builder-doc/docs/en/api/config-tools.mdx
packages/builder/builder-doc/docs/en/config/tools/rspack.md
packages/builder/builder-doc/docs/en/config/tools/webpack.md
packages/builder/builder-doc/docs/zh/api/config-tools.mdx
packages/builder/builder-doc/docs/zh/config/tools/rspack.md

docs: add tools.rspack config

---

.changeset/shaggy-baboons-fry.md
packages/cli/doc-core/package.json
packages/cli/doc-core/src/runtime/Content.tsx
packages/cli/doc-core/src/theme-default/layout/DocLayout/index.tsx
packages/cli/doc-core/src/theme-default/logic/sideEffects.ts
packages/cli/doc-core/src/theme-default/styles/base.css
pnpm-lock.yaml

feat(doc-core): support image zoom

---

packages/builder/builder-doc/docs/components/Step.tsx
packages/builder/builder-doc/docs/utils.ts
packages/cli/doc-core/src/runtime/hooks.ts
website/main/src/i18n/index.ts

Fix broken links in Step component.

docs(builder): fix broken links in Step component

---

packages/builder/builder-doc/docs/en/config/output/externals.md
packages/builder/builder-doc/docs/en/config/performance/chunkSplit.md
packages/builder/builder-doc/docs/en/config/source/alias.md
packages/builder/builder-doc/docs/en/config/source/define.md
packages/builder/builder-doc/docs/zh/config/output/externals.md
packages/builder/builder-doc/docs/zh/config/performance/chunkSplit.md
packages/builder/builder-doc/docs/zh/config/source/alias.md
packages/builder/builder-doc/docs/zh/config/source/define.md

docs(builder): add rspack tip when some config exist differences

---

tests/integration/swc/fixtures/transform-fail/package.json

change transform-fail test name

chore: change transform-fail test name

---

.changeset/dirty-wasps-hang.md
packages/toolkit/module-doc/docs/en/guide/advance/external-dependency.mdx
packages/toolkit/module-doc/docs/zh/guide/advance/external-dependency.mdx

modify [How to handle third-party dependencies] contents

docs(module-tools): modify contents

---

.changeset/tender-emus-fail.md
packages/cli/plugin-storybook/src/index.ts

remove dist dir when run `modern build`

fix(plugin-storybook): remove dist dir when build

---

packages/toolkit/main-doc/scripts/config.ts

Should generate comma by language.

chore: should generate comma by language

---

.changeset/chilled-moose-press.md
packages/cli/doc-core/LICENSE
packages/cli/doc-core/README.md
packages/cli/doc-core/package.json
packages/cli/doc-plugin-auto-sidebar/LICENSE
packages/cli/doc-plugin-auto-sidebar/README.md
packages/cli/doc-plugin-auto-sidebar/package.json
packages/solutions/doc-tools/LICENSE
packages/solutions/doc-tools/README.md
packages/solutions/doc-tools/package.json

Fix README and license of doc-tools.

chore: fix README and license of doc-tools

---

.changeset/sixty-crews-jam.md
packages/cli/doc-core/src/theme-default/components/Nav/index.module.scss
packages/cli/doc-core/src/theme-default/components/Nav/index.tsx
packages/cli/doc-core/src/theme-default/layout/Layout/index.tsx
packages/cli/doc-core/src/theme-default/logic/sideEffects.ts

fix(doc-core): home page title

---

.changeset/rare-drinks-act.md
packages/generator/generators/module-generator/templates/base-template/package.json.handlebars

fix: add build:watch and remove test scripts

---

.changeset/moody-cameras-attack.md

chore: fix stale changset

---

.changeset/stupid-foxes-stare.md
packages/cli/plugin-storybook/modern.config.js
packages/cli/plugin-storybook/src/features/utils/genConfigDir.ts

remove `require` and fix template error path

fix(plugin-storybook): fix template path

---

.changeset/bright-adults-prove.md
.changeset/metal-boats-fly.md
packages/solutions/module-tools/src/config/normalize.ts
packages/solutions/module-tools/src/config/schema.ts
packages/solutions/module-tools/src/constants/build-presets.ts
packages/solutions/module-tools/src/types/config/index.ts
packages/solutions/module-tools/tests/buildPreset.test.ts
packages/solutions/module-tools/tests/fixtures/buildPreset/extend-preset.config.ts
packages/solutions/module-tools/tests/fixtures/buildPreset/function/src/utils.js
packages/toolkit/module-doc/docs/en/api/config/build-preset.mdx
packages/toolkit/module-doc/docs/zh/api/config/build-preset.mdx
scripts/build/src/index.js

add new buildPreset and utils function

feat: add new preset and preset utils

---

.changeset/few-roses-walk.md
packages/cli/plugin-data-loader/src/cli/loader.ts
packages/server/utils/tests/ts.test.ts

fix: worker use loader error

---

.changeset/pretty-boxes-try.md
packages/runtime/plugin-router-v5/src/cli/index.ts
packages/runtime/plugin-runtime/src/router/cli/index.ts
packages/solutions/app-tools/src/analyze/generateCode.ts
packages/solutions/app-tools/src/analyze/getBundleEntry.ts
packages/solutions/app-tools/src/analyze/getFileSystemEntry.ts
packages/toolkit/utils/src/is/index.ts

fix: should not assign nestedRoutesEntry to entrypoint if use v5 router

---

packages/toolkit/module-doc/docs/en/api/config/build-config.md
packages/toolkit/module-doc/docs/zh/api/config/build-config.md

docs: add tip for style-inject and umdModuleName

---

.changeset/breezy-scissors-sort.md
packages/builder/builder-shared/src/schema/dev.ts

Fix missing dev.beforeStartUrl schema validation

fix(builder): missing dev.beforeStartUrl schema validation

---

.changeset/short-turtles-listen.md
packages/toolkit/main-doc/en/guides/topic-detail/micro-frontend/c03-main-app.mdx
packages/toolkit/main-doc/zh/guides/topic-detail/micro-frontend/c03-main-app.mdx

fix: plugin-garfish docs

---

.changeset/mean-ants-fry.md
packages/toolkit/doc-tools-doc/modern.config.ts
packages/toolkit/doc-tools-doc/package.json
pnpm-lock.yaml

fix(doc-tools-doc):doc tools base

---

.changeset/slow-planes-collect.md
packages/solutions/module-tools/src/command.ts
packages/solutions/module-tools/src/dev.ts
packages/solutions/module-tools/src/hooks/dev.ts
packages/solutions/module-tools/src/locale/en.ts
packages/solutions/module-tools/src/locale/zh.ts

add noDevTools hook, fix dev log content and add chinese and english content

feat: add noDevTools Hook and change dev log

---

.changeset/young-teachers-repair.md
packages/builder/builder-doc/docs/en/config/dev/host.md
packages/builder/builder-doc/docs/zh/config/dev/host.md
packages/builder/builder-shared/src/config.ts
packages/builder/builder-shared/src/devServer.ts
packages/builder/builder-shared/src/types/config/dev.ts
packages/solutions/app-tools/src/commands/dev.ts
packages/toolkit/main-doc/en/configure/app/dev/host.mdx
packages/toolkit/main-doc/zh/configure/app/dev/host.mdx

fix: support configure host for devServer

---

packages/toolkit/main-doc/en/guides/basic-features/data-fetch.mdx
packages/toolkit/main-doc/en/guides/basic-features/routes.mdx
packages/toolkit/main-doc/zh/guides/basic-features/data-fetch.mdx
packages/toolkit/main-doc/zh/guides/basic-features/routes.mdx

docs: add redirect guide doc

---

.changeset/three-goats-press.md
packages/solutions/module-tools/src/builder/dts/rollup.ts

fix(module-tools): set composite false when bundle dts

---

.changeset/dry-emus-flash.md
packages/solutions/module-tools/src/builder/copy.ts

fix(module-tools): fix copy context error path

---

packages/server/plugin-worker/package.json
pnpm-lock.yaml

feat: remove wrangler dep

---

.changeset/new-terms-type.md
packages/builder/builder-rspack-provider/src/plugins/swc.ts
packages/builder/builder-rspack-provider/src/shared/plugin.ts
packages/builder/builder-rspack-provider/tests/plugins/__snapshots__/default.test.ts.snap
packages/builder/builder-rspack-provider/tests/plugins/__snapshots__/swc.test.ts.snap
packages/builder/builder-rspack-provider/tests/plugins/swc.test.ts
packages/builder/plugin-swc/src/plugin.ts

给 Rspack provider 增加 swc 相关配置项，增加 builder-plugin-swc overrideBrowserslist 配置，在 builder-plugin-swc 启用 latestDecorator 后增加 warning 报错

feat(rspack-provider): add swc plugin

---

.changeset/ninety-falcons-nail.md
packages/builder/builder-rspack-provider/src/plugins/hmr.ts
packages/builder/builder-rspack-provider/src/plugins/react.ts
packages/builder/builder-shared/src/apply/hmr.ts
packages/builder/builder-shared/src/apply/index.ts
packages/builder/builder-webpack-provider/src/plugins/hmr.ts
packages/builder/builder-webpack-provider/src/plugins/react.ts
packages/builder/plugin-swc/package.json
packages/builder/plugin-swc/src/plugin.ts
packages/builder/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
packages/builder/plugin-swc/tests/plugin.test.ts
pnpm-lock.yaml

react refresh should use in web broswer,
it seems inject a RefreshReg function call.
so we need disable it when ssr mode

fix: disable swc react refresh when ssr mode.|

---

.github/workflows/test-builder-e2e.yml

fix: builder e2e script

---

.changeset/eighty-months-fry.md
packages/builder/plugin-swc/src/plugin.ts

Should bypass extensions to loader

fix(plugin-swc): should pass extensions to loader

---

.changeset/few-fans-live.md
packages/cli/plugin-ssg/src/server/index.ts
packages/cli/plugin-ssg/src/server/process.ts

fix(plugin-ssg): ssg error reporting inaccuracy problem

---

.github/workflows/test-builder-e2e.yml

fix: build e2e test workflow

---

.changeset/calm-pigs-chew.md
packages/server/server/src/server/devServer.ts
pnpm-lock.yaml

fix: modern should not serve static file extra, dev-server-middleware serve it

---

packages/toolkit/main-doc/en/configure/app/server/ssr.mdx
packages/toolkit/main-doc/zh/configure/app/server/ssr.mdx

chore: add force csr docs

---

tests/integration/ssr/test/base.test.js
tests/integration/ssr/test/streaming.test.js

feat: skip timeout test case

---

packages/cli/doc-core/src/theme-default/components/Button/index.module.scss
packages/cli/doc-core/src/theme-default/components/HomeFeatures/index.tsx
packages/cli/doc-core/src/theme-default/components/HomeHero/index.tsx
packages/cli/doc-core/src/theme-default/components/Nav/index.tsx
packages/cli/doc-core/src/theme-default/components/NavScreen/index.module.scss
packages/cli/doc-core/src/theme-default/components/NavScreen/index.tsx
packages/cli/doc-core/src/theme-default/components/NavScreenMenuGroup/NavScreenMenuGroup.tsx
packages/cli/doc-core/src/theme-default/logic/utils.ts
packages/cli/doc-core/src/theme-default/styles/doc.css

优化文档样式:
1. 移动端隐藏 header-anchor
2. 移动端支持展示分组 Group
3. 移动端代码块左右 margin 留白，优化阅读体验
4. 主页样式代码收敛到 className，后续其它组件样式会陆续迁移，最终使用 tailwind
修复问题: 
- 移动端 Menu 暗黑模式按钮点击无反应

feat(doc-core): improve doc style in mobile devices

---

.changeset/silly-eagles-grin.md
packages/builder/builder-rspack-provider/package.json
packages/builder/builder-rspack-provider/src/plugins/output.ts
packages/builder/builder-rspack-provider/src/plugins/swc.ts
packages/builder/builder-rspack-provider/src/types/config/output.ts
packages/builder/builder-rspack-provider/tests/plugins/__snapshots__/default.test.ts.snap
packages/builder/builder-rspack-provider/tests/plugins/__snapshots__/output.test.ts.snap
packages/builder/builder-rspack-provider/tests/plugins/__snapshots__/swc.test.ts.snap
packages/builder/builder-rspack-provider/tests/plugins/output.test.ts
packages/builder/builder-rspack-provider/tests/plugins/swc.test.ts
pnpm-lock.yaml

Add copy support and add alias of core-js

feat(builder): add copy support and add alias of core-js

---

.changeset/five-teachers-shout.md
packages/solutions/module-tools/package.json
packages/solutions/module-tools/scripts/debug-mode.js
packages/solutions/module-tools/src/builder/build.ts
packages/solutions/module-tools/src/builder/copy.ts
packages/solutions/module-tools/src/constants/log.ts
packages/solutions/module-tools/src/utils/log.ts
pnpm-lock.yaml

add watch feature to copy api.

feat(module-tools): add watch feature to copy api

---

.changeset/sharp-eggs-provide.md
packages/generator/generators/storybook-generator/src/index.ts

remove runtime dep for storybook

feat(generator): remove runtime dep for storybook

---

.changeset/thin-rivers-move.md
packages/cli/plugin-storybook/src/features/build.ts
packages/cli/plugin-storybook/src/features/dev.ts
packages/cli/plugin-storybook/src/features/utils/check.ts
packages/cli/plugin-storybook/src/features/utils/genConfigDir.ts
packages/cli/plugin-storybook/src/features/utils/generate.ts
packages/cli/plugin-storybook/template/main.tmpl

Required dependencies of Storybook on runtime dependency

fix: required depenencies of storybook on runtime

---

tests/integration/ssr/fixtures/streaming/src/routes/error/page.tsx
tests/integration/ssr/fixtures/streaming/src/routes/user/[id]/page.loader.ts
tests/integration/ssr/test/streaming.test.js

chore: improve streaming ssr tests

---

packages/toolkit/main-doc/en/guides/advanced-features/ssr.mdx
packages/toolkit/main-doc/zh/guides/advanced-features/ssr.mdx

docs: streaming ssr

---

.changeset/dull-socks-report.md
packages/toolkit/utils/package.json
packages/toolkit/utils/src/index.ts

fix: remove nestedRoutes export

---

tests/integration/ssr/test/base.test.js

feat: skip ssr timeout test

---

.changeset/kind-coats-sip.md
packages/cli/doc-core/modern.config.ts
packages/cli/doc-plugin-auto-sidebar/modern.config.ts
packages/generator/generators/mwa-generator/templates/js-template/modern.config.js.handlebars
packages/generator/generators/mwa-generator/templates/ts-template/modern.config.ts.handlebars
packages/generator/generators/rspack-generator/templates/modern.config.js.handlebars
packages/generator/generators/rspack-generator/templates/modern.config.ts.handlebars
packages/solutions/doc-tools/modern.config.ts
packages/toolkit/remark-container/modern.config.ts
tests/integration/app-document/modern.config.ts
tests/integration/ssr/fixtures/base/modern.config.ts
tests/integration/ssr/fixtures/streaming/modern.config.ts
tests/integration/worker/fixtures/worker-test/modern.config.ts

Update api document link.
- v1: https://modernjs.dev/docs/apis/app/config
- v2: https://modernjs.dev/en/configure/app/usage

fix(generators): update api document link

---

packages/builder/builder-doc/docs/en/config/tools/rspack.md
packages/builder/builder-doc/docs/en/guide/advanced/rspack-start.mdx
packages/builder/builder-doc/docs/en/guide/basic/builder-config.mdx
packages/builder/builder-doc/docs/en/guide/basic/html-template.md
packages/builder/builder-doc/docs/zh/config/tools/rspack.md
packages/builder/builder-doc/docs/zh/guide/advanced/rspack-start.mdx
packages/builder/builder-doc/docs/zh/guide/basic/builder-config.mdx
packages/builder/builder-doc/docs/zh/guide/basic/html-template.md
packages/builder/builder-doc/modern.config.ts
packages/cli/plugin-module-target/README.md
packages/toolkit/doc-tools-doc/docs/en/advanced/extend-build.mdx
packages/toolkit/doc-tools-doc/docs/zh/advanced/extend-build.mdx
packages/toolkit/doc-tools-doc/package.json
packages/toolkit/main-doc/en/guides/advanced-features/rspack-start.mdx
packages/toolkit/main-doc/zh/guides/advanced-features/rspack-start.mdx
packages/toolkit/module-doc/docs/zh/guide/basic/use-micro-generator.md

- rspack.org -> rspack.dev
- edenx.bytedance.net -> modernjs.dev
- update some legacy modern.js links

docs: fix some links

---

.changeset/blue-lizards-end.md
packages/server/server/src/server/devServer.ts
packages/toolkit/main-doc/en/apis/app/runtime/web-server/hook.mdx
packages/toolkit/main-doc/en/apis/app/runtime/web-server/middleware.mdx
packages/toolkit/main-doc/en/configure/app/bff/enable-handle-web.mdx
packages/toolkit/main-doc/en/configure/app/server/enable-framework-ext.mdx
packages/toolkit/main-doc/en/guides/advanced-features/web-server.mdx
packages/toolkit/main-doc/zh/apis/app/runtime/web-server/hook.mdx
packages/toolkit/main-doc/zh/apis/app/runtime/web-server/middleware.mdx
packages/toolkit/main-doc/zh/configure/app/bff/enable-handle-web.mdx
packages/toolkit/main-doc/zh/configure/app/server/enable-framework-ext.mdx
packages/toolkit/main-doc/zh/guides/advanced-features/web-server.mdx

feat: add custom web-server docs

---

.github/workflows/release-pull-request.yml
.github/workflows/release.yml

feat: update release action

---

.changeset/config.json
.github/workflows/release-pull-request.yml

feat: canary version use commit hash

---

.changeset/clever-geckos-listen.md
packages/cli/plugin-changeset/package.json
pnpm-lock.yaml

feat: bump @changesets/cli version

---

.changeset/big-buckets-grab.md
.changeset/seven-fans-shop.md
packages/toolkit/main-doc/en/guides/advanced-features/low-level.mdx

fix(typo): mdx link for Tailwind CSS

---

.changeset/nervous-readers-try.md
packages/cli/plugin-changeset/src/commands/releaseNote.ts
packages/cli/plugin-changeset/src/index.ts

feat: gen release note support return result

---

.changeset/serious-crews-exercise.md
packages/builder/plugin-swc/tests/loader.test.ts

test(builder-plugin-swc): add builder-plugin-swc loader test

---

.changeset/eight-ghosts-build.md
packages/cli/plugin-bff/src/loader.ts
packages/server/create-request/package.json

fix: remove require.cache first when the bff loader execute

---

.changeset/kind-ducks-deliver.md
packages/generator/generator-common/src/locale/en.ts
packages/generator/generator-common/src/locale/zh.ts
packages/toolkit/main-doc/zh/guides/advanced-features/rspack-start.mdx

feat(generator): update Rspack text

---

packages/toolkit/main-doc/en/components/init-rspack-app.mdx
packages/toolkit/main-doc/en/guides/advanced-features/rspack-start.mdx
packages/toolkit/main-doc/zh/components/init-rspack-app.mdx
packages/toolkit/main-doc/zh/guides/advanced-features/rspack-start.mdx

docs: rspack init doc use component

---

.changeset/rude-ghosts-grow.md
packages/cli/plugin-ssg/src/types.ts
packages/runtime/plugin-runtime/src/ssr/cli/index.ts
packages/solutions/app-tools/src/analyze/generateCode.ts
packages/solutions/app-tools/src/analyze/index.ts
packages/solutions/app-tools/src/analyze/templates.ts
packages/solutions/app-tools/src/types/config/output.ts
packages/toolkit/types/cli/index.d.ts
packages/toolkit/utils/src/is/index.ts
packages/toolkit/utils/src/prettyInstructions.ts
packages/toolkit/utils/tests/is.test.ts
pnpm-lock.yaml

fix: nested routes in ssg

---

package.json

[`rimraf`](https://github.com/isaacs/rimraf) v4 has a breaking change:  globbing requires the --glob option to be set.
This PR  fixes the issue .

fix: fix reset command

---

.changeset/plenty-badgers-fry.md
packages/runtime/plugin-runtime/src/ssr/serverRender/renderToStream/bulidTemplate.before.ts

fix: pass basename to `matchRoutes`

---

.changeset/gold-cooks-rhyme.md
packages/runtime/plugin-runtime/package.json

fix: fix types pathname for model field

---

.changeset/late-crews-yawn.md
packages/builder/builder-doc/docs/en/plugins/plugin-swc.mdx
packages/builder/builder-doc/docs/zh/plugins/plugin-swc.mdx
packages/builder/plugin-swc/package.json
packages/builder/plugin-swc/src/binding.ts
packages/builder/plugin-swc/src/config.ts
packages/builder/plugin-swc/src/loader.ts
packages/builder/plugin-swc/src/plugin.ts
packages/builder/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
packages/builder/plugin-swc/tests/plugin.test.ts
pnpm-lock.yaml
tests/integration/swc/fixtures/minify-css/modern.config.ts
tests/integration/swc/fixtures/minify-css/package.json
tests/integration/swc/fixtures/minify-css/src/bootstrap.css
tests/integration/swc/fixtures/minify-css/src/index.js
tests/integration/swc/test/__snapshots__/index.test.ts.snap
tests/integration/swc/test/index.test.ts

feat: enable swc css minify

---

.changeset/rare-dolls-impress.md
packages/builder/plugin-swc/src/plugin.ts

Should not change user react runtime config

fix(builder-plugin-swc): do not change user react runtime config

---

.changeset/fuzzy-beans-hug.md
packages/solutions/app-tools/src/builder/shared/builderPlugins/adapterSSR.ts
pnpm-lock.yaml

bulider get bundler config from chain will **sooner than** modify
so add async to guarantee run order correctness

fix(app-tools): the adapterSSR builder plugin modifyChain is not async func

---

.changeset/rare-otters-guess.md
packages/runtime/plugin-runtime/types/router.d.ts
packages/server/bff-core/package.json
packages/server/bff-core/src/router/utils.ts
packages/server/bff-core/src/types.ts
packages/toolkit/main-doc/en/components/enable-bff.mdx
packages/toolkit/main-doc/zh/components/enable-bff.mdx
pnpm-lock.yaml

fix: remove esbuild from bff-core

---

.github/workflows/release.yml

feat: release action add comment env

---

README.md
README.zh-CN.md

Update README.
[Preview](https://github.com/web-infra-dev/modern.js/blob/b0e91aa637826714b8e8b32dbaa75c422e8405be/README.md).

docs: update README

---

.changeset/nine-pugs-run.md
packages/builder/builder-shared/src/chain.ts
packages/builder/builder-shared/src/schema/tools.ts
packages/builder/builder-shared/src/types/config/tools.ts

feat: builder support tools.bundlerChain config

feat: builder support tools.bundlerChain config

---

.changeset/hot-cameras-bow.md
packages/toolkit/module-doc/docs/en/plugins/official-list/overview.md
packages/toolkit/module-doc/docs/en/plugins/official-list/plugin-banner.md
packages/toolkit/module-doc/docs/en/plugins/official-list/plugin-import.mdx
packages/toolkit/module-doc/docs/zh/plugins/official-list/overview.md
packages/toolkit/module-doc/docs/zh/plugins/official-list/plugin-banner.md
packages/toolkit/module-doc/docs/zh/plugins/official-list/plugin-import.mdx
pnpm-lock.yaml

add module import and banner plugin contents

docs: add module import and banner plugin contents

---

tests/integration/swc/test/__snapshots__/index.test.ts.snap

fix: swc test

---

packages/toolkit/main-doc/en/guides/advanced-features/bff/_category_.json
packages/toolkit/main-doc/en/guides/advanced-features/rspack-start.mdx
packages/toolkit/main-doc/en/guides/advanced-features/web-server.mdx
packages/toolkit/main-doc/zh/guides/advanced-features/bff/_category_.json
packages/toolkit/main-doc/zh/guides/advanced-features/rspack-start.mdx
packages/toolkit/main-doc/zh/guides/advanced-features/web-server.mdx

fix(docs): update rspack_sidebar_position

---

README.zh-CN.md
packages/toolkit/main-doc/en/guides/get-started/introduction.mdx
packages/toolkit/main-doc/zh/guides/get-started/introduction.mdx
website/main/src/components/ContentCard/index.tsx
website/main/src/i18n/enUS.ts
website/main/src/i18n/zhCN.ts
website/main/src/pages/index.tsx

Update introduction and homepage, add introduction of `web engineering system` and `multiple solutions`.

docs: update introduction and homepage

---

README.md

chore: readme credit

---

README.md
website/main/src/pages/index.tsx

fix: home page blink

---

.changeset/plenty-dolls-look.md
packages/runtime/plugin-runtime/src/router/runtime/index.ts

fix: export missing router types

---

.changeset/five-brooms-buy.md
packages/builder/builder-rspack-provider/src/plugins/swc.ts
packages/builder/builder-rspack-provider/tests/plugins/__snapshots__/swc.test.ts.snap
packages/builder/builder-rspack-provider/tests/plugins/swc.test.ts

fix: rspack-provider swc plugin should not inject core-js in ssr

---

packages/builder/builder-doc/docs/en/guide/advanced/rspack-start.mdx

docs: remove chinese word in rspack-start

---

LICENSE
README.md
README.zh-CN.md
packages/builder/builder-webpack-provider/src/webpackPlugins/TsConfigPathsPlugin.ts
packages/cli/doc-core/src/theme-default/styles/base.css
packages/cli/doc-core/src/theme-default/styles/doc.css
packages/cli/doc-core/src/theme-default/styles/vars.css
packages/cli/plugin-data-loader/src/cli/data.ts
packages/cli/plugin-data-loader/src/runtime/response.ts
packages/toolkit/utils/jest.config.js
packages/toolkit/utils/src/remix-router.ts
packages/toolkit/utils/src/types.d.ts

Update credits, make the credits and license consistent with current code implementation.

chore: update credits

---

README.zh-CN.md

fix punctuatio for README.zh-CN.md

docs: fix punctuation

---

.changeset/chatty-olives-punch.md
packages/cli/doc-core/src/shared/utils/index.test.ts
packages/cli/doc-core/src/shared/utils/index.ts
packages/cli/doc-core/src/theme-default/components/Nav/index.tsx
packages/cli/doc-core/src/theme-default/components/NavHambmger/index.tsx
packages/cli/doc-core/src/theme-default/components/NavScreen/index.tsx

fix: 
- https://github.com/web-infra-dev/rspack-website/issues/229 
- https://github.com/web-infra-dev/rspack-website/issues/228

fix(doc-tools): mailto url

---

packages/builder/builder-doc/docs/en/config/tools/babel.md
packages/builder/builder-doc/docs/zh/config/tools/babel.md
packages/builder/builder-webpack-provider/src/types/config/tools.ts

chore(builder): add caution for tools.babel

---

.changeset/lucky-wolves-fold.md
packages/solutions/app-tools/src/analyze/templates.ts
tests/integration/ssr/test/base.test.js
tests/integration/ssr/test/index.test.js
tests/integration/ssr/test/streaming.test.js

https://github.com/web-infra-dev/modern.js/issues/3082

fix: data loader compat in Windows

---

.changeset/kind-eagles-breathe.md
packages/solutions/app-tools/src/analyze/utils.ts

fix: should not replace to alias when filePath is not in src

---

.github/workflows/build-builder-website.yml
.github/workflows/build-doc-website.yml
.github/workflows/build-main-website.yml
.github/workflows/build-module-website.yml
.github/workflows/check-changeset.yml
.github/workflows/cypress-test.yml
.github/workflows/integration-test-Windows.yml
.github/workflows/integration-test-macOS.yml
.github/workflows/lint-Linux.yml
.github/workflows/release-pull-request.yml
.github/workflows/release.yml
.github/workflows/test-Windows.yml
.github/workflows/test-builder-e2e.yml
.github/workflows/test-macOS.yml
.github/workflows/type-check.yml
CONTRIBUTING.md
package.json

build: limit the max version of pnpm to 7.29.1

---

packages/solutions/app-tools/src/builder/index.ts

chore: add using rspack log

---

.changeset/cuddly-cobras-repeat.md
.changeset/fifty-houses-deny.md
.changeset/heavy-ties-stare.md
.changeset/quick-berries-leave.md
packages/builder/builder-webpack-provider/src/plugins/basic.ts
packages/builder/builder-webpack-provider/tests/__snapshots__/webpackConfig.test.ts.snap
packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/default.test.ts.snap
packages/runtime/plugin-runtime/src/ssr/serverRender/renderToStream/renderToPipe.worker.ts
packages/server/plugin-worker/src/index.ts
packages/toolkit/main-doc/en/guides/advanced-features/ssr.mdx
packages/toolkit/main-doc/zh/guides/advanced-features/ssr.mdx

fix: worker ability

---

packages/builder/builder-doc/docs/en/config/output/disableInlineRuntimeChunk.md
packages/builder/builder-doc/docs/zh/config/output/disableInlineRuntimeChunk.md

Improve runtimeChunk document, add more guides.

docs(builder): improve runtimeChunk document

---

packages/toolkit/main-doc/en/guides/advanced-features/ssr.mdx
packages/toolkit/main-doc/zh/guides/advanced-features/ssr.mdx
packages/toolkit/main-doc/zh/guides/basic-features/mock.mdx

fix: mock docs

---

.changeset/long-jars-confess.md
packages/toolkit/module-doc/docs/en/guide/advance/external-dependency.mdx
packages/toolkit/module-doc/docs/en/guide/advance/in-depth-about-build.md
packages/toolkit/module-doc/docs/zh/guide/advance/external-dependency.mdx
packages/toolkit/module-doc/docs/zh/guide/advance/in-depth-about-build.md

format content for module-tools document

docs: format content for module tools doc

---

.changeset/sharp-buckets-cheer.md
packages/cli/plugin-module-import/src/index.ts
pnpm-lock.yaml

fix(plugin-module-import): remove jsc config

---

CONTRIBUTING.md

Add documentation to contribution guide.

docs: add documentation to contribution guide

---

.changeset/plenty-avocados-beam.md
LICENSE
packages/server/bff-core/src/types.ts
packages/server/utils/src/compilers/typescript/tsconfigPathsPlugin.ts
packages/solutions/app-tools/src/analyze/templates.ts

fix: optimize the regexp for route matching rules & add license

---

packages/document/builder-doc/docs/en/config/html/mountId.md
packages/document/builder-doc/docs/zh/config/html/mountId.md

Add root node tip for mountId config.

docs(builder): add root node tip for mountId

---

packages/document/builder-doc/docs/en/guide/faq/exceptions.md
packages/document/builder-doc/docs/en/guide/optimization/optimize-bundle.md
packages/document/builder-doc/docs/zh/guide/faq/exceptions.md
packages/document/builder-doc/docs/zh/guide/optimization/optimize-bundle.md

Add core-js FAQ and pnpm dedupe guide.

docs(builder): add core-js FAQ and pnpm dedupe guide

---

packages/document/builder-doc/docs/en/guide/quick-start.mdx
packages/document/builder-doc/docs/en/shared/nodeVersion.md
packages/document/builder-doc/docs/zh/guide/quick-start.mdx
packages/document/builder-doc/docs/zh/shared/nodeVersion.md
packages/document/main-doc/docs/en/components/prerequisites.mdx
packages/document/main-doc/docs/en/guides/get-started/quick-start.mdx
packages/document/main-doc/docs/zh/components/prerequisites.mdx

Update Node.js version requirement, using Node.js 14 is ok.

docs: update Node.js version requirement

---

packages/document/main-doc/docs/en/guides/advanced-features/rspack-start.mdx
packages/document/main-doc/docs/zh/guides/advanced-features/rspack-start.mdx

docs: add rspack unsupport features in docs

docs: add rspack unsupport features in docs

---

.changeset/little-walls-itch.md
packages/cli/doc-core/src/node/mdx/index.ts
packages/cli/doc-core/src/theme-default/components/Link/index.tsx
packages/cli/doc-core/src/theme-default/components/Siderbar/index.tsx

1. 修复侧边栏样式问题
2. 外链默认加上 noopener noreferer，防止安全问题

fix(doc core): sidebar style & link rel

---

.changeset/twenty-eels-rest.md
packages/builder/builder-rspack-provider/src/config/validate/source.ts
packages/builder/builder-rspack-provider/src/types/config/source.ts
packages/document/builder-doc/docs/en/config/source/define.md
packages/document/builder-doc/docs/zh/config/source/define.md

fix(builder): update source.define type in rspack

---

.github/workflows/release-pull-request.yml

fix: release note pull request id not right

---

packages/document/main-doc/docs/en/guides/topic-detail/framework-plugin/plugin-api.mdx
packages/document/main-doc/docs/zh/blog/updates/2022-0708-updates.md
packages/document/main-doc/docs/zh/guides/advanced-features/eslint.mdx
packages/document/main-doc/docs/zh/guides/topic-detail/framework-plugin/plugin-api.mdx

Fix broken links and update plugin API document.

docs: fix broken links and update plugin API

---

.changeset/big-tools-deny.md
packages/generator/generators/storybook-generator/src/index.ts

fix: storybook generator dependencies judge error

---

.changeset/fast-hats-unite.md
packages/cli/doc-core/src/theme-default/components/DocFooter/index.module.scss
packages/cli/doc-core/src/theme-default/components/DocFooter/index.tsx
packages/cli/doc-core/src/theme-default/components/Nav/NavMenuGroup.tsx
packages/cli/doc-core/src/theme-default/layout/DocLayout/docComponents/list.tsx
packages/cli/doc-core/src/theme-default/layout/DocLayout/docComponents/paragraph.tsx
packages/cli/doc-core/src/theme-default/layout/DocLayout/docComponents/title.tsx
packages/cli/doc-core/src/theme-default/styles/vars.css
packages/document/main-doc/docs/en/guides/get-started/introduction.mdx

- Improve paragraph padding.
- Fix `not-last:mt-2` not work because tailwindcss not provide the className.

feat(doc-core): improve paragraph padding

---

tests/integration/ssr/test/base.test.js

feat: skip timeout ssr test

---

.changeset/lazy-swans-perform.md
packages/runtime/plugin-runtime/src/router/runtime/DeferredDataScripts.node.tsx

Fix typos in `DeferredDataScripts`.

fix: fix typos in `DeferredDataScripts`

---

.changeset/selfish-kids-dress.md
packages/runtime/plugin-runtime/src/ssr/serverRender/renderToStream/buildTemplate.after.ts
packages/runtime/plugin-runtime/src/ssr/serverRender/renderToStream/template.ts

Inject i18n placeholder in streaming ssr.

fix: streaming i18n inject

---

.changeset/great-wolves-arrive.md
packages/cli/doc-core/src/theme-default/components/Siderbar/index.tsx
packages/cli/doc-core/src/theme-default/styles/vars.css

fix(doc-core): fix left sidebar height

---

.changeset/late-needles-brake.md
packages/builder/builder-shared/package.json
packages/builder/builder-webpack-provider/package.json
packages/builder/plugin-image-compress/package.json
packages/cli/core/package.json
packages/cli/plugin-bff/package.json
packages/cli/plugin-data-loader/package.json
packages/cli/plugin-i18n/package.json
packages/cli/plugin-ssg/package.json
packages/runtime/plugin-garfish/package.json
packages/runtime/plugin-router-v5/package.json
packages/runtime/plugin-testing/package.json
packages/server/bff-core/src/router/utils.ts
packages/server/plugin-koa/package.json
packages/server/plugin-server/package.json
packages/server/plugin-worker/package.json
packages/server/prod-server/package.json
packages/solutions/app-tools/package.json
packages/toolkit/node-bundle-require/package.json
packages/toolkit/types/package.json

fix: add types field in package.json

---

packages/document/builder-doc/docs/en/guide/introduction.mdx
packages/document/builder-doc/docs/zh/guide/introduction.mdx
packages/document/doc-tools-doc/docs/en/api/config-theme.mdx
packages/document/doc-tools-doc/docs/zh/api/config-theme.mdx

Fix SidebarGroup type, `collapsable` -> `collapsible`.

docs(doc-tools): fix SidebarGroup type

---

packages/cli/core/tests/createFileWatcher.test.ts

fix(modern-js/core): the test always timeout

---

.changeset/itchy-swans-think.md
packages/runtime/plugin-garfish/package.json

fix: fix optional peerDep cause ghost dep

fix: fix optional peerDep cause ghost dep

---

.changeset/silent-lamps-applaud.md
packages/solutions/app-tools/src/builder/shared/builderPlugins/adapterSSR.ts
packages/solutions/app-tools/src/builder/shared/bundlerPlugins/RouterPlugin.ts

perf: improve routerPlugin performance

---

packages/document/doc-tools-doc/docs/zh/guide/introduction.mdx

Sync link descriptions in the Introduction section to match the corresponding content.

docs(doc-tools): sync introduction.mdx link

---

packages/document/builder-doc/docs/en/guide/faq/exceptions.md
packages/document/builder-doc/docs/en/guide/faq/general.md
packages/document/builder-doc/docs/zh/guide/faq/exceptions.md
packages/document/builder-doc/docs/zh/guide/faq/general.md
packages/document/main-doc/docs/en/guides/get-started/quick-start.mdx
packages/document/main-doc/docs/zh/guides/get-started/quick-start.mdx

- add a FAQ for react refresh
- add bundler comparison link

docs(builder): add a FAQ for react refresh

---

.changeset/thick-hats-teach.md
packages/solutions/app-tools/src/builder/shared/bundlerPlugins/RouterPlugin.ts

fix: should get publicPath from webpack stats in routerPlugin

---

packages/document/builder-doc/docs/en/guide/advanced/rspack-start.mdx
packages/document/builder-doc/docs/en/guide/introduction.mdx
packages/document/builder-doc/docs/en/guide/optimization/build-performance.mdx
packages/document/builder-doc/docs/en/shared/rspack-tip.mdx
packages/document/builder-doc/docs/en/shared/rspack.md
packages/document/builder-doc/docs/zh/guide/advanced/rspack-start.mdx
packages/document/builder-doc/docs/zh/guide/introduction.mdx
packages/document/builder-doc/docs/zh/guide/optimization/build-performance.mdx
packages/document/builder-doc/docs/zh/shared/rspack-tip.mdx
packages/document/builder-doc/docs/zh/shared/rspack.md
packages/document/main-doc/docs/en/guides/advanced-features/rspack-start.mdx
packages/document/main-doc/docs/zh/guides/advanced-features/rspack-start.mdx

docs: add Using Rspack build into build-performance

---

packages/document/builder-doc/docs/en/config/output/polyfill.md
packages/document/builder-doc/docs/zh/config/output/polyfill.md
packages/document/main-doc/docs/en/guides/advanced-features/compatibility.mdx
packages/document/main-doc/docs/zh/guides/advanced-features/compatibility.mdx

docs: add polyfill-ua tip

---

.changeset/sixty-bees-double.md
packages/cli/plugin-module-doc/src/features/docgen/index.ts
packages/cli/plugin-module-doc/src/features/index.ts
packages/cli/plugin-module-doc/src/features/lanchDoc.ts
packages/cli/plugin-module-doc/src/mdx/code-to-jsx.ts

fix(plugin-module-doc): fix api lang and the logic that merge doc config

---

.changeset/khaki-phones-admire.md
packages/cli/core/src/index.ts
packages/cli/core/src/utils/checkIsDuplicationPlugin.ts
packages/cli/core/src/utils/index.ts

feat: warning when user registe plugin duplication

---

packages/cli/plugin-module-doc/package.json
pnpm-lock.yaml

chore(module-doc): upgrade jest

---

tests/integration/server-hook/response/server/index.ts
tests/integration/server-hook/response/test/index.test.ts

fix: remove unused test case

---

tests/integration/bff-koa/test/index.test.ts

fix: increase delay after click

---

.changeset/tiny-teachers-hunt.md
packages/cli/plugin-module-doc/package.json
pnpm-lock.yaml
tests/integration/garfish/table/package.json
tests/integration/module-doc/package.json

fix: update arco-design version

---

packages/document/builder-doc/docs/en/config/output/assetsRetry.md
packages/document/builder-doc/docs/zh/config/output/assetsRetry.md

fix: asset retry doc

---

.changeset/strange-buses-care.md
packages/document/main-doc/docs/en/guides/topic-detail/framework-plugin/hook-list.mdx
packages/document/main-doc/docs/en/guides/topic-detail/model/typescript-best-practice.mdx

- translate some chinese in en docs

docs: translate some chinese in en docs

---

tests/integration/routes/modern.config.ts

Fix routes integration test, some config is deleted by mistake.

chore: fix routes integration test

---

.changeset/empty-points-carry.md
packages/solutions/doc-tools/src/index.ts

fix: doc tools cli options

---

packages/document/builder-doc/docs/en/config/performance/chunkSplit.md
packages/document/builder-doc/docs/en/guide/optimization/split-chunk.md
packages/document/builder-doc/docs/zh/config/performance/chunkSplit.md
packages/document/builder-doc/docs/zh/guide/optimization/split-chunk.md

Update split-by-experience groups, keep consistent with the code implementation.

docs(builder): update split-by-experience groups

---

.changeset/new-snails-laugh.md
packages/solutions/module-tools/src/builder/build.ts
packages/solutions/module-tools/src/builder/copy.ts
packages/solutions/module-tools/src/builder/dts/rollup.ts
packages/solutions/module-tools/src/builder/dts/tsc.ts
packages/solutions/module-tools/src/builder/index.ts
packages/solutions/module-tools/src/builder/platform.ts
packages/solutions/module-tools/src/constants/build.ts
packages/solutions/module-tools/src/dev.ts
packages/solutions/module-tools/src/locale/en.ts
packages/solutions/module-tools/src/locale/zh.ts
packages/solutions/module-tools/src/utils/builder.ts
packages/solutions/module-tools/src/utils/libuildPlugins.ts
packages/solutions/module-tools/src/utils/log.ts
packages/solutions/module-tools/src/utils/print.ts

- Pretty the log format, using `@modern-js/utils/logger` to print the log message, and use simpler colors.
Before:
After:

chore(module-tools): pretty the log format

---

.changeset/healthy-apples-camp.md
packages/cli/plugin-module-doc/src/features/lanchDoc.ts

fix: fix base in production

---

.changeset/fair-berries-exist.md
packages/cli/doc-core/src/theme-default/components/Search/logic/search.ts

修复搜索结果跳转 url 出现 `#undefined` 的情况

fix: search with content

---

.changeset/witty-donkeys-jog.md
packages/toolkit/utils/src/chainId.ts

fix: remove useless oneof chainId

---

packages/document/builder-doc/docs/en/plugins/plugin-node-polyfill.mdx
packages/document/builder-doc/docs/zh/plugins/plugin-node-polyfill.mdx

Add fallback modules list for node polyfill plugin.

docs(node-polyfill): add fallback modules list

---

.changeset/stale-forks-double.md
packages/solutions/app-tools/src/builder/shared/bundlerPlugins/RouterPlugin.ts

fix: should hide publicPath in injected manifest

---

.changeset/calm-squids-walk.md
packages/builder/builder-shared/package.json
pnpm-lock.yaml

fix: the babel-loader can not find the babel/core in builder-shared

---

packages/document/main-doc/docs/en/apis/app/hooks/src/server.mdx
packages/document/main-doc/docs/en/guides/advanced-features/ssr.mdx
packages/document/main-doc/docs/en/tutorials/first-app/c06-model.mdx
packages/document/main-doc/docs/en/tutorials/first-app/c07-container.mdx
packages/document/main-doc/docs/zh/apis/app/hooks/src/server.mdx
packages/document/main-doc/docs/zh/guides/advanced-features/ssr.mdx
packages/document/main-doc/docs/zh/tutorials/first-app/c06-model.mdx
packages/document/main-doc/docs/zh/tutorials/first-app/c07-container.mdx

docs: correct docs for data loader

---

packages/document/builder-doc/docs/en/config/source/transformImport.md
packages/document/builder-doc/docs/en/config/tools/babel.md
packages/document/builder-doc/docs/en/guide/faq/features.md
packages/document/builder-doc/docs/zh/config/source/transformImport.md
packages/document/builder-doc/docs/zh/config/tools/babel.md
packages/document/builder-doc/docs/zh/guide/faq/features.md

- Update babel-plugin-import related contents.
- Format `source.transformImport` documents.

docs(builder): update babel-plugin-import related contents

---

.github/workflows/release-pull-request.yml
.github/workflows/release.yml

fix: update action org to web-infra-dev

---

.changeset/gentle-papayas-smash.md
packages/document/main-doc/docs/en/guides/basic-features/data-fetch.mdx
packages/document/main-doc/docs/en/guides/basic-features/routes.mdx
packages/document/main-doc/docs/zh/guides/basic-features/data-fetch.mdx
packages/document/main-doc/docs/zh/guides/basic-features/routes.mdx

修正文档中使用@edenx/runtime的部分
correct the sections in the document that use @edenx/runtime.

doc: correct the sections in the document that use @edenx/runtime

---

.changeset/thirty-seas-share.md
packages/solutions/module-tools/src/locale/en.ts
packages/solutions/module-tools/src/locale/zh.ts

fix(module-tools): fix warning content

---

packages/document/builder-doc/docs/en/config/source/include.md
packages/document/builder-doc/docs/en/config/tools/tsLoader.md
packages/document/builder-doc/docs/en/plugins/plugin-swc.mdx
packages/document/builder-doc/docs/zh/config/source/include.md
packages/document/builder-doc/docs/zh/config/tools/tsLoader.md
packages/document/builder-doc/docs/zh/plugins/plugin-swc.mdx
packages/document/main-doc/docs/en/configure/app/tools/swc.mdx
packages/document/main-doc/docs/zh/configure/app/tools/swc.mdx

- add `source.include` compile node_modules tip
- add SWC generator guide.

docs(builder): add source.include node_modules tip

---

.changeset/spotty-parrots-cheer.md
packages/cli/doc-core/src/node/mdx/remarkPlugins/checkDeadLink.ts
packages/document/builder-doc/docs/en/config/tools/bundlerChain.mdx
packages/document/builder-doc/docs/zh/config/tools/bundlerChain.mdx
packages/document/builder-doc/modern.config.ts
packages/document/doc-tools-doc/modern.config.ts
packages/document/main-doc/modern.config.ts

- Check dead links in development.
- Improve dead link log message.
- Fix main website build failed.

docs: check dead links in development

---

.changeset/chilled-mice-invent.md
packages/runtime/plugin-runtime/src/ssr/cli/index.ts
packages/solutions/app-tools/src/builder/shared/bundlerPlugins/RouterPlugin.ts

fix: disable the ssr plugin when user does not use ssr

---

.changeset/itchy-fishes-rest.md
packages/cli/doc-core/src/theme-default/components/Nav/index.tsx
packages/cli/doc-core/src/theme-default/logic/code.ts
packages/cli/doc-core/src/theme-default/logic/utils.ts

1. 修复代码高亮不生效问题
2. 修复 cmd + k 搜索遮罩出现两次的问题

fix(doc-tools): code highlight not work

---

.changeset/spicy-months-decide.md
packages/solutions/module-tools/src/utils/input.ts
packages/solutions/module-tools/tests/utils/input.test.ts

fix `input: ["./src"]` config.
#3275

fix(module-tools): fix glob path for input config

---

.changeset/tidy-avocados-march.md
packages/solutions/module-tools/src/builder/clear.ts
packages/solutions/module-tools/src/builder/index.ts

fix(module-tools): fix noClear not work

---

.changeset/nine-cougars-fold.md
packages/solutions/module-tools/package.json
pnpm-lock.yaml

chore: change libuild version to ~0.11.8

---

tests/integration/bff-express/test/index.test.ts

fix: delay setTimeout in bff express case

---

.github/workflows/integration-test-Windows.yml
.github/workflows/integration-test-macOS.yml
.github/workflows/test-builder-e2e.yml

chore: trigger integration test when rspack update

---

.changeset/chilly-candles-do.md
.changeset/funny-rivers-refuse.md
packages/server/prod-server/src/libs/render/index.ts
packages/server/prod-server/src/libs/render/ssr.ts
packages/server/prod-server/src/libs/render/utils.ts
packages/server/prod-server/tests/utils.test.ts

fix: function injectServerData name typo

---

.changeset/purple-wolves-build.md
packages/document/builder-doc/docs/en/config/output/enableInlineScripts.md
packages/document/builder-doc/docs/en/config/output/enableInlineStyles.md
packages/document/builder-doc/docs/zh/config/output/enableInlineScripts.md
packages/document/builder-doc/docs/zh/config/output/enableInlineStyles.md
packages/document/main-doc/docs/zh/configure/app/runtime/router.mdx
packages/runtime/plugin-runtime/src/router/runtime/PrefetchLink.tsx
packages/runtime/plugin-runtime/src/router/runtime/plugin.tsx
tests/integration/bff-express/test/index.test.ts

fix: beforeCreateRouter should be false after render router

---

.changeset/dry-rivers-sit.md
packages/solutions/doc-tools/src/config/schema.ts

fix(doc-core): schema error in sidebar link

---

.changeset/violet-monkeys-agree.md
packages/cli/doc-core/src/theme-default/layout/DocLayout/docComponents/link.tsx

fix(doc-core): link base missing

---

.changeset/good-clocks-visit.md
packages/cli/doc-core/src/theme-default/components/Tabs/index.tsx
packages/cli/doc-core/tsconfig.json

fix(doc-core): fix Tabs props type

---

tests/e2e/builder/cases/dev/dev.test.ts

fix: hmr test

---

.changeset/eight-tigers-hear.md
packages/cli/doc-core/src/theme-default/components/Tabs/index.tsx
packages/solutions/module-tools/package.json
pnpm-lock.yaml

fix: update libuild version to fix windows resolve path

---

pnpm-lock.yaml
tests/integration/builder-rspack-with-ssr/CHANGELOG.md
tests/integration/builder-rspack-with-ssr/modern.config.ts
tests/integration/builder-rspack-with-ssr/package.json
tests/integration/builder-rspack-with-ssr/src/App.scss
tests/integration/builder-rspack-with-ssr/src/App.tsx
tests/integration/builder-rspack-with-ssr/tests/.eslintrc.js
tests/integration/builder-rspack-with-ssr/tests/index.test.ts
tests/integration/builder-rspack-with-ssr/tests/supports/index.ts
tests/integration/builder-rspack-with-ssr/tests/tsconfig.json
tests/integration/builder-rspack-with-ssr/tsconfig.json

test: add a integration test ssr with rspack

---

.changeset/nine-monkeys-judge.md
packages/cli/doc-core/src/theme-default/layout/DocLayout/docComponents/link.tsx

自动添加 base 的逻辑中，排除锚点的情况，避免锚点的链接无效

fix(doc-core): invalid anchor

---

packages/document/builder-doc/docs/en/guide/faq/exceptions.md
packages/document/builder-doc/docs/zh/guide/faq/exceptions.md

docs(builder): add import lodash type FAQ

---

packages/cli/doc-core/src/theme-default/components/Tabs/index.tsx
packages/document/main-doc/docs/en/tutorials/foundations/introduction.mdx
packages/document/module-doc/docs/en/api/config/build-config.md
packages/document/module-doc/docs/en/guide/advance/in-depth-about-build.md
packages/document/module-doc/docs/zh/api/config/build-config.md
packages/document/module-doc/docs/zh/guide/advance/in-depth-about-build.md

docs(module-doc): add redirect config

---

packages/document/module-doc/docs/en/api/config/build-config.md
packages/document/module-doc/docs/en/guide/advance/external-dependency.mdx
packages/document/module-doc/docs/zh/api/config/build-config.md
packages/document/module-doc/docs/zh/guide/advance/external-dependency.mdx

优化对于 '如何处理三方依赖' 文档的描述
原本的稍微有些啰嗦，部分示例移至API文档
解决 #3375

docs: optimize doc about dep and external

---

package.json
tests/package.json

chore: support run rspack test command in root

---

.changeset/witty-shirts-collect.md
packages/cli/plugin-bff/src/cli.ts
packages/cli/plugin-bff/tests/__snapshots__/cli.test.ts.snap
packages/cli/plugin-bff/tests/cli.test.ts

fix(plugin-bff): support bffPlugin when use rspack

---

.github/ISSUE_TEMPLATE/1-bug-report.en-US.yml
.github/ISSUE_TEMPLATE/3-bug-report.zh-Hans.yml

Recommend issue reporters to use [envinfo](https://www.npmjs.com/package/envinfo) to provide system info, which can provide more informations.

chore: add envinfo to issue template

---

packages/cli/plugin-changeset/src/commands/releaseNote.ts
packages/document/main-doc/docs/en/configure/app/source/disable-entry-dirs.mdx
packages/document/main-doc/docs/zh/configure/app/source/disable-entry-dirs.mdx
packages/document/main-doc/docs/zh/guides/topic-detail/changesets/release.mdx

- Fix disableEntryDirs demo, it should be `string[]` type.
- Fix `release` command typo.

docs: fix disableEntryDirs type in demo

---

.changeset/nice-meals-battle.md
packages/builder/builder-rspack-provider/package.json
packages/builder/builder-rspack-provider/tests/plugins/__snapshots__/default.test.ts.snap
packages/builder/builder-rspack-provider/tests/plugins/__snapshots__/swc.test.ts.snap
packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/babel.test.ts.snap
packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/default.test.ts.snap
packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/react.test.ts.snap
packages/builder/plugin-swc-base/package.json
packages/builder/plugin-swc-base/tests/__snapshots__/apply.test.ts.snap
packages/builder/plugin-swc/package.json
packages/builder/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
packages/builder/plugin-swc/tests/fixtures/browserslist/ie11/expected.js
packages/builder/plugin-swc/tests/fixtures/compat/cjs-no-preserve-dyn-import/expected.js
packages/builder/plugin-swc/tests/fixtures/compat/commonjs-es-module-mark/expected.js
packages/builder/plugin-swc/tests/fixtures/polyfill/ie_11_entry/expected.js
packages/builder/plugin-swc/tests/fixtures/polyfill/ie_11_usage/expected.js
packages/builder/plugin-swc/tests/fixtures/polyfill/no_importing_corejs/expected.js
packages/builder/plugin-swc/tests/fixtures/react/devlopment/false/expected.js
packages/builder/plugin-swc/tests/fixtures/react/devlopment/true/expected.js
packages/builder/plugin-swc/tests/fixtures/react/fast-refresh/expected.js
packages/builder/plugin-swc/tests/fixtures/react/jsx-runtime/expected.js
packages/builder/plugin-swc/tests/fixtures/typescript/tsx/expected.js
packages/cli/babel-preset-app/package.json
packages/cli/babel-preset-app/tests/utils.test.ts
pnpm-lock.yaml

Bump SWC
Bump core-js because SWC injects wrong polyfill in core-js@3.26

chore: bump core-js and swc

---

.changeset/silver-bags-lay.md
packages/cli/doc-core/src/node/searchIndex.ts
packages/cli/doc-core/src/shared/types/index.ts
packages/cli/doc-core/src/theme-default/components/Search/SuggestItem.tsx
packages/cli/doc-core/src/theme-default/components/Search/index.tsx
packages/cli/doc-core/src/theme-default/components/Search/logic/providers/RemoteProvider.ts
packages/cli/doc-core/src/theme-default/components/Search/logic/search.ts
packages/cli/doc-core/src/theme-default/components/Search/logic/util.ts

搜索功能优化:
1. 支持服务端搜索的模糊查询；
2. 修复切换语言后，搜索结果无法跟着切换的问题。

feat(doc-core): fuzzy search

---

.changeset/real-pandas-listen.md
packages/runtime/plugin-garfish/src/cli/index.ts
packages/runtime/plugin-garfish/src/cli/utils.ts
packages/runtime/plugin-runtime/src/core/compatible.tsx
pnpm-lock.yaml

feat: support global props in createApp and pass garfish props in

---

.changeset/metal-feet-remember.md
packages/document/main-doc/docs/en/guides/basic-features/routes.mdx
packages/document/main-doc/docs/zh/guides/basic-features/routes.mdx
packages/runtime/plugin-runtime/src/router/runtime/PrefetchLink.tsx
packages/runtime/plugin-runtime/src/router/runtime/index.ts
packages/runtime/plugin-runtime/tests/router/prefetch.test.tsx
packages/server/bff-core/src/router/utils.ts
tests/integration/routes/src/four/routes/layout.tsx
tests/integration/routes/src/three/routes/layout.tsx

docs: add prefetch docs

---

.changeset/silent-ways-push.md
packages/cli/doc-core/src/theme-default/layout/Layout/index.tsx
packages/cli/doc-core/src/theme-default/logic/sideEffects.ts

feat(doc-core): redirect locale language in first visit

---

.changeset/sour-jobs-help.md
packages/cli/doc-core/src/runtime/index.ts

Fix main website build failed: https://github.com/web-infra-dev/modern.js/actions/runs/4793346304/jobs/8525706286
https://github.com/web-infra-dev/rspack/issues/2927

fix(doc-core): failed to resolve useLocation method in some cases

---

.github/ISSUE_TEMPLATE/2-feature-request.en-US.yml
.github/ISSUE_TEMPLATE/4-feature-request.zh-Hans.yml
.github/ISSUE_TEMPLATE/config.yml

- Change `RFC` to `feature request`, while both RFCs and feature requests are requests for changes or improvements, RFCs are more formal and technical in nature, while feature requests are more user-focused and relate to product functionality.
- Add `Ask a question` link.

chore: update feature request issue template

---

CONTRIBUTING.md

fix contribute doc link
fix contribute doc link

docs: fix contribute doc link

---

.changeset/real-apricots-rescue.md
packages/solutions/module-tools/src/builder/esbuild/adapter.ts
packages/solutions/module-tools/src/builder/feature/redirect.ts
packages/solutions/module-tools/src/builder/feature/style/postcssTransformer.ts
packages/solutions/module-tools/src/utils/builder.ts
tests/integration/module/fixtures/build/redirect/redirect.test.ts

Reverts web-infra-dev/modern.js#4774

Revert "fix(module-tools): change the output css module json filename"

---

README.md
README.zh-CN.md

Add Rsbuild link to README.
https://github.com/web-infra-dev/rsbuild

docs: add Rsbuild link to README

---

.github/workflows/test-macOS.yml
codecov.yml

https://github.com/web-infra-dev/modern.js/issues/4780

chore: delete coverage report in ci

---

package.json
packages/builder/builder-cli/package.json
packages/builder/builder-rspack-provider/package.json
packages/builder/builder-shared/package.json
packages/builder/builder-webpack-provider/package.json
packages/builder/builder/package.json
packages/builder/plugin-esbuild/package.json
packages/builder/plugin-image-compress/package.json
packages/builder/plugin-node-polyfill/package.json
packages/builder/plugin-stylus/package.json
packages/builder/plugin-swc/package.json
packages/builder/plugin-vue/package.json
packages/builder/plugin-vue2/package.json
packages/server/bff-core/jest.config.js
packages/server/plugin-express/jest.config.js
packages/solutions/module-tools/package.json
packages/toolkit/e2e/package.json
packages/toolkit/plugin/jest.config.js
pnpm-lock.yaml
scripts/jest-config/jest.config.js
scripts/vitest-config/package.json
scripts/vitest-config/src/index.ts
tests/jest-ut.config.js
tests/jest.config.js
tests/package.json

close https://github.com/web-infra-dev/modern.js/issues/4780

chore: disable coverage in ci

---

packages/document/builder-doc/package.json
packages/document/main-doc/package.json
packages/document/module-doc/package.json
pnpm-lock.yaml

feat: update rspress version

---

packages/devtools/client/package.json
packages/devtools/client/src/client/components/HeaderRule/Editor.module.scss
packages/devtools/client/src/client/components/HeaderRule/Editor.tsx
packages/devtools/client/src/client/routes/headers/editor/page.module.scss
packages/devtools/client/src/client/routes/headers/editor/page.tsx
packages/devtools/client/src/client/routes/headers/layout.config.ts
packages/devtools/client/src/client/routes/headers/layout.module.scss
packages/devtools/client/src/client/routes/headers/layout.tsx
packages/devtools/client/src/client/routes/headers/state.ts
packages/devtools/client/src/client/routes/headers/welcome/page.tsx
packages/devtools/client/src/client/utils/service-agent.ts
pnpm-lock.yaml

https://github.com/web-infra-dev/modern.js/assets/18379948/6dfdebb1-45f3-48d5-9d6c-bced23a0a328

feat(devtools): improve UI of header modifier

---

.changeset/giant-balloons-heal.md
packages/document/module-doc/docs/en/api/plugin-api/plugin-hooks.md
packages/document/module-doc/docs/zh/api/plugin-api/plugin-hooks.md
packages/solutions/module-tools/src/build.ts
packages/solutions/module-tools/src/builder/index.ts
packages/solutions/module-tools/src/config/normalize.ts
packages/solutions/module-tools/src/hooks/build.ts
packages/solutions/module-tools/src/hooks/misc.ts
tests/integration/module/plugins/hooks/hooks.test.ts
tests/integration/module/plugins/hooks/modern.config.ts
tests/integration/module/plugins/hooks/package.json
tests/integration/module/plugins/hooks/src/index.js

feat(module-tools): support resolveModuleUserConfig

---

.changeset/brave-wasps-accept.md
packages/server/prod-server/src/libs/hook-api/index.ts
packages/server/prod-server/src/libs/hook-api/index.worker.ts
packages/server/prod-server/src/server/modernServer.ts
packages/server/prod-server/src/workerServer.ts
packages/server/prod-server/tests/hook.test.ts
packages/toolkit/types/server/hook.d.ts

feat(prod-server): afterRender Hook context add route attributes

---

packages/document/builder-doc/docs/en/config/security/checkSyntax.md
packages/document/builder-doc/docs/zh/config/security/checkSyntax.md

chore: update `security.checkSyntax`

---

.github/workflows/issue-label.yml

chore(workflow): add issue label yaml

---

.changeset/thirty-spies-drive.md
packages/document/builder-doc/docs/zh/guide/advanced/storybook.mdx

fix: change storybook doc file extension

---

.github/workflows/build-builder-website.yml
.github/workflows/build-main-website.yml

chore: update website config file

---

packages/devtools/client/plugins/ServiceWorkerCompilerPlugin.ts
packages/devtools/client/src/client/components/PairsEditor/Editor.module.scss
packages/devtools/client/src/client/components/PairsEditor/Editor.tsx
packages/devtools/client/src/client/components/PairsEditor/Pair.module.scss
packages/devtools/client/src/client/components/PairsEditor/Pair.tsx
packages/devtools/client/src/client/components/PairsEditor/types.tsx
packages/devtools/client/src/client/routes/headers/editor/page.tsx
packages/devtools/client/src/client/routes/headers/state.ts

feat(devtools): improve editor of header modifier

---

.changeset/funny-singers-listen.md
packages/document/builder-doc/docs/en/guide/advanced/storybook.mdx

fix: update storybook doc file extension

---

.changeset/silent-pianos-unite.md
packages/server/prod-server/src/workerServer.ts

fix(worker-server): rslogger can't work in worker env

---

.changeset/fresh-baboons-wave.md
packages/storybook/builder/src/plugin-storybook.ts

fix(storybook): storybook register extra addon babel plugins

---

.changeset/wicked-walls-search.md
packages/storybook/builder/src/plugin-storybook.ts

Add raw query rule and md rule as storybook also has those 2 rules

fix(storybook): add raw query and .md rules in module.rules

---

.changeset/polite-news-sort.md
packages/runtime/plugin-runtime/src/ssr/serverRender/tracker.ts

the metrics message is lack, we should add more metrics logger

fix: add more ssr metrics logger

---

packages/document/builder-doc/docs/en/guide/features.mdx
packages/document/builder-doc/docs/en/guide/glossary.mdx
packages/document/builder-doc/docs/en/guide/introduction.mdx
packages/document/builder-doc/docs/en/guide/quick-start.mdx
packages/document/builder-doc/docs/zh/guide/features.mdx
packages/document/builder-doc/docs/zh/guide/glossary.mdx
packages/document/builder-doc/docs/zh/guide/introduction.mdx
packages/document/builder-doc/docs/zh/guide/quick-start.mdx

Add Modern.js Builder upgrade tip. I will migrate some Modern.js Builder docoument to the Modern.js framework website later.

docs: add Modern.js Builder upgrade tip

---

.changeset/small-moles-crash.md
packages/builder/builder-rspack-provider/package.json
packages/builder/builder-rspack-provider/src/core/devMiddleware.ts
packages/builder/builder-rspack-provider/src/plugins/react.ts
packages/builder/builder-rspack-provider/tests/plugins/__snapshots__/default.test.ts.snap
packages/document/main-doc/docs/en/guides/advanced-features/rspack-start.mdx
packages/document/main-doc/docs/zh/guides/advanced-features/rspack-start.mdx
packages/storybook/builder/package.json
packages/storybook/builder/src/preset.ts
pnpm-lock.yaml

https://github.com/web-infra-dev/rspack/pull/4879

chore: replace @rspack/dev-client with @rspack/plugin-react-refresh

---

.github/workflows/test-builder-e2e.yml

chore: turbo -> nx

---

.changeset/few-waves-clap.md
packages/document/main-doc/docs/en/configure/app/output/enable-inline-route-manifests.mdx
packages/document/main-doc/docs/zh/configure/app/output/enable-inline-route-manifests.mdx
packages/server/core/src/types/config/output.ts
packages/solutions/app-tools/src/builder/shared/builderPlugins/adapterSSR.ts
packages/solutions/app-tools/src/config/default.ts
packages/solutions/app-tools/src/types/config/output.ts

chore: use disable instead of enableInlineRouteManifests

---

.changeset/silly-socks-report.md
packages/runtime/plugin-testing/package.json
pnpm-lock.yaml

fix: bff-core should be a dependency of testing plugin

---

.changeset/pretty-bottles-visit.md
packages/document/builder-doc/docs/en/guide/advanced/storybook.mdx
packages/document/builder-doc/docs/zh/guide/advanced/storybook.mdx
packages/document/module-doc/docs/en/guide/basic/using-storybook.mdx
packages/document/module-doc/docs/zh/guide/basic/using-storybook.mdx

docs: change builderCofnig to builderConfig

---

.changeset/olive-keys-destroy.md
packages/solutions/module-tools/src/builder/feature/swc.ts
tests/integration/module/fixtures/build/autoExternal/autoExternal.test.ts
tests/integration/module/fixtures/build/autoExternal/config.ts
tests/integration/module/fixtures/build/autoExternal/src/umd.ts

fix(module-tools): set isModule is true in swc transform

---

.changeset/giant-trees-attend.md
packages/generator/generator-common/src/newAction/module/index.ts
packages/generator/generator-common/src/newAction/mwa/index.ts

testPlugin -> testingPlugin
closes #5046

fix(typo): testPlugin -> testingPlugin

---

.changeset/new-dragons-juggle.md
packages/document/module-doc/docs/en/guide/intro/getting-started.mdx
packages/document/module-doc/docs/zh/guide/intro/getting-started.mdx

docs(module-tools): update example link

---

.changeset/selfish-hairs-invite.md
packages/solutions/module-tools/src/builder/clear.ts

fix(module-tools): not execa tsc clean in js project

---

.changeset/neat-socks-jog.md
packages/generator/generators/storybook-generator/src/index.ts

chore(storybook-generator): adjust addDep version in template

---

.changeset/clever-zebras-worry.md
packages/document/builder-doc/docs/en/config/tools/devServer.md
packages/document/builder-doc/docs/zh/config/tools/devServer.md
packages/toolkit/types/server/utils.d.ts

https://github.com/web-infra-dev/rsbuild/pull/804

types: proxy.context should allow function type

---

packages/devtools/client/LICENSE
packages/devtools/client/package.json

fix(devtools): missing license

---

.changeset/red-stingrays-drive.md
packages/devtools/client/src/entries/mount/index.module.scss
packages/devtools/client/src/entries/mount/index.tsx

feat(devtools): set z-index to avoid be covered

---

.changeset/nasty-moose-join.md
packages/solutions/module-tools/src/command.ts

fix(module-tools): `dev --config <config>` does not work (close: #5084)

---

.changeset/warm-lobsters-drop.md
packages/document/main-doc/docs/en/guides/topic-detail/framework-plugin/introduction.mdx
packages/document/main-doc/docs/zh/guides/topic-detail/framework-plugin/introduction.mdx

add more docs for plugin usage. Especially the way to register plugins and `new` command

feat(docs): enhance plugin docs

---

tests/e2e/builder/cases/css/style-loader/index.test.ts

https://github.com/web-infra-dev/modern.js/actions/runs/7205481418/job/19628557533

fix: update style-loader snapshot

---

.changeset/cool-lamps-wait.md
.vscode/settings.json
packages/document/main-doc/docs/en/apis/app/runtime/web-server/middleware.mdx
packages/document/main-doc/docs/zh/apis/app/runtime/web-server/middleware.mdx

docs: fix server middleware type docs

---

packages/builder/uni-builder/src/shared/parseCommonConfig.ts
packages/builder/uni-builder/src/types.ts
packages/builder/uni-builder/tests/__snapshots__/parseConfig.test.ts.snap
packages/builder/uni-builder/tests/babel.test.ts
packages/builder/uni-builder/tests/manifest.test.ts
packages/builder/uni-builder/tests/parseConfig.test.ts
packages/builder/uni-builder/tests/react.test.ts
packages/builder/uni-builder/tests/styledComponents.test.ts
tests/e2e/builder/cases/node-addons/index.test.ts
tests/e2e/builder/cases/output/externals/tests/index.test.ts
tests/e2e/builder/cases/web-worker/index.test.ts

fix(uni-builder): get target from createUniBuilder params

---

packages/document/main-doc/docs/en/guides/advanced-features/optimize-bundle.mdx
packages/document/main-doc/docs/en/guides/basic-features/css.mdx
packages/document/main-doc/docs/en/guides/get-started/tech-stack.mdx
packages/document/main-doc/docs/zh/guides/advanced-features/optimize-bundle.mdx
packages/document/main-doc/docs/zh/guides/basic-features/css.mdx
packages/document/main-doc/docs/zh/guides/get-started/tech-stack.mdx

Fix tailwind plugin version and update CSS modules links.

docs: fix tailwind plugin version and update CSS modules links

---

packages/builder/uni-builder/src/index.ts
packages/builder/uni-builder/src/rspack/index.ts
packages/builder/uni-builder/src/types.ts
packages/builder/uni-builder/src/webpack/index.ts
tests/e2e/builder/cases/styled-component/index.test.ts
tests/e2e/builder/scripts/shared.ts

fix(uni-builder): support tools.styledComponents

---

.changeset/dull-ghosts-cheer.md
packages/builder/builder-rspack-provider/src/core/rspackConfig.ts
packages/builder/builder-rspack-provider/src/plugins/css.ts

https://github.com/web-infra-dev/rspack-ecosystem-ci/actions/runs/7242340843/job/19727635439

fix: rspack 0.4.4 plugin & rule type error

---

.changeset/slimy-bulldogs-warn.md
packages/document/main-doc/docs/zh/guides/basic-features/data/data-write.mdx
packages/runtime/plugin-runtime/src/cli/index.ts
packages/solutions/app-tools/src/analyze/generateCode.ts
packages/solutions/app-tools/src/analyze/utils.ts
packages/toolkit/utils/src/cli/is/project.ts

fix: whether it is react18 should not rely on internalDirectory

---

packages/builder/uni-builder/src/shared/parseCommonConfig.ts

import plugins on-demand to improve performance

perf(uni-builder): import plugins on-demand

---

.changeset/purple-bottles-dream.md
packages/solutions/module-tools/src/builder/feature/style/postcssUrlPlugin.ts
packages/solutions/module-tools/src/builder/feature/style/utils.ts

chore(module-tools): simplify logic in rewrite css url

---

.changeset/popular-terms-lay.md
packages/solutions/module-tools/src/utils/dts.ts

fix(module-tools): fix logic error in remove dts task

---

.changeset/nine-colts-watch.md
packages/builder/plugin-swc/package.json
packages/module/plugin-module-import/package.json
packages/solutions/module-tools/package.json
pnpm-lock.yaml

chore: bump @modern-js/swc-plugins v0.6.6

---

.changeset/silver-mayflies-retire.md
packages/generator/generators/base-generator/templates/base-template/.vscode/settings.json
packages/generator/generators/monorepo-generator/templates/base-template/monorepo.code-workspace

https://code.visualstudio.com/updates/v1_85#_code-actions-on-save-and-auto
The setting values were also updated, with the current boolean values to be deprecated in favor of the string equivalent.

chore(generator): update vscode settings template

---

packages/document/module-doc/docs/en/guide/basic/use-module-doc.mdx
packages/document/module-doc/docs/zh/guide/basic/use-module-doc.mdx

Follow https://github.com/web-infra-dev/rspress/pull/476

docs(module-tools): desperate some config and adjust sidebar and internationalization

---

.changeset/cuddly-owls-dream.md
packages/generator/generator-plugin/src/utils/file.ts

feat: generator plugin `addManyFiles` support dotfiles

---

.changeset/breezy-falcons-jog.md
packages/runtime/plugin-runtime/src/ssr/serverRender/renderToStream/buildTemplate.share.ts
packages/runtime/plugin-runtime/src/ssr/serverRender/renderToStream/bulidTemplate.before.ts
packages/runtime/plugin-runtime/src/ssr/serverRender/renderToStream/index.ts
packages/runtime/plugin-runtime/src/ssr/serverRender/renderToStream/renderToPipe.ts
packages/runtime/plugin-runtime/src/ssr/serverRender/renderToStream/renderToPipe.worker.ts
packages/runtime/plugin-runtime/src/ssr/serverRender/renderToStream/template.ts
packages/runtime/plugin-runtime/src/ssr/serverRender/renderToString/loadable.ts
packages/runtime/plugin-runtime/src/ssr/serverRender/utils.ts

The streaming ssr support inline the script assets

fix(ssr): support stream ssr inline asserts

---

.changeset/ten-goats-bow.md
packages/server/server/src/dev-tools/dev-middleware/hmr-client/createSocketUrl.ts

there is no `window` in the service-worker context

fix(hmr-client): make hmr-client isomorphic

---

.changeset/famous-mayflies-hug.md
packages/document/main-doc/docs/en/guides/advanced-features/ssr/cache.mdx
packages/document/main-doc/docs/zh/guides/advanced-features/ssr/cache.mdx
packages/server/prod-server/src/libs/render/ssrCache/manager.ts
packages/server/prod-server/tests/ssrCache.test.ts
packages/toolkit/runtime-utils/src/node/storer/storage.ts
packages/toolkit/types/server/utils.d.ts
tests/integration/ssr/fixtures/base/server/cache.ts

fix: ssr cache container spell

---

tests/integration/module/fixtures/build/dts-composite/tsconfig.json
tests/package.json

test(module-tools): fix dts case
