web-infra-dev/modern.js

.changeset/six-experts-stare.md, packages/cli/i18n-cli-language-detector/src/index.ts
For some unknown reasons, process.env.LC_ALL || process.env.LC_MESSAGES || process.env.LANG || process.env.LANGUAGE gets 'undefined' at Windows Node enviorment, so we add  Intl.DateTimeFormat().resolvedOptions().locale methods for detecting user locale.
reference:
1. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/resolvedOptions
2. https://stackoverflow.com/questions/46072248/node-js-how-to-detect-user-language
=> fix: fix language detect in Windows

packages/cli/plugin-storybook/src/features/utils/generate.ts, packages/cli/plugin-storybook/template/preview.tmpl, packages/cli/plugin-storybook/template/user-preview.tmpl, packages/solutions/app-tools/package.json
由于 webpack peerDeps esbuild，因此在使用 app-tools的时候需要安装 esbuild，这样也解决了其他模块依赖webpack，并且没有安装esbuild的情况。目前用户项目下可能因为这个原因出现相同版本两个webpack的情况，一个名字是 webpack@xxx，另一个名字是 webpack@xxx_esbuild@xx。这样导致运行时候可能出现问题，目前是storybook调试运行出现问题。
补充 webpack 不是直接 peerDeps esbuild，webpack因为依赖了 terser-webpack-plugin,terser-webpack-plugin peerOptionalDeps esbuild，导致 webpack也具有 peerOptionalDeps。
=> Fix webpack peerdeps

.changeset/honest-dogs-refuse.md, packages/generator/generators/changeset-generator/src/index.ts, packages/generator/generators/changeset-generator/templates/.changeset/config.json, packages/toolkit/create/src/createAction.ts
codesmith 执行 git init 时，获取 context 上的 defaultBranch 配置，并切换到 defaultBranch 对应分支
https://github.com/modern-js-dev/codesmith/pull/23
在 Modern.js 中，默认使用 main 分支作为默认分支，如果需要修改默认分支，可以在 --config 参数中增加 defaultBranch 配置。
=> feat: change default branch main

.changeset/thin-insects-promise.md, .github/workflows/lint-Windows.yml, packages/cli/plugin-i18n/src/index.ts, packages/cli/plugin-ssg/src/libs/output.ts, packages/cli/plugin-testing/src/cli/index.ts, packages/review/eslint-config-app/eslintrc.js
As now default command "modern lint" in CI workflow will silently fix all errors, it did not provide the "check code format error" feature as expected, so this commit will fix the ci workflow file to make it work.
现在默认在 CI 工作流运行的"modern lint"会静默修复错误，没有如预期提示代码错误，所以这笔提交修复了这个错误，现在可正确显示错误并提示修改
=> feat: show lint error in CI console

packages/cli/plugin-analyze/src/generateCode.ts
Now, when we use `modifyEntryImports` hook in `createPlugin` function, we can import a plugin to a specified package, like the code shown below:
```typescript
modifyEntryImports({ entrypoint, imports }: any) {
imports.push({
value: '@modern-js/runtime/plugins',
specifiers: [{ imported: 'foo' }],
});
}
```
And, if we need to add some extra logic while importing plugins, we could use `initialize` param:
```typescript
modifyEntryImports({ entrypoint, imports }: any) {
imports.push({
value: '@modern-js/runtime/plugins',
specifiers: [{ imported: 'foo' }],
// put extra logic here in `initialize` 
initialize: `console.log('This is foo plugin extra logic')`
});
}
```
That would result in modern.js generated project node_modules/.modern-js/main/index.js like:
(Of course you need to import 'foo' …
=> fix: fix "initialize" param wrongfully ignored problem

.changeset/strong-windows-divide.md
Add missing changeset for "@modern-js/plugin-analyze" in [#408](https://github.com/modern-js-dev/modern.js/commit/f78d9d3d266d9a0f86ccf1d00f542dbad03fcb96)
=> fix: add missing change-set for "@modern-js/plugin-analyze"

.changeset/flat-goats-argue.md, packages/cli/plugin-less/src/cli.ts, packages/cli/plugin-less/tests/.eslintrc.js, packages/cli/plugin-less/tests/__snapshots__/index.test.ts.snap, packages/cli/plugin-less/tests/index.test.ts, packages/cli/plugin-less/tests/tsconfig.json, packages/cli/plugin-sass/src/cli.ts, packages/cli/plugin-sass/tests/.eslintrc.js, packages/cli/plugin-sass/tests/__snapshots__/index.test.ts.snap, packages/cli/plugin-sass/tests/index.test.ts, packages/cli/plugin-sass/tests/tsconfig.json, packages/cli/webpack/src/config/base.ts, packages/cli/webpack/src/utils/constants.ts
**Goal:** 
add *.global.less/sass/scss support when output.disableCssModuleExtension is set to true.
**Info:** 
When we follow the [tourrial](https://modernjs.dev/docs/guides/usages/css/css-modules#%E5%85%A8%E9%9D%A2%E5%90%AF%E7%94%A8-css-modules) and set `output.disableCssModuleExtension` to true, all css/less/sass files will be considered as css modules files if they were not named as `[name].global.css`.
```css
/* app.global.css */
.bg-blue {
background-color: blue;
}
```
But css support is **not enough**, the developers might also want to use less/sass/scss for further uses.
So this PR provides the ability to fulfill their wishes:)
=> feat: add *.global.less/sass/scss support

.changeset/late-coins-judge.md, packages/cli/plugin-proxy/src/index.ts, packages/cli/plugin-proxy/src/utils/whistleProxy.ts, packages/cli/plugin-proxy/tests/.eslintrc.js, packages/cli/plugin-proxy/tests/__snapshots__/cli.test.ts.snap, packages/cli/plugin-proxy/tests/cli.test.ts, packages/cli/plugin-proxy/tests/index.test.ts, packages/cli/plugin-proxy/tests/tsconfig.json
Terminate "whistle" proxy when exiting the process
When developers use @modern-js/plugin-proxy for proxy uses, modern.js will not automatically close "whistle" proxy when terminating the process.
This PR will fix this problem.
With unit test
=> feat: terminate whistle proxy when exiting the process

.changeset/dry-goats-press.md, packages/server/hmr-client/package.json, pnpm-lock.yaml
refer to github issue: https://github.com/facebook/create-react-app/issues/11771
create-react-app v6.0.10 causes exception on dev server hot module replacement
=> fix: hot module reload for react app throwing exception

.changeset/lucky-birds-laugh.md, packages/toolkit/node-bundle-require/src/index.ts, packages/toolkit/node-bundle-require/tests/fixture/a.ts, packages/toolkit/node-bundle-require/tests/index.test.ts, packages/toolkit/node-bundle-require/tests/tsconfig.json
fix esbuild error when project's tsconfig.json sets "target:es5"
Problem: When use modern.config.js for configuration in modern.js project, which has some typings that ES5 doesn't support, like `const`
```typescript
// modern.config.ts
const a=1;
```
and tsconfig.json has been set as “target:es5"
```typescript
{
"compilerOptions": {
"target": "es5",
}
}
```
The Compiler will throw error like this:
```shell
Transforming const to the configured target environment ("es5") is not supported yet
```
Reason:
According to ESbuild 0.12.6 [change note](https://github.com/evanw/esbuild/releases/tag/v0.12.6), `target` would be read from 'tsconfig.json' when esbuild's own target is not defined
Fix:
Manually set esbuild's target to `esnext` in @modern-js/node-bundle-require
Some snippets for the …
=> fix: fix esbuild error when project's tsconfig.json sets "target:es5"

.changeset/chatty-onions-divide.md, .changeset/cold-kangaroos-smile.md, packages/server/bff-utils/src/client/generate-client.ts, packages/server/server/jest.config.js, packages/server/server/src/dev-tools/watcher/index.ts, packages/server/server/src/server/dev-server/dev-server.ts, packages/server/server/tests/fixtures/pure/tsconfig.json, packages/server/server/tests/server.test.ts, packages/server/server/tests/watcher.test.ts, packages/solutions/app-tools/package.json, packages/solutions/app-tools/src/index.ts, packages/toolkit/utils/src/constants.ts, pnpm-lock.yaml, tests/integration/bff-express/test/index.test.ts
1.  修复 windows 系统下，服务端热更新不生效的问题
2. 目前 polyfill 插件通过生成器开启，这里从 app-tools 中移除，减少体积。
[
](https://github.com/modern-js-dev/modern.js/issues/522)]
=> fix: remove plugin-polyfill from app-tools & hot reload not working on windows

.changeset/fluffy-apes-beam.md, packages/cli/core/src/config/index.ts, packages/cli/core/src/index.ts, packages/cli/core/tests/fixtures/index-test/package.json, packages/cli/core/tests/index.test.ts
maintain 'export type {...}' to core/config/index.ts
this way core/index.ts can just export via: export * from './config'
=> fix: export all interface from @modern-js/core/config

packages/cli/plugin-analyze/src/generateCode.ts, packages/cli/plugin-analyze/src/index.ts, packages/cli/plugin-analyze/tests/generateCode.test.ts, packages/toolkit/types/cli/index.d.ts
添加修改生成 routes 文件的 hook:
```js
export const beforeGenerateRoutes = createAsyncWaterfall<{
routes: ServerRoute[];
}>();
```
=> feat(plugin-analyze): add beforeGenerateRoutes hook

.changeset/sixty-boxes-explain.md, packages/cli/plugin-unbundle/package.json, packages/cli/plugin-unbundle/src/plugins/css.ts, packages/cli/plugin-unbundle/tests/fixtures/tailwind-example/package.json, packages/cli/plugin-unbundle/tests/index.test.ts, pnpm-lock.yaml
fix "tailwindcss" logics in plugin-unbundle
As now `@modern-js/plugin-unbundle` unnecessarily includes "tailwindcss" as `dependenices` in package.json, this PR will fix this problem and make sure when `@modern-js/plugin-tailwindcss` is imported, `tailwindcss` should be imported as well.
=> fix: fix "tailwindcss" logics in plugin-unbundle

.changeset/selfish-tables-visit.md, packages/cli/plugin-unbundle/modern.config.js, packages/cli/plugin-unbundle/src/client/error-overlay.ts, packages/cli/plugin-unbundle/src/client/index.ts, packages/cli/plugin-unbundle/src/constants.ts, packages/cli/plugin-unbundle/tests/client.test.ts, packages/cli/plugin-unbundle/tests/error-overlay.test.ts
modify client/index.js and client/error-overlay.js to Typescript files,
and change injection of these files to the modern build version
the previous `modern build` changes caused plugin-unbundle build to not
include these two files anymore, causing an error. This PR fixes the issue
=> fix(plugin-unbundle): include client injected files in build

.changeset/perfect-lobsters-press.md, packages/solutions/app-tools/src/utils/routes.ts, packages/solutions/app-tools/tests/routes.test.ts
生产环境构建时 app-tools 不会生成 dist 目录，生成 routes.json 时，需要保证有 dist 目录。
=> fix: create route.json failure

.changeset/brown-bulldogs-tan.md, packages/generator/generators/module-generator/templates/ts-template/tsconfig.json.handlebars, packages/generator/generators/mwa-generator/templates/ts-template/tsconfig.json
fix eslint error with "modern.config.ts"
When using "modern.config.ts" at root directory of modern.js project, and run the command:
```bash
pnpm run lint
```
It will throw error like this
```
error: Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: modern.config.ts.
The file must be included in at least one of the projects provided at modern.config.ts
```
So, we will need to include "modern.config.ts" at `include` param in `tsconfig.json`.
This PR will fix it.
=> fix: fix eslint error with "modern.config.ts"

.changeset/early-deers-lick.md, packages/cli/core/src/index.ts, packages/cli/core/tests/index.test.ts, packages/cli/core/tests/loadEnv.test.ts, packages/cli/webpack/src/config/client.ts, packages/cli/webpack/tests/base.test.ts, packages/cli/webpack/tests/client.test.ts
1. When a custom env var starts with prefix `MODERN_`, it will be handled as a public env var(no need to define in `source.envVars`).
2. Support more .env files,  loading different .env file by the `MODERN_ENV` env var .
=> feat: enhance custom env vars

.changeset/fresh-knives-doubt.md, packages/cli/plugin-unbundle/src/parse-dts.ts, packages/cli/plugin-unbundle/tests/dts.test.ts
fix plugin-unbundle parsing error with tsconfig
If modern.js project's `tsconfig.json` has included a nonexistent files in `include` array:
For this example, the nonexistent file is `modern.config.ts`:
```js title="tsconfig.json"
{
"extends": "@modern-js/tsconfig/base",
"include": ["src", "shared", "config", "modern.config.ts"]
}
```
Then when developers try to use modern.js `unbundle` feature, it will throw the error and stop running.
When using `parseDTS` function in `plugin-unbundle`, it doesn't verify the existence of files.
=> fix: fix plugin-unbundle parsing error with tsconfig

.changeset/clean-hornets-raise.md, .changeset/ten-paws-remain.md, packages/cli/plugin-testing/package.json, packages/cli/plugin-unbundle/src/utils.ts, packages/cli/plugin-unbundle/tests/fixtures/scan-imports/package.json, packages/cli/plugin-unbundle/tests/utils.test.ts, packages/server/plugin-egg/src/plugin.ts, packages/server/plugin-koa/src/plugin.ts
放开 unbundle 判断是 bff 项目的限制。（允许非 @modern-js/plugin-bff 插件）
修复自定义 server 用户设置 404 状态码，不生效的问题。
=> fix: allow other bff plugin in unbundle mode

.changeset/clean-games-talk.md, packages/cli/plugin-unbundle/src/plugins/esbuild.ts
example:
import*as React from'react'
was originally not detected and would cause duplicate import statements
=> fix(plugin-unbundle): detect ugly react import statements

.vscode/extensions.json, .vscode/settings.json, monorepo.code-workspace, packages/generator/generators/base-generator/templates/base-templates/.vscode/extensions.json, packages/generator/generators/base-generator/templates/base-templates/.vscode/settings.json, packages/generator/generators/monorepo-generator/templates/base-template/monorepo.code-workspace
1. fix plugin name of vscode-styled-components.
2. add prettier-vscode to recommend plugins list.
3. forget to update some defaultFormatter configs in https://github.com/modern-js-dev/modern.js/pull/675
=> chore: update vscode settings

.changeset/twelve-papayas-move.md, monorepo.code-workspace, packages/cli/plugin-unbundle/src/dev.ts, packages/cli/plugin-unbundle/src/index.ts, packages/cli/plugin-unbundle/src/plugins/container.ts, packages/cli/plugin-unbundle/src/server.ts, packages/cli/plugin-unbundle/src/typings/index.d.ts, packages/cli/plugin-unbundle/src/utils.ts, packages/cli/plugin-unbundle/tests/__snapshots__/index.test.ts.snap, packages/cli/plugin-unbundle/tests/index.test.ts, packages/cli/plugin-unbundle/tests/server.test.ts, packages/cli/plugin-unbundle/tests/utils.test.ts, packages/toolkit/utils/src/constants.ts
A package that cannot be converted to ESM may be optionally required by some dependency intended only for Node.js use. However, this will cause that dependency to throw error on unbundle development. Add user config to ignore such dependencies
Fix unbunde dev server crash on restart. Should expose closeServer method to allow plugin to clean up resources on restart.
=> feat(plugin-unbundle): add config option for ignoring package

.changeset/poor-goats-occur.md, packages/cli/core/src/context.ts, packages/cli/core/src/index.ts, packages/cli/core/src/loadPlugins.ts, packages/cli/core/tests/fixtures/load-plugin/user-plugins/test-plugin-c.js, packages/cli/core/tests/index.test.ts, packages/cli/core/tests/loadPlugin.test.ts, packages/cli/plugin-multiprocess/src/index.ts, packages/toolkit/types/cli/index.d.ts
Plugins support to accept options. 
Usage:
```
// modern.config.ts
import { defineConfig } from '@modern-js/app-tools'
plugins:  [{cli: ['plugin-a', {option: 'xx'} ]
});
```
=> feat:  plugins support to accept options

.changeset/chilled-countries-beam.md, .changeset/fluffy-chefs-bow.md, packages/cli/core/src/config/index.ts, packages/cli/webpack/src/config/client.ts, packages/generator/generator-utils/tests/stripAnsi.test.ts, packages/generator/generators/bff-generator/tests/index.test.ts, packages/solutions/app-tools/lib/types.d.ts, packages/solutions/module-tools/lib/types.d.ts, packages/solutions/module-tools/package.json, packages/toolkit/utils/tests/index.test.ts, pnpm-lock.yaml
修复 output.copy 类型定义
修复图片资源使用 inline 和 url 后缀时类型问题
=> fix: output copy type && img resource support inline and url module

.changeset/lucky-tables-speak.md, packages/cli/plugin-unbundle/src/constants.ts, packages/cli/plugin-unbundle/src/plugins/lazy-import.ts, packages/cli/plugin-unbundle/tests/style.test.ts
add unbundle support for "arco design"
Now, `modern.js` supports importing [ant design](https://ant.design/) UI component without importing its css, like the examples above:
```jsx
import { List } from 'antd';
// As we don't need importing css for ant design, we add comment slash above.
// import "antd/dist/antd.css";
const App = () => <List/>
```
But somehow it's not availiable for [arco design](https://arco.design/en-US) yet. So this PR is gonna add its support.
After `arco design` is supported, developer can use command `modern dev --unbundled` to run project with `arco design` UI component, and without importing its css.
```jsx
import { List } from '@arco-design/web-react';
// As we don't need importing css for ant design, we add comment slash above.
// import …
```
=> feat: add unbundle support for "arco design"

.changeset/brown-pigs-brake.md, packages/cli/plugin-garfish/src/cli/index.ts, packages/cli/plugin-less/src/types.ts, packages/cli/plugin-sass/src/types.ts, packages/cli/plugin-tailwind/src/types.ts, packages/review/eslint-config-app/eslintrc.js, packages/runtime/src/plugin.ts, packages/solutions/monorepo-tools/src/hooks/index.ts, packages/toolkit/compiler/babel/src/type.ts, packages/toolkit/esmpack/src/utils/parseExports.ts, packages/toolkit/plugin/src/manager/async.ts, packages/toolkit/plugin/src/manager/sync.ts, packages/toolkit/plugin/src/waterfall/async.ts, packages/toolkit/plugin/src/waterfall/sync.ts, packages/toolkit/plugin/src/workflow/async.ts, packages/toolkit/plugin/src/workflow/parallel.ts, packages/toolkit/plugin/src/workflow/sync.ts, packages/toolkit/utils/src/applyOptionsChain.ts
Remove `no-invalid-void-type` rule, it is not a recommend rule of typescript-eslint, an void is a commonly used type in out codebase.
- https://typescript-eslint.io/rules/no-invalid-void-type/
=> fix(eslint): remove no-invalid-void-type rule

.changeset/friendly-apricots-accept.md, packages/cli/plugin-bff/package.json, packages/server/create-request/package.json, packages/server/plugin-egg/package.json, packages/server/plugin-express/package.json, packages/server/plugin-koa/package.json, packages/server/plugin-nest/package.json, pnpm-lock.yaml
之前因为 modernjs/utils 依赖的 typescript 版本问题，导致安装 modernjs/core 会有多个实例，把很多为 dependencies 的依赖改为了 peerDependencies。现在该问题已修复，将依赖修改回来，避免隐式依赖及 pnpm 安装之后的警告。
=> fix: move some peerDependencies to dependecies

packages/cli/core/src/manager.ts, packages/toolkit/plugin/package.json, packages/toolkit/plugin/src/manager/async.ts, packages/toolkit/plugin/src/manager/sync.ts, packages/toolkit/plugin/tests/async.test.ts, packages/toolkit/plugin/tests/sync.test.ts, pnpm-lock.yaml
manager.usePlugin support accept new plugin function, this makes it easier to write unit tests for new plugins.
```js
const plugin = () => ({
name: 'foo',
setup: () => {}
});
// before
manager.usePlugin(manager.createPlugin(plugin.setup, plugin));
// after
manager.usePlugin(plugin);
```
=> feat(plugin): manager.usePlugin support accept new plugin function

package.json
Some articles said that add `--maxWorkers=2` can speed up jest in GitHub actions.
**After verification, this param can indeed reduce the test time by 1~3 minutes.**
see: 
- https://dev.to/ddoice/fix-slow-tests-with-jest-in-github-actions-5h00
- https://bharathvaj.me/blog/speedup-jest-github-actions
=> test: speed up unit test by adding --maxWorkers=2

codecov.yml
Some times we didn't modified any code, but codecov will prompt that the coverage has dropped by 0.01 and failed.
The threshold config is to solve this issue, it allow the coverage to drop by 0.02%, and I believe this will not affect our code coverage requirements.
=> chore: add codecov threshold config

.changeset/slow-books-greet.md, packages/toolkit/plugin/src/manager/async.ts, packages/toolkit/plugin/src/manager/sync.ts, packages/toolkit/plugin/tests/async.test.ts, packages/toolkit/plugin/tests/sync.test.ts
Support using manager.clone to override plugin api, which makes it easier to write test cases.
=> feat(plugin): allow manger.clone to override plugin api

.changeset/dirty-cherries-train.md, packages/cli/core/src/context.ts, packages/cli/core/src/pluginAPI.ts, packages/cli/core/tests/pluginAPI.test.ts
- support `api.setAppContext`
plugin-analyze using `AppContext.set` api, adding `api.setAppContext` to replace it.
=> feat(core): support api.setAppContext

packages/cli/core/.eslintrc.js, tsconfig.json
Narrow the lint scope in monorepo root  `tsconfig.json`. 
It's better  that each sub-package has it's own eslint config. 
An example in `@modern-js/core`:
```
// .eslintrc.js
module.exports = {
root: true,
extends: ['@modern-js'],
parserOptions: {
// the base path used to search for `tsconfig.json`
tsconfigRootDir: __dirname,
// the relative path to sub-package's `tsconfig.json` 
project: ['./tsconfig.json'],
},
};
```
=> fix: lint scope

packages/cli/core/src/index.ts, packages/cli/core/src/manager.ts, packages/cli/core/src/pluginAPI.ts, packages/server/core/src/plugin.ts
- the `PluginAPI` type should include common api
- make exports of core more explicitly
=> fix: PluginAPI type should include common api

.changeset/giant-phones-tell.md, packages/cli/plugin-bff/package.json, packages/server/server/src/dev-tools/babel/register.ts, packages/solutions/app-tools/src/commands/dev.ts
disable load webpack when apiOnly mode
=> fix: disable load webpack when apiOnly mode

.changeset/lazy-cups-tie.md, packages/cli/plugin-runtime/src/cli/index.ts, packages/cli/plugin-runtime/tests/index.test.ts, packages/cli/plugin-state/package.json
feat(plugin-runtime): convert to new plugin
transform `@modern-js/runtime` to new plugin syntax.
=> feat(plugin-runtime): convert to new plugin

.changeset/hungry-ravens-switch.md, packages/cli/plugin-jarvis/src/index.ts
feat(plugin-jarvis): convert to new plugin
convert `@modern-js/plugin-jarvis' to new plugin syntax.
=> feat(plugin-jarvis): convert to new plugin

.changeset/afraid-bobcats-roll.md, packages/cli/core/src/config/defaults.ts, packages/cli/core/src/config/index.ts
Set default value for required keys of `NormalizedConfig` . Otherwise, the `plugins`, `runtime`, `runtimeByEntries` config could be undefined.
=> fix: set default value for required keys of NormalizedConfig

.changeset/stupid-boats-shake.md, packages/cli/core/src/context.ts, packages/cli/core/src/loadPlugins.ts, packages/cli/core/tests/loadPlugin.test.ts, packages/cli/plugin-unbundle/tests/fixtures/scan-imports-monorepo/packages/module-importer/package.json, packages/server/prod-server/tests/fixtures/pure/package.json, packages/toolkit/types/cli/index.d.ts
Support new plugin config: 
```ts
import MyPlugin from './plugins/my-plugin';
import { defineConfig } from '@modern-js/core';
plugins: [
MyPlugin({ ... }),
]
});
// or
plugins: {
cli: [
MyPlugin({ ... }),
]
}
});
```
- The old `plugin` config can still work as before.
- The `cliPkg` and `pluginPath` field of `LoadedPlugin` is removed, we can not get the `cliPkg` and `pluginPath` from the new plugin config, and no internal code is currently using this field.
- close https://github.com/modern-js-dev/modern.js/issues/686
Provide better typescript support.
=> feat(core): support new cli plugin config

.changeset/seven-kangaroos-tap.md, packages/toolkit/plugin/src/manager/async.ts, packages/toolkit/plugin/src/manager/sync.ts
feat: add compatible logic of plugin options with "setup" param
As #794 has provided `@modern-js/plugin` the ability to accept new plugin syntax with setup param, like the examples above:
```ts
// plugin example in modern.js
import type { CliPlugin } from '@modern-js/core';
export default (): CliPlugin => ({
name: 'foo',
setup: api => {},
pre: ['@modern-js/plugin-unbundle']
});
```
Changed part snippet:
``` ts
// packages/toolkit/plugin/src/manager/async.ts
const usePlugin: AsyncManager<Hooks, API>['usePlugin'] = (...input) => {
for (const plugin of input) {
//... skip old logics
// plain plugin options with `setup` param
else if (plugin.setup) {
addPlugin(createPlugin(plugin.setup, plugin));
}
// skip other logics
}
return manager;
};
```
But somehow the #794 PR forgot to bring this to …
=> feat: add compatible logic of plugin options with "setup" param

.changeset/brave-icons-yell.md, packages/cli/core/src/config/index.ts, packages/server/core/src/plugin.ts, packages/server/server/src/server/dev-server.ts, website/docs/apis/config/tools/dev-server.md
support beforeDevServer、afterDevServer server hook.
onBeforeSetupMiddleware, onAfterSetupMiddleware can be used as syntactic sugar.
can config in jupiter.config.js like this:
```
{
tools: {
devServer: {
onBeforeSetupMiddleware: [
async (ctx, next) => {
console.log('before');
next();
},
],
onAfterSetupMiddleware: [
async (ctx, next) => {
console.log('after');
next();
},
],
},
},
}
```
next step is to implement more configurations, such as specifying the middleware writing of the route
=> feat: support devServer middleware hook

.changeset/spicy-rings-talk.md, packages/cli/plugin-analyze/package.json, packages/cli/plugin-cdn-cos/package.json, packages/cli/plugin-cdn-oss/package.json, packages/cli/plugin-changeset/package.json, packages/cli/plugin-docsite/package.json, packages/cli/plugin-esbuild/package.json, packages/cli/plugin-fast-refresh/package.json, packages/cli/plugin-jarvis/package.json, packages/cli/plugin-less/package.json, packages/cli/plugin-nocode/package.json, packages/cli/plugin-proxy/package.json, packages/cli/plugin-router/package.json, packages/cli/plugin-router/src/runtime/plugin.tsx, packages/cli/plugin-runtime/package.json, packages/cli/plugin-sass/package.json, packages/cli/plugin-server-build/package.json, packages/cli/plugin-ssr/package.json, packages/cli/plugin-state/package.json, packages/cli/plugin-storybook/package.json, packages/cli/plugin-unbundle/package.json
feat: remove unnecessary peerDependencies
In the former plugin design, we need to use peerDependencies including `@modern-js/core` or `@modern-js/runtime-core` to ensure there is only one instance for core. 
But later we migrated to the new plugin design, these peerDependencies are no longer needed. So this PR is gonna remove them.
=> feat: remove unnecessary peerDependencies

.changeset/late-boats-mix.md, packages/toolkit/plugin/src/manager/async.ts, packages/toolkit/plugin/src/manager/sync.ts, packages/toolkit/plugin/tests/async.test.ts, packages/toolkit/plugin/tests/sync.test.ts
Allow to use plugin without setup function (some plugins in jupiter are just wrappers).
=> fix(plugin): should allow to use plugin without setup function

.changeset/clever-seals-learn.md, packages/cli/webpack/src/utils/createCSSRule.ts, website/docs/apis/config/output/disable-css-extract.md, website/docs/guides/features/framework-plugin/extend.md
Enable css extract in dev mode by default, so we can keep the dist files same in dev and prod mode.
=> feat(webpack): enable css extract in dev mode by default

.changeset/perfect-bobcats-wonder.md, packages/cli/plugin-cdn-cos/src/modern-app-env.d.ts, packages/cli/plugin-cdn-oss/src/modern-app-env.d.ts, packages/cli/plugin-garfish/package.json, packages/cli/plugin-lambda-fc/src/modern-app-env.d.ts, packages/cli/plugin-lambda-scf/src/modern-app-env.d.ts, packages/cli/plugin-multiprocess/src/modern-app-env.d.ts, packages/cli/plugin-sass/package.json, packages/cli/plugin-testing/package.json, packages/cli/static-hosting/src/modern-app-env.d.ts, packages/generator/generator-common/src/newAction/module/index.ts, packages/generator/generator-common/src/newAction/mwa/index.ts, packages/generator/generators/cloud-deploy-generator/src/modern-app-env.d.ts, packages/generator/generators/dependence-generator/tests/index.test.ts, packages/generator/generators/module-generator/templates/ts-template/src/modern-app-env.d.ts.handlebars, packages/server/plugin-server/src/modern-app-env.d.ts, packages/solutions/app-tools/package.json, packages/solutions/module-tools/package.json, packages/toolkit/node-bundle-require/src/modern-app-env.d.ts, packages/toolkit/node-bundle-require/tests/modern-app-env.d.ts, tests/integration/api-service-koa/api/modern-app-env.d.ts, tests/integration/bff-express/src/modern-app-env.d.ts, tests/integration/new-mwa-app/src/modern-app-env.d.ts, tests/integration/testing-app/src/modern-app-env.d.ts, tests/integration/testing-bff/src/modern-app-env.d.ts
feat: optimise "types" exports from plugin
This PR include these features listed above:
1. add types export for `@modern-js/plugin-sass` and `@modern-js/plugin-garfish`, including the plugin itself and generator's part.
2. change export path from `type` to `types` for `@modern-js/app-tools`, `@modern-js/plugin-testing` and `@modern-js/module-tools`.
Noted: As `@modern-js/plugin-testing` and `@modern-js/module-tools` has been using `type` for such a while, so for forward compatbility, the code still keep `type` as reference path.
```typescript
// regular uses for reference
/// <reference types='@modern-js/module-tools/types' />
/// <reference types='@modern-js/plugin-testing/types' />
// Old paths still work, but not recommended
/// <reference types='@modern-js/module-tools/type' />
/// …
```
=> feat: optimise "types" exports from plugin

.vscode/settings.json, monorepo.code-workspace, website/docs/apis/config/output/css-module-localIdent-name.md, website/docs/apis/config/output/enable-ts-loader.md, website/docs/apis/config/output/favicon-by-entries.md, website/docs/apis/config/output/import-style.md, website/docs/apis/config/output/inject-by-entries.md, website/docs/apis/config/output/meta-by-entries.md, website/docs/apis/config/output/ssg.md, website/docs/apis/config/output/title-by-entries.md
The `output` directory is excluded in VS Code setting, and we can not search its contents.
Currently there is no temp files that are placed in the `output` directory, so this configuration can be removed.
=> chore: failed to search content in output directory

.changeset/cyan-walls-fly.md, packages/cli/core/src/initWatcher.ts
Ignore initial add events of watching files
=> fix: ignore initial watching add events

.changeset/honest-frogs-wash.md, package.json, packages/generator/generators/module-generator/templates/base-template/package.json.handlebars, packages/generator/generators/monorepo-generator/templates/base-template/package.json.handlebars, packages/generator/generators/mwa-generator/templates/base-template/package.json.handlebars, tests/integration/api-service-koa/package.json, tests/integration/bff-express/package.json, tests/integration/new-mwa-app/package.json, tests/integration/server-prod/package.json
1.  Remove `git add` from lint-staged to fix  the warning after lint-staged v10. [[Reference](https://github.com/okonet/lint-staged/releases/tag/v10.0.0)]
2. Modify `setup` script to ensure husky `install` script would be executed during installing-dependency process.
=> fix: lint-staged warning

packages/toolkit/esmpack/tsconfig.json
esmpack 的 tsconfig.json 没有继承 `@modern-js/tsconfig`，而是单独写了一份配置。
该配置中缺少了 `DOM` lib 的定义，导致构建时提示 window 不存在：
修复方式为加上 `DOM` lib，使 window 类型可以被正确识别。
=> chore: fix esmpack tsconfig, add DOM lib

.changeset/clever-steaks-peel.md, packages/server/hmr-client/src/index.ts, packages/toolkit/utils/package.json
The `hmr-client` package will be bundled and running in the browser, do not import from the entry of @modern-js/utils.
=> fix(hmr-client): should not bundle all utils

.changeset/dull-nails-wink.md, packages/cli/plugin-router/src/runtime/plugin.tsx, packages/runtime/src/compatible.tsx
Hoc hook of the runtime plugin would break now in conventional routes. This PR would fix it.
=> fix: hoc hook break in conventional routes

.changeset/tasty-ducks-bathe.md, packages/cli/core/package.json, packages/cli/core/src/index.ts, packages/cli/core/src/utils/commander.ts, packages/server/plugin-express/package.json, packages/solutions/app-tools/package.json, packages/solutions/module-tools/package.json, packages/solutions/monorepo-tools/package.json, pnpm-lock.yaml
- Move `commandsMap` declaration to `index.ts`, makes it taking effect by default.
- Publish `@modern-js/core` v1.7.1
=> fix(core): commander.commandsMap typing not work

.changeset/twelve-paws-battle.md, packages/cli/plugin-garfish/package.json, packages/cli/plugin-garfish/src/util.ts, pnpm-lock.yaml
`plugin-garfish/utils.ts` will be bundled and running in the browser, should not import from `@modern-js/utils`.
https://github.com/modern-js-dev/modern.js/issues/911
https://github.com/modern-js-dev/modern.js/pull/883
=> fix(plugin-garfish): should not import from @modern-js/utils

.changeset/thin-impalas-talk.md, packages/server/server/src/dev-tools/dev-server-plugin.ts, packages/server/server/tests/dev.test.ts
移除 `webpack/hot/dev-server`。
`webpack/hot/dev-server` 中包含了一段与 `webpack-dev-server` 配套的运行时代码，由于 modern.js 未使用 `webpack-dev-server`，因此这段代码没有实际的作用（反而会影响依赖预打包）。
移除后，HMR 功能依然由 `hmr-client` 正常提供。
`create-react-app` 中默认也不需要引入这段代码：
=> fix(server): remove unused webpack/hot/dev-server entry

tests/integration/alias-set/test/index.test.js, tests/integration/new-mwa-app/tests/index.test.js
This [PR](https://github.com/modern-js-dev/modern.js/pull/915) removed `webpack/hot/dev-server`，and the related test cases in integration tests should be removed too.
=> fix: remove hmr log breaks integration test

packages/cli/plugin-docsite/package.json, packages/cli/plugin-nocode/package.json, packages/cli/plugin-storybook/package.json, packages/cli/plugin-testing/package.json, packages/cli/webpack/package.json, packages/review/testing/package.json, packages/solutions/app-tools/package.json, pnpm-lock.yaml
I released 1.5.5 to beta by mistake, so adjust the next version to 1.5.6.
=> chore: adjust webpack version

.changeset/wise-spiders-drive.md, packages/cli/plugin-unbundle/src/create-entry.ts
`react-refresh` added `exports` field and breaks the unbundle plugin:
=> fix(unbundle): incorrect react-refrech entry path

.changeset/purple-dancers-rescue.md, packages/cli/webpack/src/plugins/ts-config-paths-plugin.ts
Fix following error (occurs when compileOptions is not defined in `tsconfig.json`):
=> fix(webpack): failed to read property of compileOptions

.changeset/rich-beers-thank.md, packages/review/eslint-config-app/ts.withType.js
Extends `@typescript-eslint/recommended-requiring-type-checking` rules instead of custom configs.
=> chore: extend @typescript-eslint/recommended-requiring-type-checking

.changeset/many-dingos-promise.md, packages/cli/plugin-docsite/src/features/utils/webpack.ts, packages/cli/plugin-nocode/src/build-task.ts, packages/cli/plugin-nocode/src/cli.ts, packages/cli/plugin-testing/src/cli/index.ts, packages/cli/webpack/package.json, packages/cli/webpack/src/index.ts, packages/solutions/app-tools/src/commands/build.ts, packages/solutions/app-tools/src/commands/dev.ts
`@modern-js/webpack` wouldn't depend on `@modern-js/core` to avoid potential multiple `@modern-js/core` issue.
=> refactor(webpack): remove @modern-js/core

.changeset/odd-insects-relate.md, package.json, packages/cli/plugin-esbuild/src/esbuild-webpack-plugin.ts, pnpm-lock.yaml
- No need to compatible with webpack 4.
- Remove unused dep `scan-deps`
=> fix(plugin-esbuild): no need to compatible with webpack 4

.github/workflows/build-website.yml, .github/workflows/integration-test-Windows.yml, .github/workflows/integration-test-macOS.yml, .github/workflows/lint-Linux.yml, .github/workflows/reset-prepare.yml, .github/workflows/test-Windows.yml, .github/workflows/test-macOS.yml, fast-lint.sh
pnpm released v7 and have some [breaking changes](https://github.com/pnpm/pnpm/releases) (or bugs).
For example, `pnpm run build --filter @modern-js/eslint-config...` is not working, and  `pnpm --filter @modern-js/eslint-config.. build` can work as before.
I think we should lock the pnpm version in CI until pnpm v7 become stable.
The `lint` CI is broken:
=> chore: lock pnpm to v6 in CI config

.changeset/four-plums-approve.md, packages/solutions/app-tools/src/commands/build.ts
修复 build 命令的参数不生效的问题 (比如`build --analyze`).
原因是 `getWebpackConfig` 改成了外部传入 `resolvedConfig`，而 build 命令的实现中，先读取了 `resolvedConfig`，再对 `resolvedConfig` 添加了 `cliOptions` 属性，导致 `getWebpackConfig` 中无法获取到 `cliOptions` 属性。
=> fix(app-tools): build command params not work

.changeset/big-trains-compete.md, packages/cli/webpack/package.json, packages/cli/webpack/src/config/node.ts, packages/server/create-request/src/node.ts, pnpm-lock.yaml
SSR 场景下，期望 server 端也 bundle 所有的代码及依赖，目前加的 node-external 在 pnpm 下是无效的，使用 yarn 的情况下生效。两者构建出的 bundle 体积有较大的差异，不符合预期。
dist/bundles/main.js (yarn): 278 k
dist/bundles/main.js (pnpm): 973 k
=> fix: remove node-external for server bundle

packages/cli/plugin-runtime/package.json
Fix the path to `@modern-js/runtime/model` types.
Released hotfix version: @modern-js/runtime@1.2.8.
=> fix:  path to `@modern-js/runtime/model` types

.changeset/strong-shirts-count.md, packages/cli/webpack/package.json, pnpm-lock.yaml
The `tapable` should be declared in `dependencies` rather than `devDependencies`, so that the prebundled `webpack-manifest-plugin` can solve the correct version of `tapable`.
Tested in alpha version (1.6.2-alpha.0).
=> fix(webpack): incorrect tapable version in some cases

.changeset/perfect-beers-joke.md, packages/cli/babel-preset-app/package.json, packages/cli/babel-preset-base/package.json, packages/cli/babel-preset-lib/package.json, packages/cli/babel-preset-module/package.json, packages/cli/plugin-bff/package.json, packages/cli/plugin-jarvis/package.json, packages/cli/plugin-ssr/package.json, packages/cli/plugin-testing/package.json, packages/cli/plugin-unbundle/package.json, packages/cli/webpack/package.json, packages/review/testing/package.json, packages/server/server/package.json, packages/server/utils/package.json, packages/toolkit/compiler/babel/package.json, packages/toolkit/esmpack/package.json, pnpm-lock.yaml, scripts/prebundle/package.json
不再锁定 @babel/core 版本，当时锁定版本的背景是与 v8-compile-cache 有冲突，该问题已在 @babel/core 新版本中修复，因此不再需要锁版本。
锁版本会导致 `plugin-jarvis` 下的 `@babel/eslint-plugin` 无法被 hoist（yarn install可复现），最终导致 ESLint 报错
确认 `@babel/eslint-plugin` 是否可以移动到 `eslint-config-app` 下面。
=> fix: unlock @babel/core version

.changeset/blue-emus-matter.md, packages/cli/webpack/src/config/client.ts, packages/cli/webpack/tests/client.test.ts
Fix the recompile issue after running dev command (the TypeChecker is also triggered twice):
This problem is caused by the incorrect `copy-webpack-plugin` configuration, we add a copy configuration when the `upload/public`directory does not exist, which eventually triggers webpack removedFiles detection.
=> fix(webpack): fix the recompile issue after running dev command

.changeset/light-crabs-perform.md, packages/cli/webpack/src/config/client.ts
`console.xx` polyfill is unnecessary, remove it to reduce bundle size (20kb)
`require('console')` will still be polyfilled by `resolve.fallback`.
=> fix(webpack): remove console polyfill to reduce bundle size

.changeset/four-bees-compete.md, packages/review/testing-plugin-bff/src/index.ts, packages/review/testing-plugin-bff/tests/.eslintrc.js, packages/review/testing-plugin-bff/tests/__snapshots__/index.test.ts.snap, packages/review/testing-plugin-bff/tests/index.test.ts, packages/review/testing/src/config/testConfigOperator.ts, packages/review/testing/src/runJest.ts
如果用户配置是对象，会在 jestConfig 钩子执行之前合并，这样测试插件可以处理用户的配置。
=> fix: setJestConfig before jestConfig hook execute

.changeset/spicy-melons-glow.md, packages/cli/webpack/src/config/base.ts, packages/cli/webpack/src/config/client.ts, packages/cli/webpack/src/utils/getBabelOptions.ts
We should not require entire `core-js` and `regenerator-runtime` when `output.polyfill` is `ua` or `usage`, otherwise the polyfill will be fully imported.
=> fix(webpack): output.polyfill usage not work

packages/cli/plugin-garfish/src/cli/index.ts
Plugin Garfish invoke `useResolvedContextConfig` in config hook which can only get `{}` as a result.
move `useResolvedContextConfig` to webpack callback.
nil
=> fix(plugin-garfish): use resolved context in config hook

.changeset/tender-beans-shake.md, packages/cli/plugin-jarvis/package.json, packages/review/eslint-config-app/base.js, pnpm-lock.yaml
Remove `eslint-import-resolver-webpack`.
This resolver is used to resolve `webpack.config.js` and get the alias config, it is useless in modern.js projects, we did not  expose the `webpack.config.js` file.
Reduce dependencies, and fix the peer deps warning:
=> fix(eslint): remove eslint-import-resolver-webpack

.changeset/serious-rice-pretend.md, packages/cli/webpack/src/config/base.ts
webpack [v5.66.0](https://github.com/webpack/webpack/releases/tag/v5.66.0) reduce default `watchOptions.aggregateTimeout` from `200ms` to `20ms`, which caused watch mode rebuild twice on file change.
To fix this issue, we can increase  `watchOptions.aggregateTimeout` to `100ms` util webpack fix this issue.
- https://github.com/webpack/webpack/issues/15431
- https://github.com/webpack/webpack/pull/15041
=> fix(webpack): webpack watch mode rebuild twice on file change

pnpm-lock.yaml, tests/integration/alias-set/package.json, tests/integration/api-service-koa/package.json, tests/integration/bff-express/package.json, tests/integration/esbuild/fixtures/minify-js/package.json, tests/integration/new-mwa-app/package.json, tests/integration/runtime/fixtures/use-loader/package.json, tests/integration/server-config/package.json, tests/integration/server-prod/package.json, tests/integration/testing-app/package.json
Fix integration test missing `@babel/runtime` dependency.
=> chore: fix integration test missing @babel/runtime dependency

.changeset/twenty-vans-double.md, packages/cli/webpack/src/plugins/module-scope-plugin.ts
Currently `module-scope-plugin` repeats the calculation for each path, we can add cache to make the `module-scope-plugin` 10x faster.
Tested in `arco-pro` project.
Before this PR:
After this PR:
=> perf(webpack): make module-scope-plugin 10x faster

packages/cli/plugin-analyze/src/constants.ts, packages/cli/plugin-jarvis/package.json, packages/review/eslint-config-app/package.json, packages/review/eslint-config/package.json, pnpm-lock.yaml
1.  Move eslint related deps to `@modern-js/eslint-config-app`.
2. Add `typecripts` in `@modern-js/eslint-config-app` since `@typescript-eslint/*` depend on it,  otherwise the lint may fail in a JS project.
=> refactor: adjust lint related package's deps

website/docs/guides/tutorials/c05-component/5.2-use-standalone-component.md, website/docs/guides/tutorials/c06-css-and-component/6.3-postcss.md
=> docs: remove `postcss-preset-env`

.changeset/early-camels-lie.md, package.json, packages/cli/core/package.json
The `modern` command is provided by `xxx-tools`, and `@modern-js/core` should not register a `core` command.
Fix the following error:
Remove:
Also change `pnpm dlx rimraf` to `npx rimraf` because `pnpm dlx` will modify the lock file.
https://github.com/modern-js-dev/modern.js/issues/438#issuecomment-1004526723
=> fix(core): should not register a `core` command

.changeset/perfect-mirrors-grab.md, packages/cli/webpack/src/config/node.ts
- remove `config.devtool = false`, the `devtool` is already defined by `this.chain.devtool(false)`
https://github.com/modern-js-dev/modern.js/blob/a7e8b0610a1130139643125872d1a3fad778cca9/packages/cli/webpack/src/config/node.ts#L20-L22
- fix ts checker runs twice when ssr is enabled
=> fix(webpack): ts checker runs twice when ssr is enabled

.changeset/strange-radios-burn.md, packages/cli/webpack/src/config/node.ts, packages/cli/webpack/tests/node.test.ts
Filter SSR bundles by `server.ssrByEntries`.
For example, a project contains two entries: `foo` and `bar`, and only `foo` is using SSR:
```js
{
ssrByEntries: {
foo: true,
},
}
```
In this case, the bundle of bar is never used, we don't need to bundle bar.
Make SSR compile speed faster.
=> feat(webpack): filter SSR bundles by server.ssrByEntries

.changeset/quick-paws-rule.md, packages/cli/webpack/src/config/node.ts, packages/toolkit/utils/src/monorepo.ts, packages/toolkit/utils/tests/monorepo.test.ts
`isModernjsMonorepo` should return false if there is no package.json.
=> fix(utils): isModernjsMonorepo return false if no package.json

.changeset/spicy-trainers-attack.md, packages/cli/webpack/src/config/base.ts, packages/cli/webpack/tests/base.test.ts, website/docs/apis/config/tools/webpack.md
`tools.webpack` support modify or return config object.
```js
tools: {
webpack: {
mode: 'development',
},
},
});
```
```js
tools: {
webpack: config => {
config.mode = 'development';
},
},
});
```
```js
tools: {
webpack: config => {
return {
...config,
mode: 'development',
};
},
},
});
```
The legacy `chain` param can still work as before, but there will be a deprecation warning.
=> feat(webpack): tools.webpack support modify or return config object

.changeset/sour-apes-burn.md, packages/cli/core/src/config/types/index.ts, packages/cli/webpack/src/config/base.ts, packages/cli/webpack/src/config/shared.ts, packages/cli/webpack/tests/base.test.ts, website/docs/apis/config/tools/webpack.md
Add following utils to `tools.webpack`:
- addRules
- prependPlugins
- appendPlugins
- removePlugin
So jupiter and modern.js can provide the same `tools.webpack` API.
=> feat(webpack): add more utils for tools.webpack

.changeset/nice-melons-wash.md, packages/server/prod-server/src/server/modern-server.ts, packages/server/server/src/server/dev-server.ts
server hook 'reset' should only run after server side code change
precise updates api  or web frame handler
=> fix: optimize server side hot reload

.changeset/sour-buttons-report.md, packages/server/server/src/constants.ts, packages/server/server/src/dev-tools/dev-server-plugin.ts, packages/server/server/src/server/dev-server.ts, packages/server/server/src/types.ts, packages/solutions/app-tools/src/commands/dev.ts, packages/toolkit/utils/src/prettyInstructions.ts, packages/toolkit/utils/tests/__snapshots__/prettyInstructions.test.ts.snap
fix HMR not working when using proxy:
```js
dev: {
proxy: {
name: 'app',
rules: `
https://www.foo.com/ http://127.0.0.1:8080/
`,
},
},
})
```
To fix this issue, we should always use `local ip` instead of `localhost` to create socket URL (same as `webpack-dev-server`).
=> fix(server): HMR not working when using proxy

.changeset/itchy-mayflies-drive.md, packages/cli/babel-preset-app/src/built-in/babel-plugin-ssr-loader-id.ts
When combined with `react-refresh`,  `useLoader` id generated by compilation would duplicate as following:
This PR  will fix the issue.
=> fix: fix duplicate `useLoader` id by compilation

.github/workflows/build-website.yml, .github/workflows/integration-test-Windows.yml, .github/workflows/integration-test-macOS.yml, .github/workflows/lint-Linux.yml, .github/workflows/reset-prepare.yml, .github/workflows/test-Windows.yml, .github/workflows/test-macOS.yml
`@pnpm/action-setup`  fails on CI, see https://github.com/pnpm/action-setup/issues/44
=> fix: stop using pnpm action-setup, fix the CI

.changeset/rotten-chicken-guess.md, packages/solutions/app-tools/src/commands/dev.ts, packages/solutions/app-tools/src/index.ts, packages/solutions/app-tools/src/locale/en.ts, packages/solutions/app-tools/src/locale/zh.ts, packages/solutions/app-tools/src/utils/types.ts, website/docs/apis/commands/mwa/dev.md
support using `dev --analyze` to analyze bundle size (same as `build --analyze`), it can be used to:
- compare the module graph between dev and build
- view the bundle size of single page by `dev --entry --analyze`
dev is faster than build, but the analysis results are not as accurate as build.
=> feat(app-tools): support dev --analyze

.changeset/funny-cars-listen.md, packages/cli/webpack/src/config/client.ts, packages/cli/webpack/src/runtime/core-js-entry.ts, packages/cli/webpack/tests/client.test.ts, pnpm-lock.yaml
Fix `useBuiltIns: 'entry'` of `@babel/preset-env` not work, which means `browserslist` can not affect the content of core-js polyfills.
**This change can reduce bundle size by 46.63KB.**
We should not add `core-js` as an webpack entry, otherwise the `@babel/preset-env` can not transform `core-js` to sub-paths.
Ref: https://babeljs.io/docs/en/babel-preset-env#usebuiltins-entry
=> fix(webpack): fix useBuiltIns entry not work, reduce bundle size

.changeset/cuddly-lemons-remember.md, packages/cli/core/src/config/types/index.ts, packages/cli/webpack/src/config/client.ts, packages/cli/webpack/tests/base.test.ts, packages/cli/webpack/tests/client.test.ts, packages/cli/webpack/tests/util.ts, packages/server/server/src/dev-tools/dev-server-plugin.ts, packages/server/server/tests/dev.test.ts, website/docs/apis/config/tools/dev-server.md
- support using `devServer.hot` to control HMR.
- support using `devServer.liveReload` to control live reload.
These two APIs have same effect as webpack-dev-server.
=> feat(devServer): support disable hmr or live reload

.changeset/fresh-rules-march.md, packages/cli/webpack/src/plugins/ts-config-paths-plugin.ts
webpack `alias` works on files in node_modules, and `paths` are expected to have the same effect as `alias`, so `paths` should works on files in node_modules,
=> fix(webpack): tsconfig paths should work with files in node_modules

.changeset/gold-owls-breathe.md, packages/cli/core/package.json, packages/cli/core/src/config/types/index.ts, packages/cli/css-config/package.json, packages/cli/css-config/src/postcss.ts, packages/cli/css-config/tests/index.test.ts, packages/cli/plugin-design-token/package.json, packages/cli/plugin-unbundle/package.json, packages/cli/webpack/package.json, packages/toolkit/compiler/style/package.json, packages/toolkit/esmpack/package.json, packages/toolkit/utils/src/applyOptionsChain.ts, pnpm-lock.yaml, scripts/prebundle/package.json, tests/integration/new-mwa-app/modern.config.ts, website/docs/apis/config/tools/postcss.md
- support addPlugins util in `tools.postcss`
- bump postcss to latest version, the #651  can not be reproduced.
```typescript
tools: {
postcss: (config, { addPlugins }) => {
// 添加一个插件
addPlugins(require('postcss-preset-env'));
// 批量添加插件
addPlugins([require('postcss-preset-env'), require('postcss-import')]);
},
},
});
```
=> feat: support addPlugins util in tools.postcss

.changeset/nice-bikes-smoke.md, packages/solutions/app-tools/src/commands/inspect.ts, packages/solutions/app-tools/src/index.ts, packages/solutions/app-tools/src/locale/en.ts, packages/solutions/app-tools/src/locale/zh.ts, packages/solutions/app-tools/src/utils/types.ts, packages/solutions/app-tools/tests/commands/__snapshots__/inspect.test.ts.snap, packages/solutions/app-tools/tests/commands/inspect.test.ts, website/docs/apis/commands/mwa/inspect.md
Support modern inspect command, using `WebpackChain.toString` to implement this feature.
=> feat(app-tools): support modern inspect command

.changeset/moody-hats-tap.md, packages/cli/webpack/src/config/base.ts, packages/cli/webpack/src/config/client.ts, packages/cli/webpack/src/config/modern.ts, packages/cli/webpack/src/config/node.ts, packages/cli/webpack/src/utils/getBabelOptions.ts, packages/cli/webpack/tests/utils.test.ts
- fix incorrect babel loader options for node target
- fix addExcludes/addIncludes not work for node target
These bugs are introduced in https://github.com/modern-js-dev/modern.js/pull/1200
=> fix(webpack): incorrect babel loader options for node target

.changeset/many-rats-help.md, packages/cli/babel-preset-base/src/babel-utils.ts, packages/cli/core/src/config/types/index.ts, packages/cli/webpack/src/config/shared.ts, packages/cli/webpack/tests/base.test.ts, packages/toolkit/utils/src/ensureArray.ts, packages/toolkit/utils/src/index.ts, website/docs/apis/config/tools/webpack.md
Improve utils of `tools.webpack`, allow `addRules` `appendPlugins`, `prependPlugins` to using non-array params.
This change will making it easier to use these utils.
=> feat(webpack): improve utils of tools.webpack

.changeset/wicked-ladybugs-repeat.md, packages/runtime/src/compatible.tsx
`createApp` should contain the same  `context` initialization logic with `bootstrap`, so user can directly mount the component returned by `createApp` without invoking `bootstrap`.
=> fix: make sure the Component returned by `createApp` could be mounted

.changeset/tasty-weeks-drive.md, packages/cli/babel-preset-base/src/babel-utils.ts
Fix error when using `addIncludes` util in `tools.babel`:
```js
tools: {
babel(opt, utils) {
utils.addIncludes(require.resolve('test-a'));
},
},
});
```
The `tools.babel` is also used by `@modern-js/server-utils`, which does not provide the `addIncludes` and `addExcludes` utils, so we should preset the default noop function.
=> fix: utils.addIncludes is not a function

packages/cli/babel-preset-app/src/built-in/babel-plugin-lock-corejs-version.ts, pnpm-lock.yaml, tests/integration/mwa-app/package.json
fix
**babel-runtime can't math path in windows system**
- [  ] My code follows the code style of this project.
- [  ] I have updated changeset
=> fix(babel-plugin-preset-app): can't match path in windows system

.changeset/serious-peaches-judge.md, packages/cli/core/src/pluginAPI.ts, packages/toolkit/plugin/src/farrow-pipeline/context.ts, packages/toolkit/plugin/src/manager/runner.ts
I exported some required types.
When i want to bundle  a modern plugin, i found a error about type. 
It's a problem that have occurred about type.  Look [here](https://github.com/microsoft/TypeScript/issues/42873) for more info.And i found this [answer](https://github.com/microsoft/TypeScript/issues/42873#issuecomment-869057582) can solve my problem. So i exported some required types to fix it.
And i also fix the same problem in @modern-js/plugin.
look in description
Only export type and no effects.
=> fix: the inferred type of "pluginAPI" cannot be named without a reference

.changeset/ten-owls-watch.md, packages/solutions/app-tools/src/index.ts, packages/toolkit/plugin/src/farrow-pipeline/asyncHooks.node.ts
Lazy import the `dev` and `start` action to improve the boot time of `modern start`.
The boot time decreased from `1000ms` to `600ms`.
Also fixed a bug of `@modern-js/plugin` when `enable` is called twice.
=> perf(app-tools): speed up modern start command

.changeset/polite-bats-love.md, packages/review/eslint-config-app/base.js
Remove prettier options in our ESLint config, so the editor extensions can read the `.prettierrc` config, this change can fix the inconsistent experience between prettier format and ESLint auto fix.
Detailed explanation in official document:
> Note: While it is possible to pass options to Prettier via your ESLint configuration file, it is not recommended because editor extensions such as prettier-atom and prettier-vscode will read [.prettierrc](https://prettier.io/docs/en/configuration.html), but won't read settings from ESLint, which can lead to an inconsistent experience.
Also add "arrow-body-style": "off" and "prefer-arrow-callback": "off"
> turns off two ESLint core rules that unfortunately are problematic with this plugin – see the next section.
Official guide: …
=> fix(eslint-config): inconsistent experience between format and auto fix

.changeset/fresh-garlics-sniff.md, packages/cli/core/src/config/index.ts, packages/cli/core/tests/__snapshots__/mergeConfig.test.ts.snap, packages/cli/core/tests/mergeConfig.test.ts
Fix failed to load user plugins of modern.config.js in some cases.
Such as:
```ts
import { defineConfig } from '@modern-js/app-tools';
import { createWaterfall } from '@modern-js/plugin';
import type { CliPlugin } from '@modern-js/core';
const message = createWaterfall<string[]>();
const MyPlugin = (): CliPlugin => ({
name: 'my-plugin',
registerHook: {
message,
},
});
plugins: [MyPlugin()],
runtime: {
router: true,
},
});
```
Will get an error like this (because we lost the symbol of plugins when merging config):
=> fix(core): failed to load user plugins of modern.config.js

.changeset/itchy-readers-impress.md, packages/generator/generators/module-generator/templates/base-template/package.json.handlebars, packages/generator/generators/monorepo-generator/templates/base-template/package.json.handlebars, packages/generator/generators/mwa-generator/templates/base-template/package.json.handlebars, packages/solutions/app-tools/package.json, packages/solutions/app-tools/src/index.ts, packages/solutions/module-tools/package.json, packages/solutions/module-tools/src/index.ts, packages/solutions/monorepo-tools/package.json, packages/solutions/monorepo-tools/src/index.ts, pnpm-lock.yaml, tests/integration/css-modules/test/index.test.js, tests/integration/css/test/css.test.js, tests/integration/css/test/twin.macro.test.js, tests/integration/mwa-app/package.json, tests/integration/mwa-app/src/App.tsx, tests/integration/server-prod/test/index.test.js, tests/utils/modernTestUtils.js, website/docs/start/component.md, website/docs/start/library.md
Add the `plugin-jarvis` to dependencies of solutions (`app-tools`, `module-tools` and `monorepo-tools`).
And remove `plugin-jarvis` from our generator templates, so users will no longer notice this plugin.
This change makes it easier for users to upgrade modern.js version.
> This Pull Request also removed an unused `installDeps` utils from integration test folder.
```json
{
"name": "mwa",
"dependencies": {
"@modern-js/runtime": "^1.0.0"
},
"devDependencies": {
"@modern-js/app-tools": "^1.0.0",
"@modern-js/plugin-jarvis": "^1.0.0"
}
}
```
```json
{
"name": "mwa",
"dependencies": {
"@modern-js/runtime": "^1.0.0"
},
"devDependencies": {
"@modern-js/app-tools": "^1.0.0"
}
}
```
=> feat: add plugin-jarvis to dependencies of solutions

.changeset/weak-monkeys-accept.md, packages/cli/babel-preset-base/src/plugins.ts, packages/cli/core/src/loadPlugins.ts, packages/cli/core/tests/loadPlugin.test.ts, packages/cli/webpack/tests/__snapshots__/utils.test.ts.snap, packages/server/core/src/loadPlugins.ts, packages/server/core/tests/loadPlugin.test.ts, packages/server/utils/tests/__snapshots__/babel.test.ts.snap, packages/toolkit/utils/src/index.ts, packages/toolkit/utils/src/tryResolve.ts, packages/toolkit/utils/tests/isPackageInstalled.test.ts
Skip babel-plugin-import if package not installed, which means:
- if `antd` is installed, we will apply the `babel-plugin-import` of `antd`.
- if `antd` is not installed, we can skip this plugin to improve performance.
=> perf(babel): skip babel-plugin-import if package not installed

.changeset/long-books-move.md, packages/cli/webpack/src/config/base.ts
Improve dev logs, only display error messages of type checker.
Following logs are no longer displayed:
Only log error messages like:
=> feat(webpack): only display error messages of type checker

.changeset/sweet-frogs-act.md, packages/cli/webpack/src/config/base.ts, packages/cli/webpack/src/config/modern.ts
Fix webpackChunkName magic comments not work:
```js
import(
/* webpackChunkName: "my-chunk-name" */
'module'
);
```
=> fix(webpack): webpackChunkName magic comments not work

.github/workflows/release-pull-request.yml
=> feat: checkout action use personal token

packages/cli/core/package.json, packages/cli/core/src/index.ts, packages/cli/core/tests/config.test.ts, packages/cli/plugin-analyze/package.json, packages/cli/plugin-unbundle/package.json, packages/review/testing/package.json, packages/runtime/package.json, packages/server/bff-utils/package.json, packages/server/core/package.json, packages/server/utils/package.json, packages/solutions/app-tools/package.json, packages/solutions/module-tools/package.json, packages/solutions/monorepo-tools/package.json, packages/toolkit/plugin/package.json, packages/toolkit/plugin/src/manager/async.ts, packages/toolkit/plugin/src/manager/index.ts, packages/toolkit/plugin/src/manager/runner.ts, packages/toolkit/plugin/src/manager/sync.ts, packages/toolkit/plugin/tests/fixtures/async/dynamic/foo.ts, packages/toolkit/plugin/tests/fixtures/sync/dynamic/foo.ts, packages/toolkit/plugin/tests/sync.test.ts, packages/toolkit/types/package.json, pnpm-lock.yaml
- Fix incorrect runners if multiple managers are created, the RunnerContext is incorrectly overridden.
- Release `@modern-js/plugin` v1.4.1 hotfix version.
=> fix(plugin): incorrect runners if multiple managers are created

.changeset/khaki-numbers-bathe.md, packages/cli/webpack/src/config/features/svgr.ts, packages/cli/webpack/src/utils/constants.ts
Fix failed to import SVG from a CSS file in some cases.
Add an issuer option ensures that SVGR will only apply if the SVG is imported from a JS file.
If we import SVG from a CSS file, it will be processed as assets.
Ref: https://react-svgr.com/docs/webpack/#use-svg-in-css-files
=> fix(webpack): failed to import SVG from a CSS file in some cases

.changeset/hot-shirts-crash.md, packages/cli/webpack/src/config/features/css.ts
Fix inject CSS SourceMap in js bundles when using `style-loader`:
If using style-loader, we should not enable the `sourceMap` option of css-loader.
=> fix(webpack): should not inject CSS sourceMap into js bundles

.changeset/ten-feet-battle.md, packages/cli/css-config/package.json, packages/cli/css-config/src/postcss.ts, pnpm-lock.yaml
We use `css-minimizer-webpack-plugin` to minify CSS, but it can not work with style-loader, see: https://github.com/webpack-contrib/css-minimizer-webpack-plugin/issues/80
If we enabled style-loader, we should add `cssnano` to minify the CSS code.
=> fix(css-config): css minify not work when using style-loader

.changeset/chatty-squids-camp.md, packages/solutions/module-tools/src/features/build/bundle/runRollup.ts
When bundle dts, if contains .mjs or .cjs files, the output  will have some code which are not transformed by rollup-plugin-dts, so we should ignore it.
=> fix(module-tools): ignore cjs and mjs in dts bundle

.changeset/chatty-squids-camp.md, .changeset/nasty-ads-destroy.md, .changeset/smooth-pigs-applaud.md, .changeset/sour-rice-breathe.md, packages/generator/generator-plugin/package.json, packages/generator/generator-plugin/src/utils/file.ts, packages/generator/generators/bff-generator/package.json, packages/generator/generators/cloud-deploy-generator/package.json, packages/generator/generators/dependence-generator/package.json, packages/generator/generators/electron-generator/package.json, packages/generator/generators/electron-independence-generator/package.json, packages/generator/generators/entry-generator/package.json, packages/generator/generators/generator-generator/package.json, packages/generator/generators/module-generator/package.json, packages/generator/generators/monorepo-generator/package.json, packages/generator/generators/mwa-generator/package.json, packages/generator/generators/server-generator/package.json, packages/generator/generators/ssg-generator/package.json, packages/generator/generators/storybook-generator/package.json, packages/generator/generators/test-generator/package.json, packages/generator/generators/unbundle-generator/package.json, packages/generator/new-action/src/monorepo.ts, pnpm-lock.yaml
- 升级 @modern-js/codesmith-api-json，修复生成器插件中更新 json 文件路径问题
- 修复 monorepo new 命令 plugin 参数不生效问题
- 移除 `addManyFiles` destination 参数为空字符串的校验
=> fix: monorepo new command plugin params not work

.changeset/ninety-parents-type.md, packages/cli/webpack/src/utils/constants.ts
Fix failed to compile .cjs,.mjs,.mts file.
Allow `babel-loader` to process these files, rather than fallback to `file-loader`.
=> fix(webpack): failed to compile .cjs,.mts,.cts file

CONTRIBUTING.md
when running pnpm install, always occur prepare failure which cause application can not work
=> doc: avoid prepare failure

.changeset/blue-dodos-complain.md, .changeset/blue-horses-worry.md, .changeset/cuddly-boxes-carry.md, .changeset/honest-plums-train.md, .changeset/perfect-birds-judge.md, .changeset/rich-jobs-bow.md, .changeset/wise-geckos-train.md, packages/cli/plugin-ssr/CHANGELOG.md, packages/cli/plugin-ssr/package.json, packages/cli/plugin-storybook/CHANGELOG.md, packages/cli/plugin-storybook/package.json, packages/cli/plugin-testing/CHANGELOG.md, packages/cli/plugin-testing/package.json, packages/cli/plugin-unbundle/CHANGELOG.md, packages/cli/plugin-unbundle/package.json, packages/server/bff-core/package.json, packages/server/plugin-express/CHANGELOG.md, packages/server/plugin-express/package.json, packages/server/plugin-koa/CHANGELOG.md, packages/server/plugin-koa/package.json, packages/solutions/module-tools/CHANGELOG.md, packages/solutions/module-tools/package.json, pnpm-lock.yaml
- [#1388](https://github.com/modern-js-dev/modern.js/pull/1388) 
chore(testing): merge `@modern-js/testing-plugin-bff` to `@modern-js/plugin-testing`
chore(testing): 合并 `@modern-js/testing-plugin-bff` 到 `@modern-js/plugin-testing`
- [#1388](https://github.com/modern-js-dev/modern.js/pull/1388) 
chore(testing): delete `@modern-js/bff-utils`
chore(testing): 删除 `@modern-js/bff-utils`
- [#1388](https://github.com/modern-js-dev/modern.js/pull/1388) 
chore(testing): merge `@modern-js/testing` to `@modern-js/plugin-testing`
chore(testing): 合并 `@modern-js/testing` 到 `@modern-js/plugin-testing`
- [#1389](https://github.com/modern-js-dev/modern.js/pull/1389) 
feat: add addRuntimeExports hooks for module-tools
feat: 为 module-tools 添加 addRuntimeExports 钩子
- …
=> Release v1.6.4

.changeset/moody-tomatoes-wonder.md, packages/server/prod-server/src/server/modern-server.ts
_SERVER_DATA 二次注入，导致服务器路由错误
packages/server/prod-server/src/server/modern-server.ts
=> fix: the SERVER_DATA inject twice

.changeset/lovely-oranges-impress.md, packages/cli/core/src/config/mergeConfig.ts, packages/cli/core/tests/mergeConfig.test.ts
The `mergeConfig` function should keep single function value after merge config.
This bug will breaks PostCSS plugins like this:
```ts
tools: {
postcss: {
postcssOptions: {
plugins: [require('autoprefixer')({ foo: 'bar' })],
},
},
},
});
```
=> fix(core): should keep single function value after merge config

.changeset/serious-bulldogs-watch.md, packages/toolkit/types/server/utils.d.ts
Fix missing devServer.proxy.cookieDomainRewrite type.
https://www.npmjs.com/package/http-proxy-middleware
=> fix: missing devServer.proxy.cookieDomainRewrite type

.changeset/brave-olives-think.md, packages/solutions/app-tools/src/analyze/getBundleEntry.ts
Should not modify entry name when user want to custom entries, keep the logic same as jupiter v4.
=> fix(app-tools): should not modify entry when using disableDefaultEntries

.changeset/fluffy-tools-camp.md, packages/builder/web-builder/src/plugins/html.ts, packages/builder/web-builder/src/types/config/html.ts, packages/builder/web-builder/src/webpackPlugins/HtmlCrossOriginPlugin.ts, packages/builder/web-builder/tests/plugins/html.test.ts, packages/toolkit/utils/src/chainId.ts
Add `html.crossorigin` option to web builder.
This option is used to inject the `crossorigin` attribute into the `<script>` resource tag, passing in true will enable the default value of anonymous.
=> feat(web-builder): add html.crossorigin option

packages/builder/web-builder/src/plugins/html.ts, packages/builder/web-builder/src/types/config/html.ts, packages/builder/web-builder/src/webpackPlugins/HtmlAppIconPlugin.ts, packages/builder/web-builder/tests/plugins/html.test.ts
Support `html.appIcon` config in web builder, the HtmlAppIconPlugin is modified from [@modern-js/webpack/plugins/app-icon-plugin.ts](https://github.com/modern-js-dev/modern.js/blob/main/packages/cli/webpack/src/plugins/app-icon-plugin.ts).
=> feat(web-builder): support html.appIcon config

packages/builder/web-builder/src/types/config/source.ts, packages/builder/web-builder/src/types/config/tools.ts, packages/builder/web-builder/src/types/utils.ts
Added a `ChainedConfig` utils type to improve `tools.xxx` typing.
The `tools.xxx` can be `Object` `Function` or `Array`:
- Object: such as `{ foo: 1  }`
- Function: such as `(config) => { config.foo = 2; }`
- Array: A group of objects and functions, such as `[{ foo: 1 }, (config) => { config.foo = 2; }]`, this is useful for the framework to merge several configs and passing to the web builder.
=> chore(web-builder): add type utils to improve tools typing

.changeset/quiet-horses-rhyme.md, packages/server/prod-server/src/libs/proxy.ts, packages/server/prod-server/tests/format.test.ts, packages/toolkit/utils/src/format.ts
The `formatProxyOptions` method is only used in server codes, so we can move it to `prod-server` to fix the compatibility issues in iOS 10.
=> fix: compatibility issues of dev server in iOS 10

packages/builder/webpack-builder/src/plugins/font.ts, packages/builder/webpack-builder/src/plugins/image.ts, packages/builder/webpack-builder/src/plugins/media.ts, packages/builder/webpack-builder/src/plugins/svg.ts, packages/builder/webpack-builder/src/shared/fs.ts, packages/builder/webpack-builder/src/shared/utils.ts, packages/builder/webpack-builder/src/types/config/output.ts, packages/builder/webpack-builder/tests/plugins/__snapshots__/font.test.ts.snap, packages/builder/webpack-builder/tests/plugins/__snapshots__/image.test.ts.snap, packages/builder/webpack-builder/tests/plugins/__snapshots__/media.test.ts.snap, packages/builder/webpack-builder/tests/plugins/__snapshots__/svg.test.ts.snap, packages/builder/webpack-builder/tests/plugins/font.test.ts, packages/builder/webpack-builder/tests/plugins/image.test.ts, packages/builder/webpack-builder/tests/plugins/media.test.ts, packages/builder/webpack-builder/tests/plugins/svg.test.ts
1. Allow set dataUriLimit by file type:
```js
output: {
dataUriLimit: {
svg: 1024 * 5,
font: 1024 * 20
}
}
}
```
2. Allow `output.distPath.xxx` to be empty string:
```js
output: {
distPath: {
js: '',
css: '',
}
}
}
```
=> feat(builder): allow set dataUriLimit by file type

.changeset/shiny-wolves-work.md, packages/builder/webpack-builder/package.json, packages/builder/webpack-builder/src/core/createBuilder.ts, packages/builder/webpack-builder/src/index.ts, packages/builder/webpack-builder/src/plugins/svg.ts, packages/builder/webpack-builder/src/shared/fs.ts, packages/builder/webpack-builder/tests/plugins/__snapshots__/svg.test.ts.snap, packages/builder/webpack-builder/tests/plugins/svg.test.ts, packages/toolkit/utils/src/chainId.ts
- Support using svg as assets in CSS files.
- Using `oneOf` to define svg rules.
- Fix svg plugin is not registered by default.
- Export some types from webpack builder entry.
=> feat(builder): support using svg as assets in CSS files

.changeset/three-pianos-reply.md, packages/cli/core/src/bin.ts
Fix cli -c option not work, such as `modern build -c ./xxx.config.ts`.
=> fix(core): cli -c option not work

packages/builder/webpack-builder/src/core/inspectWebpackConfig.ts, packages/builder/webpack-builder/src/plugins/css.ts, packages/builder/webpack-builder/src/plugins/output.ts, packages/builder/webpack-builder/tests/plugins/__snapshots__/compatModern.test.ts.snap, packages/builder/webpack-builder/tests/plugins/__snapshots__/output.test.ts.snap, packages/builder/webpack-builder/tests/plugins/css.test.ts, tests/integration/webpack-builder/tsconfig.json
Enable css extract by default, keep the behavior same as before.
| framework | dev | build |
|---|---|---|
| modern.js | css-extract | css-extract |
| eden | style-loader | css-extract |
| next.js | style-loader | css-extract |
| umi.js | css-extract | css-extract |
Other changes:
- Fix incorrect node env when inspect webpack config.
- Using the `getBrowserslistWithDefault` utils from webpack builder.
=> fix(builder): enable css extract by default

.changeset/chatty-horses-vanish.md, .changeset/new-ducks-crash.md, packages/builder/webpack-builder/src/core/startDevServer.ts, packages/builder/webpack-builder/src/plugins/hmr.ts, packages/builder/webpack-builder/src/types/config/dev.ts, packages/builder/webpack-builder/src/types/config/tools.ts, packages/server/server/src/index.ts, packages/server/server/tests/index.test.ts, packages/toolkit/utils/src/constants.ts
- Support using `tools.devServer` to custom dev server options.
- Add new `dev.hmr` option.
- Change hmr sock path to `/webpack-hmr`.
=> feat(builder): support custom dev server options

.changeset/smart-drinks-knock.md, packages/builder/webpack-builder/tests/plugins/compatModern.test.ts, packages/builder/webpack-builder/tests/plugins/css.test.ts, packages/cli/core/src/config/defaults.ts, packages/cli/core/src/config/schema/source.ts, packages/cli/core/src/config/types/index.ts, packages/cli/core/src/types/cli.ts, packages/solutions/app-tools/src/analyze/constants.ts, packages/solutions/app-tools/src/analyze/generateCode.ts, packages/solutions/app-tools/src/analyze/index.ts, pnpm-lock.yaml, tests/integration/async-entry/.eslintrc.js, tests/integration/async-entry/README.md, tests/integration/async-entry/modern.config.ts, tests/integration/async-entry/package.json, tests/integration/async-entry/src/App.tsx, tests/integration/async-entry/tests/index.test.ts, tests/integration/async-entry/tsconfig.json, tests/integration/mwa-app/modern.config.ts, website/docs/apis/app/config/source/disable-default-entries.md, website/docs/apis/app/config/source/enable-async-entry.md, website/docs/apis/app/runtime/plugin/hook-api.md
新增 `source.enableAsyncEntry` 配置项和 `modifyAsyncEntry` 插件 Hook。
该选项用于 webpack 模块联邦 (Module Federation）场景。
开启此选项后，Modern.js 会通过 Dynamic Import 来包裹自动生成的入口文件（asynchronous boundary），使页面代码可以消费模块联邦生成的远程模块。
首先，在配置文件中开启此选项：
```js title="modern.config.js"
source: {
enableAsyncEntry: true,
},
});
```
然后执行 `dev` 或 `build` 命令，可以看到 Modern.js 自动生成的文件变为以下结构：
```bash
node_modules
└─ .modern-js
└─ main
├─ bootstrap.js  # 真正的入口代码
├─ index.js      # 异步入口文件（asynchronous boundary）
└─ index.html
```
其中 `index.js` 的内容如下：
```js
import('./bootstrap.js');
```
此时，就可以在当前页面中消费任意的远程模块了。
=> feat: add source.enableAsyncEntry config

packages/builder/webpack-builder/src/config/defaults.ts
**Added**
- `dev.hmr: true`, hmr will be enabled by default.
- `html.inject: true`, same as html-webpack-plugin defaults, but explicit would be better.
- `html.mountId: 'app'`
- `html.crossorigin: false`
**Updated**
- `tools.tsChecker: false` -> `tools.tsChecker: {}`, ts checker should be enabled by default.
**Removed**
- `tools.terser`, it's better to be maintained in terser plugin like other tools.
- All config items whose default value is `undefined`, setting the default value to `undefined` has no effect.
=> chore(builder): update default configs

packages/builder/webpack-builder/src/core/initConfigs.ts, packages/builder/webpack-builder/src/core/inspectBuilderConfig.ts, packages/builder/webpack-builder/src/core/inspectWebpackConfig.ts, packages/builder/webpack-builder/src/plugins/cleanOutput.ts, packages/builder/webpack-builder/src/shared/logger.ts
Automatically write builder config and webpack config to disk in debug mode.
=> feat(builder): auto inspect configs in debug mode

packages/builder/webpack-builder/src/plugins/babel.ts, packages/builder/webpack-builder/src/plugins/splitChunks.ts, packages/builder/webpack-builder/tests/plugins/__snapshots__/babel.test.ts.snap, packages/builder/webpack-builder/tests/plugins/__snapshots__/chunkSplit.test.ts.snap, packages/builder/webpack-builder/tests/plugins/babel.test.ts
- Fix `polyfill='entry'` not work, the `core-js-entry` is not included.
- Rename experience defined chunk name, `Experience_Defined_Cache_Group_x` -> `pre-defined-chunk-x`, make it shorter and easier to read.
=> fix(builder): polyfill entry not work

.changeset/thick-bees-give.md, packages/builder/webpack-builder/src/core/createBuilder.ts, packages/builder/webpack-builder/src/index.ts, packages/builder/webpack-builder/src/plugins/babel.ts, packages/builder/webpack-builder/src/plugins/css.ts, packages/builder/webpack-builder/src/shared/browserslist.ts, packages/builder/webpack-builder/src/types/config/output.ts, packages/builder/webpack-builder/tests/plugins/__snapshots__/babel.test.ts.snap, packages/builder/webpack-builder/tests/plugins/__snapshots__/css.test.ts.snap, packages/builder/webpack-builder/tests/plugins/__snapshots__/react.test.ts.snap, packages/builder/webpack-builder/tests/plugins/babel.test.ts, packages/builder/webpack-builder/tests/plugins/css.test.ts, packages/cli/babel-preset-app/src/common.ts, packages/cli/babel-preset-app/src/type.ts, packages/cli/babel-preset-base/src/index.ts, packages/cli/babel-preset-base/src/presets.ts
- Add `output.overrideBrowserslist` config for webpack builder, this allows user to override the browserslist of `@babel/preset-env` and `autoprefixer`.
- Export `webpack` type.
- Fix cleanOutput plugin register order, should register before other plugins.
=> feat(builder): add output.overrideBrowserslist config

packages/builder/webpack-builder/src/plugins/html.ts, packages/builder/webpack-builder/src/plugins/sri.ts, packages/builder/webpack-builder/src/types/config/html.ts, packages/builder/webpack-builder/src/webpackPlugins/HtmlCrossOriginPlugin.ts, packages/builder/webpack-builder/tests/plugins/html.test.ts
Fix `html.crossorigin` config not work for async chunks.
The `HtmlCrossOriginPlugin` can only handle the entry chunks, and we should add the `crossOriginLoading` config to handle async chunks.
=> fix(builder): html.crossorigin not work for async chunk

packages/builder/webpack-builder/src/core/createBuilder.ts, packages/builder/webpack-builder/src/plugins/inlineChunk.ts, packages/builder/webpack-builder/src/plugins/splitChunks.ts, packages/builder/webpack-builder/src/shared/constants.ts, packages/builder/webpack-builder/src/types/config/output.ts, packages/builder/webpack-builder/src/webpackPlugins/InlineChunkHtmlPlugin.ts, packages/builder/webpack-builder/tests/plugins/__snapshots__/chunkSplit.test.ts.snap, packages/builder/webpack-builder/tests/plugins/__snapshots__/inlineChunk.test.ts.snap, packages/builder/webpack-builder/tests/plugins/inlineChunk.test.ts
- add PluginInlineChunk
- add webpack plugin InlineChunkHtmlPlugin into builder
- register InlineChunkHtmlPlugin in PluginInlineChunk and enable inline base on options in `output`
- change PluginEntry
- add entries defined by source.vendorEntry into webpack-chain entry
- change PluginHtml
- filter out vendorEntry before register html plugin, because they don't need a html file
- add all vendorEntry to existing html plugin chunks option
- change PluginSplitChunk
- set runtimeChunk to `single` mode (with name `builder-runtime`) because there could be more than one entries in a html
=> feat(builder): add inline chunk plugin

packages/builder/webpack-builder/.eslintrc.js, packages/builder/webpack-builder/package.json, packages/builder/webpack-builder/src/stub/builder.ts, packages/builder/webpack-builder/tests/stub/builder.test.ts, packages/toolkit/e2e/package.json, packages/toolkit/e2e/src/server/index.ts, packages/toolkit/e2e/src/server/static.ts, packages/toolkit/utils/src/path.ts, pnpm-lock.yaml
* Remove `memfs` from `@modern-js/webpack-builder` and `@modern-js/e2e`.
* Add new util function `getTemplatePath`.
* Set a string value to the stub builder option `webpack` enable using webpack and specify the `output.distPath`.
=> feat(webpack-builder): remove `memfs` and auto set `distPath` by `webpack` option

packages/builder/webpack-builder/src/plugins/output.ts, packages/builder/webpack-builder/tests/plugins/__snapshots__/output.test.ts.snap
Disable pathinfo to improve compile performance, the path info is useless in most cases, see: https://webpack.js.org/guides/build-performance/#output-without-path-info
=> perf(builder): disable output.pathinfo to improve performance

.changeset/young-jobs-press.md, packages/server/server/src/dev-tools/dev-middleware/index.ts
use output.publicPath(default) as webpack-dev-middleware publicPath
https://github.com/webpack/webpack-dev-middleware#publicpath
1. set dev.assetPrefix in config (https://modernjs.dev/docs/apis/app/config/dev/asset-prefix)
2. run dev 
3. request resource ok
=> fix: use output.publicPath(default) as webpack-dev-middleware publicPath

.changeset/small-icons-talk.md, packages/builder/builder-doc/en/config/source/compileJsDataURI.md, packages/builder/builder-doc/zh/config/source/compileJsDataURI.md, packages/builder/webpack-builder/src/config/defaults.ts, packages/builder/webpack-builder/src/plugins/babel.ts, packages/builder/webpack-builder/src/types/config/source.ts, packages/builder/webpack-builder/tests/plugins/__snapshots__/babel.test.ts.snap, packages/builder/webpack-builder/tests/plugins/babel.test.ts, packages/toolkit/utils/src/chainId.ts, website/builder/src/en/api/config-source.md, website/builder/src/zh/api/config-source.md
Added a new `source.compileJsDataURI` config. 
If this option is enabled, when a script is imported with data URI, it can be compiled by babel too.
This is used by some frameworks such as PIA to create virtual entry.
=> feat(builder): support compile js data URI

.changeset/witty-berries-jump.md, packages/generator/generators/upgrade-generator/src/index.ts
执行 npx @modern-js/upgrade 命令时，默认会统一升级 Modern.js 相关包，由于 electron、codesmith、reduck 相关包不在 Modern.js 仓库，版本号不会和 Modern.js 依赖保持一致，因此升级时需要忽略这些包。
=> fix: upgrade command ignore electron, codesmith, reduck packages

packages/builder/builder-doc/en/config/tools/inspector.md, packages/builder/webpack-builder/src/shared/utils.ts, packages/builder/webpack-builder/tests/mergeConfig.test.ts
mergeBuilderConfig api should not effect source params when some property is undefined
=> fix: mergeBuilderConfig sideEffect

.changeset/twelve-spoons-burn.md, packages/builder/webpack-builder/package.json, packages/builder/webpack-builder/src/plugins/react.ts, packages/cli/webpack/package.json, packages/cli/webpack/src/config/features/react-refresh.ts, pnpm-lock.yaml
This PR using the forked `@modern-js/react-refresh-webpack-plugin` package to replace `@pmmmwh/react-refresh-webpack-plugin`, the forked package is under https://github.com/modern-js-dev/react-refresh-webpack-plugin.
The react-refresh-webpack-plugin has a performance issue and will cause webpack rebuild much more slower, see:https://github.com/pmmmwh/react-refresh-webpack-plugin/pull/669
This performance issue has been fixed, but react-refresh-webpack-plugin has not released a new version for a long time, so we forked the package and released a new version to fix the performance issue.
Once react-refresh-webpack-plugin released a new version, we will switch back to the official package.
=> fix(webpack): react-refresh-webpack-plugin cause rebuild slow

packages/builder/builder-webpack-provider/src/plugins/cleanOutput.ts, packages/builder/builder-webpack-provider/src/plugins/tsChecker.ts
Move `api.getBuilderConfig` inside the `api.modifyWebpackChain` callback, so we can get the correct builder config.
This change allows other plugins to modify builder config to disable the ts checker.
=> fix(builder): failed to disable tsChecker with modifyBuilderConfig

.changeset/silly-elephants-protect.md, packages/builder/builder-webpack-provider/src/plugins/react.ts, packages/builder/builder-webpack-provider/tests/plugins/react.test.ts
should not apply react refresh when dev.hmr is false.
=> fix(builder): should not apply react refresh when dev.hmr is false

.changeset/brown-cobras-reply.md, .changeset/twelve-spoons-burn.md, packages/builder/builder-shared/src/index.ts, packages/builder/builder-shared/src/onExitProcess.ts, packages/builder/builder-webpack-provider/src/core/initPlugins.ts, packages/builder/builder-webpack-provider/tests/__snapshots__/hooks.test.ts.snap, packages/builder/builder-webpack-provider/tests/createAsyncHook.test.ts, packages/builder/builder-webpack-provider/tests/hooks.test.ts
- Fix api.onExit hook not work.
- Fix builder package name in changeset.
=> fix(builder): api.onExit hook not work

.changeset/smooth-feet-attend.md, packages/toolkit/utils/src/version.ts
Fix failed to resolve execa, it is not installed.
```bash
Error: Cannot find module 'execa'
Require stack:
- /Users/Project/demos/demo/node_modules/.pnpm/@modern-js+utils@0.0.0-canary-20221012094820/node_modules/@modern-js/utils/dist/version.js
```
=> fix(utils): failed to resolve execa

.changeset/warm-keys-hammer.md, packages/builder/builder-webpack-provider/src/plugins/css.ts, packages/builder/builder-webpack-provider/tests/plugins/css.test.ts
Should not apply style-loader or extract css when target is node, otherwise there will be compile error or runtime error.
=> fix(builder): not apply style-loader or extract css when target is node

.changeset/strange-months-guess.md, packages/builder/builder-webpack-provider/src/webpackPlugins/InlineChunkHtmlPlugin.ts, packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/inlineChunk.test.ts.snap, tests/e2e/webpack-builder/inline-chunk/build.test.ts, tests/e2e/webpack-builder/inline-chunk/src/another.js
If there are more than one entries, the inlined assets are deleted right after the first html plugin being executed. That will cause the rest html files missing part of the assets (deleted ones).
This PR fixes that by delay the deletion of inlined assets to processAssets summarize stage.
=> fix(builder): inlined assets should be deleted after all html generated

.pnpmfile.cjs, packages/builder/plugin-esbuild/package.json, pnpm-lock.yaml, scripts/vitest-run-all.js
- Fix vitest failed in node 14 because esbuild >= 0.15.8 generates the logical or assignment operator.
- Fix the vitest CI process not exit when vitest failed.
=> chore: fix vitest failed in node 14

.changeset/tiny-knives-collect.md, packages/builder/builder-doc/en/config/tools/tsChecker.md, packages/builder/builder-doc/zh/config/tools/tsChecker.md, packages/builder/builder-webpack-provider/src/config/defaults.ts, packages/builder/builder-webpack-provider/src/plugins/tsChecker.ts, packages/builder/builder-webpack-provider/src/types/config/output.ts, packages/builder/builder-webpack-provider/src/types/config/tools.ts, packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/tsChecker.test.ts.snap, packages/builder/builder-webpack-provider/tests/plugins/tsChecker.test.ts
- Support configure `tools.tsChecker` to `true` to enable type checking.
- Fix the default value of `tools.tsChecker`, the value should be `true` or `{}` instead of `undefined`.
- Fix the test cases of `tools.tsChecker`.
=> fix(builder): default value of tools.tsChecker config

.changeset/weak-comics-turn.md, packages/builder/builder-doc/en/config/output/assetsRetry.md, packages/builder/builder-doc/en/config/output/distPath.md, packages/builder/builder-doc/en/config/output/enableLatestDecorators.md, packages/builder/builder-doc/zh/config/output/assetsRetry.md, packages/builder/builder-doc/zh/config/output/distPath.md, packages/builder/builder-doc/zh/config/output/enableLatestDecorators.md, packages/builder/builder-shared/src/constants.ts, packages/builder/builder-webpack-provider/src/config/defaults.ts, packages/builder/builder-webpack-provider/src/plugins/output.ts, packages/builder/builder-webpack-provider/src/shared/fs.ts, packages/builder/builder-webpack-provider/src/types/config/output.ts, packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/output.test.ts.snap, packages/builder/builder-webpack-provider/tests/plugins/output.test.ts
- Support `distPath.server` config to custom the server bundles path.
- Fix the MiniCssExtractPlugin is registered when target is node.
- Add documents of `output.enableLatestDecorators`.
=> feat(builder): support distPath.server config

.changeset/big-pears-lie.md, packages/server/utils/src/compilers/typescript/tsconfig-paths-plugin.ts
use old node's flags to transfer node.
flag types: https://github.com/microsoft/TypeScript/blob/main/src/compiler/types.ts#L754
related issue: https://github.com/nestjs/nest-cli/pull/1449
=> fix: tsconfig paths plugins cause types only import preserve

.changeset/ten-stingrays-hide.md, packages/server/prod-server/src/libs/route/matcher.ts, packages/server/prod-server/tests/route.test.ts
Fix Server failed to match URL which ends with ".html", such as `http://localhost:3000/index.html`.
=> fix(prod-server): failed to match URL which ends with ".html"

.changeset/honest-rocks-exist.md, .changeset/late-ways-wave.md, packages/cli/plugin-storybook/src/runtime-addon/typings.d.ts, packages/runtime/plugin-runtime/package.json, packages/runtime/plugin-runtime/src/exports/model.ts, packages/runtime/plugin-runtime/src/exports/router.ts, packages/runtime/plugin-runtime/src/exports/ssr.ts, packages/runtime/plugin-runtime/src/router/cli/index.ts, packages/runtime/plugin-runtime/src/router/index.ts, packages/runtime/plugin-runtime/src/ssr/cli/index.ts, packages/runtime/plugin-runtime/src/ssr/index.tsx, packages/runtime/plugin-runtime/src/state/cli/index.ts, packages/runtime/plugin-runtime/src/state/index.ts, packages/runtime/plugin-runtime/src/state/runtime/plugin.tsx, packages/runtime/plugin-runtime/tests/exports.test.ts, packages/runtime/plugin-runtime/types/model.d.ts
- @modern-js/runtime exports field `/router` and `/runtime-router` is the same file, only use `/router`.
- state plugin generator main file is wrong
expect:
StatePlugins' transform should handle in runtime.
=> fix: runtime export field and state runtime plugin params

.changeset/friendly-beers-teach.md, packages/builder/builder-shared/src/createPublicContext.ts, packages/builder/builder-shared/src/types/context.ts, packages/builder/builder-webpack-provider/src/core/createContext.ts, packages/builder/builder-webpack-provider/src/plugins/tsChecker.ts, packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/tsChecker.test.ts.snap, packages/builder/builder-webpack-provider/tests/plugins/tsChecker.test.ts, website/builder/src/en/api/builder-instance.md, website/builder/src/zh/api/builder-instance.md
If there is multiple target, only apply tsChecker to the first target, to avoid multiple tsChecker running at the same time.
Expose target in the builder context.
This change can improve the compile performance when have multiple targets.
=> fix(builder): only apply one tsChecker plugin when multiple targets

.changeset/purple-suns-beam.md, packages/cli/core/package.json, packages/cli/core/src/config/types/index.ts, packages/cli/webpack/src/config/base.ts, pnpm-lock.yaml, website/main/docs/apis/app/config/tools/webpack-chain.md, website/main/docs/apis/app/config/tools/webpack.md
Expose HtmlWebpackPlugin instance in tools.webpack and tools.webpackChain.
This is useful to add plugins for HtmlWebpackPlugin and avoid multiple instances issue.
=> feat(webpack): expose HtmlWebpackPlugin instance in tools.webpack

.changeset/late-ghosts-grin.md, packages/cli/plugin-storybook/src/features/utils/webpackConfig.ts, packages/cli/webpack/src/config/base.ts
When debugging with Storybook, the tools.webpack configuration does not work。
Because we need to call the `config` function in BaseWebpackConfig in @modern-js/webpack to trigger tools.webpack to work, we put the main logic of the config function into the `applyToolsWebpack` function.
=> fix: `tools.webpack` of Storybook API not work

.changeset/shiny-coats-mix.md, packages/builder/builder-doc/en/config/performance/buildCache.md, packages/builder/builder-doc/zh/config/performance/buildCache.md, packages/builder/builder-shared/package.json, packages/builder/builder-shared/src/types/config/dev.ts, packages/builder/builder-shared/src/types/config/html.ts, packages/builder/builder-shared/src/types/config/index.ts, packages/builder/builder-shared/src/types/config/output.ts, packages/builder/builder-shared/src/types/config/performance.ts, packages/builder/builder-shared/src/types/config/security.ts, packages/builder/builder-shared/src/types/config/source.ts, packages/builder/builder-shared/src/types/index.ts, packages/builder/builder-webpack-provider/src/config/defaults.ts, packages/builder/builder-webpack-provider/src/plugins/cache.ts, packages/builder/builder-webpack-provider/src/plugins/compatModern.ts, packages/builder/builder-webpack-provider/src/plugins/moduleScopes.ts, packages/builder/builder-webpack-provider/src/runtime/assets-retry.ts, packages/builder/builder-webpack-provider/src/shared/fs.ts, packages/builder/builder-webpack-provider/src/shared/utils.ts, packages/builder/builder-webpack-provider/src/types/config/dev.ts, packages/builder/builder-webpack-provider/src/types/config/html.ts, packages/builder/builder-webpack-provider/src/types/config/index.ts, packages/builder/builder-webpack-provider/src/types/config/output.ts, packages/builder/builder-webpack-provider/src/types/config/performance.ts, packages/builder/builder-webpack-provider/src/types/config/security.ts, packages/builder/builder-webpack-provider/src/types/config/source.ts, packages/builder/builder-webpack-provider/src/types/thirdParty/index.ts, packages/builder/builder-webpack-provider/src/webpackPlugins/AssetsRetryPlugin.ts, packages/builder/builder-webpack-provider/src/webpackPlugins/HtmlCrossOriginPlugin.ts, pnpm-lock.yaml
Move part of `BuilderConfig` type to `@modern-js/builder-shared`.
Some config items are still defined in the `builder-webpack-provider` because they are relevant  to webpack or other third party libraries.
=> feat(builder): move part of config types to shared

packages/builder/builder-shared/src/constants.ts, packages/builder/builder-shared/src/types/builder.ts, packages/builder/builder-webpack-provider/src/core/webpackConfig.ts, packages/builder/builder-webpack-provider/src/plugins/assetsRetry.ts, packages/builder/builder-webpack-provider/src/plugins/css.ts, packages/builder/builder-webpack-provider/src/plugins/hmr.ts, packages/builder/builder-webpack-provider/src/plugins/html.ts, packages/builder/builder-webpack-provider/src/plugins/inlineChunk.ts, packages/builder/builder-webpack-provider/src/plugins/output.ts, packages/builder/builder-webpack-provider/src/plugins/progress.ts, packages/builder/builder-webpack-provider/src/plugins/react.ts, packages/builder/builder-webpack-provider/src/plugins/splitChunks.ts, packages/builder/builder-webpack-provider/src/plugins/target.ts, packages/builder/builder-webpack-provider/src/types/hooks.ts, packages/builder/builder-webpack-provider/tests/plugins/css.test.ts, packages/builder/builder-webpack-provider/tests/plugins/html.test.ts, packages/builder/builder-webpack-provider/tests/plugins/inlineChunk.test.ts, packages/builder/builder-webpack-provider/tests/plugins/react.test.ts, packages/builder/builder-webpack-provider/tests/plugins/target.test.ts, tests/integration/webpack-builder/scripts/shared.ts, website/builder/src/en/api/builder-core.md, website/builder/src/zh/api/builder-core.md
Builder support `web-worker` target.
Compared with `web` target, the web-worker outputs are:
- Only emit single bundle, not support dynamic import.
- No need to generate CSS/HTML files.
- No need to enable HMR.
```js
const builder = await createBuilder(provider, {
target: ['web-worker'],
});
```
=> feat(builder): support web-worker target

.changeset/fuzzy-humans-jump.md, packages/builder/builder-webpack-provider/src/plugins/css.ts, packages/builder/builder-webpack-provider/src/webpackLoaders/ignoreCssLoader.ts, packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/css.test.ts.snap, packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/rem.test.ts.snap, packages/builder/builder-webpack-provider/tests/plugins/css.test.ts, packages/toolkit/utils/src/chainId.ts, pnpm-lock.yaml, tests/e2e/webpack-builder/ignore-css/.eslintrc.js, tests/e2e/webpack-builder/ignore-css/package.json, tests/e2e/webpack-builder/ignore-css/removeCss.test.ts, tests/e2e/webpack-builder/ignore-css/src/a.css, tests/e2e/webpack-builder/ignore-css/src/b.module.scss, tests/e2e/webpack-builder/ignore-css/src/index.js, tests/e2e/webpack-builder/ignore-css/tsconfig.json
Fix failed remove css for node/worker target.
Builder used to use the `exportOnlyLocals` option of css-loader to remove the css content, but the `exportOnlyLocals` can only work with `.module.css` files, and the normal `.css` files is not processed, so I added a `ignore-css-loader` to remove css from normal `.css` files.
=> fix(builder): failed remove css for node/worker target

.changeset/bright-llamas-yawn.md, packages/builder/builder-webpack-provider/src/webpackPlugins/ProgressPlugin/ProgressPlugin.ts, packages/builder/builder-webpack-provider/src/webpackPlugins/ProgressPlugin/helpers/index.ts, packages/builder/builder-webpack-provider/src/webpackPlugins/ProgressPlugin/helpers/percentage.ts, packages/builder/builder-webpack-provider/tests/plugins/progress.test.ts
Make the progress percentage more user friendly. The original percentage may pause at certain number for a long time, or decrease in some cases, which will confuse the user. So we format the percentage number and display a more smooth percentage.
=> feat(builder): display user friendly progress percentage

.changeset/honest-tips-begin.md, .changeset/late-fireants-boil.md, packages/builder/builder-shared/src/getBrowserslist.ts, packages/builder/builder-shared/src/types/config/dev.ts, packages/builder/builder-shared/tests/getBrowserslist.test.ts, packages/builder/builder-webpack-provider/src/core/inspectConfig.ts, packages/builder/builder-webpack-provider/src/plugins/babel.ts, packages/builder/builder-webpack-provider/src/plugins/css.ts, packages/builder/builder-webpack-provider/src/plugins/progress.ts, packages/builder/builder-webpack-provider/src/plugins/svg.ts, packages/builder/builder-webpack-provider/src/shared/utils.ts, packages/builder/builder-webpack-provider/src/webpackPlugins/ProgressPlugin/ProgressPlugin.ts
- Fix typo in `dev.progressBar` options, quite should be quiet
- Fix incorrect target label when inspect configs.
- Move the `getBrowserslistWithDefault` method to `builder-shared`.
- Remove the `getDataUrlLimit` method because it is useless yet.
=>  fix(builder): typo in dev.progressBar options

.changeset/lucky-lobsters-tan.md, packages/builder/builder-shared/src/types/provider.ts, packages/builder/builder-webpack-provider/src/core/build.ts, packages/builder/builder-webpack-provider/src/core/createCompiler.ts, packages/builder/builder-webpack-provider/src/core/initConfigs.ts, packages/builder/builder-webpack-provider/src/core/initHooks.ts, packages/builder/builder-webpack-provider/src/core/initPlugins.ts, packages/builder/builder-webpack-provider/src/core/startDevServer.ts, packages/builder/builder-webpack-provider/src/stub/builder.ts, packages/builder/builder-webpack-provider/src/types/hooks.ts, packages/builder/builder-webpack-provider/tests/__snapshots__/hooks.test.ts.snap, packages/builder/builder-webpack-provider/tests/stub/builder.test.ts, website/builder/src/en/api/builder-instance.md, website/builder/src/zh/api/builder-instance.md
1. The build method support custom compiler (same as startDevServer).
```ts
const compiler = webpack({
// ...
});
await builder.build({
compiler,
});
```
2. Remove bundlerConfig param of `api.onBeforeBuild`, this param is never used by plugins, and it is not available when custom compiler.
=> feat(builder): build method support custom compiler

.changeset/olive-lies-agree.md, packages/builder/builder-webpack-provider/src/plugins/splitChunks.ts, packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/splitChunks.test.ts.snap
Make preset chunk names more readable, `pre-defiened-chunk-0.xxxxxx.js` -> `lib-react.xxxxxx.js`.
This change can let developers easily known the content of chunk by file name.
=> feat(builder): make preset chunk names more readable

.changeset/plenty-islands-boil.md, packages/builder/builder-webpack-provider/src/core/build.ts, packages/builder/builder-webpack-provider/src/plugins/fileSize.ts, packages/builder/builder-webpack-provider/tests/plugins/fileSize.test.ts
- Fix some assets are not included in the assets list, should adjust some options of `stats.toJson` method.
- Fix the size diff is not accurate, we can not remove file name hash correctly, some files may not contain a hash. So this feature is removed now, It is useless in most cases.
- Added different color for labels when size increases.
- Removed the `building for production...` log because we want let the upper framework to do this. Some frameworks may call `builder.build` multiple times.
=> fix(builder): failed to print correct file sizes

.changeset/early-carrots-do.md, packages/generator/generator-common/src/newAction/mwa/index.ts
when run new command in mwa project, generator should add `/// <reference types='@modern-js/plugin-testing/types' />` to `src/modern-app-env.d.ts`.
=> fix: new testing reference type

.changeset/stupid-dingos-tell.md, packages/builder/builder-shared/src/utils.ts, packages/builder/builder-webpack-provider/src/core/initPlugins.ts, packages/builder/builder-webpack-provider/src/plugins/html.ts, packages/builder/builder-webpack-provider/src/shared/fs.ts, packages/builder/builder-webpack-provider/src/types/plugin.ts, packages/builder/builder-webpack-provider/tests/shared/utils.test.ts
Add new api.getHTMLPaths method.
Usage:
```js
const PluginFoo = (): BuilderPlugin => ({
setup(api) {
api.modifyWebpackChain(() => {
const htmlPaths = api.getHTMLPaths();
console.log(htmlPaths); // { main: 'html/main/index.html' };
});
}
);
```
=> feat(builder): add api.getHTMLPaths method

.changeset/big-knives-cough.md, packages/builder/builder-doc/en/config/output/disableCssModuleExtension.md, packages/builder/builder-doc/zh/config/output/disableCssModuleExtension.md, packages/builder/builder-shared/src/constants.ts, packages/builder/builder-shared/src/fs.ts, packages/builder/builder-shared/src/types/config/output.ts, packages/builder/builder-shared/src/utils.ts, packages/builder/builder-webpack-provider/src/config/defaults.ts, packages/builder/builder-webpack-provider/src/plugins/css.ts, packages/builder/builder-webpack-provider/src/stub/builder.ts, pnpm-lock.yaml, tests/e2e/webpack-builder/css-modules/.eslintrc.js, tests/e2e/webpack-builder/css-modules/cssModules.test.ts, tests/e2e/webpack-builder/css-modules/package.json, tests/e2e/webpack-builder/css-modules/src/a.css, tests/e2e/webpack-builder/css-modules/src/b.module.scss, tests/e2e/webpack-builder/css-modules/src/c.module.less, tests/e2e/webpack-builder/css-modules/src/d.global.less, tests/e2e/webpack-builder/css-modules/src/index.js, tests/e2e/webpack-builder/css-modules/tsconfig.json, tests/integration/webpack-builder/src/App.global.less, tests/integration/webpack-builder/src/App.tsx, website/builder/src/.vuepress/config.ts, website/builder/src/en/api/config-output.md, website/builder/src/zh/api/config-output.md
Add output.disableCssModuleExtension config for builder, same as modern.js v1.
=> feat(builder): add output.disableCssModuleExtension config

.changeset/witty-bats-film.md, packages/builder/builder-webpack-provider/src/plugins/rem.ts, packages/builder/builder-webpack-provider/tests/plugins/rem.test.ts
Skip rem plugin when target is node or web worker, otherwise the compilation will be failed because html plugin is not exist:
=> fix(builder): skip rem plugin when target is node or web worker

.changeset/cool-balloons-buy.md, packages/builder/builder-doc/en/config/output/externals.md, packages/builder/builder-doc/zh/config/output/externals.md, packages/builder/builder-webpack-provider/src/plugins/externals.ts, pnpm-lock.yaml, tests/e2e/webpack-builder/externals/.eslintrc.js, tests/e2e/webpack-builder/externals/index.test.ts, tests/e2e/webpack-builder/externals/package.json, tests/e2e/webpack-builder/externals/src/index.js, tests/e2e/webpack-builder/externals/tsconfig.json
When the build target is Web Worker, externals will not take effect. This is because the Worker environment can not access global variables. So we should ignore the externals config of webpack config.
=> feat(builder): ignore externals when target is web worker

.changeset/honest-news-explode.md, packages/solutions/module-tools/src/features/build/bundleless/generator-dts/utils.ts
In some projects (eg. React Native), we must enable the `node-linker=hoist`, but Modern.js only search for the `tsc` inside the current workspace to build.
https://github.com/modern-js-dev/modern.js/issues/1985
https://pnpm.io/npmrc#node-linker
Modern.js can't build correctly if it's used together in React Native projects.
Change related code in [demo repository](https://github.com/Means88/node-linker-demo) and run `build`
Tested manually, but don't know how to write the test in this case.
=> feat: support hoist node linker

.changeset/fresh-terms-drum.md, packages/server/core/src/plugin.ts, packages/server/prod-server/src/server/index.ts, packages/server/prod-server/src/server/modern-server.ts, packages/server/prod-server/src/type.ts, packages/server/prod-server/tests/fixtures/completely-custom/package.json, packages/server/prod-server/tests/fixtures/completely-custom/test-dist/bundles/main.js, packages/server/prod-server/tests/fixtures/completely-custom/test-dist/html/main/index.html, packages/server/prod-server/tests/fixtures/completely-custom/test-dist/route.json, packages/server/prod-server/tests/fixtures/completely-custom/tsconfig.json, packages/server/prod-server/tests/server.test.ts, packages/server/server/src/dev-tools/register/index.ts, packages/server/server/src/server/dev-server.ts
By default, Modern.js includes its own server with start command. 
If you have an existing backend, you can still use it with Modern.js like this.
```js
const { createServer } = require('http');
const server = require('@modern-js/prod-server').default;
async function main() {
const app = await server({
pwd: process.cwd(),
config: {
output: {
path: './dist',
},
},
});
const handler = app.getRequestHandler();
createServer(async (req, res) => {
if (req.url === '/') {
const html = await app.render(req, res);
res.end(html);
} else {
await handler(req, res);
}
}).listen(8080, () => {
console.log('listen custom server in 3000');
});
}
main();
```
we may support this feature for development env soon.
=> feat: support completely custom server

.changeset/cyan-windows-bake.md, packages/solutions/app-tools/src/builder/createToolsConfig.ts, packages/solutions/app-tools/tests/builder/createToolsConfig.test.ts
builder tools.webpackChain config args not match the Modernjs tools.webpackChain
=> fix: builder tools.webpackChain config args not match the Modernjs tools.webpackChain

.changeset/neat-jobs-design.md, packages/solutions/app-tools/src/builder/createOutputConfig.ts, packages/solutions/app-tools/src/commands/build.ts, packages/solutions/app-tools/src/commands/start.ts, packages/solutions/app-tools/src/index.ts
Clean up the dist directory in the prepare hook because some files are generated in the prepare hook into the dist directory.
=> fix: clear distDirectory in prepare hook & inject data load plugin

pnpm-lock.yaml, website/builder/package.json
This PR bumps `vuepress-theme-vt` to fix an search issue of modern.js builder website, for details please head https://github.com/ins-x/vt/issues/77
- Before: keyword `tsChecker` has not result
- After: keyword `tsChecker` has matched result
=> chore(builder-website): bump `vuepress-theme-vt` to `0.6.3`

packages/builder/builder-doc/en/config/performance/printFileSize.md, packages/builder/builder-doc/zh/config/performance/printFileSize.md, packages/builder/builder-shared/src/types/config/performance.ts, packages/builder/builder-webpack-provider/src/config/defaults.ts, packages/builder/builder-webpack-provider/src/core/build.ts, packages/builder/builder-webpack-provider/src/plugins/fileSize.ts, website/builder/src/en/api/config-performance.md, website/builder/src/zh/api/config-performance.md
Add performance.printFileSize config, allow to disable the file size logs.
```ts
performance: {
printFileSize: false,
},
};
```
=> feat(builder): add performance.printFileSize config

.changeset/weak-shirts-marry.md, packages/solutions/app-tools/src/builder/builderPlugins/compatModern.ts
fix: the html can't  inject bottom template
=> fix: add html-webpack-plugin '__internal__' options, for bottom template

.changeset/fast-rats-share.md, packages/builder/plugin-esbuild/src/index.ts, packages/builder/plugin-esbuild/tests/__snapshots__/index.test.ts.snap, website/builder/src/en/guide/advanced/build-performance.md, website/builder/src/en/plugins/plugin-esbuild.md, website/builder/src/zh/guide/advanced/build-performance.md, website/builder/src/zh/plugins/plugin-esbuild.md
- esbuild minimize target should be es2015, the default target of esbuild-loader MinifyPlugin is `esnext`
- update document of esbuild plugin, add some details.
=> fix(builder): esbuild minimize target should be es2015

.changeset/real-foxes-tan.md, packages/server/plugin-polyfill/src/const.ts, packages/server/plugin-polyfill/src/index.ts
Fix plugin-polyfill failed to join flags when restart CLI.
Close https://github.com/modern-js-dev/modern.js/issues/2074
=> fix(plugin-polyfill): failed to join flags when restart CLI

.changeset/popular-steaks-dress.md, packages/builder/builder-webpack-provider/src/plugins/splitChunks.ts, packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/splitChunks.test.ts.snap, website/builder/src/en/guide/advanced/split-chunk.md, website/builder/src/zh/guide/advanced/split-chunk.md
Adjust default split chunk group:
- remove the `babel` group, because the `@babel/runtime` is only 10KB after minified, the minSize of split chunk is `20kb`, so the `babel` group can not be splitted.
- Merge `core-js` and `babel` into a new `polyfill` group.
=> fix(builder): adjust default split chunk group

.changeset/hungry-humans-cough.md, packages/builder/builder-webpack-provider/src/plugins/cache.ts, packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/cache.test.ts.snap, packages/builder/builder-webpack-provider/tests/plugins/cache.test.ts, pnpm-lock.yaml, tests/e2e/webpack-builder/cache/index.test.ts, tests/e2e/webpack-builder/cache/package.json, tests/e2e/webpack-builder/cache/src/index.js, tests/e2e/webpack-builder/cache/tsconfig.json
Invalidate webpack cache when buildDependencies changed.
If the filenames in the buildDependencies are changed, webpack will not invalidate the previous cache. So we need to remove the cache directory to make sure the cache is invalidated.
```bash
modern build
modern build --config ./other-modern.config.ts
```
=> fix(builder): invalidate cache when buildDependencies changed

tests/e2e/webpack-builder/cache/package.json, tests/integration/css/fixtures/exclude-less/modern.config.js, tests/integration/css/fixtures/exclude-sass/modern.config.js
Fix exclude-less integration test, the `output.enableAssetFallback` is default `false` now.
=> chore: fix exclude-less integration test

.changeset/cyan-beers-behave.md, packages/builder/builder-shared/src/constants.ts, packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/babel.test.ts.snap
The default node version of Modern.js 2.0 is 16.x, and the minimal required node version is 14.x. So we can increase the default node version of builder node target to 14.x.
=> feat(builder): increase target node version to 14

.changeset/happy-laws-ring.md, packages/runtime/plugin-runtime/src/ssr/cli/index.ts
The useLoader can be used even if the SSR is not enabled, so we should always register the `babel-plugin-ssr-loader-id`.
=> fix(runtime): apply babel-plugin-ssr-loader-id when SSR is not used

.changeset/witty-mugs-repeat.md, packages/builder/builder-rspack-provider/src/index.ts, packages/builder/builder-webpack-provider/src/index.ts, packages/builder/builder/src/index.ts
Export type of hook callback functions.
```ts
import type { ModifyWebpackChainFn } from '@modern-js/builder-webpack-provider';
const fn: ModifyWebpackChainFn = (chain) => {
chain.devtool(false);
}
api.modifyWebpackChain(fn);
```
=> feat(builder): export type of hook callback functions

.changeset/sour-balloons-matter.md, packages/builder/builder-rspack-provider/src/plugins/devtool.ts, packages/builder/builder-webpack-provider/src/plugins/devtool.ts, website/builder/src/en/guide/advanced/build-performance.md, website/builder/src/en/guide/advanced/inline-assets.md, website/builder/src/en/guide/basic/alias.md, website/builder/src/en/guide/basic/typescript.md, website/builder/src/en/plugins/list.md, website/builder/src/zh/plugins/list.md
Remove source map warning in production, because we will not upload the source map files to CDN.
=> fix(builder): remove source map warning in production

.changeset/heavy-dryers-burn.md, packages/builder/builder-rspack-provider/src/plugins/html.ts, packages/builder/builder-rspack-provider/src/types/config/html.ts, packages/builder/builder-shared/src/config.ts, packages/builder/builder-shared/src/types/config/html.ts, packages/builder/builder-shared/src/types/config/index.ts, packages/builder/builder-webpack-provider/src/plugins/html.ts, packages/builder/builder-webpack-provider/src/types/config/html.ts
Fix missing html.mountId default value, the `getDefaultConfig()` method should contain the default value of mountId.
=> fix(builder): missing html.mountId default value

packages/builder/builder-shared/src/createContext.ts, packages/solutions/app-tools/src/commands/dev.ts, pnpm-lock.yaml, tests/integration/asset-prefix/fixtures/dev-asset-prefix/modern.config.ts, tests/integration/asset-prefix/fixtures/dev-asset-prefix/package.json, tests/integration/asset-prefix/fixtures/dev-asset-prefix/src/index.ts, tests/integration/asset-prefix/package.json, tests/integration/asset-prefix/test/.eslintrc.js, tests/integration/asset-prefix/test/index.test.ts, tests/integration/asset-prefix/test/tsconfig.json, tests/integration/mwa-app/modern.config.ts
Fix incorrect dev.assetPrefix when using server.port:
```ts
dev: {
assetPrefix: true,
},
server: {
port: 3333,
},
});
```
=> fix(app-tools): incorrect dev.assetPrefix when using server.port

.changeset/nasty-timers-brush.md, packages/solutions/module-tools/package.json, packages/solutions/module-tools/src/builder/build.ts, pnpm-lock.yaml
When i use module-tools, i use bundleless, but i get a log like this, i fix it.
libuild error is fixed already in this [commit](https://github.com/modern-js-dev/libuild/commit/3092decefece9faa9d36ce8c372231b02c84307a)
=> fix: inaccurate error info

packages/solutions/app-tools/src/config/initial/inits.ts, packages/solutions/app-tools/src/utils/env.ts, packages/solutions/app-tools/tests/utils/env.test.ts
auto inject MODERN_ env vars to webpack define plugin
you can define in shell
```
MODERN_XXX=xxx pnpm run dev
```
or env var define in `.env.xxx` file
```
REACT_AGE=45
MODERN_XXX=xxx
```
=> feat: support auto inject metaName_ to webpack define plugin

packages/cli/doc-core/src/node/createBuilder.ts, packages/cli/doc-core/src/node/plugins/replace.ts, packages/cli/doc-core/src/node/virtualModule/siteData.ts, packages/cli/doc-core/src/shared/types/default-theme.ts, packages/cli/doc-core/src/shared/types/index.ts, packages/cli/doc-core/src/theme-default/components/Overview/index.tsx, packages/cli/doc-core/src/theme-default/components/Search/logic/search.ts, packages/cli/doc-core/src/theme-default/components/Siderbar/index.tsx, packages/cli/doc-core/src/theme-default/logic/useLocaleSiteData.ts, packages/cli/doc-core/src/theme-default/logic/usePrevNextPage.ts, packages/cli/doc-core/src/theme-default/logic/useSidebarData.ts, packages/cli/doc-plugin-auto-sidebar/src/index.ts
1. 文档框架支持 sidebar 配置中仅填入文档路径，而不用填入 `{ text: string; link: string; }` 对象数据
2. 搜索索引优化，解决部分标题无法搜索到的问题 @李茂
3. 优化 auto sidebar 插件 sidebar_position 默认值 @嘉聪
=> feat: doc-tools support sidebar link-only config

.changeset/red-windows-flow.md, packages/solutions/app-tools/src/index.ts
analyse webpack plugin will start a server after build,
and maybe has some webpack plugin required continue to run after build
=> fix: disable exit process after build for v1

.changeset/red-windows-flow.md, packages/solutions/app-tools/src/index.ts
analyse webpack plugin will start a server after build,
and maybe has some webpack plugin required continue to run after build
=> fix: disable exit process after build

packages/cli/doc-core/src/node/mdx/remarkPlugins/tip.ts, packages/cli/doc-core/src/theme-default/components/SocialLinks/LinkContent.tsx, packages/cli/doc-core/src/theme-default/styles/doc.css
Fix `.modern-directive-content` not work, improve tip style.
Before:
After:
=> fix(doc-tools): improve tip style

packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/configure/app/output/disable-node-polyfill.md, packages/toolkit/main-doc/zh/configure/app/output/disable-node-polyfill.md
The default value of `disableNodePolyfill` is `true` in Modern.js v2, so we should update the document.
=> docs: fix disableNodePolyfill default value

.changeset/curly-months-occur.md, packages/solutions/app-tools/src/builder/index.ts, packages/solutions/app-tools/src/initialize/index.ts, packages/solutions/app-tools/src/types/config/dev.ts, packages/toolkit/main-doc/en/docusaurus-plugin-content-docs/current/configure/app/server/port.md, packages/toolkit/main-doc/zh/configure/app/server/port.md, pnpm-lock.yaml
目前 Builder 提供的 `dev.port` 配置和 Modern.js 的 `server.port` 配置在功能上有一定重合，因此我们在 Modern.js 中没有支持 `dev.port` 配置项。
但是用户可以在 Modern.js 及 Builder 文档中找到 `dev.port` 相关的介绍，却无法配置后无法生效，因而产生了困惑。我们虽然可以删除 Modern.js 中关于 `dev.port` 的文档，却无法删除 Builder 文档中 `dev.port` 的文档。
为了避免这种情况，我们后续允许在 Modern.js 中使用 `dev.port`，并在文档中说明这两者的区别。
=> feat(app-tools): allow to use dev.port config

.changeset/sixty-cats-cover.md, packages/cli/doc-core/src/theme-default/components/Nav/NavMenuGroup.tsx
Fix nav dropdown item text wrap.
Before:
After:
=> fix(doc-core): fix nav dropdown item text wrap

.changeset/few-lobsters-prove.md, packages/solutions/app-tools/src/config/default.ts
Fix server.port not work in development, because `dev.port` has a default value and overrides the `server.port` config.
=> fix(app-tools): server.port not work in development

.changeset/fuzzy-tigers-beg.md, packages/builder/builder-doc/modern.config.ts, packages/cli/doc-core/src/theme-default/components/HomeHero/index.tsx
Remove duplicate base URL in Action Button, the `<Link>` component will call `withBase`, so we do not need to call `withBase` in Action Button.
=> fix(doc-core): remove duplicate base URL

.changeset/quick-wombats-remember.md, packages/builder/builder-doc/docs/en/config/dev/startUrl.md, packages/builder/builder-doc/docs/zh/config/dev/startUrl.md, packages/builder/builder-doc/modern.config.ts, packages/builder/builder/src/plugins/startUrl.ts, packages/builder/builder/tests/plugins/startUrl.test.ts, website/module-tools/modern.config.ts
Support port placeholder in `dev.startUrl` config.
Since the port number may change, you can use the `<port>` placeholder to refer to the current port number, and Builder will automatically replace the placeholder with the actual listening port number.
```js
dev: {
startUrl: 'http://localhost:<port>/home',
},
};
```
=> feat(builder): support port placeholder in dev.startUrl config

.changeset/lazy-planes-trade.md, packages/server/prod-server/src/libs/route/matcher.ts, packages/server/prod-server/tests/route.test.ts
Fix failed to match html inside config/public directory. The urlPath of static routes will be `/xxx.html`, we need to remove `.html` to make the `matchUrlPath` working as expected.
https://github.com/modern-js-dev/modern.js/issues/2381
=> fix(prod-server): failed to match html inside config/public directory

packages/builder/builder-shared/src/index.ts, packages/builder/builder-shared/src/openBrowser.ts, packages/builder/builder/src/plugins/startUrl.ts
This PR will help OS X user when set `dev.startUrl: true` reuse an existing tab instead of creating a new one.
=> feat: dev.startUrl reuse exsiting tab under osx system

.changeset/grumpy-clocks-invent.md, packages/builder/builder-webpack-provider/src/plugins/progress.ts, packages/builder/builder-webpack-provider/src/webpackPlugins/ProgressPlugin/ProgressPlugin.ts, packages/builder/builder-webpack-provider/src/webpackPlugins/ProgressPlugin/helpers/bar.ts, packages/builder/builder-webpack-provider/src/webpackPlugins/ProgressPlugin/helpers/non-tty.ts, packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/default.test.ts.snap, tests/e2e/webpack-builder/progress/index.test.ts
- improve succeed and failed progress log, make the status more intuitive.
- Add a recompile log.
The recompile is succeed, but user may not know it.
There will be a recompile log, and the succeed status is more intuitive.
=> feat(builder): improve succeed and failed progress log

.changeset/shaggy-stingrays-explain.md, packages/cli/doc-core/src/node/mdx/remarkPlugins/toc.ts, packages/cli/doc-core/src/node/virtualModule/siteData.ts, packages/cli/doc-core/src/shared/types/index.ts, packages/cli/doc-core/src/theme-default/components/Overview/index.tsx, packages/cli/doc-core/src/theme-default/components/Siderbar/index.tsx
修复问题:
1. 大纲页面因为 pages 找不到而报错；
2. SidebarGroup 组件因 key 值不唯一，导致切换路由时 collapse 状态错乱，产生没必要的 collopse 动画
=> fix: doc-tools overview page error

.changeset/rotten-scissors-approve.md, packages/solutions/module-tools/src/builder/build.ts
=> fix: es5Plugin should apply after umd, umd will change the es5 code

.changeset/tricky-jobs-double.md, packages/builder/builder-rspack-provider/src/plugins/basic.ts, packages/builder/builder-webpack-provider/src/plugins/basic.ts
Fix `dynamicImportMode: 'eager'` is overridden by Basic plugin.
=> fix(builder): should not emit async chunk when target is web-worker

.changeset/stale-rivers-reflect.md, packages/cli/doc-core/src/theme-default/styles/doc.css
Fix list item missing line-height.
=> fix(doc-core): list item missing line-height

.changeset/forty-sloths-invite.md, .github/workflows/build-module-website.yml, packages/builder/builder-webpack-provider/src/plugins/basic.ts, packages/builder/builder-webpack-provider/tests/__snapshots__/webpackConfig.test.ts.snap, packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/default.test.ts.snap
- Increase size limit when target is node to avoid the webpack warning. (Also increased the default size limit to 3MB).
=> fix(builder): increase size limit when target is node

.changeset/pretty-onions-fetch.md, packages/runtime/plugin-runtime/src/ssr/serverRender/renderToStream/renderToPipe.ts
use `try { require(...) } catch(e) {}` instead `import` for react-dom/server in stream ssr
=> chore: catch react-dom/server require for react 17

.changeset/brave-spies-vanish.md, .github/workflows/build-main-website.yml, packages/builder/builder-doc/docs/en/guide/basic/html-template.md, packages/builder/builder-doc/docs/zh/guide/basic/html-template.md, website/main/modern.config.ts
=> docs: make v2 docs as default

.github/workflows/build-main-website.yml
Fix `Build Main Website` CI should not clean some used files such as `v1/index.html`
=> chore(CI): fix build main website clean exclude

.changeset/four-pants-pay.md, packages/builder/builder/src/plugins/startUrl.ts
Fix the `startUrl` may be opened multiple times.
For example, the developer is updating the `modern.config.ts`, then the CLI will be restarted and the `startUrl` will be opened again. This causes the browser to be opened frequently.
=> fix(builder): should not open startUrl multiple times

.changeset/quiet-vans-hide.md, packages/builder/builder-rspack-provider/package.json, packages/builder/builder-webpack-provider/package.json, packages/toolkit/utils/package.json, pnpm-lock.yaml
Bump caniuse-lite to latest version to remove warnings:
=> chore: bump caniuse-lite to latest version

.changeset/dull-rice-compete.md, packages/builder/builder-shared/src/apply/html.ts, packages/builder/builder-webpack-provider/tests/plugins/html.test.ts
Should not generate HTML for service-worker target.
=> fix(builder): should not generate HTML for service-worker target

.changeset/tall-spoons-draw.md, packages/builder/builder-doc/docs/en/config/tools/webpack.md, packages/builder/builder-doc/docs/zh/config/tools/webpack.md, packages/builder/builder-rspack-provider/src/core/rspackConfig.ts, packages/builder/builder-rspack-provider/src/types/hooks.ts, packages/builder/builder-webpack-provider/src/core/webpackConfig.ts, packages/builder/builder-webpack-provider/src/types/hooks.ts, packages/builder/builder-webpack-provider/tests/__snapshots__/webpackConfig.test.ts.snap, packages/builder/builder-webpack-provider/tests/webpackConfig.test.ts
Support mergeConfig util in tools.webpack.
```ts
tools: {
webpack: (config, { mergeConfig }) => {
return mergeConfig(config, {
devtool: 'eval',
});
},
},
};
```
=> feat(builder): support mergeConfig util in tools.webpack

.changeset/warm-shrimps-type.md, packages/builder/builder-rspack-provider/src/plugins/css.ts, packages/builder/builder-rspack-provider/tests/plugins/__snapshots__/css.test.ts.snap, packages/builder/builder-shared/src/getBrowserslist.ts, packages/builder/builder-shared/src/getCssSupport.ts, packages/builder/builder-shared/src/index.ts, packages/builder/builder-webpack-provider/src/plugins/css.ts, packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/css.test.ts.snap, packages/builder/builder-webpack-provider/tests/plugins/css.test.ts
Enable postcss plugins based on browserslist, this change can remove some unnecessary postcss plugins when the browserslist only contains modern browsers.
This change can reduce the CSS size and improve compile speed of modern projects.
=> feat(builder): enable postcss plugins based on browserslist

packages/cli/doc-core/src/theme-default/components/Search/index.module.scss, packages/toolkit/main-doc/en/configure/app/bff/_category_.json, packages/toolkit/main-doc/en/configure/app/deploy/_category_.json, packages/toolkit/main-doc/en/configure/app/dev/_category_.json, packages/toolkit/main-doc/en/configure/app/experiments/_category_.json, packages/toolkit/main-doc/en/configure/app/html/_category_.json, packages/toolkit/main-doc/en/configure/app/output/_category_.json, packages/toolkit/main-doc/en/configure/app/performance/_category_.json, packages/toolkit/main-doc/en/configure/app/runtime/_category_.json, packages/toolkit/main-doc/en/configure/app/security/_category_.json, packages/toolkit/main-doc/en/configure/app/server/_category_.json, packages/toolkit/main-doc/en/configure/app/source/_category_.json, packages/toolkit/main-doc/en/configure/app/testing/_category_.json, packages/toolkit/main-doc/en/configure/app/tools/_category_.json, packages/toolkit/main-doc/en/configure/app/usage.mdx
Fix missing sidebar items of configure page.
=> docs: fix missing sidebar items of configration page

.changeset/modern-jokes-drop.md, packages/cli/plugin-bff/src/cli.ts, packages/cli/plugin-bff/tests/__snapshots__/cli.test.ts.snap, packages/cli/plugin-bff/tests/cli.test.ts, packages/server/core/src/plugin.ts, packages/server/core/src/types/config/bff.ts, packages/server/plugin-koa/src/plugin.ts, packages/server/plugin-koa/tests/api.test.ts, packages/server/plugin-koa/tests/helpers.ts, packages/server/prod-server/src/server/modern-server.ts, packages/server/server/src/server/dev-server.ts, pnpm-lock.yaml
Before this feature, the traffic of front-end pages and BFF in the Modern.js was separate. Front-end pages can only be extended at the server level by customizing the Web Server. If you want the BFF and the page to share a set of middleware, there is some trouble here.
Now we provide a way to perform page rendering at the end of the BFF.
You only need to enable the following configuration, currently only Koa is supported.
```ts
bff: {
enableHandleWeb: true
}
}
```
=> feat: support render after server

.changeset/gorgeous-adults-sort.md, packages/cli/doc-core/src/node/mdx/remarkPlugins/normalizeLink.ts, packages/toolkit/main-doc/en/apis/app/runtime/core/create-app.mdx, website/main/modern.config.ts
When we refer a relative path markdown, the generated URL when contain a lang prefix ('zh' is the default lang):
This will cause two problems:
1. The link will be redirected.
2. The checkDeadLinks will be failed.
So I removed the default lang prefix in `normalizeLangPrefix` method.
=> fix(doc-core): remove default lang prefix from URL

.changeset/underfin-is-awesome.md, packages/runtime/plugin-runtime/src/document/cli/index.ts, packages/runtime/plugin-runtime/tests/document/cli.test.tsx
默认配置文档里面，这个地方应该去 normalizedConfig 之后的值，不然 output 这里取到的值会是 undefined，例如在官网 demo 中:
这个地方取到 undefined 了，那么下面是会直接抛错的
顺便一提，这里 output 这个配置对象里面没有 title 这个属性？按照文档表述，这里是个 `Output` 配置对象，这里示例里面当成 htmlConfig 在使用？
=> fix(runtime): document param output get undefined in default template

.changeset/rich-baboons-reflect.md, packages/builder/builder-webpack-provider/package.json, pnpm-lock.yaml
Builder-webpack-proivder would found low verson @babel/core,
Because some users use monorepo that have many version of @babel/core with modern.js.
So adjust the @babel/core to dependencies instead of devDependencies
=> fix(builder-webpack-provider): adjust @babel/core to dependency

pnpm-lock.yaml, scripts/check-changeset/package.json, scripts/check-changeset/src/index.ts
Check changeset CI add strict validate to guarantee version consistency when publishing:
- changeset not allow has major version
- changeset not allow exist not found package
- package's peerDependencies should use `workspace:^xx` to define
=> feat: check changeset

.changeset/dirty-rats-own.md, packages/cli/babel-preset-base/src/babel-utils.ts
避免 modifyPresetReactOptions  及 modifyPresetEnvOptions 配置在 windows 系统不生效的问题
=> fix: windows path compat in modifyPresetOptions

.changeset/silly-rice-retire.md, packages/builder/builder-shared/src/schema/tools.ts
fix schema check error:
devServer.proxy type is too complex
https://modernjs.dev/configure/app/tools/dev-server.html#proxy
=> hotfix(builder): make devServer.proxy schema check loosely

.changeset/fluffy-birds-type.md, packages/builder/plugin-swc/src/config.ts, packages/builder/plugin-swc/tests/fixtures/compat/cjs-no-preserve-dyn-import/expected.js
Fix webpack magic comment is removed after compilation.
It can be fixed by adding the `preserveAllComments: true` config.
https://github.com/swc-project/swc/issues/6403
=> fix(plugin-swc): webpack magic comment is removed after compilation

.changeset/twenty-monkeys-flow.md, packages/builder/plugin-swc/src/loader.ts, packages/builder/plugin-swc/src/plugin.ts, packages/builder/plugin-swc/tests/__snapshots__/plugin.test.ts.snap, packages/builder/plugin-swc/tests/plugin.test.ts
Fix runtime error when set `dev.hmr` to false.
We should disable `swc.jsc.transform.react.refresh` when `dev.hmr` is false.
=> fix(plugin-swc): runtime error when set dev.hmr to false

.changeset/moody-pots-laugh.md, packages/solutions/app-tools/src/analyze/getClientRoutes/getRoutes.ts, packages/solutions/app-tools/src/analyze/getClientRoutes/getRoutesLegacy.ts, packages/solutions/app-tools/src/analyze/nestedRoutes.ts, tests/integration/routes/src/four/routes/act/[bid$]/page.tsx, tests/integration/routes/src/two/pages/act/bar/[bid$]/detail.tsx, tests/integration/routes/src/two/pages/act/bar/[bid$]/index.tsx, tests/integration/routes/src/two/pages/act/foo/[uid$].tsx, tests/integration/routes/tests/index.test.ts
Optional parameters can now be set via `[id?]/page.tsx` in file-based routes
=> feat: support optional params in file-based route

.changeset/red-eyes-matter.md, packages/cli/doc-core/src/theme-default/logic/useAppearance.ts
Fix failed to build when using logo.dark.
```ts
doc: {
logo: {
light: 'xxx',
dark: 'xxx',
},
}
});
```
=> fix(doc-core): failed to build when using logo.dark

.changeset/silver-bears-accept.md, packages/cli/plugin-storybook/src/features/utils/webpackConfig.ts
Remove builtin babel-plugin-import when use module-tools, so we can keep the behavior consistent between storybook and module build.
=> fix(storybook): remove builtin babel-plugin-import when use module-tools

.changeset/big-melons-wave.md, packages/builder/builder-webpack-provider/src/plugins/sass.ts, packages/builder/builder-webpack-provider/src/types/thirdParty/index.ts
Sass supports two type of options: `Options` and `LegacyOptions`.
In sass-loader, the `sassOptions` should use legacy sass options by default, and users can switch the option type via the `api` config.
https://github.com/webpack-contrib/sass-loader#api
=> fix(builder): tools.sass type should use legacy sass options by default

.changeset/chilly-rice-knock.md, packages/solutions/module-tools/src/builder/dts/rollup.ts, packages/solutions/module-tools/src/utils/common.ts
ignore some tsconfig compileOptions, Because their presence can cause errors in the bundling type
=> fix(module-tools): ignore some tsconfig compileOptions

.changeset/tough-queens-repeat.md, packages/solutions/app-tools/src/builder/builder-webpack/builderPlugins/compatModern.ts, packages/solutions/app-tools/src/builder/builder-webpack/webpackPlugins/index.ts, packages/solutions/app-tools/src/builder/shared/builderPlugins/adapterModern.ts, packages/solutions/app-tools/src/builder/shared/bundlerPlugins/RouterPlugin.ts, packages/solutions/app-tools/src/builder/shared/bundlerPlugins/index.ts, packages/solutions/app-tools/tests/routes/webpackRouterPlugin.test.ts
Router Plugin would use in SSR mode.
We need support this plugin to Rspack. Otherwise the SSR mode can't run ,when we switch on Rspack bundler.
=> feat(app-tools): support router plugin in rspack

.changeset/serious-squids-bow.md, packages/builder/plugin-swc/package.json, pnpm-lock.yaml
Fix missing `@modern-js/builder-shared` dependency.
=> fix(plugin-swc): missing @modern-js/builder-shared dependency

.changeset/weak-kings-roll.md, packages/runtime/plugin-runtime/src/state/runtime/index.tsx
`@modern-js-reduck/react` currently exports `model` and `createStore`,  so we don't need to export these two API from `@modern-js-reduck/store`.
=> Fix: fix duplicate re-exports of reduck

.changeset/warm-pandas-complain.md, packages/solutions/app-tools/src/analyze/generateCode.ts, packages/solutions/app-tools/src/analyze/index.ts, packages/solutions/app-tools/src/analyze/templates.ts, packages/solutions/app-tools/src/analyze/utils.ts, packages/solutions/app-tools/src/builder/shared/builderPlugins/adapterSSR.ts
improvement: the modern.js ssr loader support rspack            
the `rspack` is not support virtualModule
so we write the `ssr` loader combinedModule in filesystem;  
then we load it from disk.                          
It is temporary.Once `rspack` support it, we will use   
virtualModule to implement it.
=> feat(app-tools): the modern.js ssr loader support rspack

.changeset/breezy-wolves-walk.md, packages/builder/builder-webpack-provider/src/types/thirdParty/css.ts
Fix missing some type in `tools.cssExtract`, import the type directly from `mini-css-extract-plugin` package.
=> fix(builder): missing some type in tools.cssExtract

.changeset/light-dragons-grin.md, packages/server/prod-server/src/libs/context/context.ts, packages/toolkit/types/server/context.d.ts
For `new url.URL(path, base)` not support ipv6 host, and we only need parse url path & search.
So use mock host 'https://modern.dev' instead real host.
Koa use `url.parse` to parse url path, but the api has deprecated.
=> fix(server): use mock host instead real url host for url parse

tests/integration/swc/test/index.test.ts
Fix integration test failure because of different hash between different platforms
=> fix(swc-integration): change the way to test swc css minify

packages/cli/doc-core/src/theme-default/components/Siderbar/index.tsx
I think the border of the nav item(such as "核心概念") is too sharp and does not match the sub-item(such as "介绍") very well, so I tried to make some style changes.
=> chore(doc-tools): add border-radius to nav item

.changeset/odd-ghosts-hide.md, package.json, packages/cli/core/src/index.ts, packages/cli/core/src/loadPlugins.ts, packages/cli/core/tests/loadPlugin.test.ts, pnpm-lock.yaml
Remove legacy transformPlugin option.
=> chore(core): remove legacy transformPlugin option

.changeset/fluffy-masks-matter.md, packages/solutions/app-tools/src/analyze/templates.ts
Currently,  css from async chunk inserts in front of one from entry chunk in html when SSR is enabled,  as shown below:
So css from async chunk may be overridden by one from entry chunk, which is unreasonable. 
This PR fixes the issue.
=> fix: fix css priority in ssr 

.changeset/twelve-gorillas-grin.md, packages/builder/builder/src/plugins/asset.ts, packages/builder/builder/src/plugins/svg.ts
修复 windows 中 asset url 使用错误的路径分隔符
#2981
=> fix(builder): asset url using incorrect path separator in windows

.changeset/curvy-vans-relate.md, packages/builder/builder-shared/src/schema/tools.ts, packages/builder/builder-webpack-provider/src/core/devMiddleware.ts, packages/document/main-doc/docs/en/apis/app/runtime/web-server/hook.mdx, packages/document/main-doc/docs/en/apis/app/runtime/web-server/middleware.mdx, packages/document/main-doc/docs/zh/apis/app/runtime/web-server/hook.mdx, packages/document/main-doc/docs/zh/apis/app/runtime/web-server/middleware.mdx, packages/server/prod-server/src/libs/hook-api/index.ts, packages/server/prod-server/tests/hook.test.ts, packages/server/server/src/types.ts, packages/toolkit/types/server/devServer.d.ts, packages/toolkit/types/server/hook.d.ts, pnpm-lock.yaml
support `string[]` type for `tools.devServer.headers`.
```ts
import AppToolsPlugin, { defineConfig } from '@modern-js/app-tools';
tools: {
devServer: {
headers: {
'Set-Cookie': process.env.COOKIE.split('; ').map(
item => `${item}; path=/; Max-Age=8640000;`,
),
},
},
},
plugins: [
AppToolsPlugin({}),
],
});
```
remove `get`、`set`、`apply` in Hook or Middleware `response.cookies` API. For Most libraries or frameworks do not provide such API.
=> fix: remove get & delete & apply api in hook or middleware api

.changeset/chilled-lobsters-destroy.md, packages/cli/doc-core/src/theme-default/styles/doc/container.css, packages/document/doc-tools-doc/docs/en/api/commands.mdx, packages/document/doc-tools-doc/docs/zh/api/commands.mdx, packages/document/doc-tools-doc/modern.config.ts, packages/solutions/doc-tools/src/index.ts
Support `--config` CLI option.
https://github.com/web-infra-dev/modern.js/issues/3151
=> feat(doc-tools): support --config CLI option

.changeset/proud-rats-rescue.md, packages/cli/doc-core/src/theme-default/styles/doc/container.css
Fix code background color in containers.
before:
after:
=> fix(doc-core): fix code background color in containers

.changeset/sour-pots-hug.md, packages/cli/core/src/index.ts, packages/cli/core/src/manager.ts, packages/cli/core/src/types/hooks.ts, packages/document/main-doc/docs/en/guides/topic-detail/framework-plugin/hook-list.mdx, packages/document/main-doc/docs/zh/guides/topic-detail/framework-plugin/hook-list.mdx
Since the callback function when exiting the process in Node.js is synchronous, the type of `beforeExit` Hook should be `Workflow` and cannot perform asynchronous operations.
=> fix(core): beforeExit should be sync workflow

.changeset/nice-walls-cover.md, packages/builder/builder/src/plugins/fileSize.ts
Print total file size after build:
=> feat(builder): print total file size after build

tests/integration/ssr/test/base.test.js, tests/integration/ssr/test/index.test.js, tests/integration/ssr/test/streaming.test.js, tests/utils/jest.setup.js
Set expect-puppetter timeout 30s.
=> fix: fix puppeteer timeout

.changeset/nervous-ducks-dress.md, packages/builder/builder-shared/src/schema/tools.ts
The builder `tools.devServer.proxy` can be a array.
But user pass a array would occur a error, because the schema parse error.
=> fix(builder): schema parser error, tools.devServer.proxy can be a array

.changeset/tough-hats-explode.md, packages/builder/builder-rspack-provider/package.json, packages/builder/builder-rspack-provider/src/plugins/babel.ts, packages/builder/builder-rspack-provider/src/shared/plugin.ts, packages/builder/builder-rspack-provider/src/types/config/tools.ts, packages/builder/builder-rspack-provider/tests/plugins/__snapshots__/babel.test.ts.snap, packages/builder/builder-rspack-provider/tests/plugins/babel.test.ts, packages/cli/babel-preset-base/src/presets.ts, packages/document/builder-doc/docs/en/config/tools/babel.md, packages/document/builder-doc/docs/en/guide/advanced/rspack-start.mdx, packages/document/builder-doc/docs/zh/config/tools/babel.md, packages/document/builder-doc/docs/zh/guide/advanced/rspack-start.mdx, packages/toolkit/utils/src/constants.ts, pnpm-lock.yaml, tests/e2e/builder/cases/babel/build.test.ts
The babel can't parser `tsx/jsx` syntax without `@babel/preset-typescript`.
For rspack-provider can use `tools.babel` configuration, inline the `@babel/preset-typescript` to handle ts syntax in rspack-provider.
=> feat(rspack-provider): add @babel/preset-typescript to handle ts syntax

.changeset/tasty-tables-mate.md, packages/cli/doc-core/README.md, packages/cli/doc-core/package.json, packages/cli/doc-core/src/node/createBuilder.ts, packages/cli/doc-plugin-auto-sidebar/README.md, packages/cli/doc-plugin-auto-sidebar/package.json, packages/document/builder-doc/docs/en/plugins/plugin-esbuild.mdx, packages/document/builder-doc/docs/en/plugins/plugin-image-compress.mdx, packages/document/builder-doc/docs/en/plugins/plugin-node-polyfill.mdx, packages/document/builder-doc/docs/en/plugins/plugin-stylus.mdx, packages/document/builder-doc/docs/en/plugins/plugin-swc.mdx, packages/document/builder-doc/docs/zh/plugins/plugin-esbuild.mdx, packages/document/builder-doc/docs/zh/plugins/plugin-image-compress.mdx, packages/document/builder-doc/docs/zh/plugins/plugin-node-polyfill.mdx, packages/document/builder-doc/docs/zh/plugins/plugin-stylus.mdx, packages/document/builder-doc/docs/zh/plugins/plugin-swc.mdx, packages/document/builder-doc/modern.config.ts, packages/solutions/doc-tools/README.md, packages/solutions/doc-tools/package.json
- Run `string-replace-loader` before `mdx-loader`, so we can using `string-replace-loader` to replace variables, such as `{MODERN_JS}`.
- Fix some doc-tools links.
=> fix(doc-core): run string-replace-loader before mdx-loader

.changeset/few-tomatoes-sparkle.md, packages/builder/builder-rspack-provider/src/index.ts, packages/builder/builder-rspack-provider/src/shared/getRspackVersion.ts, packages/builder/builder-rspack-provider/src/shared/index.ts, packages/solutions/app-tools/src/builder/index.ts
I want to output the version of rspack, which is very useful during debugging, especially when there may be multiple rspack versions in a monorepo.
before: 
```sh
info    Using Rspack  ✨
info    Create a production build...
```
after: 
```sh
info    Using Rspack 0.1.1  ✨
info    Create a production build...
```
=> feat: print the version of rspack in the console

.changeset/itchy-ties-act.md, packages/solutions/app-tools/src/commands/serve.ts
=> fix(app-tools): distPath.root not take effect when run serve

.changeset/cuddly-singers-explode.md, packages/builder/builder-rspack-provider/src/plugins/output.ts, packages/builder/builder-shared/src/apply/output.ts, packages/builder/builder-webpack-provider/src/plugins/output.ts
Fix incorrect asset URL in windows.
https://github.com/web-infra-dev/modern.js/pull/3265
=> fix(builder): incorrect asset URL in windows

.changeset/cold-pens-give.md, packages/builder/builder-webpack-provider/src/plugins/babel.ts, packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/babel.test.ts.snap, packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/default.test.ts.snap, packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/react.test.ts.snap, packages/builder/builder/src/plugins/antd.ts, packages/cli/babel-preset-app/src/common.ts, packages/cli/babel-preset-app/src/index.ts, packages/cli/babel-preset-app/src/type.ts, packages/cli/babel-preset-base/src/index.ts, packages/cli/babel-preset-base/src/plugins.ts, packages/toolkit/utils/src/index.ts, packages/toolkit/utils/src/resolve.ts, packages/toolkit/utils/tests/isPackageInstalled.test.ts
Remove duplicated babel-plugin-import.
Currently, there are two `babel-plugin-import` to import antd in Builder:
- The `@modern-js/babel-preset-base` will register one.
- The `@modern-js/builder` will register another one.
So we should disable the antd of babel-preset-base when using Builder.
=> fix(builder): remove duplicated babel-plugin-import

.changeset/sixty-dryers-attend.md, packages/builder/builder-webpack-provider/src/plugins/babel.ts
之前在 Babel 中检测了是否 transformImport 配置中有字符串参数，如果有报错，但是不应该这样因为可能会使用 SWC 插件
=> fix(transform-import): :bug: remove check for babel transform-import

.changeset/chatty-panthers-compare.md, packages/runtime/plugin-runtime/src/ssr/serverRender/renderToStream/bulidTemplate.before.ts, packages/solutions/app-tools/src/builder/shared/bundlerPlugins/RouterPlugin.ts
If the user css split many chunks, the `assetsByChunkName` can not get all chunks messages.
So we use the  chunkGroup to filter the css assets
=> fix: load chunk while can not load all css asset, when streaming ssr

.changeset/four-lions-battle.md, packages/cli/core/package.json, packages/cli/core/src/config/createLoadedConfig.ts, packages/cli/core/src/config/loadConfig.ts, packages/cli/core/src/index.ts, packages/cli/core/src/node-api.ts, packages/cli/core/tests/loadConfigs.test.ts, packages/solutions/app-tools/src/analyze/index.ts, packages/solutions/app-tools/src/utils/restart.ts, packages/toolkit/utils/src/analyzeProject.ts, packages/toolkit/utils/src/commands.ts, packages/toolkit/utils/tests/commands.test.ts
An experimental feature, most likely to change, now you can start modern.js by node api:
```ts
import { dev } from '@modern-js/core/node';
import appTools, { defineConfig } from '@modern-js/app-tools';
import runtimeCli from '@modern-js/runtime/cli';
const main = () => {
dev({
loadedConfig: defineConfig({
runtime: {
router: true,
},
plugins: [runtimeCli(), appTools()],
}),
});
};
main();
```
=> feat: support use node api run dev & build & deploy command

.changeset/gentle-actors-boil.md, packages/builder/builder-rspack-provider/tests/plugins/__snapshots__/default.test.ts.snap, packages/builder/builder-shared/src/index.ts, packages/builder/builder-shared/src/svgo.ts, packages/builder/builder-webpack-provider/tests/plugins/__snapshots__/default.test.ts.snap, packages/builder/builder/src/plugins/svg.ts, packages/builder/builder/tests/plugins/__snapshots__/svg.test.ts.snap, tests/e2e/builder/cases/svg/svg.test.ts, tests/e2e/builder/cases/svg/svgo-minify/src/image.svg, tests/e2e/builder/cases/svg/svgo-minify/src/index.jsx
Should preserve viewBox after minify SVG, because viewBox is required to resize SVGs with CSS.
- https://github.com/web-infra-dev/modern.js/issues/3254
- https://github.com/svg/svgo/issues/1128
=> fix(builder): should preserve viewBox after minify SVG

tests/e2e/builder/cases/svg/svg.test.ts
Fix SVG minify e2e case when using Rspack.
The test cases failed because the generated files of webpack and Rspack is different, **we need to make the dist files consistent in the future.**
webpack:
Rspack:
=> chore(builder): fix SVG minify e2e case when using Rspack

.changeset/eighty-trainers-love.md, packages/builder/builder-shared/src/devServer.ts, packages/builder/builder-shared/src/types/provider.ts, packages/cli/doc-core/src/node/dev.ts, packages/document/builder-doc/docs/en/api/builder-instance.mdx, packages/document/builder-doc/docs/zh/api/builder-instance.mdx, packages/toolkit/utils/src/prettyInstructions.ts
Print dev server URLs with base.
before:
after:
=> feat(doc-tools): print dev server URLs with base

.changeset/unlucky-steaks-notice.md, packages/generator/generators/module-generator/templates/ts-template/tsconfig.json.handlebars
Setting the isolatedModules flag tells TypeScript to warn you if you write certain code that can’t be correctly interpreted by a single-file transpilation process.
=> feat(module-tools): enable isolatedModules

.changeset/blue-feet-fold.md, packages/solutions/app-tools/src/builder/shared/bundlerPlugins/RouterPlugin.ts
=> fix: referenceCssAssets should not include publicPath in bundle

.changeset/clean-jokes-dream.md, packages/builder/plugin-swc-base/package.json, pnpm-lock.yaml
The `@swc/heplers` version is lower than SWC version, and some helpers can not be found.
```bash
Module not found: Can't resolve '/node_modules/.pnpm/@swc+helpers@0.4.12/node_modules/@swc/helpers/src/_object_destructuring_empty.mjs' in 'xxx'
```
=> fix(swc): can not find object_destructuring_empty.mjs

codecov.yml
Disable the codecov patch check because it is always inaccurate.
For example, #3324 only updated a dependency, but the `codecov/patch` is failed and we get some irrelavant annotations.
https://docs.codecov.com/docs/commit-status#disabling-a-status
=> chore(CI): disable codecov patch check

.changeset/big-dots-worry.md, packages/solutions/app-tools/src/utils/restart.ts, packages/toolkit/utils/src/commands.ts
Fix failed to restart CLI, because `program.parse` should accept a full argv array.
https://github.com/web-infra-dev/modern.js/pull/3295
=> fix(app-tools): failed to restart CLI

.github/workflows/build-builder-website.yml, .github/workflows/build-doc-website.yml, .github/workflows/build-main-website.yml, .github/workflows/build-module-website.yml, .github/workflows/check-changeset.yml, .github/workflows/cypress-test.yml, .github/workflows/integration-test-Windows.yml, .github/workflows/integration-test-macOS.yml, .github/workflows/lint-Linux.yml, .github/workflows/release-pull-request.yml, .github/workflows/release.yml, .github/workflows/test-Windows.yml, .github/workflows/test-builder-e2e.yml, .github/workflows/test-macOS.yml, .github/workflows/type-check.yml, package.json
- Using corepack in GitHub actions, so we do not need to install pnpm manually in CI.
- Upgrade pnpm version from `7.12.2` to `7.29.1`.
=> chore(CI): using corepack in actions

.changeset/khaki-cooks-act.md, packages/cli/plugin-module-babel/src/index.ts
add right export name for `@modern-js/plugin-module-babel`
=> fix(plugin-module-babel): add right export name

.changeset/funny-lizards-cover.md, packages/cli/core/src/types/context.ts, packages/runtime/plugin-runtime/src/ssr/cli/index.ts, packages/solutions/app-tools/src/initialize/index.ts
Plugin config hook can not get bundler type,so we can not set babelConfig correctly in ssr plugin.
1. Set bundler type in `initial plugin`
2. Ensure initial plugin run before ssr plugin.
=> fix: plugin config hook can not get bundlerType,

.changeset/spotty-monkeys-impress.md, packages/cli/doc-core/src/theme-default/components/Search/index.tsx
=> fix(doc-core): search broken when search keyword is null

.changeset/five-weeks-approve.md, packages/builder/builder-shared/src/plugins/HtmlTagsPlugin.ts, packages/builder/builder-shared/tests/plugins/HtmlTagsPlugin.test.ts, packages/builder/builder-shared/tests/tsconfig.json, packages/builder/builder-shared/vitest.config.ts
=> fix(builder): `HtmlTagsPlugin` failed to join public path with absolute url

.changeset/few-mails-dress.md, packages/builder/builder-shared/src/schema/output.ts, packages/builder/builder-shared/src/types/config/output.ts, packages/builder/builder/src/plugins/inlineChunk.ts, packages/document/builder-doc/docs/en/config/output/enableInlineScripts.md, packages/document/builder-doc/docs/en/config/output/enableInlineStyles.md, packages/document/builder-doc/docs/zh/config/output/enableInlineScripts.md, packages/document/builder-doc/docs/zh/config/output/enableInlineStyles.md, tests/e2e/builder/cases/inline-chunk/build.test.ts
Support using RegExp to inline part of chunks.
For example, only inline `main.js` into HTML:
```js
output: {
enableInlineScripts: /\/main\.\w+\.js$/,
},
};
```
=> feat(builder): support using RegExp to inline part of chunks

.changeset/tidy-squids-wash.md, packages/builder/plugin-swc-base/src/apply.ts, packages/builder/plugin-swc/tests/fixtures/compat/cjs-no-preserve-dyn-import/expected.js, packages/builder/plugin-swc/tests/fixtures/compat/cjs-preserve-dyn-import/expected.js
Remove default `usage` option for presetEnv
=> fix(builder-plugin-swc): remove default env.mode

.changeset/swift-rivers-hear.md, packages/solutions/module-tools/src/types/dts.ts, packages/solutions/module-tools/src/utils/dts.ts
This pull request modifies some files to improve the generation and publishing of declaration files for the module-tools package. It adds the `declarationDir` option to the TypeScript compiler options instead of `outDir`.
=> feat: use `declarationDir` instead of `outDir`

.changeset/fix-plugin-garfish.md, packages/runtime/plugin-garfish/package.json
closes #4505 
I add peerDependencies, as does `@garfish/bridge-react`
https://github.com/web-infra-dev/garfish/blob/695df5e5eb5f0f37c4a5e901243f9f321542e44b/packages/bridge-react/package.json#L43C1-L46C5
```json
"peerDependencies": {
"react": ">=16",
"react-dom": ">=16"
}
```
=> fix(plugin-garfish): phantom dependencies of react

.pnpmfile.cjs, pnpm-lock.yaml
Some packages still depend on esbuild < 0.17, so we upgrade it manually.
https://github.com/lukeed/tsm/issues/48
=> chore: reduce multiple esbuild versions

.npmrc, package.json
This PR brings:
- Ensure to use `﻿pnpm@>=8.7` to adopt the highest resolution by default.
- Experiment with `﻿pnpm@8.9` in CI to evaluate if it can reduce the linking time by CoW during installation.
=> chore: use pnpm@8.9 in corepack

packages/document/main-doc/docs/en/tutorials/first-app/c01-start.mdx, packages/document/main-doc/docs/en/tutorials/first-app/c03-css.mdx, packages/document/main-doc/docs/en/tutorials/first-app/c04-routes.mdx, packages/document/main-doc/docs/en/tutorials/first-app/c05-loader.mdx, packages/document/main-doc/docs/en/tutorials/first-app/c06-model.mdx, packages/document/main-doc/docs/en/tutorials/first-app/c07-container.mdx, packages/document/main-doc/docs/zh/tutorials/first-app/c01-start.mdx, packages/document/main-doc/docs/zh/tutorials/first-app/c03-css.mdx, packages/document/main-doc/docs/zh/tutorials/first-app/c04-routes.mdx, packages/document/main-doc/docs/zh/tutorials/first-app/c05-loader.mdx, packages/document/main-doc/docs/zh/tutorials/first-app/c06-model.mdx, packages/document/main-doc/docs/zh/tutorials/first-app/c07-container.mdx
The old api is not working anymore. Dicebear updated their api format. 
N/A.
=> docs: fix broken dicebear avatar api url

.github/workflows/integration-test-Linux.yml, pnpm-lock.yaml, tests/integration/module/fixtures/build/resolve/false/browser-false/package.json, tests/integration/module/fixtures/build/resolve/false/index.ts, tests/integration/module/fixtures/build/resolve/false/package.json
This PR introduces two changes:
- Use self-hosted runner for Linux integration tests
- Simply the `﻿resolve/false.test.ts` to see if they improve in Windows.
---
And there contains two case in the most failed ci recently:
- `module/build/resolve/false.test.ts` in windows.
- timeout in linux
(I think there's a 70% chance that the issue is **not** caused by nx.)
Regardless, let's proceed in trying to solve this problem
=> refactor: simpify `false.test.ts`

.github/workflows/integration-test-Linux.yml
Noticed that some dependencies are missing from our Linux machine: https://github.com/web-infra-dev/modern.js/actions/runs/6649078621/job/18067041899#step:12:21
=> chore: use github runner for integration test CI

.changeset/healthy-brooms-travel.md, packages/document/main-doc/docs/en/tutorials/first-app/c05-loader.mdx, packages/document/main-doc/docs/zh/tutorials/first-app/c05-loader.mdx
docs(main-doc): 导出 LoaderData 类型 检查代码高亮
N/A
=> docs(main-doc): add missing LoaderData export

.changeset/warm-cups-cross.md, packages/builder/builder/src/plugins/fileSize.ts
当用户给 filename 给配置 query 的时候:
```ts
output: {
filename: {
js: `[name].[contenthash:8].js?version=1.0`,
},
},
```
这里 `asset.name` 会拿到带 query 的 name 值，但实际输出文件是不带 query 的。
BTW: webpack 本身支持 query 参数的:
https://webpack.js.org/configuration/output/#outputfilename
=> fix(builder): printFileSize throw err when set output.filename query

.changeset/eighty-beans-serve.md, packages/builder/builder-rspack-provider/src/plugins/manifest.ts, packages/builder/builder-webpack-provider/src/plugins/manifest.ts, packages/document/builder-doc/docs/en/config/output/enableAssetManifest.md, packages/document/builder-doc/docs/zh/config/output/enableAssetManifest.md
Should generate manifest correctly when enable SSR.
If the current project has multiple types of build artifacts, such as including SSR build artifacts, multiple manifest.json files will be generated.
- web artifact: `asset-manifest.json`
- node artifact: `asset-manifest-node.json`
=> fix(builder): should generate manifest correctly when enable SSR

.changeset/blue-jars-raise.md, packages/builder/plugin-image-compress/src/minimizer.ts
The same situation as pr: https://github.com/web-infra-dev/modern.js/pull/4988
=> fix(builder): plugin-image-compress can not work with filename query

.changeset/lazy-days-smoke.md, packages/builder/builder-shared/src/plugins/HtmlCrossOriginPlugin.ts, packages/builder/builder-shared/src/plugins/HtmlPreloadOrPrefetchPlugin/index.ts, tests/e2e/builder/cases/html/cross-origin/index.test.ts, tests/e2e/builder/cases/html/cross-origin/src/index.js, tests/e2e/builder/cases/html/html.test.ts, tests/e2e/builder/cases/performance/load-resource/index.test.ts
fix preload resource can't be used when crossOrigin attr does not match.
=> fix(builder): preload resource can't be used if crossOrigin attr not match

packages/document/main-doc/docs/zh/guides/topic-detail/generator/plugin/structure.md
=> docs: change error name

.changeset/lemon-clocks-look.md, packages/builder/builder-rspack-provider/src/index.ts, packages/builder/builder-shared/src/types/bundlerConfig.ts
=> fix(builder): export type of rspack config and add globalObject type

.changeset/proud-gifts-love.md, packages/solutions/module-tools/src/builder/dts/tsc.ts
Add buildOptions, '-b' means that Build one or more projects and their dependencies, if out of date.
=> fix(module-tools): add -b param to tsc when user add references

packages/solutions/app-tools/src/config/initialize/inits.ts
=> fix: default appicon should after user set

.changeset/moody-donkeys-film.md, packages/storybook/builder/src/plugin-storybook.ts
use default conditionNames for storybook, align with @storybook/react-webpack5
=> fix(storybook): use default conditionNames

.changeset/wet-beds-eat.md, packages/solutions/module-tools/src/builder/clear.ts
When we use references, we will add '--build' option, this will generate tsbuildinfo which need to be cleared.
=> fix(module-tools): use tsc --clean to clear the tsbuildinfo and d.ts

.changeset/strong-seas-wash.md, packages/runtime/plugin-runtime/src/ssr/serverRender/renderToString/buildHtml.ts, packages/runtime/plugin-runtime/src/ssr/serverRender/renderToString/entry.ts
we use split to replace it.
It unsafe that we need ensure the searchValue is single.
But it's fastest.
=> fix: if the second args of string.replace is a string, it would as RegExp. 

.changeset/tall-pugs-mix.md, packages/solutions/module-tools/package.json, packages/solutions/module-tools/src/utils/map.ts, pnpm-lock.yaml, tests/integration/module/fixtures/build/dts/tsconfig.json, tests/integration/module/fixtures/build/sourceMap/__snapshots__/sourceMap.test.ts.snap
Upgrade '@ampproject/remapping' to avoid this warn.
=> fix(module-tools): upgrade remapping version to 2.2.1

.changeset/metal-adults-begin.md, packages/cli/plugin-swc/src/index.ts, packages/cli/plugin-swc/tests/index.test.ts
fix function config overrides user extension config
fix function config return undefined causes final config to be undefined
=> fix(plugin-swc): should not override extensions when using function config

.changeset/early-chairs-obey.md, packages/builder/builder-webpack-provider/package.json, packages/builder/builder/package.json, packages/devtools/client/package.json, packages/devtools/client/plugins/ServiceWorkerCompilerPlugin.ts, packages/review/eslint-config-app/package.json, packages/runtime/plugin-testing/package.json, packages/server/utils/package.json, pnpm-lock.yaml
https://github.com/web-infra-dev/rsbuild/releases/tag/v0.2.3
=> chore: bump rsbuild to 0.2.3

.changeset/weak-pumas-guess.md, packages/server/core/src/plugin.ts, packages/server/server/src/server/devServer.ts
these two hooks are not used. so we can remove them, and developer won't need to use them later.
=> chore(server): remove useless server plugin hooks

packages/builder/uni-builder/src/index.ts, packages/builder/uni-builder/src/rspack/defaults.ts, packages/builder/uni-builder/src/rspack/index.ts, packages/builder/uni-builder/src/shared/constants.ts, packages/builder/uni-builder/src/shared/defaults.ts, packages/builder/uni-builder/src/shared/parseCommonConfig.ts, packages/builder/uni-builder/src/shared/plugins/runtimeChunk.ts, packages/builder/uni-builder/src/types.ts, packages/builder/uni-builder/src/webpack/defaults.ts, packages/builder/uni-builder/src/webpack/index.ts, packages/builder/uni-builder/tests/__snapshots__/default.test.ts.snap, pnpm-lock.yaml, tests/e2e/builder/cases/css/style-loader/index.test.ts, tests/e2e/builder/cases/decorator/latest/index.test.ts, tests/e2e/builder/cases/html/inject-false/index.test.ts, tests/e2e/builder/cases/inline-chunk/index.test.ts, tests/e2e/builder/cases/node-addons/index.test.ts, tests/e2e/builder/cases/output/externals/tests/index.test.ts, tests/e2e/builder/cases/output/rem/tests/index.test.ts, tests/e2e/builder/cases/progress/index.test.ts, tests/e2e/builder/cases/serve/index.test.ts, tests/e2e/builder/cases/sri/index.test.ts, tests/e2e/builder/cases/styled-component/index.test.ts, tests/e2e/builder/cases/stylus-rem/index.test.ts, tests/e2e/builder/cases/stylus/index.test.ts, tests/e2e/builder/cases/vue/index.test.ts, tests/e2e/builder/cases/vue2/index.test.ts, tests/e2e/builder/cases/web-worker/index.test.ts, tests/e2e/builder/package.json, tests/e2e/builder/scripts/shared.ts
fix uni-builder error and migrate some e2e test cases from modern builder to uni-builder
- fix enableInlineScripts & enableInlineStyles merge error
- compat entry params
- update RUNTIME_CHUNK_NAME
- fix html.faviconByEntries / ... undefined
- runtimeChunk is not related disableInlineRuntimeChunk configuration
=> fix(uni-builder): fix some cases and update e2e test cases

.changeset/funny-flowers-hunt.md, packages/server/server/src/server/devServer.ts, packages/server/server/src/server/devServerOld.ts, packages/toolkit/runtime-utils/src/node/fileReader.ts
webpack would write output to memory.
adapte webpack-dev-middleware.
=> fix: adapte webpack-dev-middleware disable write-to-disk

.changeset/silly-timers-knock.md, packages/solutions/module-tools/src/builder/clear.ts, packages/solutions/module-tools/src/types/dts.ts
In #5064 , we execa `tsc --build --clean`, the reason is that when we clean the output, we doesn't clean the .tsbuildinfo which generated by incremental build. 
But `tsc --build --clean` will bring two problems: 
- first, tsc --clean will remove the outputs by esbuild, tsc --clean only respect the project tsconfig.json, so this need that we should set `emitDeclarationOnly` in our tsconfig.
- second, we don't respect the incremental build. we delete the outputs for all projects.
Now we will respect the incremental, in the root project, we will clear the .tsbuildinfo, unless you close the clean func.
For the dependencies, we do nothing.
#5064
=> fix(module-tools): clear .tsbuildinfo before build instead of tsc --clean

.changeset/wise-pants-sparkle.md, packages/builder/plugin-swc/src/plugin.ts, packages/cli/plugin-bff/src/cli.ts, packages/document/builder-doc/docs/en/config/tools/bundlerChain.mdx, packages/document/builder-doc/docs/en/config/tools/rspack.md, packages/document/builder-doc/docs/en/config/tools/webpackChain.md, packages/document/builder-doc/docs/zh/config/tools/bundlerChain.mdx, packages/document/builder-doc/docs/zh/config/tools/rspack.md, packages/document/builder-doc/docs/zh/config/tools/webpackChain.md, packages/runtime/plugin-runtime/src/ssr/cli/index.ts, packages/solutions/app-tools/src/builder/shared/builderPlugins/adapterHtml.ts, packages/solutions/app-tools/src/builder/shared/builderPlugins/adapterSSR.ts, packages/storybook/builder/src/docgen/index.ts, packages/toolkit/utils/src/cli/constants/chainId.ts
builder CHAIN_ID will be replaced by Rsbuild CHAIN_ID, and some CHAIN_ID not support in rsbuild.
https://github.com/web-infra-dev/rsbuild/blob/main/packages/shared/src/chain.ts#L62
=> chore: remove Rsbuild unsupported CHAIN_ID

packages/builder/uni-builder/src/rspack/index.ts, packages/builder/uni-builder/src/shared/parseCommonConfig.ts, packages/builder/uni-builder/src/types.ts, packages/builder/uni-builder/src/webpack/index.ts, tests/e2e/builder/scripts/shared.ts
unify and simplify uni-builder config type, because only three configurations not support in rspack mode.
=> chore: unify uni-builder config type

.changeset/olive-brooms-admire.md, packages/document/module-doc/docs/en/api/config/build-config.mdx, packages/document/module-doc/docs/zh/api/config/build-config.mdx, packages/solutions/module-tools/src/builder/build.ts, packages/solutions/module-tools/src/builder/clear.ts, packages/solutions/module-tools/src/builder/dts/tsc.ts, packages/solutions/module-tools/src/constants/build.ts, packages/solutions/module-tools/src/types/config/index.ts, packages/solutions/module-tools/src/types/dts.ts, tests/integration/module/fixtures/build/dts/dts-bundleless.ts, tests/integration/module/fixtures/build/dts/dts.test.ts
1. support enableTscBuild
2. only log error about config when tsc build
3. prefer to use declarationDir over outDir in tsc
=> feat(module-tools): add enableTscBuild option and improve tsc build

.changeset/three-windows-move.md, packages/document/module-doc/docs/en/api/config/build-config.mdx, packages/document/module-doc/docs/zh/api/config/build-config.mdx, packages/solutions/module-tools/src/builder/feature/asset.ts, packages/solutions/module-tools/src/builder/feature/redirect.ts, tests/integration/module/fixtures/build/asset/svgr/bundle.config.ts, tests/integration/module/fixtures/build/asset/svgr/bundleless.config.ts, tests/integration/module/fixtures/build/asset/svgr/src/namedExport.js
Move loadSvgr to getAssetContents, and support svgr with url-loader
=> feat(module-tools): support svgr with url-loader

.changeset/mighty-fireants-tan.md, packages/solutions/module-tools/src/utils/dts.ts, tests/integration/module/fixtures/build/dts/dts.test.ts, tests/package.json
=> fix(module-tools): add extension for matchPath when process dts alias

.changeset/violet-eels-pull.md, packages/server/server/src/dev-tools/dev-middleware/hmr-client/index.ts
https://github.com/webpack/webpack/blob/2e5fc25fa791e5cd2d51c3b98993666f54800c52/test/hotPlayground/index.js#L21-L22
=> fix(hmr-client): reload when the updated modules are empty

.changeset/hungry-donkeys-complain.md, packages/server/plugin-server/package.json, packages/server/plugin-server/src/cli.ts, packages/solutions/app-tools/src/plugins/serverBuild.ts, pnpm-lock.yaml
- we should compile server dir only server/cache exsits by default
=> fix: server dir compile only server/cache exsits

.changeset/fluffy-games-trade.md, packages/builder/plugin-vue/src/index.ts, packages/builder/plugin-vue/tests/__snapshots__/index.test.ts.snap
The flag was added in the recent [Vue 3.4 release](https://github.com/vuejs/core/blob/main/CHANGELOG.md#340-slam-dunk-2023-12-29).
https://vuejs.org/api/compile-time-flags.html#VUE_PROD_HYDRATATION_MISMATCH_DETAILS
=> feat(plugin-vue): set default vue hydration mismatch flag

.changeset/early-doors-join.md, packages/server/prod-server/src/server/modernServer.ts
**How to repeat?**
```shell
npm run build 
npm run serve
```
When run build, the server/cache.ts would compiler to dist/server/cache.js.
So the load path must be distDir in production.
=> fix(prod-server): ssr cache cant work in serve command

.changeset/fluffy-icons-invite.md, packages/server/prod-server/package.json, packages/server/prod-server/src/libs/render/ssr.ts, pnpm-lock.yaml
The isbot@4.x need nodev18
So we downgrade it to 3.x
=> fix: downgrade isbot to 3.x

packages/document/builder-doc/docs/en/shared/builder.md, packages/document/builder-doc/docs/en/shared/rsbuild.md, packages/document/builder-doc/docs/zh/shared/builder.md, packages/document/builder-doc/docs/zh/shared/rsbuild.md, packages/document/main-doc/docs/en/guides/get-started/glossary.mdx, packages/document/main-doc/docs/zh/guides/get-started/glossary.mdx
since we use rsbuild instead of modern builder, we need update builder glossary.
Related PR: https://github.com/web-infra-dev/modern.js/pull/5168
=> docs: update builder glossary

.changeset/ten-camels-retire.md, packages/solutions/module-tools/package.json, pnpm-lock.yaml
when remove `@modern-js/eslint-config`, we will get:
so we need add this deps
=> chore(module-tools): add babel dep, because @svgr/plugin-jsx depended after prebundle

.changeset/tough-avocados-nail.md, packages/builder/uni-builder/src/types.ts, pnpm-lock.yaml
fix the type error when the version of rsbuild/shared that the plugin depends on is different from that of uni-builder.
the uni-builder plugins type should be looser to avoid type mismatch.
=> fix(uni-builder): make the plugins type looser to avoid type mismatch

package.json, pnpm-lock.yaml
fix rspack-ecosystem-ci error: the rspack version in rspack-provider should not be override
https://github.com/web-infra-dev/rspack-ecosystem-ci/actions/runs/7509196132/job/20445962320
=> fix(CI): avoid rspack version in rspack-provider overrides by rspack-ecosystem-ci

.changeset/tender-carrots-compete.md, packages/builder/uni-builder/src/index.ts, packages/builder/uni-builder/src/shared/parseCommonConfig.ts, packages/builder/uni-builder/src/types.ts, packages/document/builder-doc/docs/en/config/experiments/sourceBuild.md, packages/document/builder-doc/docs/zh/config/experiments/sourceBuild.md
Support passing source build options via `experiments.sourceBuild` config, this allows user to set `resolvePriority` in some cases.
https://rsbuild.dev/plugins/list/plugin-source-build#options
=> feat(uni-builder): support passing source build options

.changeset/odd-dryers-compare.md, packages/solutions/module-tools/src/builder/esbuild/index.ts, packages/solutions/module-tools/src/error.ts
And then we found that our error stack is complete. The ModuleBuildError has extended the esbuild error stack.
=> perf(module-tools): log error detail which may throw by own plugin and complete error stack

.changeset/short-gifts-search.md, packages/server/create-request/package.json, pnpm-lock.yaml
fix encoding resolve warning when call node-fetch in build, `encoding` is a peerDeps in `node-fetch`:
=> fix: resolve warning 'Failed to resolve encoding' in node-fetch

.changeset/ninety-ducks-count.md, packages/builder/uni-builder/src/shared/devServer.ts, packages/builder/uni-builder/src/shared/parseCommonConfig.ts, packages/builder/uni-builder/src/types.ts, packages/builder/uni-builder/tests/__snapshots__/parseConfig.test.ts.snap, packages/builder/uni-builder/tests/parseConfig.test.ts
fix tools.devServer client options not works in rsbuild server
- update devServer.client.path default value as : `/webpack-hmr`
- tools.devServer client / liveReload / hot not works in rsbuild server
=> fix(uni-builder): tools.devServer client options not works

.changeset/clean-pumpkins-guess.md, package.json, packages/builder/uni-builder/src/shared/parseCommonConfig.ts, packages/builder/uni-builder/tests/__snapshots__/parseConfig.test.ts.snap, packages/server/server/package.json, pnpm-lock.yaml
=> fix(uni-builder): should print https url when enable dev.https

packages/devtools/client/src/components/Devtools/FrameBox.module.scss, packages/devtools/client/src/components/Devtools/FrameBox.tsx, packages/devtools/client/src/components/Loading/Icon.module.scss, packages/devtools/client/src/components/Loading/Icon.tsx, packages/devtools/client/src/components/Loading/Loading.module.scss, packages/devtools/client/src/components/Loading/Loading.tsx, packages/devtools/client/src/components/Loading/index.ts, packages/devtools/client/src/entries/client/routes/loading.tsx
Apply loading animation for each tab when suspensing.
=> feat(devtools): apply loading animation for each tab

.changeset/six-dolls-begin.md, packages/builder/uni-builder/src/shared/parseCommonConfig.ts, packages/builder/uni-builder/tests/__snapshots__/parseConfig.test.ts.snap
rsbuild server.publicDir is a new feature (not very stable...), and it repeat with app-tools `/config/public`
=> fix(uni-builder): disable default publicDir

.changeset/mighty-parrots-walk.md, packages/server/prod-server/src/libs/render/ssrCache/index.ts, packages/server/prod-server/src/libs/render/ssrCache/manager.ts, packages/server/prod-server/src/libs/render/type.ts
fix(prod-server): ssr renderResult maybe is a undefined, when use react-router redirect.
it's need handle in ssr cache.
=> fix(prod-server): ssr renderResult maybe is a undefined

packages/document/builder-doc/docs/en/config/source/include.md, packages/document/builder-doc/docs/zh/config/source/include.md
since modern.js use rsbuild, the source.include default value is same as rsbuild.
https://rsbuild.dev/config/source/include
=> docs: update source.include introduce

.changeset/quick-files-refuse.md, packages/devtools/client/src/components/Devtools/Button.module.scss, packages/devtools/client/src/components/Devtools/Button.tsx, packages/devtools/client/src/components/Devtools/Capsule.module.scss, packages/devtools/client/src/components/Devtools/Capsule.tsx, packages/devtools/client/src/components/Devtools/FrameBox.tsx, packages/devtools/client/src/components/Devtools/Puller.tsx, packages/devtools/client/src/components/Visible.tsx, packages/devtools/client/src/entries/client/routes/layout.tsx, packages/devtools/client/src/entries/client/routes/react/[tab]/page.tsx, packages/devtools/client/src/entries/client/routes/react/state.ts, packages/devtools/client/src/entries/client/routes/state.tsx, packages/devtools/client/src/entries/mount/index.tsx, packages/devtools/client/src/entries/mount/state.ts, packages/devtools/client/src/types/rpc.ts, packages/devtools/client/src/utils/draggable.ts, packages/devtools/client/src/utils/promise.ts
https://github.com/web-infra-dev/modern.js/assets/18379948/e88f514a-3b97-47cf-b370-11e5e64175f0
=> feat(devtools): pull up react devtools element inspector from capsule

packages/document/main-doc/docs/en/apis/app/commands.mdx, packages/document/main-doc/docs/en/configure/app/output/disable-node-polyfill.mdx, packages/document/main-doc/docs/en/guides/advanced-features/compatibility.mdx, packages/document/main-doc/docs/en/guides/advanced-features/optimize-bundle.mdx, packages/document/main-doc/docs/en/guides/advanced-features/rspack-start.mdx, packages/document/main-doc/docs/en/guides/basic-features/css.mdx, packages/document/main-doc/docs/en/guides/get-started/tech-stack.mdx, packages/document/main-doc/docs/zh/apis/app/commands.mdx, packages/document/main-doc/docs/zh/configure/app/output/disable-node-polyfill.mdx, packages/document/main-doc/docs/zh/guides/advanced-features/compatibility.mdx, packages/document/main-doc/docs/zh/guides/advanced-features/optimize-bundle.mdx, packages/document/main-doc/docs/zh/guides/basic-features/css.mdx, packages/document/main-doc/docs/zh/guides/get-started/tech-stack.mdx
Modern.js app-tools's builder has been upgraded to rsbuild, so some builder link should update to rsbuild link.
=> docs: use rsbuild link instead of builder

packages/devtools/client/src/components/Devtools/Capsule.tsx, packages/devtools/client/src/components/Devtools/Puller.tsx, packages/devtools/client/src/entries/client/routes/react/[tab]/page.tsx, packages/devtools/client/src/entries/client/routes/react/state.ts, packages/devtools/client/src/utils/react-devtools.ts
No longer treat the react devtools bridge as a globally shared singleton object, but rather as disposable to avoid events triggered after bridge closed.
=> feat(devtools): use wallAgent to replace disposable bridge

.changeset/tall-elephants-cross.md, packages/solutions/module-tools/src/builder/feature/asset.ts, tests/integration/module/fixtures/build/asset/asset.test.ts
Module tools should not remove SVG viewBox attribute, we can add some default SVGR options as `@modern-js/app-tools` and Rsbuild, see https://github.com/web-infra-dev/rsbuild/blob/main/packages/plugin-svgr/src/index.ts#L31-L47.
This change can fix the Rspress copy icon.
- Current:
- Fixed:
=> fix(module-tools): should not remove SVG viewBox attribute

.changeset/lovely-dolls-hang.md, packages/builder/uni-builder/src/webpack/plugins/styledComponents.ts, packages/builder/uni-builder/tests/__snapshots__/styledComponents.test.ts.snap, pnpm-lock.yaml, tests/e2e/builder/cases/externalHelpers/index.test.ts, tests/e2e/builder/cases/html/minify/index.swc.test.ts, tests/e2e/builder/cases/lodash/index.swc.test.ts, tests/e2e/builder/cases/performance/removeConsole.swc.test.ts, tests/e2e/builder/cases/source/plugin-import/index.webpack.test.ts, tests/e2e/builder/cases/styled-component/index.swc.test.ts, tests/e2e/builder/cases/swc/index.swc.test.ts, tests/e2e/builder/cases/top-level-await/index.swc.test.ts, tests/e2e/builder/package.json, tests/integration/storybook/package.json
- fix(uni-builder): styled-components not works when use webpack swc-plugin (styled-components depends swc/babel rule)
- use rsbuild swc-plugin instead of modern-js/builder-plugin-swc in test cases
=> fix(uni-builder): styled-components not works when use webpack swc-plugin

.changeset/fuzzy-ants-destroy.md, packages/generator/generator-cases/tests/index.test.ts, packages/generator/generator-common/src/locale/en.ts, packages/generator/generator-common/src/locale/zh.ts, packages/generator/generator-common/src/newAction/common/index.ts, packages/generator/generator-common/src/newAction/mwa/index.ts, packages/generator/generator-common/tests/newAction.test.ts, packages/generator/generators/rspack-generator/src/index.ts, packages/generator/generators/rspack-generator/src/locale/en.ts, packages/generator/generators/rspack-generator/src/locale/index.ts, packages/generator/generators/rspack-generator/src/locale/zh.ts
just one line of configuration to start rspack build, no need to use run new function.
```diff
plugins: [
appTools({
+     bundler: 'experimental-rspack',
}),
],
});
```
=> chore: remove enable-rspack action in generator run new

packages/document/main-doc/docs/en/configure/app/source/enable-async-entry.mdx
Fix missing translation in English doc:
https://modernjs.dev/en/configure/app/source/enable-async-entry.html
=> docs: fix missing translation in English doc

packages/builder/uni-builder/src/shared/parseCommonConfig.ts, packages/builder/uni-builder/tests/__snapshots__/parseConfig.test.ts.snap
fix: missing security config when parse rsbuild config, and `security.nonce` is also missing in rsbuild doc...
=> fix(uni-builder): missing security config

tests/e2e/builder/cases/performance/removeConsole.test.ts, tests/e2e/builder/cases/top-level-await/index.swc.test.ts
https://github.com/web-infra-dev/modern.js/actions/runs/7720734842/job/21046104474
=> fix: some builder e2e cases unstable when distPath conflict

.changeset/old-masks-flash.md, packages/solutions/app-tools/src/config/default.ts
Remove the default include glob for TS checker, this glob will cause some errors to not be output correctly.
After removing the default include glob, TS checker now runs according to the include and exclude rules in tsconfig file.
=> fix(ts-checker): remove default include glob

.github/workflows/test-macOS.yml, .github/workflows/vitest-macOS.yml
Using new M1 macOS runner to make CI faster.
see: https://github.com/web-infra-dev/rsbuild/pull/1486
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
=> test(workflow): using new M1 macOS runner

.changeset/stupid-rules-judge.md, packages/builder/uni-builder/src/shared/parseCommonConfig.ts, packages/builder/uni-builder/tests/__snapshots__/default.test.ts.snap, packages/builder/uni-builder/tests/__snapshots__/parseConfig.test.ts.snap, packages/builder/uni-builder/tests/__snapshots__/postcssLegacy.test.ts.snap
css sourcemap should be true when dev or user specify
=> fix(uni-builder): missing css sourcemap when dev

packages/document/module-doc/docs/en/plugins/official-list/plugin-vue.mdx, packages/document/module-doc/docs/zh/plugins/official-list/plugin-vue.mdx
=> docs(module-tools): add empty line to fix warning in plugin vue

.changeset/eleven-pants-hope.md, packages/builder/uni-builder/src/webpack/plugins/babel.ts, packages/builder/uni-builder/src/webpack/plugins/tsLoader.ts, packages/builder/uni-builder/tests/__snapshots__/babel.test.ts.snap, packages/builder/uni-builder/tests/__snapshots__/default.test.ts.snap, packages/builder/uni-builder/tests/__snapshots__/react.test.ts.snap, packages/builder/uni-builder/tests/__snapshots__/styledComponents.test.ts.snap, packages/builder/uni-builder/tests/__snapshots__/tsLoader.test.ts.snap, tests/integration/source-code-build/app-ts-loader/modern.config.ts, tests/integration/source-code-build/app-ts-loader/tsconfig.json
Apply babel preset-react when using ts-loader.
This change aligns the ts-loader behavior with Modern.js >= 1.30.0 (which will register @babel/preset-react by default).
=> fix(uni-builder): apply babel preset-react when using ts-loader

.changeset/ninety-apricots-rhyme.md, packages/builder/uni-builder/src/webpack/plugins/tsLoader.ts, packages/builder/uni-builder/tests/__snapshots__/tsLoader.test.ts.snap, packages/builder/uni-builder/tests/tsLoader.test.ts
in some edge case, uni-builder inserts babel plugin repeatedly  when using tsLoader and the user config babel as follow:
```
tools: {
babel: {
plugins: [
[
'babel-plugin-import',
{
libraryName: 'xxx-components',
libraryDirectory: 'es',
style: true,
},
],
],
},
},
};
```
this makes babel.plugin have the same address in js rule and ts rule.
=> fix(uni-builder): repeatedly insert babel plugin when using tsLoader

packages/devtools/client/src/components/Devtools/Capsule.tsx, packages/devtools/client/src/components/Devtools/Puller.tsx, packages/devtools/client/src/entries/client/routes/layout.tsx, packages/devtools/client/src/entries/client/routes/overview/page.module.scss, packages/devtools/client/src/entries/client/routes/overview/page.tsx, packages/devtools/client/src/entries/client/routes/react/[tab]/page.tsx, packages/devtools/client/src/entries/client/routes/state.tsx, packages/devtools/client/src/types/rpc.ts
https://github.com/web-infra-dev/modern.js/assets/18379948/72cba57a-3a7d-4133-a9ce-e18ef8ef700f
Refactor the existing `DevtoolsPuller` into `Puller` to support a common deep link. The URL hash that starts with `#/__devtools` will now open the devtools by default. It can also navigate to deeper routes of the devtools using subpaths. Helpful for debugging and community promotion.
```
- Why not sync location of devtools to deeplink?
- It may cause unexpected behaviour of the host application.
- Why not remove deep link hash from url?
- Same as above, it also makes deep links not transparent to users.
```
=> feat(devtools): refactor DevtoolsPuller into Puller to support common deep link

.changeset/kind-apples-joke.md, packages/server/core/src/plugin.ts, packages/server/prod-server/src/libs/render/index.ts, packages/server/prod-server/tests/render.test.ts
Add `handleSSRFallback` hook for server plugin to self-defined fallback logger or metrics.
=> feat(prod-server): add handleSSRFallback hook

.changeset/tasty-humans-train.md, packages/builder/uni-builder/src/rspack/plugins/babel-post.ts
set babel-post plugin order to 'post', so other plugins can modify babel config in modifyBundlerChain 'default order'
see: https://rsbuild.dev/plugins/dev/hooks#order-field
=> chore(uni-builder): set babel-post plugin order to post

packages/devtools/client/src/entries/client/routes/doctor/page.tsx, packages/devtools/client/src/entries/client/routes/state.tsx, packages/devtools/plugin/src/rpc/index.ts
- Resolve and display package version.
- Compatible with web doctor implementation.
- Remove the file size indicator from the doctor page to prevent users from being confused by the development output file size.
- Show formatted time cost.
=> feat(devtools/doctor): compatible with web doctor implementation

.changeset/silent-candles-teach.md, packages/solutions/module-tools/src/builder/feature/redirect.ts, packages/solutions/module-tools/src/utils/outExtension.ts, tests/integration/module/fixtures/build/autoExtension/type-module/modern.config.ts, tests/integration/module/fixtures/build/autoExtension/type-module/type-module.test.ts
When type is module and format is esm, we will generate js files, but it can not running in node, because node esm need file extension.
=> fix(module-tools): add js extension when pkg type is module

packages/document/module-doc/docs/en/guide/basic/use-module-doc.mdx, packages/document/module-doc/docs/zh/guide/basic/use-module-doc.mdx
=> docs(react-docgen): add some limit and more info

.changeset/tough-icons-help.md, packages/solutions/module-tools/lib/types.d.ts
The default export type depends on the asset.svgr.exportType config, it can be a string or a ReactComponent, so we need to use `any` here.
the same as app-tools: https://github.com/web-infra-dev/modern.js/pull/3688
=> feat(module-tools): improve svg typing for SVGR

packages/devtools/kit/package.json, packages/devtools/kit/src/rsdoctor.ts, pnpm-lock.yaml
Install @rsdoctor/utils & @rsdoctor/types as production dependencies.
=> feat(devtools/doctor): install @rsdoctor/utils & @rsdoctor/types as production dependencies

packages/cli/uni-builder/src/shared/plugins/fallback.ts
Avoid import JSON_REGEX from `@rsbuild/shared`, as it will be removed soon.
https://github.com/web-infra-dev/rsbuild/pull/1662
=> chore(uni-builder): avoid import JSON_REGEX

packages/server/core/src/base/adapters/node/bff.ts, tests/integration/bff-koa/modern.config.ts
=> fix: bff.enableHandleWeb should support no prefix route

.changeset/mighty-bears-rescue.md, packages/server/prod-server/src/libs/render/ssr.ts, packages/server/prod-server/src/libs/render/ssrCache/index.ts, packages/server/prod-server/src/libs/render/ssrCache/manager.ts, packages/server/prod-server/src/server/modernServer.ts, packages/server/prod-server/src/type.ts, packages/server/prod-server/tests/ssrCache.test.ts, pnpm-lock.yaml, tests/integration/ssr/package.json, tests/integration/ssr/tests/base.test.ts
=> feat: support x-render-cache response headers when open ssr cache

.changeset/silent-apricots-play.md, packages/cli/uni-builder/src/shared/plugins/postcssLegacy.ts, packages/cli/uni-builder/tests/__snapshots__/postcssLegacy.test.ts.snap, packages/cli/uni-builder/tests/postcssLegacy.test.ts
Should allow tools.postcss to override the builtin plugins of uni-builder.
=> fix(uni-builder): allow tools.postcss to override the plugins

.changeset/silly-zebras-cross.md, packages/cli/plugin-tailwind/package.json, packages/cli/uni-builder/package.json, packages/solutions/module-tools/package.json, pnpm-lock.yaml, scripts/prebundle/package.json, tests/integration/tailwindcss/fixtures/tailwindcss-v2/package.json, tests/integration/tailwindcss/fixtures/tailwindcss-v3-js-config/package.json, tests/integration/tailwindcss/fixtures/tailwindcss-v3-merge-config/package.json, tests/integration/tailwindcss/fixtures/tailwindcss-v3-ts-config/package.json, tests/integration/tailwindcss/fixtures/tailwindcss-v3/package.json, tests/integration/tailwindcss/fixtures/twin.macro-v2/package.json, tests/integration/tailwindcss/fixtures/twin.macro-v3/package.json
- Fix `@modern-js/uni-builder` missing postcss peer dependency.
- Bump postcss version and do not pin to a fixed version.
=> fix(uni-builder): missing postcss peer dependency

.changeset/tidy-comics-appear.md, packages/cli/uni-builder/src/rspack/plugins/babel-post.ts, tests/integration/basic-app/tests/index.test.ts
cacheIdentifier is an addition config and it should ignore when we check isBabelConfigModified.
=> fix(uni-builder): should not apply babel-loader when use rspack build

.changeset/wicked-melons-boil.md, packages/cli/uni-builder/package.json, packages/cli/uni-builder/src/shared/parseCommonConfig.ts, packages/document/builder-doc/docs/en/config/html/templateParameters.md, packages/document/builder-doc/docs/en/config/html/templateParametersByEntries.md, packages/document/builder-doc/docs/zh/config/html/templateParameters.md, packages/document/builder-doc/docs/zh/config/html/templateParametersByEntries.md, pnpm-lock.yaml
html.templateParametersByEntries value should merged with the default parameters (same as html.parameters object): 
https://rsbuild.dev/config/html/template-parameters#object-usage
=> fix(uni-builder): html.templateParametersByEntries should merge with default value

packages/document/builder-doc/docs/en/config/html/favicon.md, packages/document/builder-doc/docs/en/config/html/faviconByEntries.md, packages/document/builder-doc/docs/en/config/html/inject.md, packages/document/builder-doc/docs/en/config/html/injectByEntries.md, packages/document/builder-doc/docs/en/config/html/meta.md, packages/document/builder-doc/docs/en/config/html/metaByEntries.md, packages/document/builder-doc/docs/en/config/html/template.md, packages/document/builder-doc/docs/en/config/html/templateByEntries.md, packages/document/builder-doc/docs/en/config/html/title.md, packages/document/builder-doc/docs/en/config/html/titleByEntries.md, packages/document/builder-doc/docs/zh/config/html/favicon.md, packages/document/builder-doc/docs/zh/config/html/faviconByEntries.md, packages/document/builder-doc/docs/zh/config/html/inject.md, packages/document/builder-doc/docs/zh/config/html/injectByEntries.md, packages/document/builder-doc/docs/zh/config/html/meta.md, packages/document/builder-doc/docs/zh/config/html/metaByEntries.md, packages/document/builder-doc/docs/zh/config/html/template.md, packages/document/builder-doc/docs/zh/config/html/templateByEntries.md, packages/document/builder-doc/docs/zh/config/html/title.md, packages/document/builder-doc/docs/zh/config/html/titleByEntries.md
some html.xxxByEntries configurations are deprecated, should use the function usage of `favicon` instead.
=> docs: add deprecated warning for html.xxxByEntries

.changeset/wise-pianos-film.md, packages/cli/uni-builder/src/shared/plugins/splitChunk.ts
should use currentConfig overrides uni-builder inner cacheGroups if the cacheGroups name is exist.
=> fix(uni-builder): splitChunks.overrides not effective for inner cacheGroups

package.json, packages/document/builder-doc/docs/en/config/output/disableFilenameHash.md, packages/document/builder-doc/docs/en/config/output/enableLatestDecorators.md, packages/document/builder-doc/docs/zh/config/output/disableFilenameHash.md, packages/document/builder-doc/docs/zh/config/output/enableLatestDecorators.md, packages/document/main-doc/docs/en/configure/app/output/filename-hash.mdx, packages/document/main-doc/docs/en/configure/app/source/decorators.mdx, packages/document/main-doc/docs/zh/configure/app/output/filename-hash.mdx, packages/document/main-doc/docs/zh/configure/app/source/decorators.mdx, pnpm-lock.yaml
output.filenameHash and source.decorators also can be used in modern.js
https://rsbuild.dev/zh/config/source/decorators
https://rsbuild.dev/zh/config/output/filename-hash
=> docs: add rsbuild filenameHash & decorators configuration

.github/workflows/update-rsbuild.yml
`update-rsbuild-snapshot` failed in CI
https://github.com/web-infra-dev/modern.js/actions/runs/8173091592/job/22372655812
=> fix(workflow): remove update-rsbuild-snapshot step

.changeset/good-hats-grin.md, packages/toolkit/utils/src/cli/prettyInstructions.ts
should print `http://[::1]:8080/` instead of `http://::1:8080/`
=> fix(server): print ipv6 url correctly

.changeset/healthy-terms-wait.md, packages/solutions/module-tools/src/builder/feature/swc.ts, tests/integration/module/fixtures/build/target/es5-mjs.config.ts, tests/integration/module/fixtures/build/target/target.test.ts
Fix `target: 'es5'` not work for mjs chunks.
https://github.com/web-infra-dev/rsbuild/issues/1804
=> fix(module-tools): target es5 not work for mjs chunks

.changeset/dull-fireants-vanish.md, package.json, packages/cli/uni-builder/src/shared/devServer.ts, packages/cli/uni-builder/src/shared/parseCommonConfig.ts, packages/cli/uni-builder/src/shared/plugins/antd.ts, packages/cli/uni-builder/src/types.ts, packages/cli/uni-builder/tests/__snapshots__/babel.test.ts.snap, packages/cli/uni-builder/tests/__snapshots__/default.test.ts.snap, packages/cli/uni-builder/tests/__snapshots__/parseConfig.test.ts.snap, packages/cli/uni-builder/tests/__snapshots__/postcssLegacy.test.ts.snap, packages/cli/uni-builder/tests/__snapshots__/react.test.ts.snap, packages/cli/uni-builder/tests/__snapshots__/styledComponents.test.ts.snap, packages/server/server/src/server/devServer.ts, packages/server/server/src/types.ts, pnpm-lock.yaml
Move transformToRsbuildServerOptions method from modern.js server to uni-builder parseCommonConfig stage.
So users can modify Rsbuild server config in Rsbuild modifyRsbuildConfig hook, and the modern.js server does not need to care about some rsbuild server configs.
=> feat(server): support modify rsbuild server config in rsbuild hook

.changeset/brave-dragons-serve.md, packages/server/create-request/package.json
修复@modern-js/create-request中types文件指向不存在的index.d.ts文件
=> fix(create-request): fix incorrect types path

packages/devtools/client/src/entries/client/routes/layout.data.tsx, packages/devtools/client/src/entries/client/routes/storage.preset/page.tsx, packages/devtools/kit/package.json, packages/devtools/kit/src/node.ts, packages/devtools/kit/src/runtime.ts, packages/devtools/kit/src/server.ts, packages/devtools/kit/src/storage-preset.ts, packages/devtools/plugin/package.json, packages/devtools/plugin/src/cli.ts, packages/devtools/plugin/src/options.ts, packages/devtools/plugin/src/rpc/index.ts, packages/devtools/plugin/src/types/config.ts, packages/devtools/plugin/src/types/index.ts, packages/devtools/plugin/src/utils/config.ts, pnpm-lock.yaml, tests/integration/devtools/modern.config.ts, tests/integration/devtools/modern.devtools.json, tests/integration/devtools/src/prelude.css
- Extract typings of storage preset to `@modern-js/devtools-kit`.
- `DevtoolsOptions` no longer inherits from `DevtoolsConfig`.
- New interface `StoragePresetContext` for internal usages, replacing the previous `StoragePresetOptions`.
- New tab page `storage/preset` for stub.
- WIP: Use hono to implement an HTTP server instead of doing it manually.
=> feat(devtools/storage-preset): improve typings

.changeset/ninety-dragons-care.md, packages/cli/core/tests/mergeConfig.test.ts, packages/toolkit/utils/src/cli/config.ts
We should overrides `server.baseUrl` when user set it as `['/a', '/b']`.
=> fix: we should override server.baseUrl when merge it

packages/server/core/src/base/middlewares/customServer/base.ts, packages/server/core/src/base/middlewares/customServer/context.ts, packages/server/core/src/base/middlewares/customServer/index.ts, tests/integration/server-hook/response/server/index.ts, tests/integration/server-hook/response/tests/index.test.ts
=> fix: afterMatch & afterRender share a common Context

packages/devtools/client/src/components/Breadcrumbs.tsx, packages/devtools/client/src/entries/client/routes/context/layout.tsx, packages/devtools/client/src/entries/client/routes/headers/layout.tsx, packages/devtools/client/src/entries/client/routes/layout.module.scss, packages/devtools/client/src/entries/client/routes/layout.tsx, packages/devtools/client/src/entries/client/routes/overview/layout.tsx, packages/devtools/client/src/entries/client/routes/overview/page.tsx, packages/devtools/client/src/entries/client/routes/pages/layout.module.scss, packages/devtools/client/src/entries/client/routes/pages/layout.tsx, packages/devtools/client/src/entries/client/routes/pages/page.module.scss, packages/devtools/client/src/entries/client/routes/pages/page.tsx, packages/devtools/client/src/entries/client/routes/react/[tab]/page.tsx, packages/devtools/client/src/entries/client/routes/storage.preset/layout.tsx, packages/devtools/client/src/entries/client/routes/storage.preset/page.module.scss, packages/devtools/client/src/entries/client/routes/storage.preset/page.tsx, tests/integration/devtools/modern.devtools.json
- Refactor root layout, allowing sub-routes to have their own scrollable/non-scrollable layout.
- Styling storage preset page.
- Fix: breadcrumb normalization failed when getting an array.
- TODO: Mess layout of loading animation.
=> feat(devtools/client): refactor root layout & styling storage preset page

packages/devtools/client/src/entries/client/routes/layout.data.tsx, packages/devtools/client/src/entries/client/routes/storage.preset/layout.config.ts, packages/devtools/client/src/entries/client/routes/storage.preset/page.module.scss, packages/devtools/client/src/entries/client/routes/storage.preset/page.tsx
- Details panel.
- TODO: Mess of loading animation layout.
- TODO: Watch on changes of config files.
- TODO: Details panel for `Current Storage`.
=> feat(devtools): details panel of storage preset page

.changeset/dull-melons-tickle.md, packages/toolkit/utils/src/cli/prettyInstructions.ts
We should support node v14.17.6
But node v14.17.6 don't support require('node:xx')
=> fix: remove node: prefix

.changeset/poor-pandas-share.md, packages/solutions/module-tools/src/builder/feature/asset.ts, packages/solutions/module-tools/src/builder/feature/redirect.ts
Fix https://github.com/web-infra-dev/modern.js/pull/5108/files#diff-9e8d633690bde6a43076949c999e876036a958d232f685a3dc42e6f7ff1f57c2R97
=> fix(module-tools): only invoke svgr in load hook

.changeset/hungry-turkeys-kiss.md, packages/generator/generators/upgrade-generator/src/index.ts
Since mdoern.js 2.46.0, builder plugin is no longer maintained,should use Rsbuild plugin instead.
=> fix(generator): do not bump builder deps when use upgrade command

packages/document/module-doc/docs/en/api/config/build-config.mdx, packages/document/module-doc/docs/en/guide/advance/copy.md, packages/document/module-doc/docs/en/guide/basic/modify-output-product.md, packages/document/module-doc/docs/zh/api/config/build-config.mdx, packages/document/module-doc/docs/zh/guide/advance/copy.md, packages/document/module-doc/docs/zh/guide/basic/modify-output-product.md
in module docs, all anchor link are lowercase.
=> docs: fix error anchor link

packages/server/core/src/base/adapters/node/bff.ts, packages/server/core/src/base/adapters/node/hono.ts, packages/server/core/src/base/adapters/node/loadServer.ts, packages/server/core/src/base/adapters/node/middlewares/serverManifest.ts, packages/server/core/src/base/adapters/node/middlewares/templates.ts, packages/server/core/src/base/index.ts, packages/server/core/src/base/middlewares/customServer/base.ts, packages/server/core/src/base/middlewares/customServer/context.ts, packages/server/core/src/base/middlewares/monitor.ts, packages/server/core/src/base/middlewares/renderHandler/index.ts, packages/server/core/src/base/serverBase.ts, packages/server/core/src/core/hono.ts, packages/server/core/src/core/plugin.ts, packages/server/core/src/core/server.ts, packages/solutions/app-tools/src/types/index.ts
=> fix: re-export type from core/server

.changeset/three-peas-fly.md, packages/server/core/src/base/middlewares/customServer/index.ts, packages/server/core/src/base/middlewares/renderHandler/render.ts
=> fix: new server should return 404 when can't found html template

.changeset/famous-years-sell.md, packages/cli/uni-builder/src/shared/parseCommonConfig.ts, packages/cli/uni-builder/src/types.ts
Related to https://github.com/web-infra-dev/rsbuild/issues/2091.
=> fix(uni-builder): modernjs should extend "ua" type in output.polyfill

.changeset/new-tigers-jam.md, packages/server/core/src/base/middlewares/customServer/index.ts
=> fix: server middleware ctx status should be set when return response

packages/document/builder-doc/docs/en/shared/rspackPrecautions.md, packages/document/builder-doc/docs/zh/shared/rspackPrecautions.md
Update the Rspack precautions documentation. Since Rspack already supports new tree shaking and is aligned with webpack, we can remove some precautions here.
=> docs: update Rspack precautions

.changeset/two-bananas-run.md, packages/solutions/app-tools/src/config/default.ts
No need to emit assets for SSR bundles, use the `output.emitAssets` option of Rsbuild to ignore assets for node target.
https://rsbuild.dev/config/output/emit-assets
=> fix: no need to emit assets for SSR bundles

.changeset/slow-years-reply.md, packages/document/module-doc/docs/en/api/config/build-config.mdx, packages/document/module-doc/docs/zh/api/config/build-config.mdx
~~To align with the behavior on document and most other tools' `define` convention.~~
align `define` description to actual behavior
=> docs(module-doc): align `define` description to actual behavior

.changeset/friendly-maps-smell.md, packages/server/core/src/base/adapters/node/middlewares/serverManifest.ts
ModuleFederation renderBundle is Promise , but swc can not transform dynamic import in cjs normally.
previous
```js
const results = await Promise.allSettled([
Promise.resolve().then(() => __toESM(require(loaderBundlePath))),
Promise.resolve().then(() => __toESM(require(renderBundlePath)))
]);
// __toESM(require(renderBundlePath)).then() will throw error : 'Method Promise.prototype.then called on incompatible receiver #<Promise>'
```
=> fix: swc can not transform dynamic import in cjs normally

.changeset/good-cheetahs-wink.md, packages/server/core/src/base/adapters/node/middlewares/serverManifest.ts
- require bundle maybe failed, so we need use try..catch
- the serverManifest middleware is only use in node.js, so we can use `require` directly
=> fix: require bundle maybe failed

.changeset/six-ads-talk.md, packages/cli/plugin-swc/package.json, pnpm-lock.yaml
Fix `@modern-js/plugin-swc` missing `@rsbuild/core` peer dep.
This PR can ensure the `@rsbuild/plugin-swc` resolves to the correct `@rsbuild/core`.
=> fix(plugin-swc): missing `@rsbuild/core` peer dep

.changeset/moody-jobs-grow.md, packages/cli/uni-builder/package.json, packages/cli/uni-builder/src/shared/plugins/manifest.ts, pnpm-lock.yaml
I just released rspack-manifest-plugin stable version.
https://github.com/rspack-contrib/rspack-manifest-plugin
=> chore(uni-builder): use rspack-manifest-plugin stable version

.changeset/thin-singers-remember.md, packages/document/module-doc/docs/en/plugins/official-list/plugin-vue.mdx, packages/document/module-doc/docs/zh/plugins/official-list/plugin-vue.mdx
The documentation about the vue plugin in modern.js seems a bit old, some configurations are not placed in buildConfig. I encountered this problem and fixed it.
https://modernjs.dev/module-tools/plugins/official-list/plugin-vue.html#%E6%B3%A8%E5%86%8C%E6%8F%92%E4%BB%B6
=> docs: update buildConfig in plugin-vue docs

.changeset/happy-ducks-fly.md, packages/server/core/src/base/middlewares/renderHandler/render.ts
=> fix: render should handle api route when open enableHandleWeb

.changeset/happy-fans-roll.md, packages/runtime/plugin-runtime/src/ssr/cli/index.ts
=> fix: useLoader should run normally in csr when webpack build

.changeset/orange-readers-grow.md, packages/storybook/builder/package.json, pnpm-lock.yaml
=> chore: downgrade webpack-dev-middleware to 6.1.3 for support node 16

.changeset/stale-sheep-scream.md, packages/runtime/plugin-garfish/src/cli/utils.ts, pnpm-lock.yaml
pass props to modern custom bootstrap [doc link]
(https://modernjs.dev/guides/concept/entries.html#%E8%87%AA%E5%AE%9A%E4%B9%89-bootstrap)
Effect
Users can get props from master app at the beginning to init something
Before
After
=> fix: pass props to custom bootstrap

.github/workflows/integration-test-Linux.yml, .github/workflows/integration-test-Windows.yml, .github/workflows/test-builder-e2e.yml, .github/workflows/test-garfish-e2e.yml
When we update the rsbuild version we want to run more tests, so we can find some bugs early.
=> CI: should run more tests when branch is feat-update-rsbuild-*

packages/document/builder-doc/docs/en/api/plugin-hooks.mdx, packages/document/builder-doc/docs/en/config/tools/rspack.md, packages/document/builder-doc/docs/en/config/tools/webpack.md, packages/document/builder-doc/docs/en/config/tools/webpackChain.md, packages/document/builder-doc/docs/zh/api/plugin-hooks.mdx, packages/document/builder-doc/docs/zh/config/tools/rspack.md, packages/document/builder-doc/docs/zh/config/tools/webpack.md, packages/document/builder-doc/docs/zh/config/tools/webpackChain.md
`getCompiledPath` is a deprecated API of Rsbuild, we do not want users to depend on the internal packages of Rsbuild.
=> docs: remove getCompiledPath of builder

packages/devtools/client/src/components/Error/Fallback.tsx, packages/devtools/client/src/entries/client/routes/state.tsx, packages/devtools/client/src/entries/client/routes/storage/preset/[id]/page.data.ts, packages/devtools/client/src/entries/client/routes/storage/preset/[id]/page.tsx, packages/devtools/client/src/entries/client/routes/storage/preset/layout.data.ts, packages/devtools/client/src/entries/client/routes/storage/preset/layout.tsx, packages/devtools/client/src/entries/client/routes/storage/preset/shared.ts
- Highlight active storage presets (by comparing key-value records).
- Fallback and redirect to `/storage/preset` when delete the current preset and route `/storage/preset/{id}`.
- Reduce the `delayDuration` of display to tooltip component.
Pending by https://github.com/web-infra-dev/modern.js/pull/5748.
=> feat(devtools): highlight active storage presets

tests/e2e/builder/cases/check-syntax/index.test.ts
When we only specify Rspack target "web", the builder runtime code does not degrade.
=> fix: correct check-syntax test case script

packages/devtools/client/package.json, packages/devtools/client/src/components/Breadcrumbs.tsx, packages/devtools/client/src/components/Devtools/Capsule.tsx, packages/devtools/client/src/components/Devtools/FrameBox.tsx, packages/devtools/client/src/components/Error/FeatureDisabled.tsx, packages/devtools/client/src/components/NavLink.tsx, packages/devtools/client/src/components/PairsEditor/Editor.tsx, packages/devtools/client/src/components/PairsEditor/Pair.tsx, packages/devtools/client/src/components/ServerRoute/Base.tsx, packages/devtools/client/src/components/Theme.tsx, packages/devtools/client/src/components/Toast.tsx, packages/devtools/client/src/entries/client/routes/layout.tsx, packages/devtools/client/src/entries/client/routes/overview/page.tsx, packages/devtools/client/src/entries/client/routes/pages/page.tsx, packages/devtools/client/src/entries/client/routes/storage/preset/[id]/page.tsx, packages/devtools/client/src/entries/client/routes/storage/preset/layout.tsx, packages/devtools/client/src/entries/client/routes/storage/preset/page.tsx, packages/devtools/client/src/utils/theme.ts, pnpm-lock.yaml
- Bump `@radix-ui/themes` to v3 and migrate usage cases.
- Refactor theme management.
Changes mainly affect:
- packages/devtools/client/src/utils/theme.ts
- packages/devtools/client/src/components/Theme.tsx
- packages/devtools/client/src/components/Devtools/Capsule.tsx
=> feat(devtools): migrate to `@radix-ui/themes@3`

.changeset/wise-paws-sleep.md, packages/devtools/kit/src/promise.ts
- Fix: `traversePromises` should not traverse null values
=> fix(devtools): `traversePromises` should not traverse null values

.changeset/good-zoos-knock.md, packages/runtime/plugin-runtime/src/ssr/serverRender/renderToStream/bulidTemplate.before.ts, packages/runtime/plugin-runtime/src/ssr/serverRender/renderToStream/renderToPipe.ts, packages/runtime/plugin-runtime/src/ssr/serverRender/renderToStream/template.ts, pnpm-lock.yaml
* support stream to string 
* support server ender styled components
styled components not support stream ssr , so if users use it , it need to downgrade to string ssr 
https://github.com/styled-components/styled-components/issues/3658
=> feat: support stream to string & support server ender styled components

packages/cli/uni-builder/src/rspack/index.ts, packages/cli/uni-builder/src/types.ts, packages/cli/uni-builder/src/webpack/plugins/lazyCompilation.ts, packages/document/builder-doc/docs/en/config/experiments/lazyCompilation.md, packages/document/builder-doc/docs/en/guide/advanced/rspack-start.mdx, packages/document/builder-doc/docs/zh/config/experiments/lazyCompilation.md, packages/document/builder-doc/docs/zh/guide/advanced/rspack-start.mdx
modern.js `experiments.lazyCompilation` will map to rsbuild `dev.lazyCompilation` in rspack mode.
https://github.com/web-infra-dev/rsbuild/pull/2454
=> chore: experiments.lazyCompilation can be used in rspack

.changeset/spicy-lies-look.md, packages/server/core/src/base/middlewares/renderHandler/ssrCache.ts
=> fix: redablestream should not be locked, when stream transfer

.changeset/clean-masks-repair.md, packages/document/module-doc/docs/en/guide/basic/use-module-doc.mdx, packages/document/module-doc/docs/zh/guide/basic/use-module-doc.mdx
docs(module-tools-docs): correcting the name of the document product added to .gitignore
The name of the packaged product is `doc_build`, not `docs_build`.
=> docs(module-tools-docs): correcting the name of the document product added to .gitignore

.changeset/eighty-worms-jump.md, packages/server/core/package.json, packages/server/core/src/utils/serverConfig.ts, packages/server/core/tests/utils/serverConfig.test.ts, pnpm-lock.yaml
- deepmerge-ts can't run in node v16.2.0
=> [hotfix]fix: use ts-deepmerge instead of deepermge-ts

.changeset/afraid-clocks-kick.md, packages/runtime/plugin-garfish/src/cli/index.ts
It seems that rspack behavior is aligned with webpack, and this configuration should not be added.
=> fix: not specify externalsType in rspack mode

.changeset/friendly-dingos-guess.md, packages/solutions/app-tools/src/index.ts
bug in #5861 .
move the `analyze` module to `plugins/analyze` but not modify the path in restart hook.
=> fix(app-tools): error when restart app

.changeset/light-deers-greet.md, packages/runtime/plugin-garfish/src/cli/utils.ts
- add slash to garfish basename prefix if not exist
if use <Router> Component, the slash will auto add by react-router
but in modern.js, we use `createBrowserRouter`, maybe it's a bug in react-router ?
=> chore(router): add slash to basename if not exist

.changeset/poor-rings-breathe.md, packages/devtools/plugin/src/plugins/watcher.ts
The client defination property `api.context.def` should be accessed after `api.setupFramework()`. Otherwise, which maybe cause watcher plugin resolving a wrong `modern.runtime.json` filename.
=> fix(devtools): resolve storage preset config file

.changeset/strange-terms-pull.md, packages/runtime/plugin-runtime/src/router/cli/entry.ts, pnpm-lock.yaml, tests/integration/custom-file-system-entry/modern.config.ts, tests/integration/custom-file-system-entry/package.json, tests/integration/custom-file-system-entry/src/custom/layout.tsx, tests/integration/custom-file-system-entry/src/custom/page.tsx, tests/integration/custom-file-system-entry/tests/index.test.ts, tests/integration/custom-file-system-entry/tests/tsconfig.json, tests/integration/custom-file-system-entry/tsconfig.json
=> fix: fix router info error when use custom file system routes entry

.changeset/kind-forks-rush.md, packages/server/server/src/dev.ts, packages/server/server/src/helpers/repack.ts, tests/integration/routes/src/three/routes/user/layout.tsx
=> fix(ssr): hmr problem with ssr when using rspack

.changeset/bright-adults-wonder.md, packages/server/plugin-server/package.json, packages/server/plugin-server/src/runtime/assets/assets.ts, packages/server/plugin-server/src/runtime/assets/node.ts, packages/server/plugin-server/src/runtime/assets/worker.ts, packages/server/plugin-server/src/runtime/node.ts, packages/server/plugin-server/src/runtime/worker.ts, packages/server/plugin-server/tests/assets.test.ts, pnpm-lock.yaml
=> feat(server): support getting assets on the server

.changeset/sour-cows-visit.md, packages/document/main-doc/docs/en/guides/advanced-features/ssr/cache.mdx, packages/document/main-doc/docs/zh/guides/advanced-features/ssr/cache.mdx, packages/server/core/src/plugins/render/ssrCache.ts, packages/toolkit/types/server/utils.d.ts, tests/integration/ssr/fixtures/base/server/cache.ts, tests/integration/ssr/tests/base.test.ts
=> fix: cacheProvider support return false

.changeset/brown-cats-wait.md, packages/runtime/plugin-runtime/package.json, packages/runtime/plugin-runtime/src/core/server/stream/createReadableStream.ts, packages/runtime/plugin-runtime/src/core/server/stream/createReadableStream.worker.ts, packages/server/core/package.json, pnpm-lock.yaml
=> fix: isbot v4.x require nodev18, so we downgrade it into v3.x

.changeset/happy-cycles-occur.md, packages/cli/uni-builder/src/index.ts, packages/cli/uni-builder/src/shared/parseCommonConfig.ts, packages/cli/uni-builder/src/shared/plugins/fallback.ts, packages/cli/uni-builder/src/shared/utils.ts, packages/cli/uni-builder/src/types.ts, packages/cli/uni-builder/src/webpack/plugins/babel.ts, packages/cli/uni-builder/src/webpack/plugins/lazyCompilation.ts, packages/cli/uni-builder/src/webpack/plugins/minimize.ts, packages/cli/uni-builder/src/webpack/plugins/moduleScopes.ts, packages/cli/uni-builder/src/webpack/plugins/react.ts, packages/cli/uni-builder/src/webpack/plugins/styledComponents.ts, packages/cli/uni-builder/src/webpack/plugins/tsLoader.ts, packages/cli/uni-builder/tests/fallback.test.ts, packages/cli/uni-builder/tests/helper.ts, packages/storybook/builder/package.json, packages/storybook/builder/src/docgen/index.ts, packages/storybook/builder/src/plugin-storybook.ts, packages/storybook/builder/src/types.ts, pnpm-lock.yaml
Decouple some code from `@rsbuild/shared`, `@rsbuild/shared` will removed in rsbuild 1.0.0, we should remove all `@rsbuild/shared` deps in modern.js.
=> refactor(uni-builder): decouple with @rsbuild/shared

.changeset/chilled-yaks-turn.md, packages/runtime/plugin-runtime/src/cli/template.server.ts, packages/runtime/plugin-runtime/src/core/server/requestHandler.ts, packages/runtime/plugin-runtime/src/core/server/shared.ts, packages/runtime/plugin-runtime/src/core/server/stream/shared.ts, packages/runtime/plugin-runtime/src/core/server/string/index.ts, packages/runtime/plugin-runtime/src/core/server/string/prefetch.tsx, packages/runtime/plugin-runtime/tests/ssr/renderString.test.ts, packages/solutions/app-tools/src/builder/generator/createBuilderOptions.ts, tests/integration/ssr/fixtures/init/src/entry.server.jsx, tests/integration/ssr/fixtures/streaming/src/entry.server.tsx
=> fix: should use server-entires error & modify ServerRoot as ReactElement

.changeset/curvy-mangos-collect.md, packages/runtime/plugin-garfish/src/cli/index.ts, packages/runtime/plugin-garfish/src/global.d.ts, packages/runtime/plugin-garfish/src/runtime/provider.tsx, packages/runtime/plugin-garfish/src/runtime/render.tsx, packages/runtime/plugin-router-v5/package.json, tests/integration/garfish/app-dashboard/src/index.tsx
when in custom framework through custom metaName, @xx/plugin-garfish need use @xx/runtime package to use createRoot and render function, to avoid error when @xx/runtime existing more version.
=> feat: the runtime path use the meta alias in garfish provider

.changeset/few-fireants-punch.md, packages/cli/babel-preset/package.json, packages/cli/babel-preset/src/web.ts, packages/cli/babel-preset/tests/__snapshots__/web.test.ts.snap, packages/cli/uni-builder/package.json, packages/cli/uni-builder/tests/__snapshots__/babel.test.ts.snap, packages/cli/uni-builder/tests/__snapshots__/default.test.ts.snap, packages/cli/uni-builder/tests/__snapshots__/react.test.ts.snap, packages/cli/uni-builder/tests/__snapshots__/styledComponents.test.ts.snap, packages/cli/uni-builder/tests/__snapshots__/tsLoader.test.ts.snap, pnpm-lock.yaml
Fix the cjs extension should be js.
https://github.com/web-infra-dev/modern.js/pull/5946
=> fix(babel-preset): cjs extension should be js

.changeset/thirty-dancers-travel.md, packages/server/server/src/dev.ts, packages/server/server/src/helpers/mock.ts
- mockHandler should run before rsbuild middleware
- mockHandler can't hmr correctly
=> fix: mockHandler should run in dev-server correctly

.changeset/curvy-plants-fold.md, packages/storybook/builder/src/plugin-storybook.ts
strictPort is not required and will cause port occupation error.
https://github.com/rspack-contrib/storybook-rsbuild/pull/47
=> fix: storybook port occupied error

.changeset/dull-comics-attack.md, packages/cli/uni-builder/src/shared/plugins/environmentDefaults.ts, packages/cli/uni-builder/tests/__snapshots__/environment.test.ts.snap, packages/cli/uni-builder/tests/__snapshots__/styledComponents.test.ts.snap, packages/cli/uni-builder/tests/environment.test.ts
fix: match unexpected environment resources when artifact with the same name in different environments
https://github.com/web-infra-dev/rsbuild/issues/2956
=> fix: match unexpected environment resources

.changeset/chatty-lies-love.md, packages/server/core/src/plugins/customServer/index.ts, pnpm-lock.yaml, tests/integration/server-hook/new-middleware/package.json, tests/integration/server-hook/new-middleware/server/index.ts, tests/integration/server-hook/new-middleware/tests/index.test.ts
下个大版本去除旧版 middleware，当请求非 get 和 head 时
1. 不加 bff.enableHandleWeb 时，默认都被 createWebRequest 消费
2. 加 bff.enableHandleWeb 时，__loader 被 createWebRequest 消费，非 loader 不被消费
=> fix: new server middleware support get body, if request.method is post

.changeset/neat-starfishes-design.md, packages/runtime/plugin-garfish/package.json, packages/runtime/plugin-garfish/src/cli/code.ts, packages/runtime/plugin-garfish/src/cli/index.ts, pnpm-lock.yaml
remove the plugin api import from '@modern-js/core', but import from '@modern-js/plugin'
and add '@modern-js/plugin' to `@modern-js/plugin-garfish` dependencies.
=> fix: import plugin api from @modern-js/plugin instead @modern-js/core

.changeset/soft-oranges-fix.md, packages/runtime/plugin-garfish/jest.config.js, packages/runtime/plugin-garfish/src/cli/index.ts, packages/runtime/plugin-garfish/src/global.d.ts, packages/runtime/plugin-garfish/src/runtime/utils/apps.tsx, packages/runtime/plugin-router-v5/jest.config.js, packages/runtime/plugin-router-v5/src/cli/index.ts, packages/runtime/plugin-router-v5/src/global.d.ts, packages/runtime/plugin-router-v5/src/modern-app-env.d.ts, packages/runtime/plugin-router-v5/src/runtime/plugin.tsx, tests/jest-ut.config.js
=> feat: router v5 runtime plugin use meta path for runtime package

.changeset/friendly-donuts-bake.md, packages/solutions/app-tools/src/plugins/deploy/dependencies/index.ts
Limit the scope of the dependency packages to avoid `nft` finding the wrong dependencies.
=> fix(deploy): limit the scope of the find dependencies

.changeset/many-apples-attend.md, packages/runtime/plugin-garfish/package.json, packages/runtime/plugin-garfish/src/cli/template.ts, packages/runtime/plugin-garfish/src/runtime/index.ts, packages/runtime/plugin-garfish/src/runtime/tools.ts, tests/e2e/garfish/tests/dashboard.spec.ts, tests/e2e/garfish/tests/whole-process.spec.ts, tests/integration/garfish/app-table/src/entry.tsx
`@modern-js/plugin-garfish/runtime` will auto import Garfish runtime , so it can not import directly in subapp . 
Subapp usually will use `Boolean(window.__GARFISH__)` to check if in garfish env , and the prev action will make it not work.
=> fix(plugin-garfish): can not import garfish runtime directly which has sideffects

.changeset/strong-moose-wash.md, packages/server/server/src/createDevServer.ts, packages/solutions/app-tools/src/commands/dev.ts
- we should listen port outer `createDevServer`
- The listen host should be `0.0.0.0` default
=> fix: `createDevServer` should not listen port by default

package.json
now modern.js website is deploy in netlify..
so we add new script for main_doc and module_doc.
after rslib is release, we can remove these scripts.
https://deploy-preview-6005--modernjs-byted.netlify.app/
https://deploy-preview-6005--modernjs-byted.netlify.app/module-tools
=> chore(docs): add module tools to docs deploy

.changeset/popular-moose-join.md, packages/server/core/src/adapters/node/helper/loadConfig.ts, packages/server/core/src/types/config/output.ts, packages/server/server/src/createDevServer.ts
- Use `output.distPath.root` instead of output.path in server-core
=> fix: distPath should from output.distPath.root

.changeset/eighty-actors-try.md, packages/cli/plugin-data-loader/src/cli/loader.ts
fix: data loader support async-node target
=> fix(plugin-data-loader): data loader support async-node target

.changeset/mighty-mails-reply.md, packages/cli/uni-builder/src/index.ts, packages/cli/uni-builder/src/types.ts, packages/solutions/app-tools/src/types/config/index.ts
Fix type error when registering Rsbuild plugins in `builderPlugins`. We can use a loose type like Rsbuild (see https://github.com/web-infra-dev/rsbuild/pull/2875)
=> fix: type error when registering Rsbuild plugins

packages/document/module-doc/docs/en/api/config/build-config.mdx, packages/document/module-doc/docs/zh/api/config/build-config.mdx, packages/solutions/module-tools/src/builder/feature/redirect.ts, packages/solutions/module-tools/src/config/merge.ts, packages/solutions/module-tools/src/config/valid.ts, packages/solutions/module-tools/src/constants/build.ts, packages/solutions/module-tools/src/types/config/index.ts, pnpm-lock.yaml, tests/integration/module/fixtures/build/alias/alias.test.ts, tests/integration/module/fixtures/build/alias/module-id/modern.config.ts, tests/integration/module/fixtures/build/alias/module-id/package.json, tests/integration/module/fixtures/build/alias/module-id/src/index.js, tests/integration/module/fixtures/build/resolve/alias-error/alias.test.ts, tests/integration/module/fixtures/build/resolve/alias-error/object.config.ts, tests/integration/module/fixtures/build/resolve/alias-error/package.json, tests/integration/module/fixtures/build/resolve/alias-error/src/index.js, tests/integration/module/fixtures/build/resolve/alias/alias.test.ts, tests/integration/module/fixtures/build/resolve/alias/function.config.ts, tests/integration/module/fixtures/build/resolve/alias/object.config.ts, tests/integration/module/fixtures/build/resolve/alias/package.json, tests/integration/module/fixtures/build/resolve/alias/src/index.js
When we use `alias: { "react": "react-native"}` and want to redirect the module id, it failed.
We will get a result: "./react-native", but we want "react-native",
Now we use a new config, which names "resolve.alias" to support it.
In this config, we remove the default alias, and make it easier to understand.
=> feat(module-tools): add resolve.alias, to support redirect module id

packages/document/module-doc/docs/en/api/config/build-config.mdx, packages/document/module-doc/docs/zh/api/config/build-config.mdx, packages/solutions/module-tools/src/builder/esbuild/adapter.ts, packages/solutions/module-tools/src/builder/feature/swc.ts, packages/solutions/module-tools/src/config/merge.ts, packages/solutions/module-tools/src/constants/build.ts, packages/solutions/module-tools/src/types/config/index.ts, pnpm-lock.yaml, tests/integration/module/fixtures/build/loader/esbuild/modern.config.ts, tests/integration/module/fixtures/build/loader/esbuild/package.json, tests/integration/module/fixtures/build/loader/esbuild/src/index.js, tests/integration/module/fixtures/build/loader/loader.test.ts, tests/integration/module/fixtures/build/loader/swc/modern.config.ts, tests/integration/module/fixtures/build/loader/swc/package.json, tests/integration/module/fixtures/build/loader/swc/src/index.js
In fact, we can not custom loader. we need this ability.
But this is a experimental config, because loader can not overrides all scene, sometimes, we still use file exe to match the loader or config.
=> feat(module-tools): support custom loader

packages/document/module-doc/docs/en/api/config/build-config.mdx, packages/document/module-doc/docs/en/guide/advance/in-depth-about-build.md, packages/document/module-doc/docs/zh/api/config/build-config.mdx, packages/document/module-doc/docs/zh/guide/advance/in-depth-about-build.md, packages/solutions/module-tools/src/builder/esbuild/index.ts, packages/solutions/module-tools/src/types/config/index.ts, tests/integration/module/fixtures/build/hook/hook.test.ts, tests/integration/module/fixtures/build/hook/modern.config.ts, tests/integration/module/fixtures/build/hook/package.json, tests/integration/module/fixtures/build/hook/src/index.js
Before this change, our custom hook can only be applied before built-in hook, 
this can let hook apply after the built-in, and tranform or render the last result.
=> feat(module-tools): add applyAfterBuiltIn to control custom hook apply before or after built-in hook

packages/document/main-doc/docs/en/apis/app/commands.mdx, packages/document/main-doc/docs/zh/apis/app/commands.mdx, packages/solutions/app-tools/src/commands/index.ts
update inspect default output value, use relative path `./` instead of absolute output path  `/`
https://github.com/web-infra-dev/rsbuild/pull/3024
=> fix: update inspect default output value

.changeset/lovely-geese-kneel.md, packages/document/main-doc/docs/en/components/debug-app.mdx, packages/document/main-doc/docs/en/guides/get-started/quick-start.mdx, packages/document/main-doc/docs/en/guides/get-started/upgrade.mdx, packages/document/main-doc/docs/en/guides/troubleshooting/dependencies.mdx, packages/document/main-doc/docs/zh/components/debug-app.mdx, packages/document/main-doc/docs/zh/guides/get-started/quick-start.mdx, packages/document/main-doc/docs/zh/guides/get-started/upgrade.mdx, packages/document/main-doc/docs/zh/guides/troubleshooting/dependencies.mdx
Avoid confusing version number in the documentation. The in-house framework uses different major version.
=> docs: avoid confusing version number

.changeset/happy-rockets-cough.md, packages/cli/uni-builder/src/shared/plugins/htmlMinify.ts, packages/cli/uni-builder/tests/__snapshots__/default.test.ts.snap, packages/cli/uni-builder/tests/__snapshots__/minimize.test.ts.snap, packages/cli/uni-builder/tests/minimize.test.ts
should not apply html minify in production when disableMinimize. The default value of minify in `html-webpack-plugin` is true ('production' mode)
https://github.com/jantimon/html-webpack-plugin?tab=readme-ov-file#options
=> fix: should not minify html when disableMinimize in webpack mode

packages/document/main-doc/docs/zh/guides/basic-features/mock.mdx
resolve #5975.
correct '到处' to '导出'
=> chore(docs): typo in mock.mdx

.changeset/slimy-emus-clean.md, packages/runtime/plugin-runtime/src/core/server/requestHandler.ts, packages/server/core/src/plugins/customServer/index.ts, tests/integration/server-hook/new-middleware/server/index.ts, tests/integration/server-hook/new-middleware/tests/index.test.ts
- ssrContext get protocol from x-forwarded-proto first
- new server middleware support rewrite request
=> fix: ssrContext should get protocol from x-forwarded-proto first

.changeset/strong-walls-ring.md, packages/cli/plugin-swc/src/index.ts, pnpm-lock.yaml, tests/integration/swc/fixtures/config-function/modern.config.ts, tests/integration/swc/fixtures/config-function/package.json, tests/integration/swc/fixtures/config-function/src/bootstrap.css, tests/integration/swc/fixtures/config-function/src/index.js, tests/integration/swc/tests/config-function.test.ts
fix `tools.swc` function config not works when use plugin-swc.
=> fix(plugin-swc): tools.swc function config not works

tests/e2e/builder/cases/typescript/src/foo.ts
this case is used to test `const enum should compile correctly` in webpack mode.
=> fix: enum const case

.changeset/healthy-terms-yell.md, packages/runtime/plugin-runtime/src/cli/template.ts
if use `App.tsx`, when developer add `App.server.tsx`, the file is ignored.
=> fix: should remove extensions for entry file in real entry file

.changeset/twenty-dolls-remember.md, packages/runtime/plugin-runtime/src/core/server/requestHandler.ts, tests/integration/routes/src/three/routes/layout.tsx, tests/integration/routes/tests/index.test.ts
In the previous [PR] (https://github.com/web-infra-dev/modern.js/pull/5782), we supported the data loader return status code. At present, it has been removed here and restored support for this.
=> fix(runtime): status code should be controlled by data loader

.changeset/tricky-countries-live.md, packages/server/core/src/adapters/node/hono.ts, packages/server/core/src/adapters/node/node.ts
When res is piped,  res's headerSent will not be changed immediately, which will lead to error. The PR is to solve this misjudgment problem.
=> fix(server): if res was piped, res should be treated as sent

.changeset/hot-stingrays-sing.md, packages/server/core/src/plugins/customServer/base.ts
=> fix: custom server hook context request.path should carry query str

.changeset/short-rocks-knock.md, packages/server/core/src/serverBase.ts, packages/solutions/app-tools/src/commands/dev.ts, packages/solutions/app-tools/src/commands/serve.ts
Now we can get internalDirectory in server plugin context which return by `useAppContext()`
=> chore: add internal directory to server plugin context

.changeset/calm-dancers-mate.md, packages/cli/uni-builder/src/rspack/index.ts, packages/cli/uni-builder/src/types.ts, packages/document/builder-doc/docs/en/config/security/sri.md, packages/document/builder-doc/docs/zh/config/security/sri.md, tests/e2e/builder/cases/sri/index.test.ts
Support for `security.sri` when using Rspack, Rsbuild now provides partial support for SRI.
See: https://rsbuild.dev/config/security/sri
=> feat: support for security.sri when using Rspack

.changeset/fuzzy-ties-admire.md, packages/server/core/src/serverBase.ts, packages/solutions/app-tools/src/commands/dev.ts, packages/toolkit/types/server/context.d.ts
add type for `internalDirectory`.
fix the typo for `internalDircory` which miss 't'
=> fix: typo and type for internalDirectory in server appContext

.changeset/khaki-ravens-breathe.md, biome.json, packages/module/plugin-module-node-polyfill/src/globals.js
…fill
In umd scene, `import_console_browserify` depends on `util` and `util` depends on `import_browser`
so `import processBrowser from 'process/browser';` should import before `import console from 'console-browserify';`
=> fix(module-tools): import order in global.js of plugin node polyfill

.changeset/nasty-jars-dress.md, packages/runtime/plugin-runtime/src/core/server/string/index.ts, packages/runtime/plugin-runtime/tests/ssr/renderString.test.ts, packages/server/core/src/plugins/render/ssrCache.ts
=> fix: we should not cache ssr result when ssr fall error

.changeset/strong-hounds-attend.md, packages/runtime/plugin-runtime/src/router/runtime/plugin.tsx
- Add some empty node to sure the browser hydrate has same struct with ssr render.
=> fix: react's hook useId cause ssr hydrate failed

packages/document/main-doc/rspress.config.ts
enable lazyCompilation to improve doc dev startup performance. 
https://rsbuild.dev/config/dev/lazy-compilation
=> chore: enable lazyCompilation when doc dev

.changeset/spicy-tools-repair.md, packages/cli/core/src/createCli.ts
Correct the CLI process exit code, when executing ctrl + C, the exit code should be `0` instead of `1`.
- before:
- after:
=> fix(cli): correct process exit code

.changeset/hot-jobs-occur.md, packages/cli/uni-builder/src/shared/plugins/environmentDefaults.ts, packages/cli/uni-builder/src/shared/utils.ts, packages/cli/uni-builder/tests/__snapshots__/default.test.ts.snap, packages/cli/uni-builder/tests/__snapshots__/environment.test.ts.snap, packages/cli/uni-builder/tests/default.test.ts, packages/cli/uni-builder/tests/environment.test.ts, packages/runtime/plugin-runtime/src/cli/ssr/index.ts, packages/solutions/app-tools/tests/builder/__snapshots__/index.test.ts.snap
The `serviceWorker` environment is used for worker ssr, which is an inaccurate and misleading name.
=> chore: rename serviceWorker environment name to workerSSR

.changeset/tiny-fishes-smash.md, packages/cli/uni-builder/src/shared/devServer.ts
=> feat: support config dev.liveReload

.changeset/orange-carrots-study.md, packages/runtime/plugin-runtime/src/core/server/react/nossr/index.ts
1. When there is Streaming SSR + Suspense, React will hydrate in steps, so we remove the dependence on the closure value `csr`.
2. Make sure that the callback function of useEffect is only executed once.
=> fix: the problem of NoSSR with Suspense

.changeset/good-lobsters-glow.md, packages/cli/uni-builder/src/shared/parseCommonConfig.ts, packages/cli/uni-builder/tests/__snapshots__/minimize.test.ts.snap, packages/cli/uni-builder/tests/minimize.test.ts, packages/runtime/plugin-runtime/src/document/cli/index.ts
Fix html minify error when tools.htmlPlugin false, should not add modern htmlPlugin function options when user tools.htmlPlugin is false.
=> fix: html minify error when tools.htmlPlugin false

.changeset/cyan-taxis-try.md, packages/document/main-doc/docs/en/guides/topic-detail/_meta.json, packages/document/main-doc/docs/en/guides/topic-detail/model/quick-start.mdx, packages/document/main-doc/docs/zh/guides/topic-detail/_meta.json, packages/document/main-doc/docs/zh/guides/topic-detail/model/quick-start.mdx
Reduck is no longer under active development.
=> docs: add some deprecated warning in model docs and hidden generator

packages/document/main-doc/docs/en/configure/app/runtime/router.mdx, packages/document/main-doc/docs/en/configure/app/runtime/state.mdx, packages/document/main-doc/docs/zh/configure/app/runtime/router.mdx, packages/document/main-doc/docs/zh/configure/app/runtime/state.mdx
=> docs: improve router config docs

.changeset/violet-islands-sniff.md, packages/document/main-doc/docs/en/apis/app/runtime/ssr/no-ssr-cache.mdx, packages/document/main-doc/docs/zh/apis/app/runtime/ssr/no-ssr-cache.mdx, packages/runtime/plugin-runtime/src/core/server/index.ts, packages/runtime/plugin-runtime/src/core/server/react/index.ts, packages/runtime/plugin-runtime/src/core/server/react/no-ssr-cache/index.tsx, packages/server/core/src/plugins/render/ssrCache.ts, tests/integration/ssr/fixtures/base/src/routes/no-ssr-cache/layout.tsx, tests/integration/ssr/fixtures/base/src/routes/no-ssr-cache/page.tsx, tests/integration/ssr/tests/base.test.ts
Supports the`<NoSSRCache>` component, which determines whether to cache the server-side rendering of the current page.
=> Feat no ssr cache

.changeset/twelve-ghosts-ring.md, packages/document/main-doc/docs/en/apis/app/commands.mdx, packages/document/main-doc/docs/en/components/serve-command.mdx, packages/document/main-doc/docs/zh/apis/app/commands.mdx, packages/document/main-doc/docs/zh/components/serve-command.mdx
=> docs: serve command package component

.nvmrc
=> chore: remove `pnpm-version` in `.nvmrc`

.changeset/great-trains-run.md, packages/server/server/src/createDevServer.ts, packages/server/server/src/types.ts
In case the compiler is created in advance and the dev server is created later, the compiler option needs to be supported in [createDevServer](https://github.com/web-infra-dev/modern.js/blob/main/packages/server/server/src/createDevServer.ts#L11).
=> chore(server): add compiler option for createDevServer

.changeset/modern-feet-bake.md, packages/module/plugin-module-node-polyfill/src/index.ts, packages/module/plugin-module-node-polyfill/src/utils.ts, tests/integration/module/plugins/node-polyfill/node-polyfill.test.ts, tests/integration/module/plugins/node-polyfill/src/index.js
=> feat(module-plugin-polyfill): support polyfill Node.js builtin modules starting with node:

.changeset/angry-bats-own.md, packages/document/main-doc/docs/en/configure/app/output/copy.mdx, packages/document/main-doc/docs/zh/configure/app/output/copy.mdx
Link `output.copy` to Rsbuild instead of Rspack.
=> docs: link `output.copy` to Rsbuild

.changeset/spotty-mirrors-knock.md, packages/cli/uni-builder/src/shared/parseCommonConfig.ts, packages/cli/uni-builder/src/shared/plugins/devtools.ts, packages/cli/uni-builder/src/types.ts
=> fix(builder): `output.sourceMap` not work

.changeset/twenty-cycles-divide.md, packages/runtime/plugin-runtime/src/core/server/string/loadable.ts
before, we use for-in to match template many time, it would cost many system assets.
We can match all assets link one time.
=> fix(ssr): we match all asset directly, it can be more faster

.changeset/strange-comics-collect.md, packages/cli/plugin-ssg/src/server/index.ts
we should not listen `error` message in stdout data event.
This will lead to many misjudgments of normal logs.
=> fix: remove ssg stdout listener, only stderr

.changeset/nine-turkeys-hope.md, packages/solutions/app-tools/src/plugins/analyze/getFileSystemEntry.ts
=> fix: when the enableCustomEntry is set to true, the entry.tsx should be recognized first

.changeset/sweet-feet-warn.md, packages/server/core/src/adapters/node/helper/index.ts, packages/server/core/src/adapters/node/helper/utils.ts, packages/server/core/src/adapters/node/hono.ts, packages/server/core/src/adapters/node/node.ts, packages/server/prod-server/src/apply.ts, tests/package.json
1. handle the cases that res cannot be writable
2. add an env variable to control log
Currently, when using bff with koa.js framework when the socket is closed, it returns 404.
=> fix(server): handle the cases that res cannot be writable & add an env variable to control log

.changeset/weak-singers-destroy.md, packages/toolkit/runtime-utils/src/url.ts, packages/toolkit/runtime-utils/tests/url.test.ts, tests/package.json
=> fix(runtime-utils): the normalizePathname should handles multiple slashes correctly

packages/document/main-doc/package.json, packages/document/module-doc/docs/en/api/index.md, packages/document/module-doc/docs/zh/api/index.md, packages/document/module-doc/package.json, pnpm-lock.yaml
- bump rspress to 1.35.2
- fix overview page heading of module doc
=> fix: overview page heading of module doc

packages/server/server/src/dev-tools/watcher/statsCache.ts
After some deps being upgraded yesterday, there exists an error in qos https://github.com/web-infra-dev/web-infra-QoS/actions/runs/11560794413/job/32178422738
simply add `as any` to fix it.
=> fix: add any type to fix qos bff-koa case error

.changeset/seven-socks-compare.md, packages/runtime/plugin-runtime/src/router/runtime/DeferredDataScripts.node.tsx, packages/runtime/plugin-runtime/src/router/runtime/constants.ts
=> feat: splitting the code for _ROUTER_DATA initialisation

.changeset/flat-moles-think.md, packages/cli/plugin-tailwind/src/cli.ts, packages/cli/plugin-tailwind/src/config.ts
Reduce tailwindcss `hash()` overhead by passing config path to `tailwindcss()`.
See https://github.com/tailwindlabs/tailwindcss/issues/14229 for more details.
=> perf(plugin-tailwind): reduce tailwindcss `hash()` overhead

.changeset/gorgeous-bears-sit.md, README.md, README.zh-CN.md, packages/document/main-doc/docs/en/guides/get-started/introduction.mdx, packages/document/main-doc/docs/zh/guides/get-started/introduction.mdx
Modern.js is now focused on building the world-class full-stack React framework, and Modern.js Module will be deprecated in the future.
Our team has developed [Rslib](https://github.com/web-infra-dev/rslib) as the next-generation library development tool, and will soon provide a migration guide for Modern.js Module users soon.
Please note that the Modern.js Module packages and documentation will continue to be available. No new features are planned for the Modern.js Module, but we will continue to provide necessary bug fixes.
=> docs: remove Module from Modern.js introduction

packages/runtime/plugin-runtime/src/core/compatible.tsx, packages/runtime/plugin-runtime/src/core/context/runtime.ts, packages/runtime/plugin-runtime/src/core/types.ts, packages/runtime/plugin-runtime/src/index.ts
1. add `context` field in `useRuntimeContext` return value, the same as inhouse framework. 
2. add TSSRBaseContext for the `context` field.
3. remove useless export `BaseRuntimeContext`.
4. pickedContext should not be assigned extra field, so we remove `[key: string]: any` in TRuntimeContext, and use TRuntimeContext instead BaseTRuntimeContext.
=> feat: add useRuntimeContext api data structure

packages/runtime/plugin-runtime/src/core/context/runtime.ts, packages/runtime/plugin-runtime/src/router/runtime/plugin.node.tsx, packages/runtime/plugin-runtime/src/router/runtime/plugin.tsx
this field is only for inhouse framework, now we decoupling the implements
=> chore: remove router field in runtimeContext

packages/document/main-doc/docs/en/guides/get-started/tech-stack.mdx, packages/document/main-doc/docs/zh/guides/get-started/tech-stack.mdx
Correct the Vue link in tech stack docs page.
N/A.
=> docs: correct Vue link

packages/runtime/plugin-runtime/src/core/context/runtime.ts, packages/runtime/plugin-runtime/src/router/runtime/hooks.ts, packages/runtime/plugin-runtime/src/router/runtime/plugin.node.tsx, packages/runtime/plugin-runtime/src/router/runtime/plugin.tsx
1. remixRouter in browser router plugin is only for inhouse usage, now we refactor it, so we don't need it anymore.
2. remixRouter is still need in node router plugin, cause we need pass it to anther hook.(we can also use closure)
3. add comments for routes plugin
=> chore: remove remixRouter field context type declare and in browser router plugin

.changeset/small-toes-travel.md, packages/document/module-doc/docs/en/guide/intro/getting-started.mdx, packages/document/module-doc/docs/zh/guide/intro/getting-started.mdx
Add migration tip for Modern.js Module.
- https://github.com/web-infra-dev/modern.js/issues/6531
- https://github.com/web-infra-dev/modern.js/pull/6491
=> docs: add migration tip for Modern.js Module

packages/solutions/app-tools/src/new/compat/hooks.ts, packages/solutions/app-tools/src/new/compat/index.ts, packages/toolkit/plugin-v2/src/hooks.ts, packages/toolkit/plugin-v2/src/types/hooks.ts
=> feat: collect async hook support params and fix garfish test

.changeset/tasty-trees-begin.md, packages/solutions/app-tools/lib/types.d.ts
Update app-tools preset type definitions, reference `@rsbuild/core/types`, but there are some differences, such as svg.
=> feat(app-tools): update preset type definitions

.changeset/wet-trains-battle.md, packages/runtime/plugin-runtime/src/core/browser/index.tsx
now `getSSRData()` always return non-null SSR Data, so the runtime-plugin will always run into `hydrateRoot` logic.
=> fix: should only run hydrate when ssr

packages/runtime/plugin-runtime/src/router/runtime/plugin.node.tsx
before this MR, the error in loader will get 'undefined' error in logs.
=> fix: react router error is not Array but Object constructor

.changeset/selfish-seahorses-care.md, packages/document/module-doc/docs/en/guide/faq/basic.mdx, packages/document/module-doc/docs/zh/guide/faq/basic.mdx
Recommend using Rslib to reuse webpack plugins in the Modern.js Module FAQ.
=> docs: recommend using Rslib to reuse webpack plugins

.changeset/clever-rocks-enjoy.md, packages/cli/uni-builder/src/rspack/index.ts, packages/cli/uni-builder/src/webpack/index.ts, packages/cli/uni-builder/tests/__snapshots__/default.test.ts.snap, packages/cli/uni-builder/tests/default.test.ts
Uni-builder plugins should be registered earlier than user plugins.
The current uni-builder plugin is added through `addPlugins` after rsbuild is created. If other plugins are passed in through configuration, they will be registered and executed earlier than the uni-builder plugin.
=> fix: uni-builder plugins should be registered earlier than user plugins

.changeset/afraid-socks-jam.md, packages/cli/uni-builder/src/shared/parseCommonConfig.ts, packages/solutions/app-tools/src/config/default.ts, packages/toolkit/utils/src/cli/prettyInstructions.ts
Enable Rsbuild CLI shortcuts feature:
TODO: Modern.js does not support restart server and print urls yet. We need to:
- Unify the print URL logic of Rsbuild of Modern.js.
- Consider expose a `rsbuild.restartServer` API.
https://rsbuild.dev/config/dev/cli-shortcuts
=> feat(app-tools): enable Rsbuild CLI shortcuts

.changeset/funny-beds-arrive.md, packages/cli/uni-builder/src/webpack/plugins/babel.ts, packages/runtime/plugin-testing/src/base/config/transformer/babelTransformer.ts, packages/toolkit/utils/src/cli/is/project.ts
https://github.com/facebook/react/releases/tag/v16.14.0
=> feat: support automatic jsx runtime while using react@>=16.14.0

.changeset/modern-wolves-poke.md, packages/cli/uni-builder/src/rspack/index.ts, packages/cli/uni-builder/src/shared/parseCommonConfig.ts, packages/cli/uni-builder/src/shared/plugins/postcss.ts, packages/cli/uni-builder/src/webpack/index.ts, packages/cli/uni-builder/tests/__snapshots__/postcssLegacy.test.ts.snap, packages/cli/uni-builder/tests/postcssLegacy.test.ts, packages/document/main-doc/docs/en/configure/app/tools/lightningcss-loader.mdx, packages/document/main-doc/docs/en/configure/app/tools/postcss.mdx, packages/document/main-doc/docs/en/guides/basic-features/css/css.mdx, packages/document/main-doc/docs/en/guides/get-started/tech-stack.mdx, packages/document/main-doc/docs/zh/configure/app/tools/lightningcss-loader.mdx, packages/document/main-doc/docs/zh/configure/app/tools/postcss.mdx, packages/document/main-doc/docs/zh/guides/basic-features/css/css.mdx, packages/document/main-doc/docs/zh/guides/get-started/tech-stack.mdx
Modern.js supports using [Lightning CSS](https://lightningcss.dev/) to convert CSS code. This feature can be turned on by configuring `tools.lightningcssLoader`.
=> feat: support enable lightningcssLoader

.changeset/strange-crabs-walk.md, packages/server/core/src/plugins/customServer/index.ts, packages/server/core/src/plugins/render/index.ts, tests/integration/server-hook/new-middleware/server/modern.server.ts, tests/integration/server-hook/new-middleware/tests/index.test.ts
This PR fix the issue: 
when `render.middlewares` not empty, unstable middleware is not executed.
`render.middlewares` is a future feature, and is now used in some plugins.
=> fix: unstable_middlwares doesn't exec when render.middlewares not empty

.changeset/soft-spoons-greet.md, packages/server/core/src/adapters/node/plugins/resource.ts, packages/server/core/src/plugins/render/render.ts, packages/server/core/src/utils/entry.ts, packages/solutions/app-tools/src/plugins/analyze/getServerRoutes.ts, packages/solutions/app-tools/src/plugins/analyze/index.ts, packages/solutions/app-tools/src/plugins/analyze/utils.ts, tests/integration/ssg/fixtures/nested-routes/package.json, tests/integration/ssg/tests/nested-routes.test.ts
there is some issue in server routes when use ssg, this PR fix them:
1. should use routes in `route.json` when exec `serve` command instead of analysis filesystem, for ssg plugin will generate external routes.
> ssg plugin should use modifyServerRoutes to add new routes instead of rewrite `route.json`, we should refactor it in the future. But even we do this, we also should use `route.json` as serverRoutes in serve command for simulation the production environment.
2. now we get route templates by `route.entryName`, but ssg will create new page for same entry, so we should use entryName + urlPath as the unique key.
=> fix: should get server routes from route.json in serve command

.changeset/stupid-news-look.md, packages/document/main-doc/docs/en/apis/app/hooks/src/app.mdx, packages/document/main-doc/docs/zh/apis/app/hooks/src/app.mdx
=> feat: update doc routing link

packages/runtime/plugin-runtime/src/core/server/string/loadable.ts, packages/server/core/src/plugins/render/ssrRender.ts, packages/server/core/src/types/config/source.ts, packages/server/core/src/types/requestHandler.ts, pnpm-lock.yaml, tests/integration/ssr/fixtures/base-async-entry/modern.config.ts, tests/integration/ssr/fixtures/base-async-entry/package.json, tests/integration/ssr/fixtures/base-async-entry/src/modern-app-env.d.ts, tests/integration/ssr/fixtures/base-async-entry/src/routes/index.css, tests/integration/ssr/fixtures/base-async-entry/src/routes/layout.tsx, tests/integration/ssr/fixtures/base-async-entry/src/routes/page.tsx, tests/integration/ssr/fixtures/base-async-entry/tsconfig.json, tests/integration/ssr/tests/base-async-entry.test.ts
In this PR, we support preload entrypoint's assets when we enable async entry and use loadable.
and it's already support in React 18 Streaming SSR with React Lazy.
=> feat: support loadable with async entry

.changeset/tasty-ears-bake.md, packages/server/core/src/adapters/node/plugins/resource.ts
Now `getServerManifest` is running at middleware, so that after server inited, the first visit will need load all server bundles.
=> chore: getServerManifest should run first on prepare

.changeset/cool-cooks-sell.md, packages/solutions/app-tools/src/compat/hooks.ts, packages/solutions/app-tools/src/compat/index.ts, packages/solutions/app-tools/src/compat/utils.ts
Adds compatibility for Jest plugins hooks.
Due to the presence of multiple parameters in the jestConfig hook, the `transformHookParams` function add 
`isMultiple` flag to indicate whether the current parameter is multiple, ensuring correct function execution.
=> fix: compat jest plugin hooks

.changeset/purple-parrots-admire.md, packages/server/core/src/plugins/render/ssrCache.ts
before this PR, any SSR request which url has tail slash will be treat as same cache key.
it will cause page Infinite refresh with the logic in router runtime plugin.
this PR fix it.
=> fix: shoud not overrides cache when request has tail slash

.changeset/witty-hotels-collect.md, packages/cli/core/src/context.ts, packages/document/module-doc/docs/en/guide/basic/command-preview.md, packages/document/module-doc/docs/en/guide/basic/use-micro-generator.md, packages/document/module-doc/docs/zh/guide/basic/command-preview.md, packages/document/module-doc/docs/zh/guide/basic/use-micro-generator.md, packages/runtime/plugin-garfish/jest.config.js, packages/runtime/plugin-garfish/package.json, packages/runtime/plugin-garfish/src/cli/code.ts, packages/runtime/plugin-garfish/src/cli/index.ts, packages/runtime/plugin-garfish/tests/cli.test.tsx, packages/runtime/plugin-router-v5/package.json, packages/runtime/plugin-router-v5/src/cli/index.ts, packages/runtime/plugin-router-v5/tests/index.test.ts, packages/runtime/plugin-runtime/package.json, packages/runtime/plugin-runtime/src/cli/code.ts, packages/runtime/plugin-runtime/src/cli/index.ts, packages/runtime/plugin-runtime/src/cli/ssr/index.ts, packages/runtime/plugin-runtime/src/document/cli/index.ts, packages/runtime/plugin-runtime/src/router/cli/code/index.ts, packages/runtime/plugin-runtime/src/router/cli/code/templates.ts, packages/runtime/plugin-runtime/src/router/cli/handler.ts, packages/runtime/plugin-runtime/src/router/cli/index.ts, packages/runtime/plugin-runtime/src/state/cli/index.ts, packages/runtime/plugin-runtime/tests/document/cli.test.tsx, packages/solutions/app-tools/src/compat/index.ts, packages/solutions/app-tools/src/types/new.ts, packages/solutions/app-tools/src/utils/initAppContext.ts, pnpm-lock.yaml
migrate runtime cli plugin to new cli plugin
- @modern-js/runtime
- @modern-js/plugin-ssr
- @modern-js/plugin-router
- @modern-js/plugin-state
- @modern-js/plugin-document
- @modern-js/plugin-router-v5
- @modern-js/plugin-garfish
=> feat: migrate runtime cli plugin to new cli plugin

.changeset/young-trains-judge.md, packages/runtime/plugin-router-v5/src/runtime/plugin.tsx, packages/runtime/plugin-runtime/src/router/runtime/plugin.tsx, packages/runtime/plugin-runtime/src/router/runtime/types.ts, packages/server/core/src/plugins/render/render.ts, pnpm-lock.yaml
In the past, we supported server routing dynamic parameters:
```ts
{
server: {
routes: {
main: "/:id"
}
}
}
```
Then user can get the params from `useRuntimeContext().context.params`, and it will inject a script into the HTML
But this feature is not compatible with conventional routing, the script will be parsed in router runtime plugin and cause conventional routing render error. In this PR,  we remove the logic in route runtime plugin.
Now the user can still use this features in self-control route.
=> chore: remove server data parse in convention routes

.changeset/smart-lamps-shout.md, packages/solutions/app-tools/src/run/index.ts, packages/solutions/app-tools/src/types/new.ts, packages/toolkit/plugin-v2/src/types/plugin.ts
- CLI plugin setup function allow not define
- app tools AppToolsExtendContext type use interface
- app tools add NODE_ENV value before load config file
=> feat: adjust cli plugin type

packages/cli/uni-builder/src/webpack/index.ts
rsbuild already use html-webpack-plugin by default in webpack mode.
https://github.com/web-infra-dev/rsbuild/pull/4175
=> fix(uni-builder): no need to set html-webpack-plugin

.changeset/pretty-ravens-unite.md, packages/server/plugin-server/src/server.ts
In this PR, we support [unstableMiddleware](https://modernjs.dev/apis/app/runtime/web-server/unstable_middleware.html) hot reload.
Here we use a hack way, cause unstable middleware are only collect when the server init.
1. Create a new unstable middleware array in dev mode, the length will be more the original array.
2. Fill the new array, when the middleware is execute, if `storage.unstableMiddleware` has the same index function, it will be execute, otherwise execute `next()`
3. when the `storage.unstableMiddleware` is changed, the new unstable middleware array will execute the new function in `storage.unstableMiddleware`.
=> fix: support unstable middleware hot reload

.changeset/nine-cups-reply.md, packages/devtools/client/modern.config.ts
disable devtools's styledComponents build because it's not used.
fix rsbuild's eco-ci https://github.com/rspack-contrib/rsbuild-ecosystem-ci/actions/runs/12650068507/job/35247796431
=> chore(devtools): disable devtools's styledComponents build

.changeset/long-cycles-admire.md, packages/document/main-doc/docs/en/plugin/plugin-system/hook-list.mdx, packages/document/main-doc/docs/zh/plugin/plugin-system/hook-list.mdx, packages/solutions/app-tools/src/compat/hooks.ts, packages/solutions/app-tools/src/compat/utils.ts, packages/solutions/app-tools/src/index.ts, packages/solutions/app-tools/src/types/new.ts
=>  feat: deprecate beforeConfig hook

.changeset/slimy-rocks-mix.md, packages/server/core/src/plugins/customServer/index.ts, packages/server/core/src/plugins/render/index.ts, packages/server/core/src/plugins/render/render.ts, packages/server/core/src/types/render.ts, packages/server/core/src/types/server.ts, tests/integration/server-hook/router/modern.config.ts, tests/integration/server-hook/router/server/index.ts, tests/integration/server-hook/router/src/mobile/App.tsx, tests/integration/server-hook/router/src/pc/App.tsx, tests/integration/server-hook/router/tests/index.test.ts
Now, when user use `router.rewrite` in afterMatch hook, and the route pathname can matched multiple route, it's always return the first route.
In this PR, we fix the problem.
1. Set entryName to server context
2. Match the route first, and use entryName to find the true one.
=> fix: use entryName to ensure match the target route correctly

.changeset/afraid-walls-do.md, packages/runtime/plugin-runtime/src/core/compatible.tsx
The `getInitData` API is display in website docs. But it's missing on the runtimeContext.
This PR fix it.
=> fix: add getInitData api

.changeset/shy-trainers-brush.md, packages/solutions/app-tools/src/types/new.ts, packages/toolkit/plugin-v2/src/cli/context.ts, packages/toolkit/plugin-v2/src/cli/hooks.ts, packages/toolkit/plugin-v2/src/cli/run/create.ts, packages/toolkit/plugin-v2/src/types/cli/api.ts, packages/toolkit/plugin-v2/src/types/cli/context.ts, packages/toolkit/plugin-v2/src/types/cli/hooks.ts, packages/toolkit/plugin-v2/src/types/cli/plugin.ts
add extendBuildUtils type for CLIPluginExtends to support extend rsbuild modify config function
=> feat: cli plugin support extend build utils

.changeset/tricky-chairs-press.md, packages/cli/plugin-data-loader/src/cli/createRequest.ts, packages/cli/plugin-data-loader/src/runtime/errors.ts, packages/cli/plugin-data-loader/src/runtime/index.ts, packages/runtime/plugin-runtime/src/core/server/requestHandler.ts, packages/runtime/plugin-runtime/src/router/runtime/plugin.node.tsx, tests/integration/routes/src/three/routes/error/response/page.data.ts, tests/integration/routes/src/three/routes/error/response/page.tsx, tests/integration/routes/tests/index.test.ts
This PR is to unify the response logic of the Loader in SSR.
1. By default, `throw Error` or `throw new Response` in Data Loader, will catch by error boundary. 
2. Throw new Response can set the http code, Error will return 500 code, include uncaught error.
3. If `ssr.loaderFailureMode` is `clientRender`, both of `throw xxx` will be ignore in ssr render, and modern.js will request Data Loader in client again.
4. Return Response will not catch by error boundary, even if the http code is 5xx.
=> fix(data-loader): unify the response logic of the Loader in SSR

packages/server/core/src/plugins/render/ssrCache.ts
In #6649, we import `@modern-js/utils` in runtime package, it cause worker ssr failed.
So we remove it in this PR.
=> fix: @modern-js/utils cause worker ssr fail

.changeset/strange-donuts-bake.md, packages/runtime/plugin-runtime/src/core/server/stream/createReadableStream.ts
This PR support use styled-component in streaming SSR and the style will be auto added into HTML.
> styled-component docs: https://styled-components.com/docs/advanced#streaming-rendering
The docs only show the example for `renderToNodeStream`, seems not support `renderToPipeableStream`.
In fact, `interleaveWithNodeStream` is only do something like TransformStream.
We create a `new PassThrough` to transform the react PipeableStream to Node.js Readable, and the `interleaveWithNodeStream` work well.
=> feat: support styled-component in streaming ssr

.changeset/four-years-drive.md, packages/runtime/plugin-runtime/src/core/browser/hydrate.tsx, packages/runtime/plugin-runtime/src/router/runtime/plugin.tsx, packages/runtime/plugin-runtime/src/router/runtime/types.ts
This PR move the reload logic when SSR URL mismatch in `hydrateRoot` to `routerPlugin`.
In the past, this feature was designed to ensure that the page could load the current route correctly when using the Browser's native history operation, but default enable would cause many other problems.
1. This features should not enable by default.
2. This features is not entirely certain
So we add a `unstable` configuration to enable it. And this configuration will not display in modern.js document now.
=> feat(runtime): add new configuration for reload on SSR URL mismatch

.changeset/kind-panthers-fail.md, packages/toolkit/plugin-v2/package.json, packages/toolkit/plugin-v2/src/cli/run/config/loadConfig.ts, pnpm-lock.yaml
plugin v2 use `jiti` to read config file for supporting esm import
=> feat: use `jiti` to read config file for supporting esm import

.changeset/tricky-starfishes-hug.md, packages/solutions/app-tools/src/types/new.ts, packages/toolkit/plugin-v2/src/cli/context.ts, packages/toolkit/plugin-v2/src/cli/hooks.ts, packages/toolkit/plugin-v2/src/cli/run/create.ts, packages/toolkit/plugin-v2/src/types/cli/api.ts, packages/toolkit/plugin-v2/src/types/cli/context.ts, packages/toolkit/plugin-v2/src/types/cli/hooks.ts, packages/toolkit/plugin-v2/src/types/cli/plugin.ts, packages/toolkit/plugin-v2/src/types/hooks.ts
- cli extends add ExtendConfigUtils
- process.on exist event support off
=>  feat: cli plugin support ExtendConfigUtils

.changeset/strong-weeks-exercise.md, packages/runtime/plugin-garfish/src/cli/index.ts, packages/runtime/plugin-router-v5/src/cli/index.ts, packages/runtime/plugin-runtime/src/cli/template.ts, packages/runtime/plugin-runtime/src/core/browser/index.tsx, packages/runtime/plugin-runtime/src/router/cli/index.ts, packages/runtime/plugin-runtime/src/state/cli/index.ts, packages/solutions/app-tools/src/compat/hooks.ts, packages/solutions/app-tools/src/index.ts, packages/solutions/app-tools/src/types/hooks.ts, packages/solutions/app-tools/src/types/index.ts, packages/solutions/app-tools/src/types/new.ts, packages/toolkit/plugin-v2/src/cli/api.ts, packages/toolkit/plugin-v2/src/cli/hooks.ts, packages/toolkit/plugin-v2/src/cli/index.ts, packages/toolkit/plugin-v2/src/index.ts, packages/toolkit/plugin-v2/src/types/cli/api.ts, packages/toolkit/plugin-v2/src/types/cli/context.ts, packages/toolkit/plugin-v2/src/types/cli/hooks.ts, packages/toolkit/plugin-v2/src/types/cli/index.ts
feat: move _internalRuntimePlugins and _internalServerPlugins to plugin v2 to support common plugin use this hook
=> feat: move _internalRuntimePlugins and _internalServerPlugins to plugin v2

tests/e2e/builder/cases/check-syntax/index.test.ts, tests/e2e/builder/cases/source/source-exclude/index.test.ts, tests/e2e/builder/cases/source/source-include/index.test.ts, tests/e2e/builder/scripts/shared.ts, tests/utils/modernTestUtils.js
some build logs are unnecessary in CI. such as:
```bash
·error   [@rsbuild/plugin-check-syntax] Find some syntax that does not match "ecmaVersion <= 2016":
ERROR 1
source:  /src/test.js:3:19
output:  /dist/static/js/index.34a89cf2.js:1:135
reason:  Unexpected token (1:135)
code:    
1 | export const printLog = () => {
2 |   const arr = [1, 2, 3, 4, [5, 6, [7, 8]]];
> 3 |   console.log(arr, arr?.flat());
4 | };
·success [@rsbuild/plugin-check-syntax] Syntax check passed.
```
```bash
ready   Built in 0.09 s (web)
·°ready   Built in 1.51 s (web)
·start   Building...
start   Building...
ready   Built in 0.20 s (web)
ready   Built in 0.20 s (web)
··°°°start   Building...
```
```bash
PASS integration/swc/tests/transform-fail.test.ts (8.297 s)
error   Compile error: 
Failed to compile, check the …
```
=> test: clean up unnecessary build logs

.changeset/green-beans-provide.md, packages/solutions/app-tools/src/commands/dev.ts, tests/integration/dev-server/modern.config.ts, tests/integration/dev-server/tests/index.test.ts
Modern.js has `dev` and `tools.devServer` configuration. And `tools.devServer` already deprecated, we should using `dev` config instead firstly.
=> fix(dev-server): apply dev configuration, avoid dev.setupMiddleware not apply.

.changeset/dry-elephants-promise.md, packages/server/core/src/plugins/default.ts, packages/server/core/src/types/config/server.ts, packages/server/prod-server/src/apply.ts, packages/server/prod-server/src/types.ts
This PR add a new config to control internal server logger, and it will add to docs in next major version.
In the past, Modern.js did not provide feature to support user customs log monitor. Currently, Modern.js has initially provided server plugin, so when developers want to customize log monitor, we should also support users to turn off the built-in logging.
The server plugin can use it's own config to control custom logger, may like: 
```ts
server: {
logger: false
},
plugins: [myMonitors({ logger: true })]
})
```
=> fix: add server.logger to control internal logger

packages/document/main-doc/docs/en/apis/app/hooks/src/entry.mdx, packages/document/main-doc/docs/en/apis/app/hooks/src/entry.server.mdx, packages/document/main-doc/docs/en/configure/app/source/enable-custom-entry.mdx, packages/document/main-doc/docs/zh/apis/app/hooks/src/entry.mdx, packages/document/main-doc/docs/zh/apis/app/hooks/src/entry.server.mdx, packages/document/main-doc/docs/zh/configure/app/source/enable-custom-entry.mdx, packages/server/prod-server/src/index.ts, packages/solutions/app-tools/src/commands/index.ts, packages/solutions/app-tools/src/commands/serve.ts, packages/solutions/app-tools/src/index.ts
This PR export `serve` command node api like `dev` from '@modern-js/app-tools'.
So if a framework extends by modern.js, it can add internal custom server plugin for their own server in `serve` command.
> this PR also improve some docs for custom entry. However, it has no relationship with the core changes.
=> feat: export serve command

.changeset/smart-tigers-breathe.md, packages/cli/uni-builder/src/shared/plugins/frameworkConfig.ts
fix `Cannot create property 'buildDependencies' on boolean 'true'` error.
=> fix: compat chain.cache true

packages/solutions/app-tools/src/esm/esbuild-loader.mjs, packages/solutions/app-tools/src/esm/ts-node-loader.mjs, tests/integration/pure-esm-project/package.json, tests/integration/pure-esm-project/tests/index.test.ts
Starting from the node.js 22.12.0 version, node.js has enabled the `experimental-require-module` by default, which will cause modern.js to fail to handle esm (ts projects will not be affected). Currently, `require` function will not be processed through Customization Hooks registered by Modern.js to handle built-in aliases. In Modern.js 3.0, we will remove all built-in aliases, so we add `no-experimental-require-module` here first to avoid test failures.
=> test: add no-experimental-require-module for integration test cases

packages/toolkit/utils/src/cli/version.ts, tests/integration/pure-esm-project/tests/index.test.ts
=> test: only set no-experimental-require-module in node22 version

.changeset/strange-rings-thank.md, packages/solutions/app-tools/src/builder/generator/index.ts, packages/solutions/app-tools/src/builder/shared/builderPlugins/builderHooks.ts, packages/solutions/app-tools/src/builder/shared/builderPlugins/index.ts, pnpm-lock.yaml, tests/integration/rsbuild-hook/modern.config.ts, tests/integration/rsbuild-hook/package.json, tests/integration/rsbuild-hook/src/App.tsx, tests/integration/rsbuild-hook/src/modern-app-env.d.ts, tests/integration/rsbuild-hook/src/modern.runtime.ts, tests/integration/rsbuild-hook/tests/index.test.ts, tests/integration/rsbuild-hook/tsconfig.json
Support rsbuild modify config hook
- modifyBundlerChain
- modifyRsbuildConfig
- modifyRspackConfig
- modifyWebpackChain
- modifyWebpackConfig
=> feat: support rsbuild modify config hook

.changeset/bright-apricots-complain.md, packages/cli/plugin-bff/src/cli.ts, packages/cli/plugin-bff/src/utils/clientGenerator.ts, packages/cli/plugin-bff/src/utils/runtimeGenerator.ts, packages/document/main-doc/docs/en/components/create-bff-api-app.mdx, packages/document/main-doc/docs/en/guides/advanced-features/bff/_meta.json, packages/document/main-doc/docs/en/guides/advanced-features/bff/cross-project.mdx, packages/document/main-doc/docs/zh/components/create-bff-api-app.mdx, packages/document/main-doc/docs/zh/guides/advanced-features/bff/_meta.json, packages/document/main-doc/docs/zh/guides/advanced-features/bff/cross-project.mdx, packages/server/core/src/types/config/bff.ts, packages/server/create-request/src/browser.ts, packages/server/create-request/src/node.ts, packages/server/create-request/src/types.ts, packages/server/plugin-express/src/cli/index.ts, packages/server/plugin-koa/src/cli/index.ts, tests/integration/bff-corss-project/bff-api-app/modern.config.ts, tests/integration/bff-corss-project/bff-api-app/package.json, tests/integration/bff-corss-project/bff-client-app/src/ssr/App.tsx, tests/integration/bff-corss-project/bff-indep-client-app/src/base/App.tsx, tests/integration/bff-corss-project/bff-indep-client-app/src/ssr/App.tsx, tests/integration/bff-corss-project/bff-indep-client-app/src/upload/App.tsx, tests/integration/bff-express/modern.config.ts, tests/integration/bff-express/package.json
- bff support set domain
- fix bff package.files path
- add indep bff doc
=> feat: add indep bff doc

.changeset/silver-masks-flash.md, packages/server/core/src/adapters/node/node.ts
This PR is for passes through the request body when the query has `__pass_body`.
=> feat: pass through the body, when query has __pass_body

packages/document/main-doc/docs/en/guides/basic-features/deploy.mdx, packages/document/main-doc/docs/zh/guides/basic-features/deploy.mdx
Fixes typo in docs: `Nignx` => `Nginx`
=> docs: fix nginx typo

.changeset/nasty-bananas-join.md, packages/server/core/src/plugins/customServer/index.ts, packages/server/core/src/plugins/default.ts, packages/server/core/src/plugins/monitors.ts, packages/server/core/src/plugins/render/index.ts, packages/server/core/src/plugins/route.ts
This PR remove `reporter.init` API invoke in `@modern-js/server-core`.
It should implement in the place that create report instance. So we modify the middleware name to `requestLatencyMiddleware`.
And this PR also fix some problem:
1. InjectRoute and requestLatencyMiddleware should add `path`, otherwise it will run multiple times in multi-entry project.
2. Move `injectRoute` to defaultPlugins, so that user can get it before `await next()`.
=> chore: remove reporter.init and use monitors to report request cost

tests/integration/swc/tests/transform-fail.test.ts, tests/utils/modernTestUtils.js
When the build fails, the tests have already failed, and continuing execution will make it difficult to pinpoint the correct error message.
like this, compile error but report ` Error: failed to find element matching selector ".mock_file"`
https://github.com/web-infra-dev/rspack/actions/runs/13515385701/job/37763519692
=> test: should reject on compile error

.changeset/honest-turtles-chew.md, packages/runtime/plugin-runtime/src/cli/code.ts, packages/runtime/plugin-runtime/src/cli/template.ts, packages/runtime/plugin-runtime/src/core/config.ts, packages/runtime/plugin-runtime/src/core/context/index.ts, packages/runtime/plugin-runtime/src/router/cli/code/templates.ts, packages/runtime/plugin-runtime/src/router/cli/handler.ts
`src/modern.runtime.ts` defines Runtime config support function and uses entry name params.
```ts title="src/modern.runtime.ts"
import { defineRuntimeConfig } from '@modern-js/runtime';
export default defineRuntimeConfig(entryName => {
console.log('entryName', entryName);
return {
plugins: [],
};
});
```
=> feat: defineRuntimeConfig supports function parameters

.changeset/quick-rocks-float.md, packages/document/main-doc/docs/en/guides/basic-features/data/_meta.json, packages/document/main-doc/docs/en/guides/basic-features/data/data-cache.mdx, packages/document/main-doc/docs/zh/guides/basic-features/data/_meta.json, packages/document/main-doc/docs/zh/guides/basic-features/data/data-cache.mdx, packages/runtime/plugin-runtime/src/core/context/monitors/default.ts, packages/runtime/plugin-runtime/src/react-server.ts
This PR is for the following things:
1. add the doc of `cache` function
2. export the function of `getMonitors` for server component
=> docs: add cache doc & export `getMonitors` for server component

.changeset/two-guests-argue.md, packages/runtime/plugin-runtime/src/core/context/response/index.server.tsx, packages/runtime/plugin-runtime/src/core/context/response/index.tsx, packages/runtime/plugin-runtime/src/core/server/requestHandler.ts, packages/runtime/plugin-runtime/src/index.ts, packages/runtime/plugin-runtime/src/react-server.ts, packages/toolkit/runtime-utils/src/universal/async_storage.server.ts, tests/integration/rsc-ssr-app/src/client-component-root/App.tsx, tests/integration/rsc-ssr-app/src/server-component-root/App.tsx, tests/integration/rsc-ssr-app/tests/index.test.ts
Add some response APIs to support setting response headers, status codes, and redirects
=> feat: support some response APIs

packages/document/main-doc/docs/en/guides/topic-detail/module-federation/application.mdx, packages/document/main-doc/docs/en/guides/topic-detail/module-federation/usage.mdx, packages/document/main-doc/docs/zh/guides/topic-detail/module-federation/application.mdx, packages/document/main-doc/docs/zh/guides/topic-detail/module-federation/usage.mdx
This PR modify the module-federation docs.
Add `static` prefix for remoteEntry.js and manifest. For modern.js only support serve static file, and now deploy command also only copy static dir to deploy product.
related PR: #6924
example：https://github.com/web-infra-dev/modern-js-examples/pull/50
related discuss: #6911
=> docs: update mf usage docs, add static dir

.changeset/thick-fans-protect.md, packages/document/main-doc/docs/en/apis/app/commands.mdx, packages/document/main-doc/docs/zh/apis/app/commands.mdx, packages/solutions/app-tools/src/commands/build.ts, packages/solutions/app-tools/src/commands/index.ts, packages/solutions/app-tools/src/locale/en.ts, packages/solutions/app-tools/src/locale/zh.ts, packages/solutions/app-tools/src/utils/types.ts
reference https://rsbuild.dev/guide/basic/cli#rsbuild-build
=> feat: support watch mode in modern build

.changeset/calm-guests-act.md, packages/runtime/plugin-runtime/src/core/compat/hooks.ts, packages/runtime/plugin-runtime/src/core/plugin/base.ts, packages/runtime/plugin-runtime/src/core/plugin/types.ts, packages/toolkit/plugin-v2/src/runtime/api.ts, packages/toolkit/plugin-v2/src/runtime/hooks.ts, packages/toolkit/plugin-v2/src/runtime/run/create.ts, packages/toolkit/plugin-v2/src/types/cli/hooks.ts, packages/toolkit/plugin-v2/src/types/runtime/api.ts, packages/toolkit/plugin-v2/src/types/runtime/hooks.ts, tests/integration/runtime-plugin/fixtures/runtime-custom-config-plugin/src/plugins/config.tsx
The design of the Runtime plugin's `modifyRuntimeConfig` is a collectAsyncHook. Just like the `config` hook of the CLI plugin, it is used to collect the configurations of Runtime plugins and then perform merging. Calling it `modifyRuntimeConfig` is not very appropriate. It should be consistent with the CLI plugin, so it is renamed to `config`. Since this Hook has not been officially released externally, there will be a break change here, but it should not have a significant impact.
```ts
import type { RuntimePluginFuture } from '@modern-js/runtime';
export const configPlugin = (): RuntimePluginFuture => {
return {
name: 'app-custom-config-plugin',
post: ['@modern-js/plugin-router'],
setup: api => {
api.config(() => {
return {
router: {
basename: 'test',
},
};
});
},
};
};
```
=> feat: rename runtime plugin modifyRuntimeConfig hook to config

.changeset/eleven-suits-behave.md, packages/server/core/src/adapters/node/hono.ts, packages/server/core/src/adapters/node/index.ts, packages/server/server/src/helpers/mock.ts
This PR add a new middleware connect function for mock handler.
Because we are not sure how developer use `tools.devServer.before` and `tools.devServer.after`, avoid to affecting the other features, so we add a new function.
We expect mock handler will always handle response by itself.
=> fix: add new mid connet for mock handler

.changeset/tame-peas-fix.md, packages/runtime/plugin-garfish/src/runtime/provider.tsx
garfish `createProvider` function support add `appName` props to `ModernRoot`
=> feat: garfish provider support add appName props

.changeset/hip-actors-flow.md, packages/server/server/src/createDevServer.ts, packages/server/server/src/helpers/devOptions.ts, pnpm-lock.yaml, tests/integration/asset-prefix/modern.config.ts, tests/integration/asset-prefix/package.json, tests/integration/asset-prefix/src/index.ts, tests/integration/asset-prefix/tests/index.test.ts
This PR support `dev.assetPrefix` in static middleware.
In the past, this config only support rsbuild dev middleware. But the file not created by build will not be served by rsbuil dev middleware, it is served by modern.js static middleware.
So, we get the assetPrefix from builder instance, and overrides the `output.assetPrefix` in dev server.
relate MR: #6924
=> feat: support dev.assetPrefix in static middleware

packages/server/server/src/helpers/devOptions.ts
Now if we enable rsc feature, the compiler will be rename to 'client' and 'server'.
=> fix: compiler will be changed to client when enable rsc

.changeset/selfish-spies-serve.md, packages/server/core/src/plugins/route.ts
This PR fix the page detect logic.
We should use `route.entryName`, not `route.isApi`. Because when we config `bff.enableHandleWeb`, all the route `isApi`.
=> fix: should detect page route by entryName, not isApi

.changeset/violet-fireants-arrive.md, packages/cli/plugin-ssg/src/server/process.ts
This PR fixes the issue of garbled HTML in SSG when dealing with large amounts of data.
=> fix(ssg): ssg should concat buffer first

.changeset/fifty-garlics-occur.md, packages/runtime/plugin-garfish/src/cli/index.ts, packages/solutions/app-tools/src/index.ts, packages/solutions/app-tools/src/run/index.ts, packages/solutions/app-tools/src/types/index.ts, packages/solutions/app-tools/src/utils/getUserConfig.ts, packages/solutions/app-tools/src/utils/initAppContext.ts, packages/solutions/app-tools/tests/analyze/getFileSystemEntry.test.ts, packages/toolkit/plugin-v2/src/cli/run/create.ts
The CLI plugin updates the metaName when it starts running, so there is no need to update the metaName information again in the app-tools plugin.
=> fix: initAppContext should not update metaName

tests/e2e/builder/cases/progress/index.test.ts
Fix Rsbuild logs casing (now defaults to lowercase)
https://github.com/web-infra-dev/modern.js/actions/runs/14165147338/job/39676946272
=> test(e2e): fix Rsbuild logs casing

.changeset/good-colts-sparkle.md, packages/server/core/src/plugins/render/render.ts, packages/server/core/src/types/plugins/base.ts, packages/server/core/tests/plugins/render.test.ts
This PR adds support for users to specify the reason when manually falling back to CSR using `x-modern-ssr-fallback` request header, here's how it works:
```ts
// server/index.ts
export const middleware = (ctx, next) => {
const { req, res } = ctx;
if (condition) {
req.headers['x-modern-ssr-fallback'] = '1;reason=some reason';
}
next();
};
```
The final `x-modern-ssr-fallback` in the **response** header is as follows:
```ts
x-modern-ssr-fallback: 1;reason=header,some reason
```
=> feat(ssr): support customizing fallback reason via x-modern-ssr-fallback header

.changeset/quick-mayflies-sort.md, packages/server/core/src/plugins/render/render.ts, packages/server/core/tests/fixtures/render/ssr/bundles/main.js, packages/server/core/tests/fixtures/render/ssr/index.html, packages/server/core/tests/plugins/render.test.ts
When SSR falls back to CSR, inject the fallback reason into the HTML as an inline script—for example, when the request URL contains `?csr=1`, the final response’s HTML `<head>` tag will include the following inline script:
```
<script id="__modern_ssr_fallback_reason__" type="application/json">{"reason":"query"}</script>
```
=> feat(ssr): inject fallback reason to html

.changeset/young-bats-taste.md, packages/runtime/plugin-runtime/src/cli/alias.ts
This PR fix the issue when project has nested entries.
```json
{
"entries": {
"foo": "./src/foo/App.tsx",
"foo/bar": "./src/foo/bar/App.tsx"
}
}
```
Modern.js will generate the internal alias for the entries, like:
```json
{
"@modern-js/runtime/registry/foo": "/root/node_modules/.modern-js/foo/register.js",
"@modern-js/runtime/registry/foo/bar": "/root/node_modules/.modern-js/foo/bar/register.js",
}
```
But the second alias is not effected, then the compiler throw error `can not found @modern-js/runtime/registry/foo/bar`
So we add `$` to alias key to avoid this.
=> fix: add the "$" character to avoid alias override in nested entries

packages/solutions/app-tools/src/run/index.ts
This PR only for compat, the logic will be removed in next major version.
=> fix: ignore warning when use legacy state

.changeset/mean-birds-bake.md, packages/server/core/src/adapters/node/node.ts, packages/server/core/src/plugins/render/render.ts, packages/toolkit/types/server/server.d.ts
Avoid the problem that rawHeaders can only obtain the original request header. For example, the request header added by the middleware will not be synchronized at present
=> fix(server): should sync all headers from req.headers

packages/document/main-doc/src/i18n/index.ts
https://github.com/user-attachments/assets/808564b3-2400-49d0-84bc-db20b3c6087b
Summary:
Currently, clicking on links will briefly show a 404 page before being
redirected.  This is because we incorrectly set the default route to be zh
while the default language is en.  This commit fixes the issue by aligning the
default route and language.
Test Plan:
1. Go to homepage
2. Click "Introduction"
Before: Briefly see 404 before being redirected
After: See the correct page
=> fix(doc): don't briefly show 404 when navigating

packages/document/main-doc/docs/en/configure/app/usage.mdx, packages/document/main-doc/docs/en/guides/advanced-features/_meta.json, packages/document/main-doc/docs/en/guides/advanced-features/custom-server.mdx, packages/document/main-doc/docs/en/guides/advanced-features/web-server.mdx, packages/document/main-doc/docs/zh/configure/app/usage.mdx, packages/document/main-doc/docs/zh/guides/advanced-features/_meta.json, packages/document/main-doc/docs/zh/guides/advanced-features/custom-server.mdx, packages/document/main-doc/docs/zh/guides/advanced-features/web-server.mdx
- Add Custom Server usage doc
- Add doc for migrating from legacy Custom Web Server to Custom Server
=> docs: server config doc

.changeset/smooth-lions-pay.md, packages/runtime/plugin-runtime/src/core/compatible.tsx, packages/runtime/plugin-runtime/src/core/context/runtime.ts, packages/runtime/plugin-runtime/src/router/runtime/plugin.node.tsx, packages/runtime/plugin-runtime/src/router/runtime/plugin.tsx
This PR provider routes in `useRuntimeContext` API.
This is mainly to enable developers to get all routing structure in conventional routing and generate the UI they may need.
#6188 
```tsx
import { useRuntimeContext } from '@modern-js/runtime';
import renderSidebar from './sidebar';
const Page = () => {
const { routes } = useRuntimeContext();
return (
<div>{renderSidebar(routes)}</div>
);
};
export default Page;
```
The routes is an array of `RouteObject`, a routing type definition from React Router v6.
```typescript
export type RouteObject = IndexRouteObject | NonIndexRouteObject;
```
=> feat: add routes into useRuntimeContext

tests/integration/pure-esm-project/modern.config.js
In the webpack@5.99.0 version, there will be a bug that causes esm applications to report errors; here, use rspack to replace webpack.
=> test: use rspack to replace webpack for the test case

.changeset/nine-rabbits-smoke.md, packages/server/core/src/types/plugins/new.ts, packages/server/server/src/helpers/index.ts, packages/toolkit/plugin-v2/src/server/api.ts, packages/toolkit/plugin-v2/src/server/context.ts, packages/toolkit/plugin-v2/src/types/server/api.ts, packages/toolkit/types/server/context.d.ts
In this PR, we enhance the server plugin api:
1. Support for correct usage of `middlewares` and `renderMiddlewares` in server plugins.
2. Remove of compatibility for legacy APIs like `useAppContext` in new server plugins.
3. Fixed issue where the server plugin API expose `getConfig` not `getServerConfig`.
=> feat: add middlewares and renderMiddlewares to server plugin context

.changeset/happy-bats-attend.md, packages/server/core/src/adapters/node/plugins/static.ts
This PR resolves the issue where static assets cannot be accessed when developers configure the current domain name as `assetPrefix`.
```ts
import { appTools, defineConfig } from "@modern-js/app-tools";
runtime: {
router: true,
},
server: {
port: 3052,
},
output: {
assetPrefix:"http://localhost:3052"
},
plugins: [
appTools({
bundler: "rspack",
}),
],
});
```
Because middleware also valida host, which is actually unnecessary since resource requests from non-current hosts cannot enter the server.
=> fix: ignore domain when detect whether the request is for static asset

packages/document/main-doc/docs/en/apis/app/hooks/src/routes.mdx, packages/document/main-doc/docs/zh/apis/app/hooks/src/routes.mdx
=> fix: bash highlight should use `#`

packages/document/main-doc/docs/en/configure/app/tools/html-plugin.mdx, packages/document/main-doc/docs/zh/configure/app/tools/html-plugin.mdx
The HTML template of an SSR application contains placeholders for SSR injection, it cannot be used together with `removeComment`.
=> docs: improve htmlPlugin configuration docs

packages/document/main-doc/rspress.config.ts
docs(rspress): add llms.txt llms-full.txt based on "@rspress/plugin-llms""
https://github.com/web-infra-dev/rslib/pull/954
https://github.com/web-infra-dev/rsdoctor/pull/1063
https://v2.rspress.dev/plugin/official-plugins/llms
=> docs(rspress): add llms.txt llms-full.txt based on "@rspress/plugin-llms"

packages/document/main-doc/docs/en/guides/topic-detail/module-federation/deploy.mdx, packages/document/main-doc/docs/en/guides/topic-detail/module-federation/usage.mdx, packages/document/main-doc/docs/zh/guides/topic-detail/module-federation/deploy.mdx, packages/document/main-doc/docs/zh/guides/topic-detail/module-federation/usage.mdx
This PR add the deployment guide for Modern.js + Module Federation.
We recommend using [Modern.js's Node server](https://modernjs.dev/guides/basic-features/deploy.html#using-modernjs-built-in-nodejs-server) to run MF applications. It help devs get the same experience in both the development and the production.
> If you have any other deployment requirements, feel free to disscussion.
Relate PR:
MF's Modern.js Plugin: https://github.com/module-federation/core/pull/3777
Modern.js Examples: https://github.com/web-infra-dev/modern-js-examples/pull/54
=> docs: improve mf deployment docs

.changeset/ten-pigs-fetch.md, packages/cli/plugin-ssg/src/server/process.ts, packages/server/core/src/plugins/monitors.ts, packages/server/prod-server/src/apply.ts
In this PR, we have overridden the `logger` passed to the server in the SSG plugin. 
We want the error log to interrupt the SSG build but the default Logger only outputs to stdout, so we have overridden it to output to stderr.
=> fix: ssg should overrides the logger.error method to stderr

tests/integration/server-hook/router/tests/index.test.ts
#7202 upgrade puppeteer version. But in [v23]( https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-core-v23.0.0), puppeteer rename ignoreHTTPSErrors to acceptInsecureCerts.
This has caused the certificate error, this PR fix it.
=> fix: use acceptInsecureCerts instead of ignoreHTTPSErrors

.changeset/tough-snakes-stop.md, packages/cli/uni-builder/src/webpack/plugins/babel.ts, pnpm-lock.yaml, tests/integration/babel-object-config/modern.config.ts, tests/integration/babel-object-config/package.json, tests/integration/babel-object-config/src/App.tsx, tests/integration/babel-object-config/tests/index.test.ts
When the project is configured as follows:
```ts
{
tools: {
babel: {
plugins: ['custom-plugin']
}
},
server: {
ssr: true
}
}
```
Run `pnpm run build` will result in an error:
```
File: data:text/javascript,import "core-js";:1:1
Module build failed (from ./node_modules/.pnpm/babel-loader@9.2.1_@babel+core@7.27.3_webpack@5.99.9_esbuild@0.17.19_/node_modules/babel-loader/lib/index.js):
Error: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.
plugins: [
['some-plugin', {}],
['some-plugin', {}, 'some unique name'],
]
```
The main reason for this issue is that each environment currently share the same plugins array of the babel-loader options,  and this PR fixes it.
=> fix:  ensure that each environment has its own babel options

packages/document/main-doc/docs/en/guides/basic-features/debug/using-storybook.mdx, packages/document/main-doc/docs/zh/guides/basic-features/debug/using-storybook.mdx
Add new storybook usage docs. Base on Storybook Rsbuild.
Related PR:
1. https://github.com/web-infra-dev/modern.js/pull/7233
2. https://github.com/rspack-contrib/storybook-rsbuild/pull/294
=> docs: add new storybook docs

.changeset/young-coins-bet.md, packages/cli/plugin-bff/src/cli.ts, packages/cli/uni-builder/src/shared/parseCommonConfig.ts, packages/cli/uni-builder/src/types.ts, packages/cli/uni-builder/tests/__snapshots__/parseConfig.test.ts.snap, packages/runtime/plugin-garfish/src/cli/index.ts, packages/runtime/plugin-router-v5/src/cli/index.ts, packages/runtime/plugin-router-v5/tests/index.test.ts, packages/runtime/plugin-router-v7/src/cli/index.ts, packages/runtime/plugin-runtime/src/cli/alias.ts, packages/runtime/plugin-runtime/src/cli/index.ts, packages/runtime/plugin-runtime/src/cli/ssr/index.ts, packages/runtime/plugin-runtime/tests/router/index.test.ts, packages/runtime/plugin-state/src/cli/index.ts, packages/runtime/plugin-testing/src/base/config/index.ts, packages/runtime/plugin-testing/src/cli/index.ts, packages/server/plugin-express/src/cli/index.ts, packages/server/plugin-koa/src/cli/index.ts, packages/solutions/app-tools/src/builder/generator/createBuilderProviderConfig.ts, packages/solutions/app-tools/src/commands/build.ts, packages/solutions/app-tools/src/commands/dev.ts, packages/solutions/app-tools/src/config/default.ts, packages/solutions/app-tools/src/config/legacy/index.ts, packages/solutions/app-tools/src/types/config/index.ts, packages/solutions/app-tools/src/types/config/resolve.ts, packages/solutions/app-tools/tests/builder/__snapshots__/index.test.ts.snap, tests/integration/alias-set/modern.config.ts, tests/integration/alias-set/src/App.tsx, tests/integration/alias-set/src/alias/index.ts
This PR resolve the `resolve.alias` warning，and also update the internal alias usage in Modern.js.
- Introduced the `resolve` field (with `resolve.alias`) in various configs such as `UniBuilderConfig`, `AppToolsUserConfig`, and `UserConfig`. Users are now encouraged to use `resolve.alias` instead of the legacy `source.alias`.
- Updated related type definitions, default configs, and legacy compatibility logic accordingly.
- All plugins and tools that depend on alias configuration (e.g., runtime, router, state, testing, express, koa, etc.) have switched from `source.alias` to `resolve.alias`.
- The logic for passing alias config in build and dev commands has been adapted to the new structure, merging both `source.alias` and `resolve.alias` for compatibility.
- Maintained backward …
=> feat: support resolve.alias

packages/cli/uni-builder/src/shared/rsc/common.ts, packages/cli/uni-builder/src/shared/rsc/plugins/rsbuild-rsc-plugin.ts, tests/integration/rsc-ssr-app/tests/index.test.ts
=> chore: fix test cases

packages/document/main-doc/docs/en/configure/app/experiments/lazy-compilation.mdx, packages/document/main-doc/docs/zh/configure/app/experiments/lazy-compilation.mdx
Now, lazyCompilation already supports by Rspack, so point the docs to Rsbuild.
=> docs: update lazyCompilation docs for rspack

.changeset/dry-donkeys-stay.md, packages/document/main-doc/docs/en/apis/app/commands.mdx, packages/document/main-doc/docs/zh/apis/app/commands.mdx, packages/solutions/app-tools/src/commands/inspect.ts
support output modern config when calling `modern inspect`
=> feat: support output modern config when calling `modern inspect`

.changeset/flat-years-thank.md, packages/cli/plugin-bff/src/utils/createHonoRoutes.ts, packages/server/create-request/src/handleRes.ts, tests/integration/bff-hono/api/index.ts, tests/integration/bff-hono/src/routes/base/page.tsx, tests/integration/bff-hono/tests/index.test.ts
=> feat: hono bff supports return custom res

.github/workflows/test-builder-e2e.yml
The builder E2E cases all much faster since https://github.com/web-infra-dev/modern.js/pull/7352. So we can run the CI on pull request to detect builder related failure cases early.
Currently, the Nx cache is the slowest part of the workflow, but I believe it is possible to optimize dependencies and speed up the workflow:
=> chore(CI): run builder E2E cases on pull request

.changeset/cool-numbers-laugh.md, packages/cli/plugin-bff/src/cli.ts
When the streaming response is returned, if it is compressed, the streaming fails, here we make the bff's response not to be streamed.
=> feat(bff): should not compress the api response

packages/cli/plugin-data-loader/src/runtime/errors.ts, packages/cli/plugin-data-loader/src/runtime/index.ts, packages/runtime/plugin-runtime/src/core/context/index.ts, packages/runtime/plugin-runtime/src/core/context/runtime.ts, packages/runtime/plugin-runtime/src/core/server/string/index.ts, packages/runtime/plugin-runtime/src/core/server/string/ssrData.ts, packages/runtime/plugin-runtime/src/core/server/utils.ts, packages/runtime/plugin-runtime/src/router/runtime/DeferredDataScripts.node.tsx, packages/runtime/plugin-runtime/src/router/runtime/plugin.node.tsx, packages/runtime/plugin-runtime/src/router/runtime/plugin.tsx, packages/runtime/plugin-runtime/src/router/runtime/routeModule.ts, packages/runtime/plugin-runtime/src/router/runtime/utils.tsx, packages/server/core/src/plugins/render/render.ts, packages/toolkit/runtime-utils/package.json, packages/toolkit/runtime-utils/src/router.ts
This PR does two things:
1. Use `require` to import `runtime-utils/router` to avoid the interoperability issue between cjs and esm in node 22 and above.
2. Remove the `remix-router` export.
=> fix: use require to import runtime-utils/router

.changeset/bitter-cars-drive.md, packages/runtime/plugin-runtime/src/document/cli/index.ts
=> fix: replace second param can be see as pattern replace

.changeset/young-comics-drive.md, packages/server/core/src/adapters/node/node.ts
#7448
In node24, undici has added strict access restrictions to the private field #state of the Response object. Accessing it indirectly through a Proxy object will trigger a TypeError: Cannot read private member #state.
=> feat: req support node 24

.changeset/whole-parents-love.md, packages/server/prod-server/src/netlify.ts, tests/integration/server-config-v2/netlify.toml
#7453 
Netlify did not follow the unified `createProdServer` due to some special reasons, missing support for Hono Middleware, which is fixed in this PR.
=> fix: netlify server missed the hono middleware features

packages/cli/builder/src/types.ts, packages/solutions/app-tools/src/builder/generator/index.ts, packages/solutions/app-tools/src/types/config/dev.ts
`dev.setupMiddlewares` is a special field, it will not be passed to Rsbuild. Although its name is the same as in Rsbuild, it is consumed by Modern.js.
This PR separates the type of this field to prevent errors caused by updates to Rsbuild.
=> fix: update setupMiddleware type in modern.js

packages/runtime/plugin-runtime/src/core/context/index.ts, packages/runtime/plugin-runtime/src/core/context/serverPayload/index.server.tsx, packages/runtime/plugin-runtime/src/core/context/serverPayload/index.tsx, packages/runtime/plugin-runtime/src/core/server/requestHandler.tsx, packages/runtime/plugin-runtime/src/router/runtime/plugin.node.tsx
1. Move the logic of serverPayload to a separate directory and add a `serverPayload/index.ts` file to make the code clearer.
2. Note that the code worked fine before the changes, relying on `serverModuleLoader.ts`.
=> refactor: move serverPayload logic to a separate directory

packages/runtime/plugin-runtime/src/core/server/string/index.ts
Removed the logic of useLoader, so it is not necessary to determine whether to renderToString based on prefetch is successful.
=> fix: should not rely on renderLevel to execute renderToString

.changeset/beige-memes-relax.md, packages/runtime/plugin-runtime/src/router/runtime/plugin.tsx
If `server.routes` is configured as follows：
```
server: {
routes: {
main: ['/shop', '/shop/us'],
},
}
```
When accessing the `/shop/user` link, it will match the baseUrl `/shop/us`.
=> fix: should get basename correctly

.changeset/clever-stars-stand.md, packages/server/core/src/adapters/node/node.ts, packages/toolkit/runtime-utils/src/node/stream.ts
This PR avoid the process exit when user abort the request.
1. The error judgment for `abort code` is incorrect.
2. When the stream is destroyed, Node.js will throw an error. The `error` listener should be removed in the nextTick,  otherwise, the error will not be caught.
=> fix: process should not exit caused when user abort the request

packages/document/main-doc/docs/en/guides/advanced-features/page-performance/optimize-bundle.mdx, packages/document/main-doc/docs/zh/guides/advanced-features/page-performance/optimize-bundle.mdx
1. Fix 404 link to Rsbuild code split docs
2. Add content on the differences between Modern.js and Rsbuild's default chunk splitting strategies
=> docs: improve code split docs

packages/solutions/app-tools/src/commands/build.ts, packages/solutions/app-tools/src/commands/dev.ts
=> fix: resolve tsconfig-path errors when using destructuring aliases

.changeset/khaki-coins-sit.md, packages/toolkit/utils/package.json
This PR adds sub-path exports for the require and env modules in the @modern-js/utils package, improving the module's accessibility and enabling more granular imports.
Enhanced Package Exports: Added new sub-path exports in [package.json](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) for two specific modules:
- `./require` - exports the CLI require utility module
- `./env` - exports the environment detection utilities
=> chore(@modern-js/utils): add sub-path exports for require and env modules

packages/cli/plugin-bff/package.json, packages/cli/plugin-swc/package.json, packages/cli/rsbuild-plugin-esbuild/package.json, packages/cli/uni-builder/package.json, packages/devtools/client/package.json, packages/devtools/plugin/package.json, packages/runtime/plugin-runtime/package.json, packages/solutions/app-tools/package.json, packages/solutions/module-tools/package.json, packages/storybook/builder/package.json, packages/toolkit/plugin-v2/package.json, pnpm-lock.yaml, tests/e2e/builder/package.json
Avoid minifier bugs in the latest SWC versions: https://github.com/swc-project/swc/pull/11031
=> chore: revert rsbuild version to 1.5.9

packages/solutions/app-tools/src/builder/shared/bundlerPlugins/RouterPlugin.ts
This PR exposes the relationship between routes and source files (including dependencies), enabling MF 2.0 to analyze it for collecting remote modules dependent on the routes, and supporting the preloading of static resources.
=> feat: share routes info with other bundler plugins
