- .changeset/violet-eels-pull.md
- packages/server/server/src/dev-tools/dev-middleware/hmr-client/index.ts
Reverts web-infra-dev/modern.js#5152
> Revert "fix(hmr-client): reload when the updated modules are empty"

- .changeset/slimy-masks-give.md
- packages/storybook/framework/src/preset.ts
resolve react renderer from package using absolute path
> fix(storybook): resolve react renderer from package

- .changeset/two-wombats-argue.md
- packages/builder/builder-shared/src/types/config/source.ts
- packages/builder/builder/src/plugins/antd.ts
- packages/builder/builder/src/plugins/arco.ts
- pnpm-lock.yaml
- tests/e2e/builder/cases/source/plugin-import/helper.ts
- tests/integration/transform-import/modern.config.ts
- tests/integration/transform-import/package.json
- tests/integration/transform-import/src/App.css
- tests/integration/transform-import/src/App.tsx
- tests/integration/transform-import/src/modern-app-env.d.ts
- tests/integration/transform-import/tests/index.test.ts
- tests/integration/transform-import/tests/tsconfig.json
- tests/integration/transform-import/tsconfig.json
Remove SharedTransformImport config, so user can use correct customName and customStyleName type
> fix(transform-import): remove SharedTransformImport config

- packages/document/builder-doc/docs/en/config/performance/dnsPrefetch.md
- packages/document/builder-doc/docs/en/config/performance/preconnect.md
- packages/document/builder-doc/docs/zh/config/performance/dnsPrefetch.md
- packages/document/builder-doc/docs/zh/config/performance/preconnect.md
- packages/document/module-doc/docs/en/api/config/build-config.mdx
- packages/document/module-doc/docs/en/plugins/official-list/plugin-banner.mdx
- packages/document/module-doc/docs/zh/api/config/build-config.mdx
- packages/document/module-doc/docs/zh/plugins/official-list/plugin-banner.mdx
Fix example URLs.
https://github.com/web-infra-dev/rspress/issues/499
> docs: fix example URLs

- packages/builder/uni-builder/package.json
- packages/builder/uni-builder/src/index.ts
- packages/builder/uni-builder/src/rspack/index.ts
- packages/builder/uni-builder/src/shared/devServer.ts
- packages/builder/uni-builder/src/shared/parseCommonConfig.ts
- packages/builder/uni-builder/src/shared/plugins/frameworkConfig.ts
- packages/builder/uni-builder/src/types.ts
- packages/builder/uni-builder/src/webpack/index.ts
> fix(uni-builder): some type & logic problems

- package.json
https://nx.dev/recipes/troubleshooting/unknown-local-cache
> fix: nx-unknown-cache error

- packages/document/main-doc/docs/en/guides/basic-features/data/data-fetch.mdx
- packages/document/main-doc/docs/zh/guides/basic-features/data/data-fetch.mdx
> docs: add the doc about client loader

- .changeset/mighty-lies-lie.md
- packages/builder/builder-cli/bin/builder.js
> chore(builder-cli): add deprecated warning

- packages/document/builder-doc/package.json
- packages/document/main-doc/package.json
- packages/document/module-doc/package.json
- pnpm-lock.yaml
> feat: update rspress to v1.9.3

- packages/document/main-doc/docs/en/guides/advanced-features/ssr/stream.mdx
- packages/document/main-doc/docs/zh/guides/advanced-features/ssr/stream.mdx
> docs: add stream ssr performance

- packages/document/main-doc/docs/zh/guides/topic-detail/generator/plugin/api/onForged.md
> docs: fix typo of generator plugin

- tests/integration/server-prod/tests/index.test.ts
> fix: server-prod tests in windows

- packages/document/module-doc/docs/en/guide/basic/using-storybook.mdx
- packages/document/module-doc/docs/zh/guide/basic/using-storybook.mdx
> docs(module-tools): migrate storybook from v6 to v7

- .changeset/mighty-lies-lie.md
- packages/builder/builder-cli/README.md
- packages/builder/builder-rspack-provider/README.md
- packages/builder/builder-shared/README.md
- packages/builder/builder-webpack-provider/README.md
- packages/builder/builder/README.md
- packages/builder/plugin-esbuild/README.md
- packages/builder/plugin-esbuild/src/index.ts
- packages/builder/plugin-image-compress/README.md
- packages/builder/plugin-image-compress/src/index.ts
- packages/builder/plugin-node-polyfill/README.md
- packages/builder/plugin-node-polyfill/src/index.ts
- packages/builder/plugin-stylus/README.md
- packages/builder/plugin-stylus/src/index.ts
- packages/builder/plugin-swc/README.md
- packages/builder/plugin-swc/src/plugin.ts
- packages/builder/plugin-vue/README.md
- packages/builder/plugin-vue/src/index.ts
- packages/builder/plugin-vue2/README.md
- packages/builder/plugin-vue2/src/index.ts
> chore(builder-related): add deprecated warning

- packages/document/main-doc/docs/en/guides/advanced-features/rspack-start.mdx
- packages/document/main-doc/docs/zh/guides/advanced-features/rspack-start.mdx
> docs: update using-rspack

- packages/document/builder-doc/docs/en/config/experiments/sourceBuild.md
- packages/document/builder-doc/docs/en/config/source/exclude.md
- packages/document/builder-doc/docs/en/config/source/include.md
- packages/document/builder-doc/docs/zh/config/experiments/sourceBuild.md
- packages/document/builder-doc/docs/zh/config/source/exclude.md
- packages/document/builder-doc/docs/zh/config/source/include.md
> docs: update rspack supported configurations

- packages/document/module-doc/docs/en/guide/advance/in-depth-about-build.md
- packages/document/module-doc/docs/en/guide/faq/build.mdx
- packages/document/module-doc/docs/en/guide/faq/index.md
- packages/document/module-doc/docs/zh/guide/advance/in-depth-about-build.md
- packages/document/module-doc/docs/zh/guide/faq/build.mdx
- packages/document/module-doc/docs/zh/guide/faq/index.md
> docs(module-tools): add info for bundle dts and faq

- packages/document/module-doc/docs/en/guide/basic/command-preview.md
- packages/document/module-doc/docs/en/guide/basic/use-micro-generator.md
- packages/document/module-doc/docs/en/guide/basic/use-module-doc.mdx
- packages/document/module-doc/docs/zh/guide/basic/command-preview.md
- packages/document/module-doc/docs/zh/guide/basic/use-micro-generator.md
- packages/document/module-doc/docs/zh/guide/basic/use-module-doc.mdx
> docs(module-tools): adjust cli and scripts info

- .changeset/shiny-turkeys-trade.md
- packages/document/module-doc/docs/en/plugins/official-list/plugin-import.mdx
- packages/document/module-doc/docs/zh/plugins/official-list/plugin-import.mdx
- packages/solutions/module-tools/src/types/config/index.ts
- packages/solutions/module-tools/src/types/config/transform-import.ts
> fix(module-tools): remove function type in transformImport

- .github/workflows/update-rsbuild.yml
support auto update rsbuild  & create PR by workflow.
> chore: add update-rsbuild workflow

- packages/generator/generator-common/package.json
- packages/generator/generator-plugin/package.json
- packages/generator/generator-utils/package.json
- packages/generator/generators/base-generator/package.json
- packages/generator/generators/bff-generator/package.json
- packages/generator/generators/changeset-generator/package.json
- packages/generator/generators/dependence-generator/package.json
- packages/generator/generators/entry-generator/package.json
- packages/generator/generators/generator-generator/package.json
- packages/generator/generators/module-doc-generator/package.json
- packages/generator/generators/module-generator/package.json
- packages/generator/generators/module-test-generator/package.json
- packages/generator/generators/monorepo-generator/package.json
- packages/generator/generators/mwa-generator/package.json
- packages/generator/generators/packages-generator/package.json
- packages/generator/generators/repo-generator/package.json
- packages/generator/generators/router-v5-generator/package.json
- packages/generator/generators/rspack-generator/package.json
- packages/generator/generators/server-generator/package.json
- packages/generator/generators/ssg-generator/package.json
- packages/generator/generators/storybook-generator/package.json
- packages/generator/generators/storybook-next-generator/package.json
- packages/generator/generators/tailwindcss-generator/package.json
- packages/generator/generators/test-generator/package.json
- packages/generator/generators/upgrade-generator/package.json
- packages/generator/new-action/package.json
- packages/generator/sandpack-react/package.json
- packages/toolkit/create/package.json
- packages/toolkit/upgrade/package.json
- pnpm-lock.yaml
> chore: bump codesmith 2.3.3

- packages/document/builder-doc/theme/components/Announcement/index.tsx
- packages/document/builder-doc/theme/index.tsx
- packages/document/builder-doc/tsconfig.json
> docs: add builder upgrade announcement

- packages/server/prod-server-new/src/index.ts
- packages/server/server-base/src/adapters/serverStatic.ts
- packages/server/server-base/src/index.ts
- packages/server/server-base/src/type.ts
> feat: add node static middleware

- packages/server/server-base/src/ServerCore.ts
- packages/server/server-base/src/adapters/hono.ts
- packages/server/server-base/src/adapters/node.ts
- packages/server/server-base/src/adapters/serverStatic.ts
- packages/server/server-base/src/index.ts
- packages/server/server-base/src/libs/metrics.ts
- packages/server/server-base/src/libs/utils.ts
- packages/server/server-base/src/middlewares/faviconFallback.ts
- packages/server/server-base/src/types/hono.ts
- packages/server/server-base/src/types/index.ts
> feat: adjust types && add iconFallbackMiddlewares

- packages/document/builder-doc/docs/en/config/tools/tsLoader.md
- packages/document/builder-doc/docs/zh/config/tools/tsLoader.md
> docs: add alternative warning to ts-loader

- packages/server/core/src/plugin.ts
- packages/server/prod-server-new/src/index.ts
- packages/server/prod-server/src/server/index.ts
- packages/server/server-base/src/ServerCore.ts
- packages/server/server-base/src/adapters/node.ts
- packages/toolkit/types/server/context.d.ts
> feat: support beforeServerInit hook

- packages/document/main-doc/docs/en/guides/advanced-features/rspack-start.mdx
- packages/document/main-doc/docs/zh/guides/advanced-features/rspack-start.mdx
> docs: add guide about how to modify swc-loader configuration

- packages/document/module-doc/docs/en/api/config/build-config.mdx
- packages/document/module-doc/docs/zh/api/config/build-config.mdx
> docs(module-tools): fix info about declaration when enable svgr

- packages/document/module-doc/docs/en/guide/faq/basic.mdx
- packages/document/module-doc/docs/en/guide/faq/index.md
- packages/document/module-doc/docs/zh/guide/faq/basic.mdx
- packages/document/module-doc/docs/zh/guide/faq/index.md
> docs(module-tools): add basic faq

- packages/document/main-doc/docs/en/guides/advanced-features/rspack-start.mdx
- packages/document/main-doc/docs/zh/guides/advanced-features/rspack-start.mdx
- packages/generator/generators/rspack-generator/templates/modern.config.ts.handlebars
- doc: add debug mode introduce line
- template: update rspack template, not need <'rspack'> generics
> chore: update rspack content

- packages/server/plugin-polyfill/src/index.ts
- packages/server/prod-server-new/src/index.ts
- packages/server/server-base/src/ServerCore.ts
- packages/server/server-base/src/index.ts
- packages/server/server-base/src/types/index.ts
- packages/server/server-base/tests/middleware.test.ts
> feat: refractor polyfill plugin and create a test sample

- packages/server/core/src/base/ServerCore.ts
- packages/server/core/src/base/adapters/hono.ts
- packages/server/core/src/base/index.ts
- packages/server/core/src/base/types/index.ts
- packages/server/plugin-polyfill/src/index.ts
- packages/server/plugin-polyfill/tests/index.test.ts
- packages/server/prod-server-new/src/index.ts
> feat: use hono as default server core instance

- packages/document/builder-doc/docs/en/guide/advanced/rspack-start.mdx
- packages/document/builder-doc/docs/zh/guide/advanced/rspack-start.mdx
- packages/document/main-doc/docs/en/guides/advanced-features/rspack-start.mdx
- packages/document/main-doc/docs/zh/guides/advanced-features/rspack-start.mdx
> docs: fix webpack typo

- packages/server/core/src/base/ServerCore.ts
- packages/server/core/src/base/adapters/hono.ts
- packages/server/core/src/base/adapters/mock.ts
- packages/server/core/src/base/index.ts
- packages/server/core/src/base/libs/constants.ts
- packages/server/core/src/base/types/hono.ts
- packages/server/core/src/base/types/index.ts
- packages/server/core/src/core/plugin.ts
- packages/server/core/tests/base/fixtures/mock/cjs/config/mock/index.js
- packages/server/core/tests/base/fixtures/mock/disable-runtime/config/mock/index.ts
- packages/server/core/tests/base/fixtures/mock/disable/config/mock/index.ts
- packages/server/core/tests/base/fixtures/mock/exist/config/mock/index.ts
- packages/server/core/tests/base/fixtures/mock/module-error/config/mock/index.ts
- packages/server/core/tests/base/fixtures/mock/type-error/config/mock/index.ts
- packages/server/core/tests/base/fixtures/mock/zero/config/mock/index.ts
- packages/server/core/tests/base/helpers.ts
- packages/server/core/tests/base/middleware.test.ts
- packages/server/core/tests/base/mock.test.ts
> feat: mock middleware

- packages/server/core/src/base/adapters/mock.ts
- packages/server/core/src/base/adapters/node.ts
- packages/server/core/src/base/index.ts
- packages/server/core/src/base/renderHandler/index.ts
- packages/server/core/src/base/serverBase.ts
- packages/server/prod-server-new/src/index.ts
> refactor: server bind render handler & afterCreateNodeServer

- .changeset/short-wolves-battle.md
- packages/server/prod-server/src/libs/render/ssrCache/manager.ts
> fix(prod-server): ssr cache would return error result when use stream ssr

- packages/server/core/src/base/adapters/serverStatic.ts
- packages/server/core/src/base/libs/utils.ts
- packages/server/core/src/base/serverBase.ts
> fix: handle static asset can't found

- .changeset/short-crabs-hang.md
- packages/runtime/plugin-runtime/src/router/runtime/index.ts
> feat: reexport unstable_useviewtransitionstate

- packages/server/core/src/base/libs/utils.ts
- packages/server/core/src/base/libs/warmup.ts
- packages/server/core/src/base/renderHandler/index.ts
> feat: warm up ssr bundle

- packages/builder/uni-builder/src/shared/devServer.ts
- packages/server/core/package.json
- packages/server/core/src/base/index.ts
- packages/server/prod-server-new/package.json
- packages/server/prod-server-new/src/index.ts
- packages/server/server/package.json
- packages/server/server/src/createDevServer.ts
- packages/server/server/src/index.ts
- packages/server/server/src/server/devServer.ts
- packages/server/server/src/types.ts
- packages/solutions/app-tools/src/commands/dev.ts
- packages/solutions/app-tools/src/commands/serve.ts
- pnpm-lock.yaml
> feat: use new version of dev server

- packages/document/module-doc/docs/en/guide/faq/build.mdx
- packages/document/module-doc/docs/zh/guide/faq/build.mdx
> docs(module-tools): add faq about how to skip less or scss processing

- packages/builder/uni-builder/src/shared/devServer.ts
- packages/server/core/src/base/adapters/node.ts
- packages/server/core/src/base/index.ts
- packages/server/core/src/base/renderHandler/index.ts
- packages/server/prod-server-new/src/index.ts
- packages/server/server/package.json
- packages/server/server/src/createDevServer.ts
- packages/server/server/src/index.ts
- packages/server/server/src/types.ts
- packages/solutions/app-tools/src/commands/dev.ts
- packages/solutions/app-tools/src/commands/serve.ts
- pnpm-lock.yaml
> feat: extract createProdServer

- packages/server/core/src/base/renderHandler/index.ts
- packages/server/core/src/base/serverBase.ts
> fix: csr render

- packages/server/core/src/base/middlewares/customServer.ts
- packages/server/core/src/base/renderHandler/index.ts
- packages/server/core/src/base/renderHandler/ssrHandler.ts
- packages/server/core/src/base/serverBase.ts
- packages/server/core/src/base/types/index.ts
- packages/server/core/src/core/plugin.ts
- pnpm-lock.yaml
- add logger
- fix: run ssr mode
> feat: add logger

- packages/runtime/plugin-runtime/src/core/compatible.tsx
- packages/runtime/plugin-runtime/src/router/runtime/plugin.node.tsx
- packages/runtime/plugin-runtime/src/ssr/serverRender/tracker.ts
- packages/server/core/src/base/libs/customServer.ts
- packages/server/core/src/base/libs/hook/base.ts
- packages/server/core/src/base/middlewares/customServer.ts
- packages/server/core/src/base/renderHandler/index.ts
- packages/server/core/src/base/renderHandler/ssrHandler.ts
- packages/server/prod-server/src/libs/render/ssr.ts
- packages/toolkit/types/server/context.d.ts
> fix: handle TODO & FIXME

- packages/server/core/package.json
- packages/server/core/src/base/adapters/hono.ts
- packages/server/core/src/base/index.ts
- packages/server/core/src/base/serverBase.ts
- packages/server/server/src/createDevServer.ts
> feat: add connectMid2HonoMid

- packages/server/core/package.json
- packages/server/core/src/base/adapters/hono.ts
- packages/server/core/src/base/index.ts
- packages/server/core/src/base/renderHandler/index.ts
- packages/server/prod-server/src/type.ts
- packages/server/server/src/createDevServer.ts
- pnpm-lock.yaml
> feat: add dev middlewares

- packages/devtools/client/src/components/Devtools/Button.module.scss
- packages/devtools/client/src/components/Devtools/Button.tsx
- packages/devtools/client/src/components/Devtools/Capsule.module.scss
- packages/devtools/client/src/components/Devtools/Capsule.tsx
- packages/devtools/client/src/utils/promise.ts
- packages/devtools/client/src/utils/react-devtools.ts
https://github.com/web-infra-dev/modern.js/assets/18379948/d257137c-d3af-42bb-8b8d-0e23fd517abd
> feat(devtools): toggle the display of devtools while inspecting React elements

- packages/server/core/src/base/adapters/mock.ts
- packages/server/core/src/base/adapters/node.ts
- packages/server/core/src/base/index.ts
- packages/server/server/src/createDevServer.ts
- packages/solutions/app-tools/src/commands/dev.ts
- packages/solutions/app-tools/src/commands/serve.ts
> feat: add watcher

- packages/server/core/src/base/libs/constants.ts
- packages/server/core/src/base/libs/customServer.ts
- packages/server/core/src/base/libs/hook/template.ts
- packages/server/core/src/base/libs/utils.ts
- packages/server/core/src/base/middlewares/customServer.ts
- packages/server/core/src/base/renderHandler/ssrHandler.ts
> feat: support inject serverData

- packages/server/core/src/base/adapters/node.ts
- packages/server/core/src/base/serverBase.ts
- packages/server/server/src/createDevServer.ts
> feat: support api handler hot reload

- packages/server/core/src/base/middlewares/customServer.ts
- packages/server/core/src/base/renderHandler/index.ts
- packages/server/core/src/base/renderHandler/ssrHandler.ts
- packages/toolkit/types/server/context.d.ts
> fix: resolve TODO & FIXME

- packages/document/main-doc/docs/en/guides/advanced-features/rsbuild-plugin.mdx
- packages/document/main-doc/docs/zh/guides/advanced-features/rsbuild-plugin.mdx
- packages/document/module-doc/docs/en/plugins/official-list/overview.md
Introduce Rsbuild Plugin and Official Plugins
> docs: add rsbuild-plugin guide

- packages/server/core/package.json
- packages/server/core/tests/base/loadConfig.test.ts
- pnpm-lock.yaml
> fix: remove @modern-js/core from @modern-js/server-core

- packages/server/core/jest.config.js
- packages/server/core/src/base/libs/utils.ts
- packages/server/core/src/base/middlewares/customServer.ts
- packages/server/core/src/base/renderHandler/index.ts
- packages/server/core/src/base/renderHandler/ssrCache.ts
- packages/server/core/src/base/renderHandler/ssrHandler.ts
- packages/server/core/src/base/types/index.ts
- packages/server/core/tests/base/helpers.ts
- packages/server/core/tests/base/middleware.test.ts
- packages/server/core/tests/base/mock.test.ts
- packages/server/core/tests/base/render.test.ts
- packages/server/prod-server/src/libs/render/ssr.ts
> feat: support ssr cache && fix unit test

- packages/builder/builder-rspack-provider/src/core/startDevServer.ts
- packages/builder/builder-shared/src/prodServer.ts
- packages/builder/builder-webpack-provider/src/core/startDevServer.ts
- packages/builder/uni-builder/src/shared/devServer.ts
- packages/server/core/src/base/renderHandler/ssrHandler.ts
- packages/server/prod-server/src/workerServer.ts
- packages/server/server/src/createDevServer.ts
- packages/solutions/app-tools/src/commands/dev.ts
- tests/integration/ssr/tests/preload.test.ts
> fix: types error && test error

- packages/server/core/src/base/libs/utils.ts
- packages/server/core/src/base/renderHandler/index.ts
- packages/server/core/src/base/renderHandler/ssrHandler.ts
- tests/integration/ssr/fixtures/base/src/routes/layout.loader.ts
- tests/integration/ssr/fixtures/base/src/routes/layout.tsx
> fix: ssr cache & injectSeverData

- packages/document/module-doc/docs/en/api/config/build-config.mdx
- packages/document/module-doc/docs/zh/api/config/build-config.mdx
> docs(module-tools): fix code demo about style.inject

- packages/builder/uni-builder/package.json
- packages/builder/uni-builder/src/shared/devServer.ts
- packages/cli/plugin-data-loader/src/runtime/index.ts
- packages/cli/plugin-data-loader/src/server/index.ts
- packages/server/core/src/base/adapters/monitor.ts
- packages/server/core/src/base/adapters/node.ts
- packages/server/core/src/base/index.ts
- packages/server/core/src/base/middlewares/dataHandler.ts
- packages/server/core/src/base/middlewares/index.ts
- packages/server/core/src/base/serverBase.ts
- packages/server/core/src/base/types/hono.ts
- packages/server/core/src/base/types/index.ts
- packages/server/prod-server-new/src/error.ts
- packages/server/prod-server-new/src/index.ts
- packages/server/server/src/createDevServer.ts
- packages/server/server/src/types.ts
- packages/solutions/app-tools/src/commands/dev.ts
- pnpm-lock.yaml
- tests/integration/routes/modern.config.ts
> feat: add loader handler and optimize create server

- packages/builder/builder-rspack-provider/src/core/devMiddleware.ts
- packages/builder/builder-rspack-provider/src/core/startDevServer.ts
- packages/builder/builder-webpack-provider/src/core/devMiddleware.ts
- packages/builder/builder-webpack-provider/src/core/startDevServer.ts
- packages/builder/uni-builder/package.json
- packages/builder/uni-builder/src/shared/devServer.ts
- packages/server/core/package.json
- packages/server/core/src/base/index.ts
- packages/server/core/src/base/libs/customServer.ts
- packages/server/core/src/base/middlewares/customServer.ts
- packages/server/core/src/base/renderHandler/index.ts
- packages/server/core/src/base/renderHandler/ssrHandler.ts
- packages/server/core/src/base/types/index.ts
- packages/server/prod-server-new/package.json
- packages/server/prod-server-new/src/index.ts
- packages/server/server/package.json
- packages/server/server/src/createDevServer.ts
- packages/server/server/src/index.ts
- packages/server/server/src/server/devServer.ts
- packages/server/server/src/server/devServerOld.ts
- packages/server/server/src/server/index.ts
- packages/server/server/src/types.ts
- packages/solutions/app-tools/src/commands/dev.ts
- packages/solutions/app-tools/src/utils/createServer.ts
- pnpm-lock.yaml
> fix: type errors

- packages/document/module-doc/docs/en/guide/faq/build.mdx
- packages/document/module-doc/docs/zh/guide/faq/build.mdx
> docs(module-tools): add faq about build

- packages/server/core/src/base/libs/hook/base.ts
- packages/server/core/src/base/middlewares/customServer.ts
- packages/server/core/src/base/middlewares/dataHandler.ts
- packages/server/core/src/base/renderHandler/index.ts
- packages/server/core/src/base/renderHandler/ssrHandler.ts
- packages/server/core/src/base/serverBase.ts
- packages/server/core/src/base/types/index.ts
- packages/server/plugin-server/src/server.ts
- packages/server/prod-server-new/src/index.ts
- packages/solutions/app-tools/src/commands/dev.ts
- packages/solutions/app-tools/src/commands/serve.ts
- tests/integration/server-hook/router/tests/index.test.ts
> fix: some bugs

- .changeset/cool-apples-exercise.md
- packages/builder/uni-builder/src/shared/parseCommonConfig.ts
- packages/builder/uni-builder/tests/__snapshots__/parseConfig.test.ts.snap
- packages/builder/uni-builder/tests/parseConfig.test.ts
fix deepmerge cause plugin apply undefined
> fix(uni-builder): deepmerge cause plugin apply undefined

- packages/document/module-doc/docs/en/guide/basic/publish-your-project.mdx
- packages/document/module-doc/docs/zh/guide/basic/publish-your-project.mdx
> docs(module-tools): add slot for release npm in monorepo

- packages/server/core/src/base/adapters/env.ts
- packages/server/core/src/base/index.ts
- packages/server/core/src/base/serverBase.ts
- packages/server/prod-server-new/src/index.ts
> fix: loadServeEnv in different runtime

- .github/workflows/integration-test-Linux.yml
- .github/workflows/integration-test-Windows.yml
> CI: should run integration test when bump rsbuild

- packages/generator/generator-common/package.json
- packages/generator/generator-plugin/package.json
- packages/generator/generator-utils/package.json
- packages/generator/generators/base-generator/package.json
- packages/generator/generators/bff-generator/package.json
- packages/generator/generators/changeset-generator/package.json
- packages/generator/generators/dependence-generator/package.json
- packages/generator/generators/entry-generator/package.json
- packages/generator/generators/generator-generator/package.json
- packages/generator/generators/module-doc-generator/package.json
- packages/generator/generators/module-generator/package.json
- packages/generator/generators/module-test-generator/package.json
- packages/generator/generators/monorepo-generator/package.json
- packages/generator/generators/mwa-generator/package.json
- packages/generator/generators/packages-generator/package.json
- packages/generator/generators/repo-generator/package.json
- packages/generator/generators/router-v5-generator/package.json
- packages/generator/generators/rspack-generator/package.json
- packages/generator/generators/server-generator/package.json
- packages/generator/generators/ssg-generator/package.json
- packages/generator/generators/storybook-generator/package.json
- packages/generator/generators/storybook-next-generator/package.json
- packages/generator/generators/tailwindcss-generator/package.json
- packages/generator/generators/test-generator/package.json
- packages/generator/generators/upgrade-generator/package.json
- packages/generator/new-action/package.json
- packages/generator/sandpack-react/package.json
- packages/toolkit/create/package.json
- packages/toolkit/upgrade/package.json
- pnpm-lock.yaml
> chore: bump codesmith 2.3.4

- packages/server/core/src/base/adapters/bff.ts
- packages/server/core/src/base/adapters/node.ts
- packages/server/core/src/base/index.ts
- packages/server/core/src/base/middlewares/customServer.ts
- packages/server/core/src/base/serverBase.ts
- packages/server/core/src/core/plugin.ts
- packages/server/plugin-express/src/plugin.ts
- packages/server/plugin-koa/src/plugin.ts
- packages/server/prod-server-new/src/index.ts
- packages/server/server/src/createDevServer.ts
> fix: bind bff handlers

- packages/server/core/src/base/adapters/mock.ts
- packages/server/core/src/base/middlewares/customServer.ts
- packages/server/core/src/base/serverBase.ts
- packages/server/core/src/base/types/hono.ts
- packages/server/core/src/base/types/index.ts
- packages/server/core/src/core/plugin.ts
- packages/server/prod-server/src/server/modernServer.ts
- packages/toolkit/types/server/context.d.ts
> fix: types

- packages/devtools/client/modern.config.ts
- packages/devtools/client/src/entries/client/routes/doctor/layout.config.ts
- packages/devtools/client/src/entries/client/routes/doctor/page.module.scss
- packages/devtools/client/src/entries/client/routes/doctor/page.tsx
- packages/devtools/client/src/entries/client/routes/overview/page.module.scss
> feat(devtools): styling doctor tab of devtools

- packages/document/builder-doc/package.json
- packages/document/main-doc/package.json
- packages/document/module-doc/package.json
- pnpm-lock.yaml
> feat: update Rspress v1.11.2

- packages/server/core/src/base/adapters/monitor.ts
- packages/server/core/src/base/libs/constants.ts
- packages/server/core/src/base/libs/customServer.ts
- packages/server/core/src/base/middlewares/customServer.ts
- packages/server/core/src/base/renderHandler/index.ts
- packages/server/core/src/base/renderHandler/render.ts
- packages/server/prod-server/src/server/modernServer.ts
- packages/toolkit/types/server/utils.d.ts
- tests/integration/ssg/tests/nested-routes.test.ts
> fix: errors & support report

- .changeset/smooth-donuts-bow.md
- packages/review/eslint-config-app/package.json
- packages/solutions/app-tools/package.json
- pnpm-lock.yaml
> fix(deps): missing @rsbuild/core peer dependency

- packages/server/core/src/base/serverBase.ts
- tests/integration/server-config/plugins/serverPlugin.ts
> fix: load server-runtime.config correctly

- packages/document/module-doc/docs/en/guide/basic/use-module-doc.mdx
- packages/document/module-doc/docs/zh/guide/basic/use-module-doc.mdx
with https://github.com/web-infra-dev/rspress/pull/639
> docs(module-doc): update options

- packages/server/core/src/base/adapters/node/hono.ts
- packages/server/core/src/base/adapters/node/node.ts
- packages/server/core/src/base/index.ts
- packages/server/core/src/index.ts
- packages/server/plugin-express/src/plugin.ts
- packages/server/plugin-koa/src/plugin.ts
- tests/integration/bff-koa/tests/index.test.ts
> feat: support render by bff plugins

- packages/server/core/src/base/adapters/node/middlewares/serverStatic.ts
> fix: server-static middlewares

- packages/server/server/src/createDevServer.ts
- packages/server/server/src/dev-tools/register/index.ts
- packages/server/server/src/utils.ts
- tests/integration/routes/modern.config.ts
- tests/integration/server-config/tests/index.test.ts
> fix: should call beforeServerInit in dev-server

- packages/server/core/src/base/adapters/node/index.ts
- packages/server/core/src/base/index.ts
- packages/server/core/src/base/middlewares/dataHandler.ts
- packages/server/core/src/base/middlewares/index.ts
- packages/server/core/src/base/renderHandler/render.ts
- packages/server/core/src/base/renderHandler/ssrCache.ts
- packages/server/prod-server-new/src/index.ts
- packages/server/server/src/createDevServer.ts
> refactor: server-base

- packages/server/core/src/base/adapters/node/index.ts
- packages/server/core/src/base/adapters/node/middlewares/index.ts
- packages/server/core/src/base/adapters/node/polyfills/index.ts
- packages/server/core/src/base/adapters/node/polyfills/install.ts
- packages/server/core/src/base/renderHandler/render.ts
- packages/server/prod-server-new/src/index.ts
- tests/integration/bff-koa/modern.config.ts
> fix: add getSetCookie for Headers

- packages/server/core/jest.config.js
- packages/server/core/src/base/middlewares/renderHandler/ssrRender.ts
- packages/server/core/tests/base/fixtures/data/bundles/user-server-loaders.js
- packages/server/core/tests/base/fixtures/render/ssr/bundles/main.js
- packages/server/core/tests/base/fixtures/render/ssr/bundles/user.js
- packages/server/core/tests/base/fixtures/render/ssr/index.html
- packages/server/core/tests/base/fixtures/render/ssr/route.json
- packages/server/core/tests/base/fixtures/render/ssr/user.html
- packages/server/core/tests/base/middlewares/dataHandler.test.ts
- packages/server/core/tests/base/middlewares/mock.test.ts
- packages/server/core/tests/base/middlewares/render.test.ts
> chore: add more test

- packages/server/core/jest.config.js
- packages/server/core/src/base/utils/transformStream.ts
- packages/server/plugin-express/jest.config.js
- packages/server/plugin-express/tests/lambdaMode.test.ts
- packages/server/plugin-express/tests/setup.ts
- packages/server/plugin-koa/jest.config.js
- packages/server/plugin-koa/tests/api.test.ts
- packages/server/plugin-koa/tests/setup.ts
- packages/server/plugin-server/tests/index.test.ts
- packages/server/server/src/helpers/devOptions.ts
- packages/solutions/app-tools/jest.config.js
- scripts/jest-config/jest.config.js
- tests/jest-ut.config.js
> fix: pass unit tests

- packages/cli/core/src/config/loadConfig.ts
- packages/cli/core/src/context.ts
- packages/cli/core/src/createCli.ts
- packages/cli/core/src/types/coreOptions.ts
- packages/cli/core/src/utils/initAppDir.ts
> feat(core): add global cli feature

- packages/server/core/package.json
- packages/server/core/src/base/middlewares/dataHandler.ts
- packages/server/core/src/base/middlewares/renderHandler/index.ts
- packages/server/core/src/base/middlewares/renderHandler/render.ts
- packages/server/core/src/base/middlewares/renderHandler/ssrCache.ts
- packages/server/core/src/base/middlewares/renderHandler/ssrRender.ts
- packages/server/core/src/base/serverBase.ts
- packages/server/core/src/base/utils/index.ts
- packages/server/core/src/base/utils/path.ts
- packages/server/core/src/base/utils/serverConfig.ts
- packages/server/core/tests/base/middlewares/dataHandler.test.ts
- packages/server/core/tests/base/utils/serverConfig.test.ts
- packages/server/prod-server-new/src/index.ts
- pnpm-lock.yaml
> fix: remove server-base node module dependency

- .changeset/shiny-parents-explain.md
- packages/document/main-doc/docs/en/configure/app/server/ssr.mdx
- packages/document/main-doc/docs/zh/configure/app/server/ssr.mdx
- packages/runtime/plugin-runtime/src/ssr/index.tsx
- tests/integration/routes/modern.config.ts
> fix: ssr.inlineScript shouldn't works in streaming ssr

- packages/server/core/src/base/middlewares/renderHandler/index.ts
- packages/server/core/src/base/middlewares/renderHandler/render.ts
- packages/server/prod-server-new/src/index.ts
- packages/server/server/src/createDevServer.ts
> fix: pass templates from every prod-server

- packages/generator/generator-common/package.json
- packages/generator/generator-plugin/package.json
- packages/generator/generator-utils/package.json
- packages/generator/generators/base-generator/package.json
- packages/generator/generators/bff-generator/package.json
- packages/generator/generators/changeset-generator/package.json
- packages/generator/generators/dependence-generator/package.json
- packages/generator/generators/entry-generator/package.json
- packages/generator/generators/generator-generator/package.json
- packages/generator/generators/module-doc-generator/package.json
- packages/generator/generators/module-generator/package.json
- packages/generator/generators/module-test-generator/package.json
- packages/generator/generators/monorepo-generator/package.json
- packages/generator/generators/mwa-generator/package.json
- packages/generator/generators/packages-generator/package.json
- packages/generator/generators/repo-generator/package.json
- packages/generator/generators/router-v5-generator/package.json
- packages/generator/generators/server-generator/package.json
- packages/generator/generators/ssg-generator/package.json
- packages/generator/generators/storybook-generator/package.json
- packages/generator/generators/storybook-next-generator/package.json
- packages/generator/generators/tailwindcss-generator/package.json
- packages/generator/generators/test-generator/package.json
- packages/generator/generators/upgrade-generator/package.json
- packages/generator/new-action/package.json
- packages/generator/sandpack-react/package.json
- packages/toolkit/create/package.json
- packages/toolkit/upgrade/package.json
- pnpm-lock.yaml
> chore: bump codesmith 2.3.5

- packages/document/builder-doc/package.json
- packages/document/main-doc/package.json
- packages/document/module-doc/package.json
- pnpm-lock.yaml
> chore: update rspress version to 1.12.3

- packages/solutions/module-tools/src/builder/esbuild/adapter.ts
Noticed a small typo in a comment while reading some source code
n/a
> Fix typo in comment in adapter.ts

- .github/workflows/update-rsbuild.yml
rsbuild updates always cause config snapshot updates 
https://github.com/web-infra-dev/modern.js/actions/runs/8063614523/job/22025805317
> chore(workflow): support auto update rsbuild snapshot

- packages/server/core/src/base/adapters/node/hono.ts
- packages/server/core/src/base/adapters/node/middlewares/index.ts
- packages/server/core/src/base/adapters/node/middlewares/templates.ts
- packages/server/core/src/base/index.ts
- packages/server/core/src/base/middlewares/renderHandler/index.ts
- packages/server/core/src/base/middlewares/renderHandler/render.ts
- packages/server/core/src/core/render.ts
- packages/server/plugin-express/src/plugin.ts
- packages/server/plugin-koa/src/plugin.ts
- packages/server/prod-server/src/index.ts
- packages/toolkit/runtime-utils/package.json
> feat: inject html templates by middlewares

- packages/server/server/src/createDevServer.ts
> fix: should not start dev server after compilation

- packages/server/core/tests/base/middlewares/render.test.ts
> fix: render test cases

- .changeset/early-mugs-double.md
- packages/document/module-doc/docs/en/api/config/build-config.mdx
- packages/document/module-doc/docs/zh/api/config/build-config.mdx
- packages/solutions/module-tools/src/builder/feature/asset.ts
- packages/solutions/module-tools/src/constants/build.ts
- packages/solutions/module-tools/src/types/config/index.ts
- pnpm-lock.yaml
- tests/integration/module/fixtures/build/asset/asset.test.ts
- tests/integration/module/fixtures/build/asset/name/name.config.ts
- tests/integration/module/fixtures/build/asset/name/package.json
- tests/integration/module/fixtures/build/asset/name/src/index.jsx
> feat(module-tools): add support for custom asset name

- .changeset/eleven-kids-exist.md
- packages/generator/generator-utils/src/utils/getGeneratorPath.ts
- packages/generator/generator-utils/src/utils/index.ts
- packages/generator/generators/generator-generator/src/index.ts
- packages/generator/generators/module-doc-generator/src/index.ts
- packages/generator/generators/module-generator/src/index.ts
- packages/generator/generators/module-test-generator/src/index.ts
- packages/generator/generators/monorepo-generator/src/index.ts
- packages/generator/generators/mwa-generator/src/index.ts
- packages/generator/generators/repo-generator/src/index.ts
- packages/generator/generators/router-v5-generator/src/index.ts
- packages/generator/generators/server-generator/src/index.ts
- packages/generator/generators/ssg-generator/src/index.ts
- packages/generator/generators/storybook-generator/src/index.ts
- packages/generator/generators/storybook-next-generator/src/index.ts
- packages/generator/generators/tailwindcss-generator/src/index.ts
- packages/generator/generators/test-generator/src/index.ts
> chore(generator): extract getGeneratorPath function to generator-utils

- packages/generator/generator-utils/src/utils/getGeneratorPath.ts
- packages/generator/generators/module-doc-generator/src/index.ts
- packages/generator/generators/module-generator/src/index.ts
- packages/generator/generators/module-test-generator/src/index.ts
- packages/generator/generators/monorepo-generator/src/index.ts
- packages/generator/generators/mwa-generator/src/index.ts
- packages/generator/generators/repo-generator/src/index.ts
- packages/generator/generators/router-v5-generator/src/index.ts
- packages/generator/generators/server-generator/src/index.ts
- packages/generator/generators/ssg-generator/src/index.ts
- packages/generator/generators/storybook-generator/src/index.ts
- packages/generator/generators/storybook-next-generator/src/index.ts
- packages/generator/generators/tailwindcss-generator/src/index.ts
- packages/generator/generators/test-generator/src/index.ts
fix https://github.com/web-infra-dev/modern.js/pull/5465
> fix: generator testing

- README.md
- README.zh-CN.md
> chore: update benchmark link

- packages/document/main-doc/docs/en/guides/advanced-features/ssr/cache.mdx
- packages/document/main-doc/docs/zh/guides/advanced-features/ssr/cache.mdx
> docs: cache identify

- .changeset/small-lies-grin.md
- packages/solutions/module-tools/src/builder/feature/redirect.ts
> fix(module-tools): new matcher to match alias when exist comment in dynamic import

- package.json
- pnpm-lock.yaml
> chore: overrides rspress to solve error in website

- packages/server/core/src/base/index.ts
- packages/server/core/src/base/middlewares/renderHandler/render.ts
- packages/server/core/src/base/middlewares/renderHandler/ssrRender.ts
- packages/server/core/src/index.ts
> fix: export more types && fix some problems

- .changeset/selfish-peas-grab.md
- packages/devtools/client/src/entries/client/routes/external/$.tsx
- packages/devtools/client/src/entries/client/routes/layout.data.tsx
- packages/devtools/client/src/entries/client/routes/state.tsx
- packages/devtools/client/src/utils/pluggable.ts
- packages/devtools/kit/src/client.ts
- packages/devtools/kit/src/runtime-globals.ts
> feat(devtools): support runtime plugins

- .changeset/four-feet-joke.md
- packages/server/bff-core/package.json
- pnpm-lock.yaml
> fix: type-fest shouldn't be a devDependency

- packages/server/core/src/base/adapters/node/node.ts
- packages/server/prod-server/package.json
- packages/server/prod-server/src/handler.ts
- packages/server/prod-server/src/index.ts
- packages/server/prod-server/src/types.ts
> feat: prod-server export handler

- packages/server/plugin-server/src/server.ts
> fix: errors

- .changeset/green-years-deliver.md
- packages/document/main-doc/docs/zh/guides/basic-features/routes.mdx
> docs: fix loader arrow function syntax

- .changeset/three-peas-search.md
- packages/runtime/plugin-runtime/src/ssr/index.tsx
- packages/server/prod-server/src/libs/render/ssrCache/manager.ts
- packages/toolkit/runtime-utils/package.json
- packages/toolkit/runtime-utils/src/url.ts
- packages/toolkit/runtime-utils/tests/url.test.ts
Relation issue: https://github.com/web-infra-dev/modern.js/issues/5517
> fix: normalize pathname

- .changeset/fifty-planets-live.md
- packages/server/prod-server/src/workerServer.ts
- packages/server/server/src/server/devServer.ts
- packages/server/server/src/server/devServerOld.ts
- packages/server/server/src/server/workerSSRRender.ts
- packages/server/server/src/types.ts
> fix(worker): worker can run correctly when dev and prod

- .changeset/curly-boxes-repeat.md
- packages/runtime/plugin-runtime/src/ssr/index.tsx
> fix: ssr reload infinite

- packages/document/main-doc/docs/en/guides/troubleshooting/builder.mdx
- packages/document/main-doc/docs/zh/guides/troubleshooting/builder.mdx
> docs: add type checker range FAQ

- packages/server/core/package.json
- packages/server/core/src/base/adapters/node/index.ts
- packages/server/core/src/base/index.ts
- packages/server/core/src/base/middlewares/customServer/context.ts
- packages/server/core/src/base/middlewares/customServer/index.ts
- packages/server/core/src/base/middlewares/renderHandler/index.ts
- packages/server/core/src/base/serverBase.ts
- packages/server/core/src/core/hono.ts
- packages/server/core/src/core/server.ts
- packages/server/core/src/index.ts
- packages/server/plugin-express/src/plugin.ts
- packages/server/plugin-express/tests/setup.ts
- packages/server/plugin-koa/src/plugin.ts
- packages/server/plugin-koa/tests/setup.ts
- packages/server/prod-server/src/handler.ts
- packages/server/prod-server/src/index.ts
- packages/server/server/src/createDevServer.ts
- packages/server/server/src/helpers/index.ts
> refactor: server-core separate node & worker code

- packages/server/core/src/base/adapters/node/index.ts
- packages/server/core/src/base/adapters/node/middlewares/templates.ts
- packages/server/core/src/base/constants.ts
- packages/server/core/src/base/middlewares/renderHandler/ssrCache.ts
- packages/server/core/src/base/middlewares/renderHandler/ssrRender.ts
- packages/server/core/tests/base/adapters/loadEnv.test.ts
- packages/server/core/tests/base/middlewares/ssrCache.test.ts
- packages/server/core/tests/base/utils/serverConfig.test.ts
- packages/server/core/tests/core/loadPlugin.test.ts
- packages/server/core/tests/setup.ts
> fix: ssr cache should return response header

- .github/workflows/release.yml
After the separation of rsbuild (formerly modern.js builder), we no longer need automatic update logic.
> chore: remove auto trigger action

- packages/devtools/plugin/package.json
- packages/devtools/plugin/src/cli.ts
- pnpm-lock.yaml
- tests/integration/devtools/modern.config.ts
- Refactor server of devtools plugin by using honojs.
- Add new cookie api.
> feat(devtools/plugin): new cookie api

- packages/server/core/src/base/adapters/node/middlewares/serverPublic.ts
- packages/server/core/src/base/adapters/node/middlewares/serverStatic.ts
- packages/server/prod-server/src/handler.ts
- packages/toolkit/runtime-utils/src/node/fileReader.ts
> feat: support server public

- .changeset/polite-tips-kick.md
- packages/generator/generators/tailwindcss-generator/.eslintignore
- packages/generator/generators/tailwindcss-generator/templates/ts-template/tailwind.config.ts
- packages/generator/generators/tailwindcss-generator/tsconfig.json
Ref: https://tailwindcss.com/docs/configuration#using-esm-or-type-script
Avoid lint error `@typescript-eslint/consistent-type-assertions`
> fix(generator): tailwindcss config file type

- packages/cli/plugin-data-loader/package.json
- packages/cli/plugin-data-loader/src/runtime/index.ts
- packages/runtime/plugin-runtime/package.json
- packages/runtime/plugin-runtime/src/router/runtime/fetch.node.tsx
- packages/runtime/plugin-runtime/src/router/runtime/fetch.tsx
- packages/runtime/plugin-runtime/src/router/runtime/fetch.worker.tsx
- packages/runtime/plugin-runtime/src/router/runtime/plugin.node.tsx
- packages/server/core/package.json
- packages/server/core/src/base/adapters/node/polyfills/install.ts
- packages/server/core/src/base/adapters/node/polyfills/stream.ts
- packages/server/core/src/base/middlewares/customServer/index.ts
- packages/server/core/src/base/middlewares/renderHandler/render.ts
- packages/server/core/src/base/middlewares/renderHandler/ssrRender.ts
- packages/server/core/src/base/utils/transformStream.ts
- pnpm-lock.yaml
> fix: routes need serverData when csr

- .changeset/eight-walls-serve.md
- packages/document/module-doc/docs/en/guide/basic/test-your-project.mdx
- packages/document/module-doc/docs/zh/guide/basic/test-your-project.mdx
> docs(module): fix test example

- packages/server/core/src/base/adapters/node/middlewares/serverPublic.ts
- packages/server/core/src/base/middlewares/renderHandler/render.ts
> fix: route match

- packages/runtime/plugin-testing/src/cli/bff/app.ts
- packages/server/core/src/base/adapters/node/node.ts
- packages/server/prod-server/package.json
- packages/server/prod-server/src/index.ts
- packages/server/prod-server/src/init.ts
> fix: load webHandler & nodeReuqestListener to nodeServer

- packages/server/server/src/createDevServer.ts
- packages/server/server/src/helpers/devOptions.ts
> fix: dev proxy can not validate

- packages/devtools/client/package.json
- packages/devtools/client/src/entries/client/routes/storage.preset/page.data.tsx
- packages/devtools/client/src/entries/client/routes/storage.preset/page.module.scss
- packages/devtools/client/src/entries/client/routes/storage.preset/page.tsx
- packages/devtools/client/src/entries/mount/state.ts
- packages/devtools/client/src/types/rpc.ts
- packages/devtools/kit/src/server.ts
- packages/devtools/kit/src/storage-preset.ts
- packages/devtools/plugin/src/cli.ts
- packages/devtools/plugin/src/rpc/index.ts
- packages/devtools/plugin/src/types/config.ts
- packages/devtools/plugin/src/utils/config.ts
- pnpm-lock.yaml
- tests/integration/devtools/modern.devtools.json
- Cookie Manage API
- Basic storage preset page UI.
> feat(devtools): basic storage preset page

- packages/server/core/src/base/middlewares/customServer/context.ts
- packages/server/core/src/base/middlewares/customServer/index.ts
- packages/server/core/src/base/middlewares/renderHandler/index.ts
- packages/server/core/src/base/middlewares/renderHandler/render.ts
- packages/server/core/src/base/middlewares/renderHandler/ssrRender.ts
- packages/server/core/src/core/render.ts
- packages/server/core/src/core/server.ts
- packages/toolkit/types/server/context.d.ts
> fix: add locals

- .changeset/metal-plums-dress.md
- packages/runtime/plugin-runtime/src/ssr/index.tsx
> fix: when router does't exist, no pathname detection

- .changeset/green-beds-trade.md
- packages/cli/plugin-proxy/src/index.ts
- packages/document/main-doc/docs/en/components/global-proxy.mdx
- packages/document/main-doc/docs/zh/components/global-proxy.mdx
> chore(plugin-proxy): deprecated warnings

- packages/document/builder-doc/package.json
- packages/document/main-doc/package.json
- packages/document/module-doc/package.json
- pnpm-lock.yaml
> feat: update rspress v1.16.0

- packages/runtime/plugin-runtime/src/ssr/index.tsx
- packages/server/core/src/base/middlewares/customServer/base.ts
- packages/server/core/src/base/middlewares/renderHandler/render.ts
- packages/server/core/src/base/middlewares/renderHandler/ssrRender.ts
- pnpm-lock.yaml
- tests/integration/ssr/fixtures/fallback/modern.config.ts
- tests/integration/ssr/fixtures/fallback/package.json
- tests/integration/ssr/fixtures/fallback/server/index.ts
- tests/integration/ssr/tests/base-fallback.test.ts
> fix: resolved reload infinite & custom server request can be set

- packages/server/core/src/base/middlewares/customServer/base.ts
- packages/server/core/src/base/middlewares/renderHandler/ssrRender.ts
- packages/server/core/tests/base/middlewares/render.test.ts
- tests/integration/server-hook/request/server/index.ts
> fix: get pathname from nodeReq

- .changeset/grumpy-rats-matter.md
- packages/runtime/plugin-runtime/src/document/cli/index.ts
title tag should only be once in an html file
> fix: make sure only one title tag

- .github/workflows/release-pull-request.yml
> chore: remove schedule on release pr workflow

- packages/server/core/src/base/adapters/node/middlewares/serverStatic.ts
> fix: correct the filename in static middleware

- .changeset/stale-ligers-hug.md
- packages/devtools/client/src/components/Breadcrumbs.tsx
Checkout from [dev/devtools-storage-presets](https://github.com/web-infra-dev/modern.js/blob/57cd79c7c6d98b852a8114640f458d4b01e7ab4a/packages/devtools/client/src/components/Breadcrumbs.tsx).
> fix(devtools): failed to render breadcrumb

- packages/server/core/src/base/middlewares/renderHandler/index.ts
> fix: match routes into middlewares

- .changeset/honest-tables-mate.md
- packages/document/builder-doc/docs/en/config/source/alias.md
- packages/document/builder-doc/docs/zh/config/source/alias.md
remove dead link in builder-doc
> docs: fix dead link in source.alias

- packages/server/core/src/base/middlewares/customServer/index.ts
> fix: middlewares maybe send res already

- .changeset/modern-buttons-retire.md
- packages/module/plugin-module-babel/modern.config.js
- packages/module/plugin-module-babel/src/index.ts
- packages/solutions/module-tools/package.json
- scripts/build/src/index.js
> fix(plugin-module-babel): bundle utils which in module tools to avoid not found error

- packages/module/plugin-module-babel/modern.config.js
- scripts/build/src/index.js
#5596  may break the tests and can not use.
> chore: update module-plugin-babel outputs

- .changeset/fast-needles-give.md
- packages/solutions/module-tools/src/utils/dts.ts
> fix(module-tools): new matcher to match alias in dts

- packages/cli/plugin-data-loader/src/cli/loader.ts
> fix: target may be an array

- packages/runtime/plugin-runtime/src/ssr/serverRender/tracker.ts
- packages/server/core/src/base/middlewares/customServer/index.ts
- packages/server/core/src/base/middlewares/renderHandler/index.ts
> fix: support disableCustomHook & adapter ssr logger

- packages/server/core/src/base/index.ts
- packages/server/core/src/base/middlewares/index.ts
- packages/server/core/src/base/middlewares/logger.ts
- packages/server/prod-server/src/init.ts
> feat: log request info

- packages/server/core/src/base/adapters/node/polyfills/install.ts
- packages/server/core/src/base/middlewares/logger.ts
- tests/jest-ut.config.js
> fix: the problem of no test case matching on windows os

- packages/cli/plugin-data-loader/package.json
- packages/document/builder-doc/docs/en/shared/nodeVersion.md
- packages/document/builder-doc/docs/zh/shared/nodeVersion.md
- packages/document/main-doc/docs/en/guides/troubleshooting/dependencies.mdx
- packages/document/main-doc/docs/zh/guides/troubleshooting/dependencies.mdx
- packages/server/core/package.json
- packages/server/prod-server/package.json
> chore: modify the minimum supported node version

- .changeset/fluffy-deers-walk.md
> chore: add changeset

- packages/runtime/plugin-runtime/tests/ssr/serverRender/renderToStream/index.test.ts
- packages/runtime/plugin-runtime/tests/ssr/serverRender/tracker.test.ts
> fix: unit test

- packages/server/core/src/base/adapters/node/middlewares/serverStatic.ts
- packages/server/core/src/base/middlewares/renderHandler/ssrRender.ts
- packages/toolkit/types/server/context.d.ts
> fix: ssrCtx add web req & html.favicon maybe a function

- packages/server/core/src/base/index.ts
- packages/server/core/src/base/middlewares/frameworkHeader.ts
- packages/server/core/src/base/middlewares/index.ts
- packages/server/prod-server/src/init.ts
> feat: add processd-by response header

- packages/server/core/src/base/middlewares/renderHandler/render.ts
- packages/solutions/app-tools/src/utils/env.ts
- packages/toolkit/utils/package.json
- packages/toolkit/utils/src/cli/path.ts
- packages/toolkit/utils/src/universal/index.ts
- packages/toolkit/utils/src/universal/path.ts
> fix: move cutNameByHyphen into universal

- packages/server/core/src/base/middlewares/customServer/base.ts
> fix: use # instead of private keyword

- tests/package.json
Made some rspack bugs can findable in rspack-ecosystem-ci.
https://github.com/web-infra-dev/modern.js/actions/runs/8628077508/job/23650919727
https://github.com/web-infra-dev/rspack/issues/6164
> ci: support run garfish test case when run rspack test

- packages/cli/uni-builder/src/shared/devServer.ts
- packages/document/main-doc/docs/en/guides/basic-features/proxy.mdx
- packages/document/main-doc/docs/zh/guides/basic-features/proxy.mdx
- packages/server/core/package.json
- packages/server/core/src/base/middlewares/renderHandler/render.ts
- tests/e2e/builder/cases/dev/history-api-fallback.test.ts
> fix: e2e test cases and dead links

- tests/e2e/builder/cases/dev/history-api-fallback.test.ts
> fix: history-api-fallback e2e test cases

- .changeset/blue-ears-shave.md
- packages/server/core/src/base/middlewares/logger.ts
- packages/server/prod-server/src/init.ts
> fix: adjust rslog level so that user can print log in middleware

- tests/integration/bff-express/tests/index.test.ts
- tests/integration/ssr/tests/base.test.ts
> fix: reduce the timeout probability of test case

- .changeset/clever-bananas-deliver.md
- packages/server/core/src/base/middlewares/customServer/index.ts
> fix: server hook need save the res status and headers

- .changeset/hot-terms-tan.md
- packages/server/core/src/base/middlewares/renderHandler/index.ts
- packages/server/core/src/base/middlewares/renderHandler/render.ts
- packages/server/core/src/base/middlewares/renderHandler/ssrRender.ts
- packages/server/core/src/base/utils/transformStream.ts
- packages/server/core/src/core/render.ts
- packages/toolkit/types/server/context.d.ts
> fix: ssrContext add metrics

- tests/integration/server-hook/router/tests/index.test.ts
> chore: avoid test case failure

- .changeset/small-yaks-vanish.md
- packages/server/server/package.json
- pnpm-lock.yaml
> fix: @modern-js/server-core should be a dependency in @modern-js/server

- .changeset/orange-jars-applaud.md
- packages/runtime/plugin-runtime/src/ssr/react/prerender/index.ts
> fix: remove prod log error

- .changeset/lazy-cameras-hunt.md
- packages/server/prod-server/package.json
- pnpm-lock.yaml
> fix: @modern-js/utils should be a dependency in @modern-js/prod-server

- packages/cli/doc-plugin-auto-sidebar/package.json
- pnpm-lock.yaml
fix inconsistent rspress shared version, see:  https://github.com/web-infra-dev/modern.js/pull/5662
> chore: fix inconsistent rspress shared version

- .changeset/weak-rings-tie.md
- packages/cli/uni-builder/src/shared/devServer.ts
- packages/document/builder-doc/docs/en/config/tools/devServer.md
- packages/document/builder-doc/docs/zh/config/tools/devServer.md
- packages/document/main-doc/docs/en/configure/app/dev/client.mdx
- packages/document/main-doc/docs/zh/configure/app/dev/client.mdx
Same functionality as `tools.devServer.client`, but easier to configure.
> feat: support dev.client configuration

- .changeset/tricky-chefs-sneeze.md
- packages/runtime/plugin-runtime/src/ssr/cli/index.ts
- tests/integration/routes/tests/index.test.ts
> fix: should not include babel-loader in streaming ssr project

- .changeset/sour-bugs-unite.md
- packages/server/core/package.json
- packages/server/core/src/base/adapters/node/index.ts
- packages/server/core/src/base/adapters/node/middlewares/serverManifest.ts
> chore: export getServerManifest

- .changeset/strong-plants-joke.md
> chore: add changeset for release

- .changeset/dirty-lobsters-lie.md
- packages/solutions/app-tools/src/utils/register.ts
> fix: ignore should be a relative path in ts-node

- .changeset/red-pugs-battle.md
- packages/runtime/plugin-runtime/src/ssr/serverRender/renderToStream/bulidTemplate.before.ts
> fix: helmet can't replace <html> when streaming ssr

- .changeset/nasty-ads-push.md
- packages/server/core/src/base/adapters/node/middlewares/serverManifest.ts
> fix: we should not log error when bundle is not exists

- .changeset/early-windows-crash.md
- packages/runtime/plugin-runtime/src/document/Html.tsx
> fix: <Html> should add <html> props types

- .changeset/lovely-olives-flow.md
- packages/server/core/src/base/adapters/node/bff.ts
- packages/server/core/src/base/middlewares/renderHandler/index.ts
- packages/server/core/src/base/middlewares/renderHandler/render.ts
- packages/server/core/src/core/plugin.ts
> feat: add fallback hook for render

- .changeset/shiny-keys-remember.md
- packages/server/core/src/base/middlewares/customServer/context.ts
> fix: server middleware response lose some methods

- .changeset/fresh-pianos-grin.md
- packages/server/core/src/base/adapters/node/bff.ts
- packages/server/core/src/base/middlewares/renderHandler/index.ts
> fix: serverBase may be undefined when get renderHandler

- .changeset/good-toys-behave.md
- packages/cli/uni-builder/package.json
- pnpm-lock.yaml
> fix: uni-builder should depedency prod-server correctly

- .changeset/good-walls-clap.md
- packages/solutions/app-tools/src/builder/shared/builderPlugins/adapterSSR.ts
- tests/integration/ssg/fixtures/nested-routes/src/routes/user/page.data.js
- tests/integration/ssg/fixtures/nested-routes/src/routes/user/page.jsx
> fix: data.ts should not be imported into the client bundle in the ssg project

- packages/document/main-doc/docs/zh/guides/topic-detail/monorepo/sub-project-interface.mdx
> docs(repo): fix typo on docs

- .changeset/shaggy-coins-give.md
- packages/runtime/plugin-garfish/src/cli/utils.ts
- packages/runtime/plugin-runtime/src/router/runtime/plugin.node.tsx
- packages/runtime/plugin-runtime/src/router/runtime/plugin.tsx
- packages/runtime/plugin-runtime/src/router/runtime/types.ts
> fix: add originalBaseUrl param

- .changeset/tiny-nails-glow.md
- packages/server/core/src/base/adapters/node/middlewares/serverPublic.ts
- packages/server/core/src/base/middlewares/renderHandler/render.ts
> fix: server support add extends res headers from routes

- .changeset/two-pears-hide.md
- packages/server/core/src/base/middlewares/renderHandler/render.ts
- packages/server/core/src/base/middlewares/renderHandler/ssrRender.ts
- pnpm-lock.yaml
- tests/integration/server-routes/modern.config.ts
- tests/integration/server-routes/package.json
- tests/integration/server-routes/src/App.tsx
- tests/integration/server-routes/tests/index.test.ts
- tests/integration/server-routes/tests/tsconfig.json
> feat(server-core): render support dynamic route

- packages/document/module-doc/docs/en/guide/faq/build.mdx
- packages/document/module-doc/docs/zh/guide/faq/build.mdx
> docs: fix dead link in module doc

- .changeset/metal-plums-boil.md
- packages/server/core/src/base/adapters/node/middlewares/serverStatic.ts
> fix(server-core): server static can't handle page route correctly

- .vscode/settings.json
- packages/devtools/client/src/entries/client/routes/doctor/error.tsx
- packages/devtools/client/src/entries/client/routes/doctor/page.tsx
- packages/devtools/client/src/entries/client/routes/layout.data.tsx
- packages/devtools/client/src/entries/client/routes/overview/page.tsx
- packages/devtools/client/src/entries/client/routes/storage.preset/page.tsx
- packages/devtools/kit/src/client.ts
- packages/devtools/kit/src/server.ts
- packages/devtools/kit/src/state.ts
- packages/devtools/plugin/src/cli.ts
- packages/devtools/plugin/src/options.ts
- packages/devtools/plugin/src/rpc/index.ts
- packages/devtools/plugin/src/types/config.ts
- packages/devtools/plugin/src/utils/config.ts
- pnpm-lock.yaml
- tests/integration/devtools/modern.runtime.json
- tests/integration/devtools/src/main/routes/page.tsx
- Create new storage preset item and write it to config file.
- Watch on the changes of config files and syncing it to client.
> feat(devtools): create new storage preset by remote function

- tests/integration/nonce/tests/index.test.ts
> test: add timeout

- tests/integration/nonce/modern.config.ts
- tests/integration/nonce/tests/index.test.ts
> test: remove https from the test case

- .changeset/shiny-dragons-switch.md
- packages/server/core/src/base/middlewares/customServer/base.ts
- packages/server/core/src/base/middlewares/customServer/context.ts
- packages/server/core/src/base/middlewares/customServer/index.ts
- packages/server/core/src/base/middlewares/renderHandler/index.ts
- tests/integration/server-hook/middleware/server/_middleware.ts
- tests/integration/server-hook/middleware/server/index.ts
- tests/integration/server-hook/middleware/tests/index.test.ts
> fix(server-core): support custom server middleware redirect

- packages/document/builder-doc/docs/en/config/output/assetsRetry.md
- packages/document/builder-doc/docs/zh/config/output/assetsRetry.md
update assetsRetry configuration introduce, more detailed usage linked to [Rsbuild - Assets Retry Plugin](https://rsbuild.dev/plugins/list/plugin-assets-retry#options).
> docs: update assetsRetry configuration introduce

- .changeset/tall-bobcats-attend.md
- packages/generator/generator-common/src/newAction/module/index.ts
- packages/generator/generator-common/src/newAction/mwa/index.ts
- packages/generator/new-action/src/constants.ts
- packages/generator/new-action/src/module.ts
- packages/generator/new-action/src/mwa.ts
> feat: new command add already enable function tooltip

- pnpm-lock.yaml
- tests/integration/server-hook/new-middleware/package.json
- tests/integration/server-hook/new-middleware/server/index.ts
- tests/integration/server-hook/new-middleware/tests/index.test.ts
> fix: new middleware integration test

- tests/integration/devtools/tests/index.test.ts
> fix: devtools snapshot mismatch

- packages/devtools/kit/package.json
- packages/devtools/plugin/src/cli.ts
- packages/devtools/plugin/src/rpc/index.ts
- packages/devtools/plugin/src/types/common.ts
- pnpm-lock.yaml
- Compatible with latest rsdoctor manifest.
> fix(devtools): compatible with latest rsdoctor manifest

- packages/devtools/plugin/src/cli.ts
- packages/devtools/plugin/src/utils/config.ts
> fix: devtools fixed config file name

- packages/document/main-doc/docs/en/apis/app/runtime/web-server/middleware.mdx
- packages/document/main-doc/docs/en/apis/app/runtime/web-server/unstable_middleware.mdx
- packages/document/main-doc/docs/en/guides/advanced-features/web-server.mdx
- packages/document/main-doc/docs/zh/apis/app/runtime/web-server/middleware.mdx
- packages/document/main-doc/docs/zh/apis/app/runtime/web-server/unstable_middleware.mdx
- packages/document/main-doc/docs/zh/guides/advanced-features/web-server.mdx
> docs: unstable server middleware

- .changeset/happy-pumas-melt.md
- packages/server/core/src/base/adapters/node/node.ts
> chore: add bodyInit for createWebRequest

- .changeset/olive-files-sin.md
- packages/cli/plugin-ssg/package.json
- pnpm-lock.yaml
> fix(plugin-ssg): prod-server should be dependencies in ssg plugin

- .changeset/lemon-lies-mate.md
- packages/runtime/plugin-runtime/src/router/runtime/types.ts
> fix: default types should be Record<string, unknown>

- tests/integration/deploy-csr/tests/index.test.ts
- tests/integration/deploy-server/tests/index.test.ts
> test: add target in CI env to pass test cases

- tests/integration/deploy-csr/tests/index.test.ts
- tests/integration/deploy-server/tests/index.test.ts
> test: the environment variables should be set correctly on the windows

- packages/document/builder-doc/docs/en/config/tools/cssExtract.md
- packages/document/builder-doc/docs/en/config/tools/cssLoader.md
- packages/document/builder-doc/docs/en/guide/advanced/rspack-start.mdx
- packages/document/builder-doc/docs/zh/config/tools/cssExtract.md
- packages/document/builder-doc/docs/zh/config/tools/cssLoader.md
- packages/document/builder-doc/docs/zh/guide/advanced/rspack-start.mdx
https://github.com/web-infra-dev/rsbuild/releases/tag/v0.7.0
> docs: tools.cssExtract & tools.cssLoader supported in rspack

- .changeset/orange-rats-dream.md
- packages/server/plugin-server/src/server.ts
> fix(plugin-server): support update server hook & middleware

- .changeset/curvy-impalas-yell.md
- packages/runtime/plugin-runtime/src/ssr/serverRender/renderToStream/renderToPipe.ts
> fix: streaming ssr should set renderLevel correctly when render error

- .github/workflows/build-builder-website.yml
- .github/workflows/build-main-website.yml
- .github/workflows/build-module-website.yml
ref: https://github.com/JamesIves/github-pages-deploy-action/issues/1110
> chore: bump deploy action to 4.6.1

- .changeset/ten-poems-agree.md
- packages/runtime/plugin-garfish/src/cli/utils.ts
> fix: should inject basename for garfish projects with router v5

- .changeset/curvy-cups-rule.md
- packages/cli/plugin-data-loader/src/runtime/errors.ts
- packages/cli/plugin-data-loader/src/runtime/index.ts
- packages/cli/plugin-data-loader/tests/fixtures/server/bundles/three-server-loaders/index.js
- packages/cli/plugin-data-loader/tests/server.test.ts
- packages/document/main-doc/docs/en/guides/basic-features/data/data-fetch.mdx
- packages/document/main-doc/docs/zh/guides/basic-features/data/data-fetch.mdx
- packages/runtime/plugin-runtime/src/core/compatible.tsx
- packages/runtime/plugin-runtime/src/router/runtime/DeferredDataScripts.node.tsx
- packages/runtime/plugin-runtime/src/router/runtime/plugin.node.tsx
- packages/runtime/plugin-runtime/src/ssr/serverRender/renderToStream/renderToPipe.ts
- packages/toolkit/runtime-utils/src/browser/nestedRoutes.tsx
- pnpm-lock.yaml
- tests/integration/routes/src/three/routes/error/error.tsx
- tests/integration/routes/src/three/routes/error/response/page.data.ts
- tests/integration/routes/src/three/routes/error/response/page.tsx
- tests/integration/routes/tests/index.test.ts
- tests/integration/ssr/fixtures/base-json/src/routes/error/error.tsx
- tests/integration/ssr/fixtures/base/src/routes/error/error.tsx
- tests/integration/ssr/tests/__snapshots__/base-json.test.ts.snap
- tests/integration/ssr/tests/__snapshots__/base.test.ts.snap
- tests/integration/ssr/tests/base-json.test.ts
- tests/integration/ssr/tests/base.test.ts
> feat: support control status code by data loader

- tests/integration/ssr/fixtures/base-json/src/routes/error/error.tsx
- tests/integration/ssr/fixtures/base/src/routes/error/error.tsx
- tests/integration/ssr/tests/__snapshots__/base-json.test.ts.snap
- tests/integration/ssr/tests/__snapshots__/base.test.ts.snap
- tests/integration/ssr/tests/base-json.test.ts
- tests/integration/ssr/tests/base.test.ts
> fix: integration test cases

- packages/document/main-doc/docs/en/apis/app/runtime/web-server/unstable_middleware.mdx
- packages/document/main-doc/docs/en/guides/advanced-features/web-server.mdx
- packages/document/main-doc/docs/zh/apis/app/runtime/web-server/unstable_middleware.mdx
- packages/document/main-doc/docs/zh/guides/advanced-features/web-server.mdx
- add unstable server middleware modify response examples
> docs: enhance server middlewares

- packages/document/main-doc/docs/en/guides/basic-features/deploy.mdx
- packages/document/main-doc/docs/zh/guides/basic-features/deploy.mdx
> docs: add guide for deploy on vercel

- .changeset/sweet-bugs-notice.md
- packages/server/core/src/base/adapters/node/hono.ts
- packages/server/core/src/base/adapters/node/index.ts
- packages/server/core/src/base/adapters/node/node.ts
> fix: export writeReadableStreamToWritable

- packages/solutions/app-tools/src/config/legacy/index.ts
- packages/solutions/app-tools/src/initialize/index.ts
- packages/solutions/app-tools/src/types/config/index.ts
- packages/solutions/app-tools/src/types/legacyConfig/index.ts
- packages/solutions/module-tools/src/config/transformLegacyConfig.ts
- packages/solutions/module-tools/src/types/config/index.ts
> feat: recorve testing config

- .changeset/fast-plums-build.md
- packages/server/core/src/base/constants.ts
> fix:  avoid to mismatch header label

- .changeset/metal-lies-taste.md
- packages/server/core/src/base/constants.ts
> fix: should add the escape character for the regexps

- .changeset/funny-parrots-build.md
- packages/server/core/src/base/adapters/node/hono.ts
> fix(server-core): avoid memory leaks in node versions 18 and 20

- packages/document/main-doc/docs/en/guides/basic-features/routes.mdx
- packages/document/main-doc/docs/zh/guides/basic-features/routes.mdx
> docs: use initialData instead of getInitialData

- .changeset/plenty-ducks-itch.md
- packages/server/core/src/base/middlewares/renderHandler/render.ts
- pnpm-lock.yaml
- tests/integration/routes-match/modern.config.ts
- tests/integration/routes-match/package.json
- tests/integration/routes-match/src/a/App.tsx
- tests/integration/routes-match/src/b/App.tsx
- tests/integration/routes-match/src/c/App.tsx
- tests/integration/routes-match/tests/index.test.ts
- tests/integration/routes-match/tsconfig.json
> fix: render function dynamic router match error

- .changeset/heavy-spoons-wave.md
- packages/runtime/plugin-runtime/src/router/cli/entry.ts
> fix: entrypoint error when use custom index entry

- packages/solutions/app-tools/src/commands/deploy.ts
> fix: deploy commands add server plugin should add metaName

- .changeset/green-balloons-nail.md
- packages/runtime/plugin-runtime/src/cli/entry.ts
- packages/runtime/plugin-runtime/src/router/cli/entry.ts
> fix: fix the failure of App entry recognition 

- .changeset/stupid-toys-smash.md
- packages/cli/plugin-bff/package.json
- packages/server/plugin-express/package.json
- packages/server/plugin-koa/package.json
- pnpm-lock.yaml
> fix(server): move @modern-js/server-core to dependencies

- .changeset/fair-zebras-sit.md
- packages/server/core/src/adapters/node/helper/index.ts
- packages/server/core/src/adapters/node/helper/loadConfig.ts
- packages/server/core/src/adapters/node/index.ts
- packages/server/prod-server/src/index.ts
- packages/server/server/src/createDevServer.ts
> fix: we should load modern.config.json when production

- .changeset/pink-drinks-invent.md
- packages/solutions/app-tools/src/plugins/deploy/platforms/netlify.ts
- packages/solutions/app-tools/src/plugins/deploy/platforms/netlifyEntry.js
- packages/solutions/app-tools/src/plugins/deploy/platforms/node.ts
- packages/solutions/app-tools/src/plugins/deploy/platforms/nodeEntry.js
- packages/solutions/app-tools/src/plugins/deploy/platforms/vercel.ts
- packages/solutions/app-tools/src/plugins/deploy/platforms/vercelEntry.js
> fix(deploy): adapt to the new server plugin for entry

- .changeset/many-laws-scream.md
- packages/server/prod-server/src/index.ts
- packages/server/prod-server/src/netlify.ts
- packages/server/server/src/createDevServer.ts
> fix: we should add cli config correctly

- packages/document/module-doc/docs/en/guide/faq/storybook.mdx
- packages/document/module-doc/docs/zh/guide/faq/storybook.mdx
> docs: add Tailwind CSS does not work in Storybook FAQ

- .changeset/wicked-shirts-rule.md
- packages/document/main-doc/docs/en/guides/deprecat.md
- packages/document/main-doc/docs/zh/guides/deprecat.md
> feat: add deprecat function doc

- packages/document/module-doc/docs/en/guide/faq/storybook.mdx
- packages/document/module-doc/docs/zh/guide/faq/storybook.mdx
> docs: update storybook proxy file path

- packages/runtime/plugin-runtime/src/router/cli/code/nestedRoutes.ts
- packages/runtime/plugin-runtime/tests/router/__snapshots__/nestedRoutes.test.ts.snap
> fix(router): ensure that the page has a higher priority

- .changeset/cold-squids-rhyme.md
- packages/server/core/package.json
- packages/solutions/app-tools/package.json
- packages/solutions/app-tools/src/plugins/deploy/dependencies/index.ts
- packages/solutions/app-tools/src/plugins/deploy/dependencies/utils.ts
- packages/solutions/app-tools/src/plugins/deploy/exports.ts
- packages/solutions/app-tools/src/plugins/deploy/platforms/netlify.ts
- packages/solutions/app-tools/src/plugins/deploy/platforms/node.ts
- packages/solutions/app-tools/src/plugins/deploy/platforms/vercel.ts
- pnpm-lock.yaml
> feat(deploy): export handleDependencies

- .changeset/orange-cows-yawn.md
- packages/runtime/plugin-runtime/package.json
- packages/server/core/src/plugins/render/render.ts
- packages/server/core/src/utils/error.ts
- packages/server/prod-server/src/apply.ts
- pnpm-lock.yaml
> fix: logger maybe undefined when server occur error 

- .changeset/wise-pandas-repeat.md
> chore: update the version

- packages/document/main-doc/docs/en/apis/app/runtime/web-server/middleware.mdx
- packages/document/main-doc/docs/zh/apis/app/runtime/web-server/middleware.mdx
> docs: adjust middleware note

- packages/runtime/plugin-runtime/src/core/server/requestHandler.ts
- packages/runtime/plugin-runtime/src/core/server/stream/afterTemplate.ts
- packages/runtime/plugin-runtime/src/core/server/string/index.ts
- packages/runtime/plugin-runtime/src/core/server/string/ssrData.ts
- packages/server/core/src/plugins/render/ssrRender.ts
- packages/server/core/src/types/requestHandler.ts
- packages/solutions/app-tools/src/types/index.ts
> fix: add reporter to ssrContext

- packages/runtime/plugin-runtime/package.json
- packages/runtime/plugin-runtime/src/core/browser/index.tsx
- packages/runtime/plugin-runtime/src/core/server/string/index.ts
- packages/server/core/src/plugins/render/render.ts
- packages/server/core/src/plugins/render/serverTiming.ts
> fix: adjust loadable-bundle-plugin export & add onError, onTiming function

- packages/runtime/plugin-runtime/src/core/server/requestHandler.ts
- packages/runtime/plugin-runtime/src/core/server/stream/afterTemplate.ts
- packages/runtime/plugin-runtime/src/core/server/stream/createReadableStream.ts
- packages/runtime/plugin-runtime/src/core/server/stream/createReadableStream.worker.ts
- packages/runtime/plugin-runtime/src/core/server/stream/shared.ts
- packages/runtime/plugin-runtime/src/core/server/stream/template.ts
- packages/runtime/plugin-runtime/src/core/server/string/index.ts
- packages/runtime/plugin-runtime/src/core/server/string/ssrData.ts
- packages/runtime/plugin-runtime/src/core/server/utils.ts
- packages/runtime/plugin-runtime/src/core/types.ts
- packages/runtime/plugin-runtime/tests/ssr/__snapshots__/renderString.test.ts.snap
- packages/runtime/plugin-runtime/tests/ssr/renderString.test.ts
- packages/server/core/src/plugins/render/index.ts
- packages/server/core/src/plugins/render/ssrRender.ts
- packages/server/core/src/types/requestHandler.ts
- packages/toolkit/types/server/context.d.ts
> fix: resolve some todo

- packages/runtime/plugin-runtime/src/core/server/string/index.ts
> fix: loadable need stats

- packages/document/main-doc/docs/en/apis/app/hooks/src/entry.server.mdx
- packages/document/main-doc/docs/en/apis/app/runtime/ssr/renderStreaming.mdx
- packages/document/main-doc/docs/en/apis/app/runtime/ssr/renderString.mdx
- packages/document/main-doc/docs/en/apis/app/runtime/ssr/requestHandler.mdx
- packages/document/main-doc/docs/zh/apis/app/hooks/src/entry.server.mdx
- packages/document/main-doc/docs/zh/apis/app/runtime/ssr/renderStreaming.mdx
- packages/document/main-doc/docs/zh/apis/app/runtime/ssr/renderString.mdx
- packages/document/main-doc/docs/zh/apis/app/runtime/ssr/requestHandler.mdx
> docs: server runtime v2

- packages/runtime/plugin-runtime/src/core/server/requestHandler.ts
- packages/runtime/plugin-runtime/src/core/server/stream/afterTemplate.ts
- packages/runtime/plugin-runtime/src/core/server/stream/shared.ts
- packages/runtime/plugin-runtime/src/core/server/string/index.ts
- packages/runtime/plugin-runtime/src/core/server/string/prefetch.tsx
- packages/runtime/plugin-runtime/src/core/server/string/ssrData.ts
- packages/runtime/plugin-runtime/src/router/runtime/plugin.node.tsx
- packages/toolkit/runtime-utils/package.json
- packages/toolkit/runtime-utils/src/universal/index.ts
> fix: solve some issues

- packages/runtime/plugin-runtime/src/core/server/requestHandler.ts
- packages/runtime/plugin-runtime/src/core/server/stream/createReadableStream.ts
- packages/runtime/plugin-runtime/src/core/server/stream/createReadableStream.worker.ts
- packages/runtime/plugin-runtime/src/core/server/stream/shared.ts
- packages/solutions/app-tools/src/commands/serve.ts
- packages/toolkit/types/server/context.d.ts
> fix: resolve codeview issues

- .github/workflows/check-dependencies.yml
- .github/workflows/integration-test-Linux.yml
- .github/workflows/type-check.yml
Upgrade [`pnpm/action-setup`](https://github.com/pnpm/action-setup) version from v2 to v4.
https://github.com/pnpm/action-setup/issues/136
> chore: upgrade pnpm/action-setup version to v4

- packages/document/main-doc/docs/en/configure/app/output/ssg.mdx
- packages/document/main-doc/docs/zh/configure/app/output/ssg.mdx
Add prerequisits content about `output.ssg` documentation.
> docs: add prerequisits about `output.ssg`

- packages/document/module-doc/docs/en/guide/basic/use-micro-generator.md
- packages/document/module-doc/docs/zh/guide/basic/use-micro-generator.md
> docs: module doc container syntax error

- packages/document/main-doc/docs/zh/configure/app/dev/client.mdx
> docs: update client overlay default value

- .changeset/flat-bobcats-shout.md
- packages/runtime/plugin-runtime/src/cli/alias.ts
- packages/runtime/plugin-runtime/src/cli/template.server.ts
- packages/runtime/plugin-runtime/src/cli/template.ts
- packages/runtime/plugin-runtime/src/router/cli/code/templates.ts
- packages/toolkit/utils/src/cli/path.ts
> fix: runtime template windows path

- .changeset/friendly-impalas-end.md
- packages/generator/generators/entry-generator/src/index.ts
- packages/generator/generators/mwa-generator/templates/js-template/src/modern.runtime.js.handlebars
- packages/generator/generators/mwa-generator/templates/ts-template/src/modern.runtime.ts.handlebars
- packages/runtime/plugin-runtime/src/cli/index.ts
- packages/runtime/plugin-runtime/src/index.ts
- packages/runtime/plugin-runtime/types/router.d.ts
> feat: generator support runtime config file

- .changeset/seven-ties-enjoy.md
- packages/cli/plugin-ssg/src/server/index.ts
> fix(ssg): make sure that BFF run products of the dist when building with ssg

- .changeset/green-tomatoes-live.md
- packages/solutions/module-tools/src/builder/esbuild/adapter.ts
- packages/solutions/module-tools/src/builder/feature/style/postcssUrlPlugin.ts
> fix(module-tools): support imports field in package.json

- packages/document/main-doc/docs/en/apis/app/hooks/src/entry.server.mdx
- packages/document/main-doc/docs/en/apis/app/runtime/ssr/renderStreaming.mdx
- packages/document/main-doc/docs/en/apis/app/runtime/ssr/renderString.mdx
- packages/document/main-doc/docs/en/apis/app/runtime/ssr/requestHandler.mdx
- packages/document/main-doc/docs/zh/apis/app/hooks/src/entry.server.mdx
- packages/document/main-doc/docs/zh/apis/app/runtime/ssr/renderStreaming.mdx
- packages/document/main-doc/docs/zh/apis/app/runtime/ssr/renderString.mdx
- packages/document/main-doc/docs/zh/apis/app/runtime/ssr/requestHandler.mdx
> fix: modify server runtime docs

- .changeset/fifty-bugs-try.md
- packages/server/prod-server/package.json
- packages/server/prod-server/src/index.ts
- pnpm-lock.yaml
> fix: prod-server support source-map

- .changeset/angry-hairs-bathe.md
- packages/runtime/plugin-garfish/src/cli/code.ts
- packages/runtime/plugin-garfish/src/cli/template.ts
- packages/runtime/plugin-garfish/src/runtime/provider.tsx
- packages/runtime/plugin-garfish/src/runtime/render.tsx
- tests/integration/garfish/app-dashboard/src/index.tsx
> fix: garfish plugin use custom bootstrap not work

- .changeset/polite-seas-design.md
- packages/runtime/plugin-runtime/src/core/server/requestHandler.ts
- packages/runtime/plugin-runtime/src/core/server/stream/shared.ts
- packages/runtime/plugin-runtime/src/core/server/string/index.ts
- packages/runtime/plugin-runtime/src/core/server/string/prefetch.tsx
> fix: ssr use-loader should set \_internal_context.ssr = false

- packages/cli/uni-builder/tests/__snapshots__/default.test.ts.snap
- packages/cli/uni-builder/tests/default.test.ts
add builder config snapshot for node and service-worker.
> chore: add more builder config snapshots

- .changeset/stupid-clouds-chew.md
- packages/runtime/plugin-runtime/src/router/cli/code/index.ts
- packages/runtime/plugin-runtime/src/router/cli/entry.ts
- packages/solutions/app-tools/src/plugins/analyze/getBundleEntry.ts
- packages/solutions/app-tools/src/types/config/source.ts
- packages/toolkit/types/cli/index.d.ts
- tests/integration/esbuild/tests/transform-and-minify.test.ts
- tests/integration/swc/tests/minify-js.test.ts
> feat: refactor the logic of the system file router entry

- .changeset/stale-actors-greet.md
- packages/cli/doc-plugin-auto-sidebar/package.json
- packages/document/builder-doc/docs/en/index.md
- packages/document/builder-doc/package.json
- packages/document/main-doc/package.json
- packages/document/module-doc/docs/en/index.md
- packages/document/module-doc/package.json
- pnpm-lock.yaml
[https://github.com/web-infra-dev/rspress/releases](https://github.com/web-infra-dev/rspress/releases)
Fixed sidebar incorrect active https://github.com/web-infra-dev/rspress/issues/991
Fixed homepage hero link https://github.com/web-infra-dev/rspress/issues/1234
etc.
> chore(deps): bump rspress to 1.26.1

- packages/cli/uni-builder/src/shared/devServer.ts
- packages/document/builder-doc/docs/en/config/tools/devServer.md
- packages/document/builder-doc/docs/zh/config/tools/devServer.md
- packages/document/main-doc/docs/en/configure/app/dev/live-reload.mdx
- packages/document/main-doc/docs/en/configure/app/dev/setup-middlewares.mdx
- packages/document/main-doc/docs/en/configure/app/dev/watch-files.mdx
- packages/document/main-doc/docs/en/configure/app/dev/write-to-disk.mdx
- packages/document/main-doc/docs/zh/configure/app/dev/live-reload.mdx
- packages/document/main-doc/docs/zh/configure/app/dev/setup-middlewares.mdx
- packages/document/main-doc/docs/zh/configure/app/dev/watch-files.mdx
- packages/document/main-doc/docs/zh/configure/app/dev/write-to-disk.mdx
update modern.js doc, support more rsbuild dev config, and dev config has higher priority than legacy configuration
> feat: support more rsbuild dev config

- .changeset/two-pumpkins-smell.md
- packages/runtime/plugin-runtime/src/core/browser/index.tsx
> fix: ssr Context in browser should add document information

- .changeset/short-geese-bathe.md
- packages/runtime/plugin-runtime/src/router/runtime/plugin.node.tsx
> fix: router plugin should receive request that method is GET

- .changeset/curly-eels-perform.md
- packages/document/main-doc/docs/en/guides/basic-features/data/data-fetch.mdx
- packages/document/main-doc/docs/en/guides/basic-features/routes.mdx
- packages/document/main-doc/docs/zh/guides/basic-features/data/data-fetch.mdx
- packages/document/main-doc/docs/zh/guides/basic-features/routes.mdx
- packages/runtime/plugin-runtime/src/router/runtime/PrefetchLink.tsx
- packages/server/server/src/helpers/index.ts
> fix(prefetch): chunkId may be string or number

- packages/document/builder-doc/docs/en/config/tools/babel.md
- packages/document/builder-doc/docs/zh/config/tools/babel.md
fix tools.babel example error.
https://babeljs.io/docs/options#targets
> chore(docs): fix tools.babel example error

- .changeset/thin-kiwis-swim.md
- packages/runtime/plugin-garfish/src/runtime/provider.tsx
> feat: garfish beforeRender function support props params

- .changeset/violet-pans-jump.md
- packages/runtime/plugin-runtime/src/core/server/string/loadable.ts
> fix: style assets should be add to cssChunk

- .github/workflows/check-dependencies.yml
- packages/devtools/client/modern.config.ts
- packages/devtools/client/src/components/Card/Card.module.scss
- packages/devtools/plugin/package.json
- pnpm-lock.yaml
> fix: mismatch hono version in devtools plugin

- .changeset/beige-timers-help.md
- packages/runtime/plugin-runtime/src/router/cli/code/templates.ts
set async entry for data loader
> feat: set async entry for data loader

- .changeset/little-jars-grab.md
- .changeset/mighty-kids-buy.md
- packages/runtime/plugin-runtime/src/cli/code.ts
- packages/runtime/plugin-runtime/src/cli/constants.ts
- packages/solutions/app-tools/src/builder/generator/getBuilderEnvironments.ts
- packages/solutions/app-tools/src/builder/shared/builderPlugins/adapterBasic.ts
- tests/integration/ssr/fixtures/init/modern.config.ts
> fix: we should generate bootstrap.server.jsx when ssr mode

- packages/runtime/plugin-garfish/src/cli/index.ts
- packages/runtime/plugin-router-v5/src/cli/index.ts
> fix: runtime alias order

- .changeset/happy-monkeys-pump.md
- packages/runtime/plugin-garfish/src/cli/index.ts
- packages/runtime/plugin-router-v5/src/cli/index.ts
- packages/runtime/plugin-runtime/src/cli/index.ts
> fix: more runtime plugin add alias not work

- .changeset/old-years-speak.md
- .changeset/strong-moose-wash.md
- packages/server/server/src/createDevServer.ts
- packages/server/server/src/dev.ts
- packages/solutions/app-tools/src/commands/dev.ts
- packages/solutions/app-tools/src/utils/createServer.ts
> fix: dev server should call rsbuild.afterListen when listen

- .changeset/poor-cougars-dream.md
- packages/document/main-doc/docs/en/apis/app/runtime/web-server/hook.mdx
- packages/document/main-doc/docs/en/apis/app/runtime/web-server/middleware.mdx
- packages/document/main-doc/docs/zh/apis/app/runtime/web-server/hook.mdx
- packages/document/main-doc/docs/zh/apis/app/runtime/web-server/middleware.mdx
- packages/server/core/src/plugins/customServer/base.ts
- packages/toolkit/types/server/hook.d.ts
> fix: user can get status in afterRenderContext

- packages/document/builder-doc/docs/en/config/tools/htmlPlugin.md
- packages/document/builder-doc/docs/zh/config/tools/htmlPlugin.md
> docs: update html-rspack-plugin link

- tests/integration/ssr/fixtures/partial/src/one/routes/layout.tsx
- tests/integration/ssr/tests/partial.test.ts
> fix: integration test

- .changeset/hungry-frogs-bow.md
- packages/cli/plugin-bff/src/server.ts
- packages/server/core/src/plugins/default.ts
- packages/server/core/src/plugins/index.ts
- packages/server/core/src/plugins/monitors.ts
- packages/server/core/src/plugins/render/index.ts
- packages/server/core/src/plugins/render/inject.ts
- packages/server/core/src/types/plugin.ts
- packages/server/core/tests/plugins/render.test.ts
- packages/server/prod-server/src/apply.ts
- packages/server/prod-server/src/types.ts
> feat: inject renderHandler to appContext & add default serverPlugins

- .changeset/tender-trees-move.md
- packages/server/core/src/plugins/default.ts
- packages/server/prod-server/src/apply.ts
- tests/integration/ssr/fixtures/partial/src/one/routes/a/page.tsx
- tests/integration/ssr/tests/partial.test.ts
> fix: faviconPlugin should after staticPlugin & update integration test

- .changeset/spicy-buses-rush.md
- packages/server/core/src/helper.ts
- packages/server/core/src/index.ts
- packages/server/core/src/plugins/customServer/index.ts
- packages/server/core/src/plugins/index.ts
- packages/server/core/src/plugins/render/index.ts
> fix: we should export `getLoaderCtx` from server-core

- .changeset/hot-squids-warn.md
- packages/runtime/plugin-runtime/src/router/runtime/plugin.node.tsx
> fix: add deferedDataScripts only streaming ssr

- .changeset/tasty-ads-rest.md
- packages/runtime/plugin-runtime/src/core/browser/hydrate.tsx
> fix: react 17 ssr context error

- .changeset/tall-socks-listen.md
- packages/runtime/plugin-runtime/src/core/plugin/index.ts
- packages/toolkit/runtime-utils/tests/merge.test.ts
> fix: mergeConfig function to return an object

- .changeset/five-crabs-tease.md
- packages/solutions/app-tools/src/plugins/deploy/dependencies/index.ts
- packages/solutions/app-tools/src/plugins/deploy/dependencies/utils.ts
> fix(deploy): the subpath should be judged correctly

- packages/document/module-doc/docs/en/api/config/build-config.mdx
- packages/document/module-doc/docs/zh/api/config/build-config.mdx
Add warning, which make user easier to understand
> docs(module-tools): add warning for resolve.alias

- .changeset/neat-schools-raise.md
- packages/server/core/src/plugins/render/render.ts
> fix: should use dynamic import to import matchRoutes

- .changeset/small-walls-live.md
- packages/solutions/app-tools/src/plugins/deploy/dependencies/index.ts
- packages/solutions/app-tools/src/plugins/deploy/dependencies/utils.ts
> feat(deploy): export nodeFileTrace and traceOptions

- .changeset/modern-cycles-develop.md
- packages/document/main-doc/docs/en/guides/topic-detail/framework-plugin/hook-list.mdx
- packages/document/main-doc/docs/zh/guides/topic-detail/framework-plugin/hook-list.mdx
> feat: update runtime plugin hook doc

- .changeset/moody-cherries-warn.md
- packages/runtime/plugin-runtime/src/core/browser/index.tsx
- packages/runtime/plugin-runtime/src/core/constants.ts
- packages/runtime/plugin-runtime/src/core/server/constants.ts
- packages/runtime/plugin-runtime/src/core/server/string/ssrData.ts
> fix: we should get ssr data from HTMLElement when set ssr.inlineScript = false

- .changeset/sour-guests-tap.md
> chore: set minor version for release

- packages/runtime/plugin-runtime/src/core/context/index.ts
> feat: runtime export wrap context function

- .changeset/loud-pans-behave.md
- packages/runtime/plugin-runtime/src/core/server/requestHandler.ts
- packages/toolkit/types/server/context.d.ts
> fix: ssr context in runtime should get host from X-Forwarded-Host first

- .changeset/stale-kangaroos-smash.md
- packages/server/core/package.json
- packages/server/core/src/adapters/node/helper/loadConfig.ts
- packages/solutions/app-tools/package.json
- packages/solutions/app-tools/src/utils/config.ts
- packages/solutions/app-tools/tests/__snapshots__/utils.test.ts.snap
- packages/solutions/app-tools/tests/utils.test.ts
- pnpm-lock.yaml
> fix: use flatted instead of safeReplacer

- .changeset/old-walls-applaud.md
- packages/runtime/plugin-runtime/src/core/server/stream/afterTemplate.ts
- packages/runtime/plugin-runtime/src/core/server/string/ssrData.ts
- packages/runtime/plugin-runtime/tests/ssr/renderString.test.ts
> fix: ssrData should get request.url from ssrContext

- .changeset/large-ties-exist.md
- packages/runtime/plugin-runtime/src/cli/code.ts
- packages/runtime/plugin-runtime/src/core/server/stream/afterTemplate.ts
- packages/runtime/plugin-runtime/src/core/server/stream/beforeTemplate.ts
- packages/runtime/plugin-runtime/src/core/server/stream/createReadableStream.ts
- packages/runtime/plugin-runtime/src/core/server/stream/createReadableStream.worker.ts
- packages/runtime/plugin-runtime/src/core/server/stream/shared.ts
- packages/server/plugin-server/src/runtime/assets/assets.ts
- packages/solutions/app-tools/src/builder/shared/bundlerPlugins/RouterPlugin.ts
> feat(runtime): adapt to some features for async entries

- .changeset/eighty-badgers-drop.md
- tests/e2e/builder/cases/inspect-config/index.test.ts
Fix rsbuild inspect config cases, see https://github.com/web-infra-dev/rsbuild/pull/3189
> test: fix rsbuild inspect config cases

- .changeset/stale-walls-dress.md
- packages/runtime/plugin-runtime/src/cli/template.ts
> fix: garfish config name when use app.config

- packages/generator/generator-common/package.json
- packages/generator/generator-plugin/package.json
- packages/generator/generator-utils/package.json
- packages/generator/generators/base-generator/package.json
- packages/generator/generators/bff-generator/package.json
- packages/generator/generators/changeset-generator/package.json
- packages/generator/generators/dependence-generator/package.json
- packages/generator/generators/entry-generator/package.json
- packages/generator/generators/generator-generator/package.json
- packages/generator/generators/module-doc-generator/package.json
- packages/generator/generators/module-generator/package.json
- packages/generator/generators/mwa-generator/package.json
- packages/generator/generators/packages-generator/package.json
- packages/generator/generators/repo-generator/package.json
- packages/generator/generators/router-v5-generator/package.json
- packages/generator/generators/server-generator/package.json
- packages/generator/generators/ssg-generator/package.json
- packages/generator/generators/storybook-next-generator/package.json
- packages/generator/generators/tailwindcss-generator/package.json
- packages/generator/generators/upgrade-generator/package.json
- packages/generator/new-action/package.json
- packages/generator/sandpack-react/package.json
- packages/toolkit/create/package.json
- packages/toolkit/upgrade/package.json
- pnpm-lock.yaml
> feat: update codesmith version

- .changeset/blue-cows-jog.md
- packages/runtime/plugin-runtime/src/core/browser/index.tsx
- packages/runtime/plugin-runtime/src/core/server/requestHandler.ts
- packages/runtime/plugin-runtime/src/core/server/string/index.ts
> fix: we should inject ssrData & window's data when ssr failed,

- biome.json
- packages/devtools/client/src/utils/pluggable.ts
- packages/generator/generator-common/src/common/packagePath.ts
- packages/generator/generator-common/src/common/solution.ts
- packages/runtime/plugin-garfish/src/cli/utils.ts
- packages/solutions/module-tools/shims/cjs.js
- packages/solutions/module-tools/src/builder/build.ts
- packages/solutions/module-tools/src/builder/copy.ts
- packages/solutions/module-tools/src/builder/esbuild/sourcemap.ts
- packages/storybook/builder/src/plugin-storybook.ts
- scripts/skipCI.js
- tests/e2e/garfish/fixtures/dashboard-router-v6/src/routes/detail/$.tsx
- tests/utils/modernTestUtils.js
- tests/utils/puppeteer_environment.js
> chore: enable some biome complexity rules and fix the lint error 

- packages/solutions/app-tools/lib/types.d.ts
> feat(app-tools): add avif type support

- packages/runtime/plugin-runtime/src/document/Body.tsx
- packages/runtime/plugin-runtime/src/document/Html.tsx
- packages/runtime/plugin-runtime/src/document/Root.tsx
- packages/runtime/plugin-runtime/src/document/Style.tsx
- tests/integration/app-document/src/sub/Document.tsx
- tests/integration/entries/fixtures/app-route/src/Document.tsx
> fix: app-document windows test

- .changeset/breezy-mangos-cover.md
- packages/server/core/src/plugins/customServer/index.ts
> fix: custom server route rewrite should carry honoContext.env

- .changeset/thin-deers-try.md
- packages/runtime/plugin-runtime/src/cli/index.ts
- packages/runtime/plugin-runtime/src/cli/template.ts
- pnpm-lock.yaml
- tests/integration/entries/fixtures/app-server-entry/modern.config.ts
- tests/integration/entries/fixtures/app-server-entry/package.json
- tests/integration/entries/fixtures/app-server-entry/src/App.server.tsx
- tests/integration/entries/fixtures/app-server-entry/src/App.tsx
- tests/integration/entries/fixtures/app-server-entry/src/modern-app-env.d.ts
- tests/integration/entries/fixtures/app-server-entry/src/routes.tsx
- tests/integration/entries/fixtures/app-server-entry/tsconfig.json
- tests/integration/entries/package.json
- tests/integration/entries/tests/app-server-entry.test.ts
> fix: modern-entry rules not use array && add server entry test case

- packages/document/builder-doc/docs/en/config/output/convertToRem.md
- packages/document/builder-doc/docs/zh/config/output/convertToRem.md
add rem plugin reference link.
> docs: add rem plugin reference link

- .changeset/six-rabbits-drum.md
- packages/runtime/plugin-runtime/src/router/cli/code/templates.ts
- packages/server/core/src/adapters/node/plugins/resource.ts
> fix(data-loader): compatible with asyncEntry for data loader

- packages/document/builder-doc/docs/en/config/source/define.md
- packages/document/builder-doc/docs/zh/config/source/define.md
- packages/document/main-doc/docs/en/configure/app/tools/swc.mdx
- packages/document/main-doc/docs/en/guides/advanced-features/rspack-start.mdx
- packages/document/main-doc/docs/en/guides/basic-features/data/data-fetch.mdx
- packages/document/main-doc/docs/zh/configure/app/tools/swc.mdx
- packages/document/main-doc/docs/zh/guides/advanced-features/rspack-start.mdx
- packages/document/main-doc/docs/zh/guides/basic-features/data/data-fetch.mdx
Updated some rspack links and moved `useLoader` rspack usage tip to self introduction.
> docs: update rspack content

- .changeset/warm-stingrays-deny.md
- packages/solutions/app-tools/src/builder/shared/builderPlugins/adapterSSR.ts
> fix: filter entries by ssr or ssg should not apply the single entry

- packages/server/core/src/plugins/customServer/index.ts
- packages/server/core/src/plugins/render/index.ts
- packages/server/core/src/plugins/render/render.ts
- packages/server/core/src/types/render.ts
- packages/server/core/src/types/server.ts
> fix: rewrite routes to use the new path

- package.json
Easy to report errors on windows machines
> chore: limit maxParallel of nx

- packages/solutions/app-tools/modern.config.js
> chore: unify the config of different build formats for app-tools

- .changeset/old-snakes-cheer.md
- packages/solutions/app-tools/src/plugins/analyze/getFileSystemEntry.ts
- packages/solutions/app-tools/tests/analyze/getFileSystemEntry.test.ts
- pnpm-lock.yaml
- tests/integration/entries/fixtures/app-builder-index/modern.config.ts
- tests/integration/entries/fixtures/app-builder-index/package.json
- tests/integration/entries/fixtures/app-builder-index/src/entry-1/App.tsx
- tests/integration/entries/fixtures/app-builder-index/src/entry-1/index.tsx
- tests/integration/entries/fixtures/app-builder-index/src/entry-2/App.tsx
- tests/integration/entries/fixtures/app-builder-index/src/entry-2/index.tsx
- tests/integration/entries/fixtures/app-builder-index/src/utils/index.tsx
- tests/integration/entries/fixtures/app-builder-index/tsconfig.json
- tests/integration/entries/tests/app-builder-index.test.ts
> fix: entry detection not work

- .changeset/honest-chefs-whisper.md
- packages/runtime/plugin-runtime/src/core/browser/index.tsx
- packages/runtime/plugin-runtime/src/core/react/index.tsx
> fix: move parse window ssr data to createRoot

- packages/server/core/src/plugins/render/render.ts
Touch SSR Fallback
```
forceCSR config + open with req params
?csr=1 
req header x-[framework like: pia]-ssr-fallback:1  
```
Hit SSR Fallback
```
res header x-[framework like: pia]-ssr-fallback: 1;reason=xxx
// reason:  query || header || error
```
> feat: add ssr fallback flag info to response header

- .changeset/nice-mirrors-approve.md
- packages/server/core/src/plugins/customServer/index.ts
- packages/server/core/src/plugins/render/render.ts
> fix: server-core should not be import node api

- packages/server/core/src/plugins/render/render.ts
> fix(server): avoid the require problem on windows

- .changeset/thirty-balloons-punch.md
- packages/cli/uni-builder/src/shared/devServer.ts
> fix: dev.setupMiddlewares not work

- .changeset/long-cups-tickle.md
- packages/server/core/src/plugins/render/inject.ts
- packages/server/core/src/plugins/render/render.ts
- packages/server/core/src/types/plugin.ts
> fix: we should run runner.fallback when ssr fallback

- packages/server/core/src/adapters/node/node.ts
> fix(server): avoid possible memory leaks

- .changeset/loud-eels-whisper.md
- packages/cli/uni-builder/src/webpack/plugins/babel.ts
- packages/cli/uni-builder/tests/__snapshots__/babel.test.ts.snap
- packages/cli/uni-builder/tests/__snapshots__/default.test.ts.snap
- packages/cli/uni-builder/tests/__snapshots__/react.test.ts.snap
- packages/cli/uni-builder/tests/__snapshots__/styledComponents.test.ts.snap
- packages/cli/uni-builder/tests/__snapshots__/transformImport.test.ts.snap
- pnpm-lock.yaml
- tests/integration/transform-lodash-import/modern.config.ts
- tests/integration/transform-lodash-import/package.json
- tests/integration/transform-lodash-import/src/App.tsx
- tests/integration/transform-lodash-import/tests/index.test.ts
- tests/integration/transform-lodash-import/tests/tsconfig.json
- tests/integration/transform-lodash-import/tsconfig.json
> feat: add warn when transformLodash and transformImport for lodash library both exist

- .changeset/tough-ligers-exercise.md
- packages/generator/generators/base-generator/src/index.ts
- packages/generator/generators/base-generator/templates/base-template/.husky/pre-commit
- packages/generator/generators/module-generator/templates/base-template/package.json.handlebars
- packages/generator/generators/mwa-generator/templates/base-template/package.json.handlebars
- packages/generator/generators/upgrade-generator/src/index.ts
- packages/generator/generators/upgrade-generator/src/locale/en.ts
- packages/generator/generators/upgrade-generator/src/locale/zh.ts
- packages/generator/generators/upgrade-generator/templates/.husky/pre-commit
- packages/server/prod-server/package.json
- pnpm-lock.yaml
- tests/integration/module/package.json
> feat: generator template replace husky to simple git hook

- packages/document/main-doc/docs/en/configure/app/server/port.mdx
- packages/document/main-doc/docs/en/configure/app/server/ssr.mdx
- packages/document/main-doc/docs/zh/configure/app/server/port.mdx
- packages/document/main-doc/docs/zh/configure/app/server/ssr.mdx
- packages/document/main-doc/src/components/RsbuildLink/index.tsx
> docs: refactor builder server config doc

- .changeset/wild-falcons-shave.md
- packages/runtime/plugin-garfish/src/cli/template.ts
> fix: custom entry path in windows when use garfish plugin

- packages/document/main-doc/docs/en/guides/basic-features/routes.mdx
- packages/document/main-doc/docs/zh/guides/basic-features/routes.mdx
- packages/runtime/plugin-runtime/src/router/runtime/PrefetchLink.tsx
> docs: remove the tip that rspack is not yet supported

- packages/document/main-doc/docs/en/configure/app/tools/swc.mdx
- packages/document/main-doc/docs/zh/configure/app/tools/swc.mdx
> docs: add swc plugin guide

- .changeset/tender-eyes-occur.md
- packages/runtime/plugin-router-v5/src/runtime/plugin.tsx
- packages/runtime/plugin-runtime/src/router/runtime/plugin.tsx
> fix: router plugin baseUrl not work

- .changeset/clever-fishes-behave.md
- packages/server/utils/src/compilers/typescript/index.ts
> fix(server): should not include tsconfig.json

- .changeset/twenty-files-think.md
- packages/runtime/plugin-runtime/src/cli/index.ts
> fix(runtime): alias @meta/runtime should be configured correctly

- .changeset/olive-colts-smoke.md
- packages/runtime/plugin-runtime/jest.config.js
- packages/runtime/plugin-runtime/src/cli/index.ts
- tests/jest-ut.config.js
> fix(runtime): fix the alias problem on windows

- .github/renovate.json5
> chore: fix renovate config warning

- .github/renovate.json5
> chore: add codesmith && reduck group for renovate

- .changeset/chilly-coins-chew.md
- packages/generator/generator-common/package.json
- packages/generator/generator-plugin/package.json
- packages/generator/generator-utils/package.json
- packages/generator/generators/base-generator/package.json
- packages/generator/generators/bff-generator/package.json
- packages/generator/generators/changeset-generator/package.json
- packages/generator/generators/dependence-generator/package.json
- packages/generator/generators/entry-generator/package.json
- packages/generator/generators/generator-generator/package.json
- packages/generator/generators/module-doc-generator/package.json
- packages/generator/generators/module-generator/package.json
- packages/generator/generators/module-generator/src/index.ts
- packages/generator/generators/mwa-generator/package.json
- packages/generator/generators/mwa-generator/src/index.ts
- packages/generator/generators/packages-generator/package.json
- packages/generator/generators/repo-generator/package.json
- packages/generator/generators/router-v5-generator/package.json
- packages/generator/generators/server-generator/package.json
- packages/generator/generators/ssg-generator/package.json
- packages/generator/generators/storybook-next-generator/package.json
- packages/generator/generators/tailwindcss-generator/package.json
- packages/generator/generators/upgrade-generator/package.json
- packages/generator/new-action/package.json
- packages/generator/sandpack-react/package.json
- packages/toolkit/create/package.json
- packages/toolkit/upgrade/package.json
- pnpm-lock.yaml
> feat: add timing log for mwa and module generator to get solution version

- .github/renovate.json5
> fix: renovate group config not work

- .changeset/mighty-candles-retire.md
- packages/solutions/app-tools/src/plugins/deploy/platforms/netlify.ts
- packages/solutions/app-tools/src/plugins/deploy/platforms/node.ts
- packages/solutions/app-tools/src/plugins/deploy/platforms/vercel.ts
- packages/solutions/app-tools/src/plugins/deploy/utils.ts
> feat(deploy): support server plugin options for deploy

- .changeset/violet-islands-sniff.md
- .github/renovate.json5
> chore: renovate group config

- .github/renovate.json5
> chore: renovate not ignore test directory

- .github/renovate.json5
> fix: renovate error

- packages/document/main-doc/docs/en/configure/app/output/inline-scripts.mdx
- packages/document/main-doc/docs/en/configure/app/output/inline-styles.mdx
- packages/document/main-doc/docs/zh/configure/app/output/inline-scripts.mdx
- packages/document/main-doc/docs/zh/configure/app/output/inline-styles.mdx
`/splitRouteChunks` => `/split-route-chunks`
> docs: fix splitRouteChunks link

- .changeset/weak-clocks-knock.md
- packages/document/main-doc/docs/zh/plugin/introduction.mdx
- packages/solutions/app-tools/src/utils/register.ts
- packages/toolkit/utils/src/cli/require.ts
> fix: should load ts-node from project

- pnpm-lock.yaml
- tests/e2e/builder/cases/progress/index.test.ts
> test: fix update build test text

- .github/workflows/release.yml
> chore: remove release workflow issue_comment trigger

- biome.json
- tests/integration/swc/fixtures/config-function/src/bootstrap.css
- tests/integration/swc/fixtures/minify-css/src/bootstrap.css
> fix: integration test because of biome format

- tests/e2e/builder/cases/html/html.test.ts
> fix: e2e html outputStructure case

- .changeset/fast-birds-wonder.md
- packages/solutions/app-tools/src/utils/register.ts
> fix(bff): should register esbuild for js projects

- .changeset/tidy-ducks-beg.md
- packages/cli/plugin-ssg/package.json
- packages/runtime/plugin-garfish/package.json
- packages/solutions/app-tools/src/utils/register.ts
- packages/toolkit/runtime-utils/package.json
- pnpm-lock.yaml
> fix: upgrade react-router to the latest version & log in debug mode only

- .changeset/famous-balloons-rule.md
- packages/server/core/src/plugins/render/ssrCache.ts
- packages/server/core/src/utils/error.ts
> Add catch logic to ssr cache container

- .changeset/strong-toes-trade.md
- packages/cli/plugin-data-loader/src/runtime/index.ts
- packages/server/core/src/plugins/render/dataHandler.ts
- packages/server/core/src/types/server.ts
- tests/integration/server-hook/new-middleware/src/routes/login/page.tsx
- tests/integration/server-hook/new-middleware/tests/index.test.ts
> fix(server): should get context from unstable middleware correctly

- packages/server/core/src/plugins/render/ssrCache.ts
- packages/server/core/src/utils/error.ts
> fix(server): use requestHandlerOptions.onError function

- .changeset/clever-scissors-admire.md
- packages/generator/generators/upgrade-generator/src/index.ts
- packages/toolkit/upgrade/src/index.ts
> fix: upgrade command get modern version error

- .changeset/eleven-singers-pay.md
- packages/cli/uni-builder/package.json
- packages/cli/uni-builder/tests/__snapshots__/default.test.ts.snap
- packages/cli/uni-builder/tests/__snapshots__/minimize.test.ts.snap
- pnpm-lock.yaml
fix rsbuild ci https://github.com/rspack-contrib/rsbuild-ecosystem-ci/actions/runs/11383897804/job/31670479339
https://github.com/web-infra-dev/rsbuild/pull/3750
> feat(deps): bump html-webpack-plugin to support getCompilationHooks

- packages/document/main-doc/docs/en/configure/app/output/dist-path.mdx
- packages/document/main-doc/docs/en/configure/app/output/filename.mdx
- packages/document/main-doc/docs/zh/configure/app/output/dist-path.mdx
- packages/document/main-doc/docs/zh/configure/app/output/filename.mdx
Provide by rsbuild.
https://github.com/web-infra-dev/rsbuild/pull/3688
> docs: add `distPath.assets` and `filename.assets` configuration

- packages/document/main-doc/docs/en/configure/app/html/output-structure.mdx
- packages/document/main-doc/docs/zh/configure/app/html/output-structure.mdx
> docs: fix html.outputStructure default value

- .changeset/twelve-monkeys-turn.md
- packages/runtime/plugin-runtime/src/router/runtime/hooks.ts
- packages/runtime/plugin-runtime/src/router/runtime/plugin.node.tsx
> feat: router plugin add beforeCreateRoutes hook

- .changeset/fluffy-cooks-heal.md
- packages/generator/generators/module-generator/templates/base-template/package.json.handlebars
- packages/generator/generators/mwa-generator/templates/base-template/package.json.handlebars
> feat: update @types/node version for template

- .changeset/weak-queens-fry.md
- packages/generator/generators/tailwindcss-generator/src/index.ts
> feat: generator upgrade tailwindcss version

- packages/document/main-doc/docs/en/configure/app/tools/html-plugin.mdx
- packages/document/main-doc/docs/zh/configure/app/tools/html-plugin.mdx
> docs: update htmlPlugin.minify default value

- biome.json
- packages/runtime/plugin-runtime/package.json
- packages/runtime/plugin-runtime/scripts/gen-static.ts
- packages/runtime/plugin-runtime/src/core/server/requestHandler.ts
- packages/runtime/plugin-runtime/src/core/server/stream/afterTemplate.ts
- packages/runtime/plugin-runtime/src/core/server/utils.ts
- packages/runtime/plugin-runtime/src/core/types.ts
- packages/runtime/plugin-runtime/src/router/runtime/DeferredDataScripts.node.tsx
- packages/runtime/plugin-runtime/src/router/runtime/constants.ts
- packages/runtime/plugin-runtime/src/router/runtime/plugin.node.tsx
- pnpm-lock.yaml
- tests/integration/ssr/fixtures/streaming-inline/modern.config.ts
- tests/integration/ssr/fixtures/streaming-inline/package.json
- tests/integration/ssr/fixtures/streaming-inline/src/entry.server.tsx
- tests/integration/ssr/fixtures/streaming-inline/src/modern-app-env.d.ts
- tests/integration/ssr/fixtures/streaming-inline/src/routes/about/About.tsx
- tests/integration/ssr/fixtures/streaming-inline/src/routes/about/about.css
- tests/integration/ssr/fixtures/streaming-inline/src/routes/about/page.tsx
- tests/integration/ssr/fixtures/streaming-inline/src/routes/error/page.loader.ts
- tests/integration/ssr/fixtures/streaming-inline/src/routes/error/page.tsx
- tests/integration/ssr/fixtures/streaming-inline/src/routes/layout.tsx
- tests/integration/ssr/fixtures/streaming-inline/src/routes/redirect/page.loader.ts
- tests/integration/ssr/fixtures/streaming-inline/src/routes/redirect/page.tsx
- tests/integration/ssr/fixtures/streaming-inline/src/routes/user/[id]/page.loader.ts
- tests/integration/ssr/fixtures/streaming-inline/src/routes/user/[id]/page.tsx
- tests/integration/ssr/fixtures/streaming-inline/src/routes/user/layout.tsx
- tests/integration/ssr/fixtures/streaming-inline/src/routes/user/page.tsx
- tests/integration/ssr/fixtures/streaming-inline/tsconfig.json
- tests/integration/ssr/tests/streaming-inline.test.ts
> Feat ssr stream csp

- .changeset/honest-trainers-sell.md
- packages/runtime/plugin-router-v5/src/runtime/plugin.tsx
> fix: router v5 baseUrl problem

- tests/e2e/builder/scripts/shared.ts
https://github.com/rspack-contrib/rsbuild-ecosystem-ci/actions/runs/11511145042/job/32044116940
> test: fix ERR_UNSAFE_PORT error

- .changeset/old-ties-type.md
- packages/cli/plugin-ssg/src/server/index.ts
> feat: print ssg subprocess log

- .changeset/brave-humans-flash.md
- packages/cli/uni-builder/src/shared/plugins/htmlMinify.ts
- packages/cli/uni-builder/tests/__snapshots__/minimize.test.ts.snap
- packages/cli/uni-builder/tests/minimize.test.ts
> fix: support tools.htmlPlugin.minify false

- packages/document/main-doc/docs/en/configure/app/tools/terser.mdx
- packages/document/main-doc/docs/en/configure/app/tools/ts-loader.mdx
- packages/document/main-doc/docs/en/configure/app/tools/webpack-chain.mdx
- packages/document/main-doc/docs/zh/configure/app/tools/terser.mdx
- packages/document/main-doc/docs/zh/configure/app/tools/ts-loader.mdx
- packages/document/main-doc/docs/zh/configure/app/tools/webpack-chain.mdx
- packages/document/module-doc/docs/en/api/config/dev.md
- packages/document/module-doc/docs/zh/api/config/dev.md
- packages/toolkit/utils/src/universal/formatWebpack.ts
- packages/toolkit/utils/tests/universal/__snapshots__/formatWebpack.test.ts.snap
> docs: fix broken builder links

- .changeset/hip-bears-switch.md
- packages/solutions/app-tools/src/commands/index.ts
- packages/solutions/app-tools/src/hooks.ts
- packages/solutions/app-tools/src/plugins/analyze/index.ts
- packages/solutions/app-tools/src/types/hooks.ts
> feat: delete unused hook api

- .changeset/silent-weeks-allow.md
- packages/runtime/plugin-runtime/src/common.ts
- packages/runtime/plugin-runtime/src/router/runtime/plugin.tsx
- packages/runtime/plugin-runtime/src/router/runtime/types.ts
> feat(router): support v7_startTransition configuration

- tests/integration/bff-express/src/upload/App.tsx
- tests/integration/bff-koa/src/routes/upload/page.tsx
> fix: upload test case

- .changeset/angry-tigers-scream.md
- packages/server/bff-core/src/operators/http.ts
> fix: zod not found error

- .github/renovate.json5
> chore: rsbuild package update add updateTypes config with renovate

- .changeset/fifty-starfishes-remain.md
- packages/runtime/plugin-runtime/src/router/runtime/constants.ts
> fix: parse routerDataFnArgs in mergeLoaderData function

- .changeset/quiet-ravens-watch.md
- packages/document/main-doc/docs/en/guides/advanced-features/source-build.mdx
- packages/document/main-doc/docs/zh/guides/advanced-features/source-build.mdx
- pnpm-lock.yaml
fix the documentation of source build error
> docs: fix the documentation of source build error

- .changeset/soft-kiwis-nail.md
- packages/cli/plugin-bff/package.json
- packages/cli/plugin-data-loader/package.json
- packages/cli/rsbuild-plugin-esbuild/package.json
- packages/cli/uni-builder/package.json
- packages/runtime/plugin-runtime/package.json
- packages/server/server/package.json
- packages/solutions/app-tools/package.json
- packages/toolkit/utils/package.json
- pnpm-lock.yaml
- scripts/prebundle/package.json
fix rsbuild-ecosystem-ci
https://github.com/rspack-contrib/rsbuild-ecosystem-ci/actions/runs/11660099879/job/32461776639
> chore(deps): bump webpack to 5.96.x

- packages/server/core/src/types/server.ts
> chore: remove useless SSRServerContext type

- packages/runtime/plugin-runtime/src/core/context/runtime.ts
> chore: pickContext should be extend now

- .changeset/curly-ducks-kiss.md
- packages/server/core/src/pluginManager.ts
- packages/server/core/src/types/plugin.ts
- packages/toolkit/utils/src/cli/require.ts
> fix: hot reload problems for server

- packages/document/main-doc/src/i18n/enUS.ts
- packages/document/main-doc/src/i18n/zhCN.ts
- packages/document/main-doc/src/pages/index.tsx
This PR follows https://github.com/web-infra-dev/modern.js/pull/6491 and removes Modern.js Module from the home page.
> docs: update homepage

- packages/document/main-doc/docs/en/guides/concept/entries.mdx
- packages/document/main-doc/docs/zh/guides/concept/entries.mdx
Add new `In-Depth` and `Trouableshooting` chapters to the `entries` page.
> docs: refine entries docs

- .changeset/large-carrots-remember.md
- packages/server/core/src/adapters/node/node.ts
> feat: passthrough body, when receiving an mf request

- packages/document/main-doc/docs/en/apis/app/runtime/core/use-runtime-context.mdx
- packages/document/main-doc/docs/zh/apis/app/runtime/core/use-runtime-context.mdx
add standard data structure docs for RuntimeContext API
> docs: modify use runtimeRuntimeContext api docs

- .changeset/ninety-foxes-deliver.md
- packages/document/module-doc/docs/en/api/config/build-config.mdx
- packages/document/module-doc/docs/zh/api/config/build-config.mdx
- packages/solutions/module-tools/src/builder/esbuild/index.ts
- packages/solutions/module-tools/src/builder/esbuild/resolve.ts
- packages/solutions/module-tools/src/config/merge.ts
- packages/solutions/module-tools/src/constants/build.ts
- packages/solutions/module-tools/src/types/config/index.ts
add resolve.tsConfig to let user adjust the configuration
> feat(module-tool): add resolve.tsConfig

- packages/document/module-doc/docs/en/api/config/build-config.mdx
- packages/document/module-doc/docs/zh/api/config/build-config.mdx
- packages/solutions/module-tools/src/builder/esbuild/index.ts
- packages/solutions/module-tools/src/config/merge.ts
- packages/solutions/module-tools/src/config/normalize.ts
use absolute path, fix the CI error
> fix(module-tools): `resolve.tsConfig.configFilePath` default value should work

- .changeset/curvy-buttons-march.md
- packages/runtime/plugin-runtime/src/document/Script.tsx
- packages/runtime/plugin-runtime/src/document/cli/index.ts
- packages/runtime/plugin-runtime/src/document/constants.ts
- tests/integration/app-document/src/sub/Document.tsx
- tests/integration/app-document/tests/index.test.ts
> feat: support Script with script properties

- .changeset/curvy-buttons-march.md
- tests/integration/app-document/package.json
- tests/integration/app-document/tests/index.test.ts
> fix: support script properity in script

- .changeset/mean-turkeys-cry.md
- packages/generator/generators/base-generator/modern.config.js
- packages/generator/generators/mwa-generator/modern.config.js
- packages/generator/generators/packages-generator/modern.config.js
- packages/generator/generators/upgrade-generator/package.json
- packages/toolkit/create/modern.config.js
- packages/toolkit/upgrade/modern.config.js
- scripts/build/src/index.js
> fix: new and upgrade command run error

- .changeset/serious-beers-beg.md
- pnpm-lock.yaml
- tests/integration/devtools/package.json
fix(devtools): rsdoctor get resolved module module graph
> fix(devtools): rsdoctor getResolvedModule module graph

- .changeset/swift-experts-rhyme.md
- packages/cli/uni-builder/package.json
- packages/cli/uni-builder/src/shared/parseCommonConfig.ts
- packages/cli/uni-builder/src/types.ts
- packages/cli/uni-builder/tests/__snapshots__/default.test.ts.snap
- packages/cli/uni-builder/tests/__snapshots__/environment.test.ts.snap
- packages/cli/uni-builder/tests/__snapshots__/minimize.test.ts.snap
- pnpm-lock.yaml
Bump @rsbuild/plugin-type-check v1.1.
https://github.com/rspack-contrib/rsbuild-plugin-type-check/releases/tag/v1.1.0
close https://github.com/web-infra-dev/modern.js/pull/6553
> chore(deps): bump @rsbuild/plugin-type-check v1.1

- .changeset/fast-frogs-accept.md
- packages/document/main-doc/docs/en/guides/advanced-features/bff/function.mdx
- packages/document/main-doc/docs/zh/guides/advanced-features/bff/function.mdx
> feat: bff doc add shared source

- .changeset/red-sloths-happen.md
- packages/solutions/app-tools/src/new/compat/hooks.ts
- packages/solutions/app-tools/src/new/compat/utils.ts
- packages/solutions/app-tools/src/utils/restart.ts
- packages/toolkit/plugin-v2/src/cli/api.ts
- packages/toolkit/plugin-v2/src/types/cli/api.ts
> fix: addWatchFiles && fileChange hook not work

- tests/integration/ssr/fixtures/streaming-inline/modern.config.ts
> fix: ssr streaming json script test case

- packages/toolkit/plugin-v2/src/cli/run/create.ts
> fix: setup can be empty

- packages/solutions/app-tools/src/compat/utils.ts
> fix: partials params for test

- .changeset/unlucky-boats-own.md
- packages/server/core/src/adapters/node/plugins/resource.ts
#6638 load server bundles on server preparing
> chore: should load html template while server preparing

- .changeset/dirty-spies-cough.md
- packages/solutions/app-tools/src/compat/utils.ts
> fix: compat htmlPartials hooks result error

- .changeset/tasty-cameras-hide.md
- packages/solutions/app-tools/src/run/index.ts
> feat: add metaName

- tests/integration/server-routes/tests/index.test.ts
Related to #6651 
Delete useless test case.
> fix: remove test case

- .github/workflows/release-nightly.yml
- .github/workflows/release-pull-request.yml
- .github/workflows/release.yml
- package.json
> chore: release workflow use GITHUB_TOKEN

- .github/workflows/create-release-tag.yml
- .github/workflows/release-pull-request.yml
- package.json
- pnpm-lock.yaml
- scripts/release-version/package.json
- scripts/release-version/src/index.ts
- scripts/release-version/tsconfig.json
- add get-release-version scripts
- adjust create release pull request workflow
- add create release and release tag workflow
> chore: release workflow

- .changeset/modern-bulldogs-cross.md
- packages/toolkit/plugin-v2/src/manager.ts
- packages/toolkit/plugin-v2/src/types/plugin.ts
> feat: support isPluginExists for plugin manager

- packages/document/main-doc/docs/zh/guides/basic-features/render/ssr.mdx
> docs: ssr typo

- .changeset/plenty-beers-guess.md
- packages/toolkit/plugin-v2/src/cli/api.ts
- packages/toolkit/plugin-v2/src/cli/index.ts
- packages/toolkit/plugin-v2/src/cli/run/index.ts
- packages/toolkit/plugin-v2/src/types/cli/api.ts
> feat: plugin api add isPluginExists

- packages/cli/plugin-ssg/src/server/process.ts
It's unreleased bug so no need to add a changeset.
> fix: ssg result disorder

- .changeset/gorgeous-buttons-wink.md
- .changeset/kind-ducks-worry.md
- .changeset/lazy-comics-sleep.md
- .changeset/silver-gorillas-obey.md
- packages/solutions/app-tools/src/compat/hooks.ts
- packages/solutions/app-tools/src/compat/utils.ts
- packages/solutions/app-tools/src/plugins/analyze/index.ts
- packages/toolkit/plugin-v2/src/cli/api.ts
- packages/toolkit/plugin-v2/src/cli/hooks.ts
- packages/toolkit/plugin-v2/src/cli/index.ts
- packages/toolkit/plugin-v2/src/cli/run/config/createLoadedConfig.ts
- packages/toolkit/plugin-v2/src/cli/run/create.ts
- packages/toolkit/plugin-v2/src/cli/run/types.ts
- packages/toolkit/plugin-v2/src/cli/run/utils/debug.ts
- packages/toolkit/plugin-v2/src/manager.ts
- packages/toolkit/plugin-v2/src/types/cli/api.ts
- packages/toolkit/plugin-v2/src/types/cli/hooks.ts
- feat: add onDevCompileDone hook
- feat: export plugin v2 function type
- feat: plugin run function support config params to overrides config file content
- feat: handle api not register error
> feat: plugin v2 support config params && plugin v2 add onDevCompileDone hook && handle api not register error

- .changeset/tender-llamas-float.md
- packages/generator/generators/mwa-generator/templates/base-template/package.json.handlebars
> feat: upgarde the basic dependency version in the template

- .changeset/plenty-donuts-call.md
- .changeset/silly-ways-smile.md
- packages/runtime/plugin-router-v5/src/runtime/index.ts
- packages/runtime/plugin-router-v5/src/runtime/plugin.tsx
- packages/runtime/plugin-runtime/src/router/runtime/hooks.ts
- packages/runtime/plugin-runtime/src/router/runtime/index.ts
- packages/runtime/plugin-runtime/src/router/runtime/plugin.node.tsx
- packages/runtime/plugin-runtime/src/router/runtime/plugin.tsx
- packages/toolkit/plugin-v2/src/cli/api.ts
- packages/toolkit/plugin-v2/src/runtime/api.ts
- packages/toolkit/plugin-v2/src/types/cli/api.ts
- packages/toolkit/plugin-v2/src/types/runtime/api.ts
- export RouterExtendsHooks type
- plugin api type support extend hooks and api
> feat: export router extend hooks type

- .changeset/plenty-cobras-brush.md
- packages/server/core/src/plugins/log.ts
- packages/solutions/app-tools/src/esm/register-esm.mjs
> fix: remove register esbuild in registerEsm & should log status correctly

- .github/workflows/integration-test-Windows.yml
- .github/workflows/lint-Linux.yml
- .github/workflows/release-nightly.yml
- .github/workflows/release.yml
- .github/workflows/test-Windows.yml
- .github/workflows/test-builder-e2e.yml
- .github/workflows/test-garfish-e2e.yml
- .github/workflows/test-macOS.yml
- .github/workflows/test-module-Linux.yml
- .github/workflows/test-module-Windows.yml
- .github/workflows/vitest-Windows.yml
- .github/workflows/vitest-macOS.yml
- packages/cli/uni-builder/tests/__snapshots__/parseConfig.test.ts.snap
- packages/cli/uni-builder/tests/parseConfig.test.ts
https://github.com/actions/setup-node/issues/1222
> fix: setup-node error

- packages/document/main-doc/package.json
- packages/document/main-doc/rspress.config.ts
- packages/document/module-doc/package.json
- packages/document/module-doc/rspress.config.ts
- pnpm-lock.yaml
https://github.com/web-infra-dev/rslib/pull/735
https://github.com/web-infra-dev/rspack/pull/9158
https://github.com/web-infra-dev/rsbuild/pull/4483
https://github.com/web-infra-dev/rsdoctor/pull/748
> docs: update rspress 1.41.0 and enable codeBlocks search

- .changeset/rotten-numbers-heal.md
- packages/solutions/app-tools/src/index.ts
- packages/solutions/app-tools/src/types/new.ts
- packages/toolkit/plugin-v2/src/cli/api.ts
- packages/toolkit/plugin-v2/src/cli/hooks.ts
- packages/toolkit/plugin-v2/src/cli/index.ts
- packages/toolkit/plugin-v2/src/types/cli/api.ts
- packages/toolkit/plugin-v2/src/types/cli/hooks.ts
> feat: move modifyServerRoutes hook to plugin v2

- packages/cli/uni-builder/src/shared/rsc/plugins/rsbuild-rsc-plugin.ts
- pnpm-lock.yaml
- tests/integration/rsc-csr-app/package.json
- tests/integration/rsc-ssr-app/package.json
> fix: integration test cases for windows

- .changeset/good-cars-knock.md
- packages/server/prod-server/src/index.ts
- packages/solutions/app-tools/src/commands/dev.ts
- packages/solutions/app-tools/src/commands/serve.ts
Some change for the pre PR #6815 . We need pass server launcher to serve command.
> chore: support serve command use custom serve launcher

- .changeset/friendly-lobsters-notice.md
- packages/toolkit/plugin-v2/package.json
> fix: plugin v2 runtime export add node config

- packages/toolkit/utils/src/cli/version.ts
- tests/integration/rsc-csr-app/tests/index.test.ts
- tests/integration/rsc-ssr-app/tests/index.test.ts
> chore: only run rsc tests in node18 and above

- tests/integration/rsc-csr-app/tests/index.test.ts
- tests/integration/rsc-ssr-app/tests/index.test.ts
> chore: add default test case when node version is less than 18

- .changeset/silver-schools-whisper.md
- packages/toolkit/types/server/hook.d.ts
> fix: types for custom server hook

- .changeset/yellow-mugs-return.md
- packages/runtime/plugin-runtime/src/router/cli/code/templates.ts
> fix(router): compatible with splitRouteChunks is false in react17 + csr

- .changeset/thick-rules-lie.md
- packages/cli/plugin-bff/src/utils/clientGenerator.ts
- tests/integration/bff-corss-project/tests/index.test.ts
> fix: bff package path

- .changeset/swift-apes-unite.md
> docs: add changeset

- .changeset/early-bats-remain.md
- packages/toolkit/plugin-v2/src/cli/api.ts
cli plugin use merge utils to update context will add extra info, so adjust using assign utils
> feat: use assign to update context

- README.md
Add some links to badges in README which could provide more info.
> docs: add links to badges

- packages/cli/uni-builder/src/shared/rsc/plugins/rsbuild-rsc-plugin.ts
- packages/toolkit/runtime-utils/src/universal/cache.ts
- packages/toolkit/runtime-utils/tests/universal/cache-client.test.ts
- packages/toolkit/utils/package.json
> fix: some test problems

- packages/cli/uni-builder/src/shared/rsc/plugins/rsbuild-rsc-plugin.ts
> fix: should share async_storage module

- packages/document/main-doc/docs/en/configure/app/runtime/master-app.mdx
- packages/document/main-doc/docs/zh/configure/app/runtime/master-app.mdx
> docs: update garfish config doc link

- .vscode/extensions.json
> chore: remove some recommend extensions

- packages/toolkit/runtime-utils/package.json
- pnpm-lock.yaml
> fix: lru-cache version

- packages/toolkit/runtime-utils/src/node/fileReader.ts
> fix: remove console

- packages/document/main-doc/docs/en/guides/basic-features/routes.mdx
- packages/document/main-doc/docs/zh/guides/basic-features/routes.mdx
> docs: improve types and code in the doc of router

- .changeset/curvy-lemons-press.md
- packages/runtime/plugin-garfish/src/runtime/provider.tsx
> fix(plugin-garfish): fix the compatibility issue of the garfish plugin rendering nodes

- .changeset/khaki-coins-lie.md
- packages/runtime/plugin-garfish/src/cli/index.ts
- packages/runtime/plugin-garfish/tests/__snapshots__/cli.test.tsx.snap
- packages/runtime/plugin-garfish/tests/cli.test.tsx
> feat: remove garfish plugin set public path

- .changeset/khaki-coins-lie.md
- packages/runtime/plugin-garfish/src/cli/index.ts
- packages/runtime/plugin-garfish/tests/__snapshots__/cli.test.tsx.snap
- packages/runtime/plugin-garfish/tests/cli.test.tsx
Reverts web-infra-dev/modern.js#6948
> Revert "feat: remove garfish plugin set public path"

- .changeset/gorgeous-planets-exercise.md
- packages/solutions/app-tools/src/plugins/analyze/getServerRoutes.ts
> fix: route.json html entry path when config html.outputStructure

- .changeset/tame-eggs-deliver.md
- packages/toolkit/runtime-utils/src/universal/cache.ts
- packages/toolkit/runtime-utils/tests/universal/cache-server.test.ts
> fix(cache): handle different functions with same params for cache function

- packages/document/main-doc/docs/en/apis/app/hooks/config/_meta.json
- packages/document/main-doc/docs/en/apis/app/hooks/config/favicon.mdx
- packages/document/main-doc/docs/en/apis/app/hooks/config/icon.mdx
- packages/document/main-doc/docs/zh/apis/app/hooks/config/_meta.json
- packages/document/main-doc/docs/zh/apis/app/hooks/config/favicon.mdx
- packages/document/main-doc/docs/zh/apis/app/hooks/config/icon.mdx
> fix: split icon/ docs to favicon.* and icon.*

- .changeset/early-drinks-repeat.md
- .changeset/two-guests-argue.md
- packages/cli/uni-builder/src/shared/rsc/plugins/rsc-server-plugin.ts
- packages/cli/uni-builder/src/shared/rsc/plugins/rspack-rsc-client-plugin.ts
- packages/cli/uni-builder/src/shared/rsc/plugins/rspack-rsc-server-plugin.ts
- tests/integration/rsc-csr-app/tests/index.test.ts
- tests/integration/rsc-ssr-app/modern.config.ts
- tests/integration/rsc-ssr-app/tests/index.test.ts
The PR is for improve support rsc with rspack
> feat: improve support rsc with rspack

- .changeset/afraid-pumas-complain.md
- packages/runtime/plugin-runtime/src/router/cli/code/templates.ts
> fix: global context appInit and appConfig not define error

- .changeset/stale-otters-attack.md
- packages/solutions/app-tools/src/builder/generator/index.ts
- packages/solutions/app-tools/src/builder/shared/builderPlugins/adapterBasic.ts
> fix: temp dir of the framework should be watched

- .changeset/short-cows-clap.md
- packages/solutions/app-tools/src/run/index.ts
> feat: add node 16 will not support warning

- packages/toolkit/utils/src/cli/version.ts
- tests/integration/pure-esm-project/tests/index.test.ts
> test: add --no-experimental-require-module for node20 test cases

- tests/integration/ssr/fixtures/streaming/modern.config.ts
> test: should not use http2

- .changeset/light-seals-divide.md
- .nvmrc
- packages/document/main-doc/docs/en/components/nodeVersion.mdx
- packages/document/main-doc/docs/en/components/prerequisites.mdx
- packages/document/main-doc/docs/zh/components/nodeVersion.mdx
- packages/document/main-doc/docs/zh/components/prerequisites.mdx
- packages/generator/generators/base-generator/templates/base-template/.nvmrc
- packages/solutions/app-tools/src/run/index.ts
> docs: update node version

- packages/document/module-doc/docs/en/api/config/build-preset.mdx
- packages/document/module-doc/docs/zh/api/config/build-preset.mdx
Remove wrong description of bundleless css.
> docs: remove wrong description of bundleless css

- .changeset/witty-news-vanish.md
- packages/server/server/src/helpers/devOptions.ts
> fix(server): webCompiler maybe undefined

- .changeset/twenty-bugs-mate.md
- packages/runtime/plugin-garfish/src/runtime/plugin.tsx
> fix: garfish plugin config name

- .changeset/rude-lemons-poke.md
- packages/generator/generators/storybook-next-generator/templates/stories/index.stories.handlebars
> fix: storybook generator template

- packages/document/main-doc/docs/en/apis/app/runtime/app/define-config.mdx
- packages/document/main-doc/docs/zh/apis/app/runtime/app/define-config.mdx
> fix: runtime doc typo

- .github/workflows/check-dependencies.yml
- package.json
- scripts/check-dependencies.js
> build: check dependencies while commiting

- .changeset/odd-eagles-drive.md
- packages/server/create-request/src/browser.ts
- packages/server/create-request/src/utiles.ts
- tests/integration/bff-express/api/upload.ts
- tests/integration/bff-express/src/upload/App.tsx
> feat(bff): support params and headers for Upload

- .changeset/fresh-hats-relax.md
- packages/solutions/app-tools/package.json
- packages/solutions/app-tools/src/plugins/deploy/platforms/netlify-entry.cjs
- packages/solutions/app-tools/src/plugins/deploy/platforms/netlify.ts
- pnpm-lock.yaml
> fix(deploy): fix the deploy problem for netlify

- .changeset/mighty-spoons-brush.md
- packages/server/core/src/adapters/node/plugins/resource.ts
- packages/server/core/src/adapters/node/plugins/static.ts
- packages/server/core/src/plugins/render/index.ts
- packages/server/core/src/types/config/server.ts
In this PR, we optimized the server-side performance of modern.js. 
The improvements mainly comprise three key optimizations:
1. Page routes no longer go through "static assets middleware" processing.
2. Pages without RSC enabled will not use the "RSC Manifest injection middleware".
3. Added a new configuration `server.disableHook` to allow project which not use Hooks to skip "Hook middleware" execution.
The Hook middleware, due to historical reasons, performs stream-to-string conversion and back, which significantly impacts performance. 
Going forward, we recommend directly handling streams in "Unstable_Middleware" rather than converting them to strings for processing.
These optimizations resulted in a 60% performance improvement for the Demo running in a 1C1G (1 Core 1GB) container …
> feat: improve ssr performance

- .changeset/giant-moons-lie.md
- packages/document/main-doc/rspress.config.ts
- packages/server/core/src/adapters/node/plugins/static.ts
This PR modify the default language of document.
And add some fix for #7048 .
> docs: use en as the default lang of document

- tests/integration/image-component/tests/index.test.ts
> fix(image): failed in node16 CI environment

- tests/integration/deploy-server/tests/__snapshots__/index.test.ts.snap
- tests/integration/deploy-server/tests/index.test.ts
> chore: fix the deploy test case

- packages/document/module-doc/docs/en/api/config/build-config.mdx
- packages/document/module-doc/docs/en/guide/advance/copy.md
- packages/document/module-doc/docs/zh/api/config/build-config.mdx
- packages/document/module-doc/docs/zh/guide/advance/copy.md
Link the copy option to the copy guide page and add new example for glob files.
> docs(module-tools): link to copy guide and add new example

- .changeset/heavy-days-kick.md
- packages/toolkit/runtime-utils/src/browser/nestedRoutes.tsx
> fix(router): replace slashes in route ID for loader timing reporting

- packages/document/main-doc/docs/en/guides/basic-features/deploy.mdx
- packages/document/main-doc/docs/en/guides/get-started/quick-start.mdx
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/web-infra-dev/modern.js/pull/7119).
* __->__ #7119
* #7118
> fix(doc): fix several MDX bugs

- packages/document/main-doc/docs/en/guides/get-started/quick-start.mdx
Change-Id: max/fix-doc-port-number
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/web-infra-dev/modern.js/pull/7118).
* #7119
* __->__ #7118
> fix(doc): fix port number in tutorial

- packages/document/module-doc/docs/en/api/config/build-config.mdx
- packages/document/module-doc/docs/zh/api/config/build-config.mdx
> docs: fix default sass version

- packages/document/module-doc/docs/zh/api/config/build-config.mdx
> docs(module-tools): remove some useless code

- packages/document/main-doc/docs/en/guides/advanced-features/compatibility.mdx
- packages/document/main-doc/docs/en/guides/basic-features/data/data-fetch.mdx
- packages/document/main-doc/docs/en/guides/basic-features/render/ssr.mdx
- packages/document/main-doc/docs/en/guides/concept/entries.mdx
- packages/document/main-doc/docs/en/tutorials/first-app/c05-loader.mdx
- packages/generator/generators/entry-generator/templates/routes/page.handlebars
- packages/runtime/plugin-runtime/src/router/runtime/plugin.node.tsx
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/web-infra-dev/modern.js/pull/7138).
* __->__ #7138
* #7137
* #7135
* #7134
* #7133
> fix(doc): fix markdown bug in compatibility.mdx

- packages/document/main-doc/docs/en/guides/advanced-features/bff.mdx
- packages/document/main-doc/docs/en/guides/advanced-features/page-performance/inline-assets.mdx
- packages/document/main-doc/docs/en/guides/advanced-features/page-performance/optimize-bundle.mdx
- packages/document/main-doc/docs/en/guides/basic-features/html.mdx
- packages/server/core/src/plugins/render/ssrRender.ts
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/web-infra-dev/modern.js/pull/7148).
* __->__ #7148
* #7146
* #7145
> fix(doc): fix performance typos

- packages/document/main-doc/docs/en/plugin/runtime-plugins/api.mdx
- packages/document/main-doc/docs/zh/plugin/runtime-plugins/api.mdx
> fix: runtime plugin example

- packages/document/main-doc/docs/en/configure/app/tools/swc.mdx
- packages/document/main-doc/docs/en/guides/basic-features/deploy.mdx
- packages/document/main-doc/docs/zh/configure/app/tools/swc.mdx
- packages/document/main-doc/docs/zh/guides/basic-features/deploy.mdx
- packages/document/main-doc/package.json
- pnpm-lock.yaml
docs(deps): upgrade to rspress-2.0.0-beta.6 and fix diff code block highlight
https://github.com/web-infra-dev/rspress/pull/2175
https://github.com/web-infra-dev/rspack/pull/10387
> docs(deps): upgrade to rspress-2.0.0-beta.6 and fix diff code block highlight

- README.md
- README.zh-CN.md
- packages/document/main-doc/rspress.config.ts
> docs: readme add discord and lark link

- packages/document/main-doc/docs/en/configure/app/output/dist-path.mdx
- packages/document/main-doc/docs/en/guides/basic-features/output-files.mdx
- packages/document/main-doc/docs/zh/configure/app/output/dist-path.mdx
- packages/document/main-doc/docs/zh/guides/basic-features/output-files.mdx
> docs: remove `distPath.server` docs until support it

- packages/document/main-doc/docs/en/guides/basic-features/data/data-cache.mdx
- packages/document/main-doc/docs/en/guides/basic-features/render/ssr.mdx
- packages/document/main-doc/docs/en/guides/basic-features/render/streaming-ssr.mdx
- packages/document/main-doc/docs/en/guides/basic-features/static-assets/wasm-assets.mdx
- packages/document/main-doc/docs/zh/guides/basic-features/data/data-cache.mdx
- packages/document/main-doc/docs/zh/guides/basic-features/render/ssr.mdx
- packages/document/main-doc/docs/zh/guides/basic-features/render/streaming-ssr.mdx
- packages/document/main-doc/docs/zh/guides/basic-features/static-assets/wasm-assets.mdx
Fixed some documentation errors that I personally reported through OnCall Requests
N/A
Commits for 4 different files in English and Chinese
> docs: fix some information in both Chinese and English

- .changeset/late-readers-bet.md
- packages/generator/generators/server-generator/src/index.ts
> fix: server generator add version verification

- packages/runtime/plugin-image/package.json
- pnpm-lock.yaml
> revert: bump @rsbuild-image/react

- packages/cli/uni-builder/src/webpack/plugins/babel.ts
fix integration issue caused by #7209
> fix: integration test for babel-object-config

- tests/e2e/builder/cases/dev/dev.test.ts
> fix: skip some unnecessary test case in unibuilder

- packages/document/main-doc/docs/zh/guides/topic-detail/micro-frontend/c02-development.mdx
> fix: garfish doc link

- .github/renovate.json5
- packages/document/main-doc/package.json
- pnpm-lock.yaml
Reverts web-infra-dev/modern.js#7277
> Revert "chore(deps): update rspress monorepo to v2.0.0-beta.18"

- packages/document/main-doc/docs/en/apis/app/runtime/web-server/hook.mdx
- packages/document/main-doc/docs/en/apis/app/runtime/web-server/middleware.mdx
- packages/document/main-doc/docs/en/apis/app/runtime/web-server/unstable_middleware.mdx
- packages/document/main-doc/docs/zh/apis/app/runtime/web-server/hook.mdx
- packages/document/main-doc/docs/zh/apis/app/runtime/web-server/middleware.mdx
- packages/document/main-doc/docs/zh/apis/app/runtime/web-server/unstable_middleware.mdx
> feat: doc warns old Web Server migrate to new version

- .changeset/all-trams-vanish.md
- package.json
- packages/cli/rsbuild-plugin-esbuild/package.json
- packages/runtime/plugin-runtime/package.json
- packages/solutions/app-tools/package.json
- packages/toolkit/node-bundle-require/package.json
- pnpm-lock.yaml
- scripts/jest-config/package.json
feat: update esbuild version to 0.25.5
> feat: update esbuild version to 0.25.5

- packages/cli/plugin-swc/package.json
- packages/cli/rsbuild-plugin-esbuild/package.json
- packages/cli/uni-builder/package.json
- packages/cli/uni-builder/tests/__snapshots__/babel.test.ts.snap
- packages/cli/uni-builder/tests/__snapshots__/default.test.ts.snap
- packages/cli/uni-builder/tests/__snapshots__/environment.test.ts.snap
- packages/cli/uni-builder/tests/__snapshots__/transformImport.test.ts.snap
- packages/devtools/client/package.json
- packages/devtools/plugin/package.json
- packages/runtime/plugin-runtime/package.json
- packages/solutions/app-tools/package.json
- packages/solutions/module-tools/package.json
- packages/storybook/builder/package.json
- packages/toolkit/plugin-v2/package.json
- pnpm-lock.yaml
- tests/e2e/builder/package.json
Reverts web-infra-dev/modern.js#7311
> Revert "fix(deps): update dependency @rsbuild/core to v1.4.5"

- .github/renovate.json5
> chore: renovate branch add v2

- .changeset/config.json
> chore: changeset base branch use v2

- packages/solutions/app-tools/tests/analyze/fixtures/entries/index-entry/src/index.jsx
- tests/e2e/builder/cases/dev/basic/src/index.ts
- tests/e2e/builder/cases/dev/hmr/src/index.ts
- tests/e2e/builder/cases/html/minify/src/index.ts
- tests/e2e/builder/cases/html/mount-id/src/index.ts
- tests/e2e/builder/cases/html/template/src/index.ts
- tests/e2e/builder/cases/legalComments/src/index.jsx
- tests/e2e/builder/cases/manifest/src/index.jsx
- tests/e2e/builder/cases/output/assets-inline/src/index.js
- tests/e2e/builder/cases/output/assets-no-inline/src/index.js
- tests/e2e/builder/cases/output/assets-url/src/index.js
- tests/e2e/builder/cases/output/assets/src/index.js
- tests/e2e/builder/cases/output/assets__inline/src/index.js
- tests/e2e/builder/cases/output/externals/src/index.js
- tests/e2e/builder/cases/output/rem/src/index.ts
- tests/e2e/builder/cases/react/remove-prop-types/src/index.js
- tests/e2e/builder/cases/source-map/src/index.js
- tests/e2e/builder/cases/source/basic/src/index.js
- tests/e2e/builder/cases/source/global-vars/src/index.ts
- tests/e2e/builder/cases/source/module-scopes/src/index.js
- tests/e2e/builder/cases/source/resolve-extension-prefix/src/index.js
- tests/e2e/builder/cases/source/tsconfig-paths/src/index.ts
- tests/e2e/builder/cases/sri/src/index.js
- tests/e2e/builder/cases/tools/pug/src/index.ts
> fix: builder e2e test

- tests/integration/pure-esm-project/api/info.js
Fix test case in pure-esm-test
> fix: pure esm test case

- packages/solutions/app-tools/src/constants.ts
- packages/solutions/app-tools/src/run/index.ts
- packages/solutions/app-tools/src/utils/generateWatchFiles.ts
- packages/toolkit/plugin/src/cli/run/config/createLoadedConfig.ts
- packages/toolkit/plugin/src/cli/run/config/loadConfig.ts
- packages/toolkit/plugin/src/cli/run/create.ts
- packages/toolkit/plugin/src/cli/run/types.ts
- tests/generator/mwa.ts
- tests/integration/server-config/package.json
- tests/package.json
- remove use  modernConfig field in package.json to add modern config, recommend to use `modern.config.ts` file
> feat: remove package json config

- .changeset/bitter-cars-drive.md
- packages/runtime/plugin-runtime/src/document/cli/index.ts
sync for https://github.com/web-infra-dev/modern.js/pull/7449
> sync: cherry pick sync from main

- .changeset/brave-years-jump.md
- packages/runtime/plugin-runtime/src/router/runtime/utils.tsx
- packages/server/core/src/adapters/node/helper/utils.ts
- packages/server/core/src/adapters/node/hono.ts
> feat: support enableHandleWeb for csr + rsc projects

- .changeset/quick-taxis-beam.md
- packages/server/core/src/adapters/node/node.ts
> fix: proxy request

- packages/solutions/app-tools/src/run/index.ts
sync https://github.com/web-infra-dev/modern.js/pull/7463
> feat: export createRunOptions func

- packages/document/main-doc/docs/en/guides/topic-detail/module-federation/application.mdx
- packages/document/main-doc/docs/en/guides/topic-detail/module-federation/ssr.mdx
- packages/document/main-doc/docs/zh/guides/topic-detail/module-federation/application.mdx
- packages/document/main-doc/docs/zh/guides/topic-detail/module-federation/ssr.mdx
This PR update Module Federation Docs.
1. Using the latest API
2. Add guide for fetch data in ssr with mf
> docs: update mf api, add fecth data docs

- .changeset/huge-moons-chew.md
- packages/runtime/plugin-runtime/src/router/cli/code/nestedRoutes.ts
Fix the edge case in the pathless route. At present, when there is a pathless route, and no layout component under pathless route, and the direct sub-route under pathless route is dynamic route, this problem will be reproduced.
> fix: correct route path construction in optimizeRoute function

- packages/server/core/src/adapters/node/node.ts
- packages/toolkit/runtime-utils/src/node/stream.ts
> fix: process should not exit caused when user abort the request

- .github/workflows/check-dependencies.yml
- .github/workflows/integration-test-Linux.yml
- .github/workflows/integration-test-Windows.yml
- .github/workflows/lint-Linux.yml
- .github/workflows/test-Windows.yml
- .github/workflows/test-builder-e2e.yml
- .github/workflows/test-macOS.yml
- .github/workflows/type-check.yml
- .github/workflows/vitest-Windows.yml
- .github/workflows/vitest-macOS.yml
- .pnpmfile.cjs
- pnpm-lock.yaml
- simple .pnpmfile.cjs config
- update github action workflow's node version to v22
> chore: simple pnpm file && update action workflow node version to 22

- packages/document/main-doc/docs/en/guides/advanced-features/web-server.mdx
- packages/document/main-doc/docs/zh/guides/advanced-features/web-server.mdx
> docs: add hono link in web server

- .changeset/spotty-olives-visit.md
- packages/runtime/plugin-garfish/src/runtime/utils/apps.tsx
> fix: garfish component render

- packages/cli/plugin-bff/package.json
- packages/cli/plugin-bff/src/cli.ts
- pnpm-lock.yaml
> fix: the alias structure being an object caused BFF build errors

- .changeset/wide-humans-tease.md
- packages/cli/plugin-bff/src/runtime/hono/adapter.ts
- packages/cli/plugin-bff/src/utils/createHonoRoutes.ts
- packages/document/main-doc/docs/en/guides/advanced-features/web-server.mdx
- packages/document/main-doc/docs/zh/guides/advanced-features/web-server.mdx
- packages/server/core/src/types/plugins/base.ts
- packages/server/prod-server/src/apply.ts
- tests/integration/bff-hono/api/error/index.ts
- tests/integration/bff-hono/api/error/managed.ts
- tests/integration/bff-hono/server/modern.server.ts
- tests/integration/bff-hono/src/routes/error/page.tsx
- tests/integration/bff-hono/tests/index.test.ts
- Custom Web Server supports error handling
> feat: server config support onError

- packages/document/main-doc/docs/en/tutorials/first-app/c02-component.mdx
> use en url

- .changeset/silly-carpets-mix.md
- packages/server/server/src/dev-tools/watcher/dependencyTree.ts
> fix: update treeNode

- .changeset/wet-spiders-sell.md
- packages/server/server/src/dev-tools/watcher/dependencyTree.ts
> fix: update treeNode (v2)

- .changeset/common-bats-agree.md
- packages/runtime/plugin-garfish/src/runtime/utils/apps.tsx
> fix: garfish plugin popstate not trigger

- packages/runtime/plugin-runtime/src/document/cli/index.ts
> fix: add runtime/document alias

- packages/runtime/plugin-runtime/package.json
> fix: should export document entry correctly

- .changeset/angry-results-bake.md
- packages/solutions/app-tools/package.json
> feat: add applools builder types
