web-infra-dev/modern.js

packages/cli/plugin-tailwind/package.json
packages/toolkit/utils/src/constants.ts

1. change `tools.tailwind` to `tools.tailwindcss`
2. change tailwindcss deps in package.json

feat(plugin-tailwindcss): change option

---

.changeset/wise-dodos-argue.md
packages/cli/plugin-storybook/package.json
packages/cli/plugin-storybook/src/features/utils/genConfigDir.ts
packages/cli/plugin-storybook/template/preview.tmpl

Feat esbuild generator preview

---

packages/cli/plugin-unbundle/src/utils.ts
packages/cli/plugin-unbundle/src/websocket-server.ts

feat(plugin-unbundle): log info for file change

---

packages/cli/plugin-storybook/CHANGELOG.md
packages/cli/plugin-storybook/package.json
packages/cli/plugin-unbundle/src/plugins/container.ts
packages/solutions/app-tools/CHANGELOG.md
packages/solutions/app-tools/package.json

* @modern-js/plugin-storybook
* @modern-js/app-tools

chore:  publish hotfix

---

.changeset/eleven-mirrors-learn.md
packages/cli/plugin-storybook/src/index.ts

fix stories path in window env when run `dev` command

Fix module storybook error path

---

.changeset/eleven-bugs-impress.md
packages/cli/babel-preset-base/src/plugins.ts
packages/server/utils/tests/__snapshots__/babel.test.ts.snap

Fix remove transform typescrit

---

packages/cli/webpack/src/config/base.ts
pnpm-lock.yaml

* 修复 colors@1.4.2 安装错误的问题
* 修复 css url function  中使用 svg 报错的问题

fix(webpack): use svgr with css-loader@6.0

---

.github/workflows/test-macOS.yml
jest.config.js

feat: enable codecov

---

fast-lint.sh

Eslint got an error for file not existing when a file is deleted in develop branch.

fix(lint): add file filter ACM [skip ci]

---

.changeset/large-planes-repeat.md
packages/generator/generator-cases/tests/index.test.ts
packages/generator/generator-common/src/locale/en.ts
packages/generator/generator-common/src/locale/zh.ts
packages/generator/generator-common/src/mwa/deploy.ts
packages/generator/generator-common/src/newAction/common/index.ts
packages/generator/generator-common/src/newAction/mwa/index.ts

应用（MWA）项目 new 命令支持启用基于「UA 的 Polyfill」功能
app-tools new 命令增加 启用基于「UA 的 Polyfill」功能 选项，启用后自动安装  @modern-js/plugin-polyfill
https://github.com/modern-js-dev/modern-js-examples/issues/15

feat: polyfill function support enable

---

.changeset/tender-fishes-perform.md
CONTRIBUTING.md
packages/generator/generator-plugin/src/context/input.ts

fix: generator plugin input type

---

.changeset/breezy-geese-speak.md
packages/cli/plugin-ssr/node.ts
packages/cli/plugin-ssr/package.json
packages/cli/plugin-testing/tests/index.test.ts
packages/cli/webpack/src/config/client.ts
packages/cli/webpack/tests/client.test.ts
packages/review/testing-plugin-bff/src/mockAPI.ts
packages/review/testing-plugin-bff/tests/index.test.ts
packages/server/create-request/src/node.ts

fix #501
在 #481 对应的 PR 里面修改了 @modern-js/plugin-ssr 中 package.json 的配置，影响到了一些其他模块。
现在回滚之前的这个改动。

fix: @modern-js/plugin-ssr exported issue

---

.github/workflows/reset-prepare.yml

增加定义任务，同步最新依赖，执行 prepare 和集成测试，保证三方依赖更新响应及时
添加定时任务，每天一次
- rm -rf node_modules && rm -rf pnpm-lock.yaml
- pnpm install --ignore-scripts
- pnpm run prepare --filter ./packages
- cd ./tests && pnpm run test

[skip ci] feat: add schedule task

---

.github/workflows/integration-test-Windows.yml
.github/workflows/integration-test-macOS.yml
.github/workflows/lint-Linux.yml
.github/workflows/test-Windows.yml
.github/workflows/test-macOS.yml

修改 ci 的触发时机：
1. 提 pr： 触发单侧和 lint
2. 合并 pr 到 main 分支：触发集成测试
3. 定时任务：触发

[skip ci]feat: adjust workflow trigger

---

packages/toolkit/node-bundle-require/package.json
packages/toolkit/node-bundle-require/src/index.ts
pnpm-lock.yaml

fix: not use fs promise, as far as possibile support node 12

---

.changeset/angry-trains-rest.md
packages/toolkit/utils/package.json
pnpm-lock.yaml

fix @modern-js/utils deps config.
add  "typescript" to the dependency list and remove it from devDependencies and peerDependencies.
fix peerDeps missing question.

Fix utils deps config

---

.changeset/famous-ways-matter.md
packages/runtime/src/compatible.tsx
packages/runtime/src/loader/loaderManager.ts
packages/runtime/tests/loaderManager.test.ts

This PR fix the issue: useLoader doesn't work as expected when loader function fails.

fix: useLoader fallback

---

.changeset/odd-birds-scream.md
.changeset/tricky-ties-work.md
packages/cli/babel-preset-app/package.json
packages/cli/babel-preset-lib/package.json
packages/cli/babel-preset-module/package.json
packages/cli/plugin-bff/package.json
packages/cli/plugin-unbundle/package.json
packages/generator/new-action/package.json
packages/server/server/package.json
packages/server/utils/package.json
packages/toolkit/compiler/babel/package.json
packages/toolkit/esmpack/package.json
pnpm-lock.yaml

修复 repo-generator 编译之后没有生成打包后文件
原因： repo-generator 依赖 generator-plugin, generator-plugin 依赖 new-action，new-action 创建子项目又 dev 依赖 repo-generator，这里的 dev 依赖是方便本地调试生成器使用的，造成了循环依赖
解决方案：暂时移除 new-action 的 dev 依赖

fix: repo generator build error

---

.changeset/blue-brooms-tickle.md
packages/generator/generators/module-generator/templates/ts-template/tsconfig.json.handlebars
packages/generator/generators/monorepo-generator/CHANGELOG.md
packages/generator/generators/monorepo-generator/package.json
packages/generator/generators/monorepo-generator/src/index.ts
packages/generator/generators/monorepo-generator/templates/base-template/package.json.handlebars
packages/generator/generators/monorepo-generator/tests/index.test.ts
packages/generator/generators/mwa-generator/templates/ts-template/tsconfig.json
packages/server/server/tests/dev.test.ts

Fix monorepo template

---

.changeset/proud-cobras-cover.md
packages/solutions/module-tools/lib/types.d.ts
packages/solutions/module-tools/package.json

modify type file pointer and content

fix(module-tools): modify type file

---

.changeset/silent-rivers-peel.md
packages/cli/plugin-cdn-cos/src/modern-app-env.d.ts
packages/cli/plugin-cdn-oss/src/modern-app-env.d.ts
packages/cli/plugin-lambda-fc/src/modern-app-env.d.ts
packages/cli/plugin-lambda-scf/src/modern-app-env.d.ts
packages/cli/plugin-multiprocess/src/modern-app-env.d.ts
packages/cli/static-hosting/src/modern-app-env.d.ts
packages/generator/generators/cloud-deploy-generator/src/modern-app-env.d.ts
packages/generator/generators/module-generator/templates/ts-template/src/modern-app-env.d.ts.handlebars
packages/server/plugin-server/src/modern-app-env.d.ts
packages/toolkit/node-bundle-require/src/modern-app-env.d.ts

change modern-app-env.d.ts tempalte content

fix(module-generator): change template

---

packages/cli/plugin-multiprocess/src/index.ts
packages/cli/plugin-multiprocess/tests/fixtures/ssr-bff/route.json
packages/cli/plugin-multiprocess/tests/index.test.ts
packages/toolkit/plugin/src/waterfall/async.ts

fix: load bff/server plugin before multi-process

---

.changeset/breezy-yaks-fold.md
.changeset/violet-jobs-care.md
packages/cli/plugin-bff/src/cli.ts
packages/cli/plugin-proxy/src/index.ts
packages/cli/plugin-unbundle/package.json
packages/cli/plugin-unbundle/src/server.ts
packages/cli/plugin-unbundle/src/typings/index.d.ts
packages/cli/plugin-unbundle/tests/server.test.ts
packages/cli/plugin-unbundle/tests/tsconfig.json
packages/server/server/src/type.ts
pnpm-lock.yaml

fix: extend core module config interfaces

---

.changeset/empty-wasps-cross.md
packages/cli/babel-preset-module/package.json
packages/cli/babel-preset-module/src/built-in/import-path.ts
packages/cli/babel-preset-module/tests/check-static-file.test.ts
packages/solutions/module-tools/.eslintrc.js
packages/solutions/module-tools/package.json
packages/solutions/module-tools/src/cli/dev.ts
packages/solutions/module-tools/src/commands/dev.ts
packages/solutions/module-tools/src/features/dev/index.ts
packages/solutions/module-tools/tests/dev-cli.test.ts
packages/solutions/module-tools/tests/dev-command.test.ts
packages/solutions/module-tools/tests/dev-feature.test.ts
packages/solutions/module-tools/tests/tsconfig.json
pnpm-lock.yaml

support dev subCommand
Subcommands under the dev command are supported：
- storybook
- docsite
- nocode
when not match any command, it will be queit.

feat(module-tools): add subCmd

---

packages/solutions/module-tools/CHANGELOG.md
packages/solutions/module-tools/package.json

chore(module-tools): publish 1.3.0

---

.changeset/dry-papayas-whisper.md
packages/cli/core/src/context.ts
packages/cli/core/tests/context.test.ts

fix: internalDirectory path

---

scripts/build/bin/modern.js

…an indicator
Whether to rebuild based on modification time

build: Whether to rebuild based on modification time

---

packages/solutions/app-tools/src/commands/build.ts

fix: exit 1 if build error

---

.changeset/dull-ravens-fetch.md
packages/cli/webpack/src/config/base.ts
packages/cli/webpack/tests/base.test.ts

`source.include` supports RegExp.

fix: source.include supports regexp

---

.changeset/calm-ears-float.md
packages/cli/plugin-testing/src/cli/resolver.ts
packages/cli/plugin-testing/tests/.eslintrc.js
packages/cli/plugin-testing/tests/resolver.test.ts

fix: test resolver

---

.changeset/poor-olives-hang.md
packages/review/eslint-config-app/eslintrc.js
packages/review/eslint-config-app/package.json

Upgrade prettier version and rename the `jsxBracketSameLine` option to `bracketSameLine`.  [Prettier 2.4 Release Note](https://prettier.io/blog/2021/09/09/2.4.0.html)

feat: upgrade prettier

---

.changeset/calm-ears-float.md
.changeset/dull-ravens-fetch.md
.changeset/poor-olives-hang.md
.changeset/shiny-otters-shop.md
.changeset/sixty-boxes-explain.md
.changeset/tall-fireants-attack.md
packages/cli/plugin-i18n/CHANGELOG.md
packages/cli/plugin-i18n/package.json
packages/cli/plugin-testing/CHANGELOG.md
packages/cli/plugin-testing/package.json
packages/cli/plugin-unbundle/CHANGELOG.md
packages/cli/plugin-unbundle/package.json
packages/cli/webpack/CHANGELOG.md
packages/cli/webpack/package.json
packages/review/eslint-config-app/CHANGELOG.md
packages/review/eslint-config-app/package.json
pnpm-lock.yaml

feat: publish

---

.changeset/nice-feet-jog.md
packages/generator/generators/bff-generator/src/index.ts
packages/generator/generators/bff-generator/templates/function/app/ts/nest.ts.handlebars
packages/generator/generators/bff-generator/tests/index.test.ts

Fix bff template

---

.changeset/real-cheetahs-eat.md
.changeset/silly-eagles-tease.md
packages/generator/generators/bff-generator/templates/function/app/ts/nest.ts.handlebars
packages/generator/generators/dependence-generator/src/index.ts
packages/generator/generators/dependence-generator/tests/index.test.ts
packages/generator/generators/dependence-generator/tests/tsconfig.json
packages/generator/generators/module-generator/src/index.ts
packages/generator/generators/module-generator/tests/index.test.ts
packages/generator/generators/mwa-generator/src/index.ts
packages/generator/generators/mwa-generator/tests/index.test.ts

修复创建 MWA 和 模块子项目 less 和 sass 安装依赖位置问题

Fix monorepo sub project generator

---

.github/workflows/integration-test-Windows.yml

fix: filename too long when ci runs in windows

fix: filename too long in windows

---

.changeset/green-olives-jog.md
packages/cli/plugin-router/package.json
packages/cli/plugin-router/src/cli/index.ts
packages/cli/plugin-router/src/runtime/plugin.tsx
packages/cli/plugin-router/src/runtime/utils.tsx
packages/cli/plugin-router/tests/utils.test.ts
packages/runtime/package.json
packages/runtime/src/runtime-context.ts
packages/server/server/src/libs/context/context.ts
packages/server/server/src/libs/hook-api/route.ts
packages/server/server/src/libs/render/index.ts
packages/server/server/src/libs/render/ssr.ts
packages/server/server/src/libs/route/index.ts
packages/server/server/src/libs/route/matcher.ts
packages/server/server/src/libs/route/route.ts
packages/server/server/src/server/modern-server-split.ts
packages/server/server/src/server/modern-server.ts
packages/server/server/src/utils.ts
packages/server/server/tests/context.test.ts
packages/server/server/tests/dev.test.ts
packages/server/server/tests/fixtures/route-spec/dynamic.json
packages/server/server/tests/hook.test.ts
packages/server/server/tests/route.test.ts
packages/server/server/tests/utils.test.ts
packages/toolkit/types/server/context.d.ts
pnpm-lock.yaml

feat: support multi baseurl

---

.changeset/slow-houses-dress.md
packages/cli/babel-preset-app/src/index.ts
packages/cli/babel-preset-app/tests/index.test.ts

fix: babel preset default options

fix: babel preset default options

---

.changeset/wet-camels-fold.md
packages/server/core/src/plugin.ts
packages/server/core/tests/server-plugin.test.ts

fix: remove unused changeset

---

.changeset/proud-adults-call.md
packages/cli/plugin-ssg/src/libs/make.ts
packages/generator/generator-common/src/locale/zh.ts

fix: ssg generate correctly route

---

.changeset/lazy-buses-try.md
.changeset/soft-tables-retire.md
packages/cli/core/src/index.ts
packages/cli/core/src/initWatcher.ts
packages/cli/core/tests/initWatcher.test.ts
packages/cli/plugin-analyze/package.json
packages/cli/plugin-analyze/src/index.ts
packages/cli/plugin-analyze/src/utils.ts
packages/solutions/app-tools/src/index.ts
packages/toolkit/utils/src/index.ts
packages/toolkit/utils/src/wait.ts
packages/toolkit/utils/tests/wait.ts
pnpm-lock.yaml

fix: file route changed not trigger hot reload

---

packages/cli/plugin-ssr/src/index.node.tsx

remove @modern-js/server from plugin-ssr

fix: remove @modern-js/server from plugin-ssr

---

.changeset/dirty-moles-agree.md
packages/cli/plugin-analyze/src/getHtmlTemplate.ts
packages/cli/plugin-analyze/src/templates.ts
packages/cli/webpack/jest.config.js
packages/cli/webpack/package.json
packages/cli/webpack/src/config/client.ts
packages/cli/webpack/src/plugins/bottom-template-plugin.ts
packages/cli/webpack/tests/bottom-template-plugin.test.ts
packages/cli/webpack/tests/client.test.ts
packages/cli/webpack/tests/fixtures/index.js
packages/cli/webpack/tests/fixtures/templateParam.html
pnpm-lock.yaml

feat: support bottom template

---

.changeset/cold-cups-compete.md
packages/generator/generator-common/src/common/solution.ts

fix: generator scenes order

---

.changeset/cold-cups-compete.md
.changeset/wild-horses-join.md
packages/cli/plugin-router/CHANGELOG.md
packages/cli/plugin-router/package.json
packages/generator/generator-common/CHANGELOG.md
packages/generator/generator-common/package.json

chore: publish local [skip ci]

---

packages/solutions/app-tools/src/commands/dev.ts

fix: support dev compile by entry

---

.changeset/real-pants-pretend.md
packages/server/server/src/server/modern-server.ts
pnpm-lock.yaml

fix: catch api error

---

packages/cli/plugin-analyze/src/getBundleEntry.ts
packages/solutions/app-tools/src/commands/dev.ts
packages/toolkit/utils/src/prettyInstructions.ts

fix: fix two bugs

---

.changeset/silver-bananas-glow.md
packages/toolkit/utils/src/prettyInstructions.ts

chore: add changeset [skip ci]

---

.github/workflows/integration-test-Windows.yml
.github/workflows/integration-test-macOS.yml
.github/workflows/lint-Linux.yml
.github/workflows/reset-prepare.yml
.github/workflows/test-Windows.yml
.github/workflows/test-macOS.yml

调整 github action workflow：
- job 命名使用具体名称
- mac 单侧只更改文档不跳过，保证 codecov 验证通过

feat: rename workflow && fix doc only ci error

---

.changeset/cool-elephants-melt.md
packages/cli/plugin-ssg/src/index.ts
packages/cli/plugin-ssg/src/libs/util.ts
packages/cli/plugin-ssg/src/server/index.ts
packages/cli/plugin-ssg/src/server/process.ts
packages/cli/plugin-ssg/tests/util.test.ts

plugin-route update cause ssg bug exposed

fix: fix ssg with new plugin route logic

---

.changeset/proud-suits-drive.md
packages/cli/plugin-testing/src/cli/plugins/modern.test.ts
packages/cli/plugin-testing/src/cli/plugins/modern.ts
packages/cli/plugin-testing/src/cli/test.ts
packages/cli/plugin-testing/type.d.ts
packages/review/testing-plugin-bff/package.json
packages/review/testing-plugin-bff/src/env.ts
packages/review/testing-plugin-bff/src/index.ts
packages/review/testing-plugin-bff/src/utils/bff.ts
packages/review/testing-plugin-bff/tests/__snapshots__/index.test.ts.snap
packages/review/testing-plugin-bff/tests/index.test.ts
packages/review/testing-plugin-bff/tests/utils.test.ts
packages/review/testing/package.json
packages/review/testing/src/index.ts
packages/review/testing/src/plugin.ts
packages/review/testing/src/utils.ts
packages/review/testing/tests/__snapshots__/utils.test.ts.snap
packages/review/testing/tests/tsconfig.json
packages/review/testing/tests/utils.test.ts
pnpm-lock.yaml
tests/integration/api-service-koa/api/index.test.ts
tests/integration/api-service-koa/api/modern-app-env.d.ts
tests/integration/api-service-koa/package.json
tests/jest.config.js
tests/package.json

feat: support bff test for api service

---

.changeset/purple-days-end.md
packages/generator/generator-cases/tests/index.test.ts
packages/generator/generator-common/src/locale/en.ts
packages/generator/generator-common/src/locale/zh.ts
packages/generator/generator-common/src/newAction/common/index.ts
packages/generator/generator-common/src/newAction/mwa/index.ts
packages/generator/generator-common/tests/.eslintrc.js
packages/generator/generator-common/tests/new-action.test.ts
packages/generator/generator-common/tests/tsconfig.json

Feat support enable proxy

---

.changeset/spicy-snails-call.md
packages/cli/plugin-unbundle/src/constants.ts
packages/cli/plugin-unbundle/src/install/scan-imports.ts
packages/cli/plugin-unbundle/src/plugins/css.ts
packages/solutions/app-tools/lib/types.d.ts
packages/solutions/module-tools/lib/types.d.ts

Remove stylus support at modern.js

fix: remove stylus support

---

.changeset/early-ways-explain.md
.changeset/two-poems-search.md
packages/cli/plugin-ssr/src/cli/index.ts
packages/server/server/src/dev-tools/socket-server.ts
packages/server/server/src/server/dev-server/dev-server.ts
packages/server/server/tests/dev.test.ts

getEntryOptions will priority use ssrByEntries, when use ssg and ssrByEntries, ssg is ignored. fix it in plugin-ssr

fix: ssr by entries cause ssg not work

---

.changeset/wet-jobs-shake.md
packages/cli/core/src/config/index.ts
packages/cli/core/src/index.ts

if some framework build on modern.js, may need remind schema error by itself

feat: support add schem error hook to core.init

---

.changeset/gold-chairs-doubt.md
packages/cli/babel-preset-app/src/common.ts
packages/cli/babel-preset-app/src/index.ts
packages/cli/babel-preset-app/src/type.ts
packages/cli/babel-preset-app/tests/common.test.ts
packages/cli/babel-preset-base/src/index.ts
packages/cli/babel-preset-base/src/plugins.ts
packages/cli/core/src/config/schema/tools.ts
packages/cli/webpack/src/config/modern.ts
packages/cli/webpack/src/config/node.ts
packages/cli/webpack/src/utils/getBabelOptions.ts

fix: fix the wrong field

---

.changeset/violet-grapes-relax.md
packages/cli/plugin-runtime/package.json
pnpm-lock.yaml

修复 runtime 插件使用 head 和 loadable 类型找不到问题

fix: runtime head and loadable type not found

---

.changeset/selfish-mails-film.md
packages/runtime/src/compatible.tsx
packages/runtime/tests/bootstrap.test.tsx

ensure `bootstrap` work with normal Component

feat: ensure `bootstrap` work with normal Component

---

.changeset/nervous-pets-sell.md
packages/cli/plugin-storybook/modern.config.js
packages/solutions/module-tools/src/tasks/generator-dts/index.ts
packages/solutions/module-tools/src/tasks/generator-dts/utils.ts
packages/solutions/module-tools/tests/generator-dts.test.ts
packages/toolkit/compiler/babel/modern.config.js

fix: modify the type of error text

---

packages/solutions/module-tools/jest.config.js
packages/solutions/module-tools/src/tasks/generator-dts/index.ts
packages/solutions/module-tools/src/tasks/generator-dts/utils.ts
packages/solutions/module-tools/tests/generator-dts-utils.test.ts

fix ts error in @modern-js/module-tools

fix(module-tools): ts error

---

.github/ISSUE_TEMPLATE/bug-report.zh-Hans.yml
.github/ISSUE_TEMPLATE/feature-request.zh-Hans.yml

Improve issue templates, add more guides.
Test link: https://github.com/chenjiahan/chenjiahan/issues/new?assignees=&labels=bug&template=bug-report.zh-Hans.yml&title=%5BBug%5D%3A+

chore: improve issue template

---

.changeset/silver-months-listen.md
packages/cli/core/src/config/index.ts
packages/cli/core/src/config/schema/output.ts
packages/cli/plugin-storybook/src/features/dev.ts
packages/cli/plugin-storybook/src/features/utils/webpackConfig.ts
packages/cli/webpack/package.json
packages/cli/webpack/src/config/base.ts
packages/solutions/module-tools/src/schema/output.ts
pnpm-lock.yaml

add typescript check
1. Unified output.disableTsChecker configuration
2. Add fork-ts-checker-webpack-plugin 
3. Adjusting the webpack configuration in storybook

feat: add ts check

---

packages/generator/generators/module-generator/templates/ts-template/modern.config.js.handlebars
packages/generator/generators/module-generator/templates/ts-template/modern.config.ts.handlebars
packages/generator/generators/module-generator/templates/ts-template/tsconfig.json.handlebars
tests/integration/api-service-koa/api/tests/index.test.ts

1. 修复集成测试 api-service-koa 报错
2. 修复模块工程方案模板 module.config.ts 引用问题

fix: test error && module config template

---

.changeset/dry-readers-tickle.md
.changeset/lucky-parrots-poke.md
.changeset/neat-kiwis-agree.md
packages/generator/generator-common/src/common/package-manager.ts
packages/generator/generator-common/src/monorepo/project.ts
packages/generator/generators/dependence-generator/src/index.ts

修复开启功能时自动补充类型定义问题
修复 packageManager schema，items 字段不能为函数，生成器插件中 options 转换逻辑会有问题

Fix plugin type append

---

.github/ISSUE_TEMPLATE/1-bug-report.en-US.yml
.github/ISSUE_TEMPLATE/2-feature-request.en-US.yml
.github/ISSUE_TEMPLATE/3-bug-report.zh-Hans.yml
.github/ISSUE_TEMPLATE/4-feature-request.zh-Hans.yml

Add english issue templates.
Tested in https://github.com/chenjiahan/chenjiahan/issues/new/choose.

chore: add english issue templates

---

.changeset/popular-kids-call.md
.changeset/short-pumas-visit.md
.changeset/silly-gifts-applaud.md
packages/cli/plugin-bff/.eslintrc.js
packages/cli/plugin-bff/src/cli.ts
packages/cli/plugin-bff/types.d.ts
packages/generator/generator-common/src/mwa/common.ts
packages/solutions/app-tools/src/commands/build.ts
packages/solutions/app-tools/tests/commands/build.test.ts
packages/toolkit/utils/src/emptyDir.ts
packages/toolkit/utils/src/index.ts

给 plugin-bff 增加一个 types 文件，在生成器生成代码的时候，将此类型文件注入到 modern-app.env.ts 文件中。解决如 modern.config.ts 中使用 defineConfig api，会有类型错误的问题。
```
/// <reference types='@modern-js/plugin-express/types' />
/// <reference types='@modern-js/plugin-bff/types' />
```

fix: add types.d.ts for plugin bff

---

.changeset/eighty-horses-give.md
.changeset/metal-flowers-ring.md
.changeset/yellow-buses-trade.md
packages/cli/plugin-tailwind/package.json
packages/cli/plugin-tailwind/src/types.ts
packages/generator/generator-common/src/newAction/module/index.ts
packages/generator/generator-common/src/newAction/mwa/index.ts
packages/generator/generators/tailwindcss-generator/package.json
packages/generator/generators/tailwindcss-generator/src/index.ts
packages/generator/generators/tailwindcss-generator/tests/index.test.ts
packages/generator/new-action/src/module.ts
pnpm-lock.yaml

修复使用 new 命令开启 tailwindcss 时，tailwindcss 的版本号

fix module solution tainwindcss version

---

packages/cli/plugin-tailwind/package.json

修复 plugin-tailwindcss 导出 types 路径

fix: plugin tailwindcss exports type

---

website/docs/apis/config/usage.md
website/docs/guides/features/custom/framework-plugin/config.md

Improve config usage, make it easier to read.

docs: improve config usage [skip ci]

---

.changeset/tough-bulldogs-run.md
packages/solutions/monorepo-tools/package.json
packages/solutions/monorepo-tools/src/cli/deploy.ts
packages/solutions/monorepo-tools/src/commands/deploy.ts
packages/solutions/monorepo-tools/src/features/deploy/index.ts
packages/solutions/monorepo-tools/src/hooks/index.ts
packages/solutions/monorepo-tools/src/index.ts
packages/toolkit/types/cli/index.d.ts
pnpm-lock.yaml

给 monorepo-tools 增加部署完成的 hook。

feat: add afterMonorepoDeploy hook for monorepo-tools

---

.changeset/shaggy-owls-fold.md
packages/generator/generators/module-generator/templates/base-template/package.json.handlebars
packages/generator/generators/monorepo-generator/templates/base-template/package.json.handlebars
packages/generator/generators/mwa-generator/templates/base-template/package.json.handlebars
packages/solutions/app-tools/package.json
packages/solutions/module-tools/package.json
packages/solutions/monorepo-tools/package.json
packages/toolkit/utils/jest.config.js
pnpm-lock.yaml

fix: core package not found

---

.changeset/curly-singers-explain.md
.changeset/purple-ghosts-smoke.md
packages/cli/babel-preset-app/src/type.ts
packages/cli/babel-preset-base/src/index.ts
packages/cli/babel-preset-base/src/type.ts
packages/cli/babel-preset-lib/src/index.ts
packages/cli/babel-preset-lib/src/types.ts
packages/cli/core/src/config/index.ts
packages/cli/core/src/config/mergeConfig.ts
packages/cli/plugin-docsite/src/index.ts
packages/solutions/module-tools/src/commands/build.ts
packages/solutions/module-tools/src/tasks/build-source-code.ts
packages/solutions/module-tools/src/tasks/build-watch-source-code.ts
packages/solutions/module-tools/src/utils/babel.ts

1. support tools.styledComponents for module-tools
2. support close generator d.ts process with output.disableTsChecker
3. fix port problem for plugin-docsite
- [] New feature (non-breaking change which adds functionality)

Feat compat config file

---

packages/generator/generators/repo-generator/package.json

由于生成器是通过打包优化的，修复了 generator-common 的 bug，需要发布 repo-generator

feat: publish repo generator

---

packages/cli/babel-preset-app/package.json
packages/cli/plugin-analyze/package.json
packages/cli/plugin-analyze/src/isDefaultExportFunction.ts
packages/cli/plugin-unbundle/package.json
packages/cli/plugin-unbundle/src/typings/index.d.ts
packages/solutions/module-tools/package.json
packages/solutions/module-tools/src/utils/tspaths-transform/index.ts
packages/toolkit/esmpack/package.json
packages/toolkit/esmpack/src/utils/parseExports.ts
pnpm-lock.yaml

- fix @babel/traverse type declaration (which breaks the Integration Test)
- upgrate @babel/types to 7.17.0 and remove some any types.

types: fix @babel/traverse type declaration

---

.github/workflows/build-website.yml
.gitignore
.vscode/settings.json
monorepo.code-workspace
website/package.json

The `build` folder is excluded in vscode settings, so some source code cannot be searched:
- /packages/solutions/module-tools/src/features/build
- /scripts/build/src
- /packages/toolkit/compiler/babel/tests/fixtures/build/src

chore: failed to search content in build folder

---

.changeset/tough-bulldogs-run.md
packages/server/server/package.json
pnpm-lock.yaml

fix: restore bff-utils in server dependencies

---

.changeset/tall-wasps-beam.md
packages/cli/plugin-ssg/package.json
packages/cli/plugin-ssg/src/types.ts
packages/generator/generator-common/src/newAction/mwa/index.ts

修复在 defineConfig 中使用 output.ssg 类型报错问题

Fix output ssg type

---

.changeset/early-melons-repeat.md
packages/cli/core/src/config/schema/deploy.ts
packages/cli/core/tests/schema.test.ts
packages/cli/plugin-garfish/src/cli/index.ts

fix: garfish schema

---

website/docs/apis/runtime/app/define-config.md

fix link URL in define-config.md

docs: fix link URL in define-config.md

---

.changeset/thirty-starfishes-grin.md
packages/cli/core/src/config/mergeConfig.ts
packages/cli/core/tests/mergeConfig.test.ts

Fix `mergeConfig` util function

fix: `mergeConfig` util function

---

.changeset/great-teachers-burn.md
packages/cli/plugin-ssg/src/types.ts

ssg 配置约定是路由支持 preventDefault 配置，routes 不是必填项，修复其类型

Fix ssg type

---

packages/cli/core/package.json
packages/cli/plugin-garfish/package.json
packages/cli/plugin-ssg/src/index.ts

发布 @modern-js/core 和  @modern-js/plugin-grafish 包
修复 plugin-ssg 包 build 报错

Feat publish package

---

.changeset/giant-flies-push.md
packages/server/prod-server/src/server/index.ts

[skip ci] fix(prod-server): runner instance chaos in dev

---

.changeset/ninety-balloons-report.md
packages/server/prod-server/tests/spr.test.ts

chore(server): add unit test for spr

---

packages/solutions/app-tools/src/locale/zh.ts
website/docs/apis/commands/mwa/build.md

add description of build --analyze command

docs: add description of build --analyze command

---

.changeset/fresh-peaches-turn.md
packages/server/prod-server/src/server/modern-server-split.ts
packages/server/prod-server/tests/fixtures/pure/test-dist/bundles/main.js
packages/server/prod-server/tests/fixtures/pure/test-dist/html/main/index.html
packages/server/prod-server/tests/fixtures/pure/test-dist/route.json
packages/server/prod-server/tests/server.test.ts
packages/server/server/src/server/dev-server-split.ts

fix(server): do not run server hook if api server

---

.changeset/five-eagles-rest.md
packages/cli/core/src/config/index.ts

修复 server.logger 类型，支持 boolean

Fix server logger type

---

.changeset/curvy-keys-stare.md
packages/cli/core/src/config/index.ts

修复 server.metrics 类型，支持 boolean

Fix server metrics type

---

.changeset/flat-hornets-destroy.md
.changeset/fresh-peaches-turn.md
packages/server/core/src/plugin.ts
packages/server/prod-server/package.json
packages/server/prod-server/src/server/index.ts
packages/server/prod-server/src/server/modern-server.ts
packages/server/prod-server/tests/fixtures/pure/test-dist/route.json
packages/server/prod-server/tests/server.test.ts
packages/toolkit/types/server/context.d.ts
pnpm-lock.yaml

fix(server): babel register should before plugin require

---

.changeset/weak-buses-swim.md
packages/server/prod-server/package.json

fix(server): publish prod-server

---

.changeset/khaki-rings-design.md
packages/cli/core/src/config/index.ts

修复 server.routes 类型，支持 string 数组

Fix server routes type

---

packages/cli/core/src/manager.ts
packages/cli/plugin-garfish/src/cli/index.ts

add CliHookCallbacks type for garfish plugin.
Fix the Integration Test in main branch.

fix: add CliHookCallbacks type for garfish plugin

---

.changeset/nine-gifts-change.md
packages/server/prod-server/src/utils.ts
packages/server/prod-server/tests/utils.test.ts

fix: fix static handler regexp when static file not exist

---

.changeset/young-jars-allow.md
packages/cli/plugin-proxy/package.json
packages/cli/plugin-proxy/src/index.ts
packages/cli/plugin-proxy/src/types.ts
packages/cli/plugin-proxy/src/utils/createProxyRule.ts
packages/generator/generator-common/src/newAction/mwa/index.ts

修复 dev.proxy 类型定义未生效，启用代理功能时添加类型定义

fix: dev.proxy type not work

---

packages/cli/plugin-esbuild/modern.config.js
packages/cli/plugin-esbuild/package.json
packages/cli/plugin-esbuild/src/index.ts

- convert plugin-esbuild to new plugin.
- move modernConfig to modern.config.js

feat(plugin-esbuild): convert to new plugin

---

packages/cli/plugin-analyze/tests/fixtures/entries/file-system-routes/_node_modules/.modern-js/main/internal_components/internal_pages_about.jsx
packages/cli/plugin-analyze/tests/fixtures/entries/file-system-routes/_node_modules/.modern-js/main/internal_components/internal_pages_index.jsx
packages/cli/plugin-analyze/tests/fixtures/entries/file-system-routes/_node_modules/.modern-js/main/internal_components/internal_pages_info.jsx
packages/cli/plugin-analyze/tests/fixtures/entries/file-system-routes/_node_modules/.modern-js/main/routes.js

Rename some files to fix git clone failed on win10.
> error: unable to create file packages/cli/plugin-analyze/tests/fixtures/entries/file-system-routes/_node_modules/.modern-js/main/internal_components/Comp___modern_js_internal_pages_a_b_about_ts___modern_js_internal_pages_a_b__layout_ts___modern_js_internal_pages_a__layout_ts.jsx: Filename too long
see https://github.com/modern-js-dev/modern.js/issues/754.

fix: git clone failed on win10

---

packages/server/server/tests/watcher.test.ts
packages/toolkit/utils/src/format.ts

fix: use import type instead of import

---

website/docusaurus.config.js
website/src/css/custom.css

- remove hideOnScroll behavior of navbar, close https://github.com/modern-js-dev/modern.js/issues/231

docs(website): remove hideOnScroll behavior of navbar

---

.changeset/wild-walls-explain.md
packages/server/server/src/dev-tools/dev-server-plugin.ts
packages/server/server/src/server/dev-server.ts

hrm options set error when only set client.host or client.path...
support tools.devServer.headers

fix: support custom headers, fix hmr url concat

---

packages/cli/plugin-server-build/jest.config.js
packages/cli/plugin-server-build/modern.config.js
packages/cli/plugin-server-build/package.json
packages/cli/plugin-server-build/src/index.ts
packages/cli/plugin-server-build/tsconfig.json

- convert plugin-server-build to new plugin
- move modernConfig to modern.config.js

feat(plugin-server-build): convert to new plugin

---

.changeset/shy-buckets-breathe.md
.changeset/young-jars-allow.md
packages/cli/core/src/initWatcher.ts
packages/cli/plugin-less/package.json
packages/generator/generator-common/src/newAction/module/index.ts
packages/generator/generator-common/src/newAction/mwa/index.ts

Fix tools less type

---

packages/cli/core/src/context.ts
packages/cli/core/src/initWatcher.ts
packages/cli/core/src/manager.ts
packages/server/core/src/plugin.ts
packages/toolkit/plugin/src/manager/async.ts
packages/toolkit/plugin/src/manager/sync.ts
packages/toolkit/plugin/src/manager/types.ts

- add more comments for plugin system

chore: add more comments for plugin system

---

packages/server/server/tests/watcher.test.ts

Remove timeout test case. 
https://github.com/modern-js-dev/modern.js/runs/5671889349?check_suite_focus=true

test: remote timeout test case

---

.changeset/dry-queens-tell.md
packages/cli/plugin-bff/modern.config.js
packages/cli/plugin-bff/package.json
packages/cli/plugin-bff/src/cli.ts
packages/server/plugin-egg/package.json
packages/server/plugin-egg/src/cli/index.ts
packages/server/plugin-express/package.json
packages/server/plugin-express/src/cli/index.ts
packages/server/plugin-koa/package.json
packages/server/plugin-koa/src/cli/index.ts
packages/server/plugin-nest/package.json
packages/server/plugin-nest/src/cli/index.ts
packages/solutions/app-tools/src/commands/dev.ts
pnpm-lock.yaml

迁移至新的插件写法（plugin-bff, plugin-express, plugin-koa, plugin-egg, plugin-nest）

feat: convert to new plugin

---

packages/cli/plugin-analyze/modern.config.js
packages/cli/plugin-analyze/package.json
packages/cli/plugin-analyze/src/generateCode.ts
packages/cli/plugin-analyze/src/getBundleEntry.ts
packages/cli/plugin-analyze/src/getFileSystemEntry.ts
packages/cli/plugin-analyze/src/index.ts
packages/cli/plugin-analyze/tests/index.test.ts

- convert plugin-analyze to new plugin
- move modernConfig to modern.config.js

feat(plugin-analyze): convert to new plugin

---

packages/cli/plugin-design-token/.eslintrc.js
packages/cli/plugin-design-token/package.json
packages/cli/plugin-design-token/src/.eslintrc.json
packages/cli/plugin-design-token/src/cli/index.ts

- convert plugin-design-token to new plugin
- update eslint config

feat(plugin-design-token): convert to new plugin

---

packages/cli/plugin-analyze/.eslintrc.js
packages/cli/plugin-analyze/src/getBundleEntry.ts
packages/cli/plugin-analyze/src/getFileSystemEntry.ts

由于缺少 eslint 配置，导致 eslint fix 错误的移除了感叹号

fix(plugin-analyze): fix entriesDir typing

---

.changeset/popular-cups-unite.md
packages/cli/core/.eslintrc.js
packages/solutions/app-tools/.eslintrc.js
packages/solutions/app-tools/modern.config.js
packages/solutions/app-tools/package.json
packages/solutions/app-tools/src/commands/build.ts
packages/solutions/app-tools/src/commands/deploy.ts
packages/solutions/app-tools/src/commands/dev.ts
packages/solutions/app-tools/src/commands/start.ts
packages/solutions/app-tools/src/hooks.ts
packages/solutions/app-tools/src/index.ts
packages/solutions/app-tools/src/utils/createCompiler.ts
packages/solutions/app-tools/src/utils/printInstructions.ts
packages/solutions/app-tools/src/utils/routes.ts
packages/solutions/app-tools/tests/.eslintrc.js
packages/solutions/app-tools/tests/commands/build.test.ts

- convert app-tools to new plugin
- add eslint config
- move modernConfig to modern.config.js

feat(app-tools): convert to new plugin

---

packages/runtime/package.json
packages/solutions/monorepo-tools/src/cli/build-watch.ts
packages/solutions/monorepo-tools/src/cli/build.ts
packages/solutions/monorepo-tools/src/cli/install.ts

1. 修复 monorepo-tools 编译报错
2. 发布 @modern-js/runtime-core

fix: monorepo-tools compile error,  publish runtime-core

---

.changeset/ten-toys-buy.md
packages/cli/plugin-state/src/cli/index.ts
packages/cli/plugin-state/src/runtime/plugin.tsx

feat(plugin-state): convert to new plugin
convert `@modern-js/plugin-state` to new plugin syntax.

feat(plugin-state): convert to new plugin

---

.changeset/late-geckos-think.md
packages/cli/plugin-router/src/runtime/plugin.tsx
packages/cli/plugin-router/tests/router.test.tsx

fix: custom router history

---

.changeset/rich-houses-rule.md
packages/cli/plugin-router/src/cli/index.ts
packages/cli/plugin-router/src/runtime/plugin.tsx
packages/cli/plugin-router/tests/index.test.ts

feat(plugin-router): convert to new plugin
convert `@modern-js/plugin-router` to new plugin syntax.

feat(plugin-router): convert to new plugin

---

.changeset/ninety-peas-prove.md
packages/cli/plugin-ssr/src/cli/index.ts
packages/cli/plugin-ssr/src/index.node.tsx
packages/cli/plugin-ssr/src/index.tsx

feat(plugin-ssr): convert to new plugin
upgrade `@modern-js/plugin-ssr` to new plugin syntax.

feat(plugin-ssr): convert to new plugin

---

.changeset/wet-owls-pump.md
packages/cli/plugin-nocode/src/cli.ts

convert plugin-nocode to new plugin

feat(plugin-nocode): convert to new plugin

---

.changeset/dull-lies-stare.md
packages/cli/plugin-docsite/src/index.ts

feat(plugin-docsite): convert to new plugin

---

.changeset/lazy-pears-rhyme.md
packages/cli/plugin-storybook/src/features/dev.ts
packages/cli/plugin-storybook/src/index.ts

convert plugin-storybook to new plugin

feat: convert plugin-storybook

---

.changeset/rude-bats-visit.md
packages/solutions/module-tools/src/cli/build.ts
packages/solutions/module-tools/src/cli/dev.ts
packages/solutions/module-tools/src/commands/build.ts
packages/solutions/module-tools/src/commands/dev.ts
packages/solutions/module-tools/src/features/build/build-platform.ts
packages/solutions/module-tools/src/features/build/build-watch.ts
packages/solutions/module-tools/src/features/build/build.ts
packages/solutions/module-tools/src/features/build/index.ts
packages/solutions/module-tools/src/features/build/utils.ts
packages/solutions/module-tools/src/features/dev/index.ts
packages/solutions/module-tools/src/index.ts
packages/solutions/module-tools/tests/dev-cli.test.ts
packages/solutions/module-tools/tests/dev-command.test.ts
packages/solutions/module-tools/tests/dev-feature.test.ts
packages/toolkit/module-tools-hooks/src/build.ts
packages/toolkit/module-tools-hooks/src/dev.ts
packages/toolkit/module-tools-hooks/src/index.ts

convert module-tools to new plugin

feat: convert module-tools

---

.changeset/empty-cows-mix.md
packages/server/core/src/loadPlugins.ts
packages/server/plugin-server/package.json

fix: support load plugin instace

---

.changeset/soft-carrots-hammer.md
packages/cli/plugin-runtime/src/cli/index.ts

fix(plugin-runtime): fix usePlugins error
fix usePlugins error.

fix(plugin-runtime): fix usePlugins error

---

packages/toolkit/plugin/package.json

feat: publish @modern-js/plugin

---

.changeset/rare-rockets-jam.md
packages/cli/plugin-design-token/package.json
packages/cli/plugin-design-token/src/runtime/plugin.tsx

convert runtime plugin-desgin-token to new plugin

feat(plugin-desgin-token): convert runtime plugin to new plugin

---

.changeset/fluffy-steaks-eat.md
packages/cli/plugin-fetch/src/plugin.tsx

- convert runtime plugin-fetch to new plugin

feat(plugin-fetch): convert runtime plugin to new plugin

---

website/docs/apis/config/plugins.md

- update plugin config document

docs: update plugin config document

---

.changeset/giant-pumas-dream.md
packages/generator/generators/module-generator/src/index.ts

remove module generator @types/react-dom dependence

fix(module-generator): remove @types/react-dom dependence

---

.changeset/shiny-games-doubt.md
packages/cli/core/src/config/index.ts
packages/server/server/src/server/dev-server.ts
website/docs/apis/config/tools/dev-server.md

fix: change name and add type for devServer config

---

packages/server/plugin-egg/package.json
packages/server/plugin-koa/package.json
pnpm-lock.yaml

Module-tools 构建需要  typescript。

fix: add typescript as devDependency

---

.changeset/unlucky-experts-deliver.md
packages/cli/plugin-nocode/package.json
packages/cli/plugin-nocode/src/cli.ts
packages/cli/plugin-nocode/src/compiler/index.ts
packages/cli/plugin-nocode/src/contants.ts
packages/cli/plugin-nocode/src/register/butter-auth.ts
packages/cli/plugin-nocode/src/register/env.ts
packages/cli/plugin-nocode/tests/handleWebpackConfig.test.ts
pnpm-lock.yaml

nocode plugin 支持style-loader（默认）
nocode plugin 支持通过环境变量注入 butter 注册源（私有化环境专用）

feat: nocode plugin 默认支持 style-loader

---

.changeset/giant-yaks-shop.md
packages/cli/webpack/.eslintrc.js
packages/cli/webpack/src/config/base.ts
packages/cli/webpack/src/config/node.ts
packages/cli/webpack/src/utils/createCSSRule.ts

remove style-loader in ssr bundle build config.

fix: style-loader should never use in ssr bundle

---

.changeset/popular-cherries-pretend.md
packages/cli/plugin-router/package.json
packages/cli/plugin-router/src/runtime/index.ts
packages/cli/plugin-router/src/runtime/plugin.tsx

Feat: export more types from router plugin

feat: export more types from router plugin

---

packages/server/create-request/src/node.ts

fix(create-request): fix configure function typing

---

.changeset/brown-icons-develop.md
packages/server/hmr-client/package.json
packages/server/hmr-client/src/index.ts
pnpm-lock.yaml

Remove react-error-overlay, it is not necessary and has bugs in some scenarios (such as `Module Federation`)

fix(hmr-client): remove react-error-overlay

---

packages/cli/core/src/config/index.ts
packages/cli/core/src/index.ts
packages/cli/core/src/initWatcher.ts
packages/cli/plugin-ssr/src/cli/index.ts
packages/cli/plugin-tailwind/src/tailwind.ts
packages/cli/webpack/src/config/modern.ts
packages/cli/webpack/src/config/node.ts
packages/cli/webpack/src/utils/getBabelOptions.ts
packages/cli/webpack/src/utils/getSourceIncludes.ts
packages/solutions/app-tools/src/commands/dev.ts
packages/solutions/app-tools/src/commands/start.ts
packages/toolkit/utils/src/is/platform.ts

Remove unnecessary any type assertion.

fix: remove unnecessary any type assertion

---

.changeset/giant-shrimps-accept.md
packages/solutions/module-tools/src/tasks/generator-dts/index.ts
packages/solutions/module-tools/src/tasks/generator-dts/utils.ts
packages/solutions/module-tools/tests/generate-dts.test.ts
packages/toolkit/utils/tests/is.test.ts
packages/toolkit/utils/tests/isPlatform.test.ts

- Throw error when `tsc` is not installed.
- Fix the problem that there is no error message in some cases.

fix(module-tools): throw error when tsc is not installed

---

.changeset/wild-apricots-dance.md
packages/cli/babel-preset-app/package.json
packages/cli/babel-preset-app/src/index.ts
packages/cli/babel-preset-app/src/type.ts
packages/cli/babel-preset-app/tests/index.test.ts
packages/cli/core/package.json
packages/cli/core/src/config/types/index.ts
packages/cli/plugin-ssr/src/cli/index.ts
packages/cli/webpack/src/config/base.ts
packages/cli/webpack/src/config/modern.ts
packages/cli/webpack/src/config/node.ts
packages/cli/webpack/src/utils/getBabelOptions.ts
packages/solutions/module-tools/src/utils/babel.ts
pnpm-lock.yaml

1. Fix the issue that `tools.babel`  is not working as expected.
2. Avoid using `BabelChain` in  `tools.babel`  since it should be treated as a inner API.

fix: config babel via tools.babel

---

.changeset/hip-cars-do.md
packages/cli/core/src/config/types/index.ts

Fix the build error shown in the below picture.

fix: module-tools build error

---

packages/generator/new-action/package.json

修复 @modern-js/new-action 包内容和源码不一致问题

fix: new action package content not right

---

tests/integration/css-modules/test/index.test.js

近期升级依赖后，CSS 压缩工具的行为有所变化，因此修正相关的集测用例：
https://github.com/modern-js-dev/modern.js/runs/5983143729?check_suite_focus=true#step:10:46

chore: fix css modules integration

---

packages/cli/core/package.json
packages/cli/core/src/config/types/index.ts
packages/cli/core/src/config/types/less.ts
packages/cli/core/src/config/types/sass.ts
packages/cli/webpack/src/config/base.ts
pnpm-lock.yaml

1. Add types for `tools.webpack`,`tools.autoprefixer`, `tools.terser`.
2. Use `any` type for `utils` parameter in tools config temporarily.

fix: tools config types

---

.changeset/old-feet-juggle.md
packages/solutions/app-tools/src/utils/config.ts

fix: generate config helper file only config file exist

---

packages/server/prod-server/src/server/index.ts

feat: inject context before create hook runner

---

.changeset/neat-moose-listen.md
.changeset/shiny-starfishes-brake.md
packages/server/adapter-helpers/src/index.ts
packages/server/adapter-helpers/src/utils.ts
packages/server/adapter-helpers/tests/utils.test.ts
packages/server/plugin-egg/src/cli/index.ts
packages/server/plugin-express/src/cli/index.ts
packages/server/plugin-koa/src/cli/index.ts
packages/server/plugin-nest/src/cli/index.ts

fix: compatible with babel-plugin-resolver's handling of relative paths on windows

---

.changeset/strong-phones-move.md
packages/generator/generators/base-generator/package.json
packages/generator/generators/bff-generator/package.json
packages/generator/generators/bff-refactor-generator/package.json
packages/generator/generators/changeset-generator/package.json
packages/generator/generators/cloud-deploy-generator/package.json
packages/generator/generators/dependence-generator/package.json
packages/generator/generators/docsite-generator/package.json
packages/generator/generators/electron-generator/package.json
packages/generator/generators/electron-independence-generator/package.json
packages/generator/generators/entry-generator/package.json
packages/generator/generators/eslint-generator/package.json
packages/generator/generators/generator-generator/package.json
packages/generator/generators/module-generator/package.json
packages/generator/generators/monorepo-generator/package.json
packages/generator/generators/mwa-generator/package.json
packages/generator/generators/repo-generator/package.json
packages/generator/generators/server-generator/package.json
packages/generator/generators/ssg-generator/package.json
packages/generator/generators/storybook-generator/package.json
packages/generator/generators/tailwindcss-generator/package.json
packages/generator/generators/test-generator/package.json
packages/generator/generators/unbundle-generator/package.json
packages/generator/plugins/generator-plugin/package.json
packages/toolkit/create/package.json
pnpm-lock.yaml

升级 @modern-js/csmith-tools  ，修复因 @modern-js/plugin-i18n 依赖 @modern-js/utils/lodash 造成打包生成之后，lodash 包为空的问题。

feat: upgrade csmith tools

---

.changeset/new-impalas-joke.md
packages/cli/core/src/manager.ts
packages/cli/core/src/utils/commander.ts
packages/cli/plugin-changeset/src/index.ts
packages/cli/plugin-docsite/src/index.ts
packages/cli/plugin-jarvis/src/index.ts
packages/solutions/app-tools/src/index.ts

fix: export extended Command type

---

.changeset/honest-rats-carry.md
packages/cli/core/src/index.ts
packages/cli/core/src/loadPlugins.ts
packages/cli/core/tests/loadPlugin.test.ts

Add transformPlugin option for legacy plugins.

feat(core): add transformPlugin option for legacy plugins

---

.changeset/rotten-pugs-explode.md
.changeset/thick-trees-exercise.md
packages/cli/core/package.json
packages/cli/plugin-fast-refresh/package.json
packages/cli/plugin-unbundle/package.json
pnpm-lock.yaml
website/docs/start/electron.md

- bump react-refresh@0.12.0
- bump better-ajv-errors 1.2.0 [changelog](https://github.com/atlassian/better-ajv-errors/blob/main/CHANGELOG.md)

chore: fix some unmet peer deps

---

.changeset/happy-bobcats-tickle.md
packages/cli/core/src/config/types/index.ts
packages/cli/core/src/manager.ts
packages/cli/plugin-bff/src/cli.ts
packages/cli/plugin-bff/src/loader.ts
packages/cli/plugin-esbuild/src/index.ts
packages/cli/plugin-fast-refresh/package.json
packages/cli/plugin-fast-refresh/src/cli.ts
packages/cli/plugin-garfish/src/cli/index.ts
packages/cli/plugin-less/package.json
packages/cli/plugin-less/src/cli.ts
packages/cli/plugin-sass/package.json
packages/cli/plugin-sass/src/cli.ts
packages/cli/plugin-ssr/src/cli/index.ts
packages/cli/webpack/src/config/base.ts
pnpm-lock.yaml
website/docs/apis/config/tools/webpack.md

- Fix config hook type.
- Fix missing `env` param in `tools.webpack`.

fix(core): fix config hook type

---

packages/solutions/app-tools/src/index.ts

fix: remove startOptions

---

.changeset/bright-dogs-melt.md
packages/server/prod-server/src/libs/loadConfig.ts

fix: throw server config error

---

scripts/prebundle/README.md
scripts/prebundle/src/types.ts

Add document of prebundle script.

docs: add document of prebundle script

---

jest.config.js
packages/server/create-request/jest.config.js
packages/server/create-request/package.json
packages/server/create-request/src/node.ts
packages/server/create-request/tests/.eslintrc.js
packages/server/create-request/tests/node.test.ts
packages/server/create-request/tests/tsconfig.json
pnpm-lock.yaml

之前因为 esbuild-jest 编译的问题，将 node.test.ts 从测试文件中删掉了，现在将该文件重新加入到测试文件中。

chore: add node.test.ts to test files

---

.changeset/wet-ties-bathe.md
packages/cli/plugin-ssg/src/server/index.ts
pnpm-lock.yaml

fix: ssg run with server plugins

---

.changeset/shaggy-moose-buy.md
packages/cli/plugin-ssr/src/prefetch.tsx
packages/cli/plugin-ssr/src/serverRender/index.ts
packages/server/create-request/tests/node.test.ts
packages/toolkit/utils/package.json
packages/toolkit/utils/src/index.ts
packages/toolkit/utils/src/ssr.ts

fix: export ssrHelpers from subpath

---

.changeset/sour-bears-count.md
packages/server/server/src/constants.ts
packages/server/server/src/server/dev-server.ts
packages/server/server/src/types.ts
packages/server/server/tests/dev.test.ts
packages/solutions/app-tools/src/commands/dev.ts

devMiddleware same as webpack-dev-server

feat: support tools.devServer.devMiddleware

---

.changeset/weak-keys-beg.md
packages/server/create-request/package.json
packages/server/create-request/src/browser.ts
packages/server/create-request/src/node.ts
packages/server/create-request/tests/browser.test.ts
packages/server/create-request/tests/node.test.ts
packages/server/plugin-express/src/plugin.ts
pnpm-lock.yaml

feat: support array-style for bff request query parameters

---

.changeset/cold-boats-retire.md
package.json
packages/cli/plugin-esbuild/package.json
packages/cli/plugin-runtime/package.json
packages/cli/plugin-runtime/types/model.d.ts
packages/cli/plugin-state/package.json
packages/cli/plugin-testing/package.json
packages/cli/plugin-unbundle/package.json
packages/review/testing/package.json
packages/toolkit/compiler/esbuild/package.json
packages/toolkit/node-bundle-require/package.json
pnpm-lock.yaml
scripts/jest-config/package.json

Fix missing peer deps warnings.

fix: missing peer deps warnings

---

.changeset/calm-carpets-attend.md
.changeset/gold-mayflies-invent.md
packages/cli/plugin-runtime/package.json
packages/cli/plugin-ssr/node.ts
packages/cli/plugin-ssr/package.json
packages/cli/webpack/src/config/node.ts
packages/toolkit/utils/package.json

use treeshaking product for ssr bundle

---

.changeset/selfish-ducks-glow.md
packages/cli/plugin-testing/src/cli/index.ts
packages/cli/plugin-testing/tests/merge-config.test.ts
packages/review/testing/src/config/testConfigOperator.ts
packages/review/testing/src/hook.ts
packages/review/testing/src/index.ts
packages/review/testing/src/runJest.ts
packages/review/testing/tests/.eslintrc.js
packages/review/testing/tests/tsconfig.json

Add `afterTest` hook for testing plugin. The hook is not open to the public  temporarily.

feat(testing): add `afterTest` hook 

---

packages/cli/core/package.json
packages/solutions/app-tools/package.json
packages/solutions/module-tools/package.json
packages/solutions/monorepo-tools/package.json
pnpm-lock.yaml

Fix incorrect types path, release hotfix version 1.9.1

fix(core): incorrect types path

---

packages/cli/plugin-testing/package.json
packages/review/testing/package.json

`@modern-js/plugin-testing` 1.5.2 and `@modern-js/testing` 1.4.5  have published to npm.

chore: bump version

---

.changeset/new-pets-warn.md
packages/generator/generator-plugin/src/context/file.ts

修复生成器插件 renderString 方法 this 指向导致的报错问题

fix: generator plugin renderString error

---

.changeset/polite-lions-guess.md
packages/cli/plugin-ssr/package.json

fix: reuse node/index.node.js for plugin-ssr main field

---

.changeset/healthy-walls-dance.md
packages/generator/generators/eslint-generator/templates/ts-template/.eslintrc.js.handlebars

fix: eslint template

---

.changeset/moody-trains-unite.md
packages/cli/plugin-router/src/runtime/plugin.tsx
packages/cli/plugin-ssr/src/prefetch.tsx
packages/cli/plugin-ssr/src/serverRender/entry.ts
packages/server/prod-server/src/libs/render/measure.ts
packages/server/prod-server/tests/render.test.ts
packages/toolkit/types/server/context.d.ts

fix: router build

---

.changeset/nervous-baboons-draw.md
packages/generator/generators/module-generator/templates/ts-template/.eslintrc.js.handlebars
packages/generator/generators/module-generator/templates/ts-template/modern.config.js.handlebars
packages/generator/generators/module-generator/templates/ts-template/modern.config.ts.handlebars
packages/generator/generators/mwa-generator/templates/ts-template/.eslintrc.js.handlebars

fix:eslint template

---

website/docs/apis/config/tools/esbuild.md

Improve esbuild plugin document.

docs: improve esbuild plugin document

---

.changeset/tasty-queens-remember.md
packages/cli/babel-preset-base/package.json
packages/cli/plugin-tailwind/src/tailwind.ts
packages/runtime/package.json
pnpm-lock.yaml

fix: fix react & react-dom types problem

---

.changeset/fifty-mayflies-wonder.md
packages/generator/generators/server-generator/src/index.ts
packages/generator/generators/server-generator/templates/base-template/js/server/.eslintrc.js.handlebars
packages/generator/generators/server-generator/templates/base-template/server/.eslintrc.json
packages/generator/generators/server-generator/templates/base-template/ts/server/.eslintrc.js.handlebars

fix: server generator eslint template

---

packages/cli/plugin-docsite/package.json
packages/cli/plugin-nocode/package.json
packages/cli/plugin-storybook/package.json
packages/cli/plugin-testing/package.json
packages/cli/webpack/package.json
packages/solutions/app-tools/package.json
pnpm-lock.yaml

Release hotfix version for https://github.com/modern-js-dev/modern.js/pull/1000

chore: release @modern-js/webpack 1.6.2

---

.changeset/new-wolves-explode.md
packages/cli/core/src/config/mergeConfig.ts

add filter logic for merge tools.tailwindcss and source.designSystem

feat: add filter logic for merge config

---

packages/cli/plugin-nocode/src/register/butter-cache.ts
packages/cli/plugin-nocode/src/register/butter.ts
packages/cli/plugin-nocode/src/register/constants.ts
packages/cli/plugin-nocode/src/register/index.ts

fix: 移除nocode plugin 的内网域名 & 取消umd上传接口

---

.changeset/quiet-jeans-relax.md
.changeset/six-humans-end.md
.changeset/six-suns-join.md
packages/cli/plugin-ssr/src/index.node.tsx
packages/cli/plugin-ssr/src/index.tsx
packages/cli/plugin-ssr/src/utils.ts
packages/cli/plugin-ssr/tests/index.test.ts
packages/cli/webpack/src/config/node.ts
packages/runtime/src/compatible.tsx

chore: remove unused code

---

packages/toolkit/utils/package.json

@modern-js/utils 包使用缓存会有一些问题，暂时移除。

chore: remove wireit from modern-js/utils

---

.changeset/lucky-comics-listen.md
packages/generator/generators/entry-generator/templates/main.css
packages/generator/generators/entry-generator/templates/main.handlebars
website/docs/guides/features/monorepo/sub-project-interface.md
website/docs/guides/tutorials/c03-ide/3.2-hints-in-ide.md
website/docs/start/component.md
website/docs/start/library.md
website/docs/start/website.md

fix: entry template style conflict with tailwindcss

---

.changeset/friendly-icons-jog.md
README.md
packages/toolkit/plugin/node.d.ts
packages/toolkit/plugin/node.js
packages/toolkit/plugin/package.json
packages/toolkit/plugin/src/farrow-pipeline/asyncHooks.node.ts
packages/toolkit/plugin/src/farrow-pipeline/asyncHooksInterface.ts
packages/toolkit/plugin/src/farrow-pipeline/context.ts
packages/toolkit/plugin/src/farrow-pipeline/counter.ts
packages/toolkit/plugin/src/farrow-pipeline/hook.ts
packages/toolkit/plugin/src/farrow-pipeline/index.ts
packages/toolkit/plugin/src/farrow-pipeline/pipeline.ts
packages/toolkit/plugin/src/index.ts
packages/toolkit/plugin/src/manager/async.ts
packages/toolkit/plugin/src/manager/runner.ts
packages/toolkit/plugin/src/manager/sync.ts
packages/toolkit/plugin/src/manager/types.ts
packages/toolkit/plugin/src/waterfall/async.ts
packages/toolkit/plugin/src/waterfall/sync.ts
packages/toolkit/plugin/src/workflow/async.ts
packages/toolkit/plugin/src/workflow/parallel.ts
packages/toolkit/plugin/src/workflow/sync.ts
packages/toolkit/plugin/tests/async.test.ts
packages/toolkit/plugin/tests/pipeline.test.ts
packages/toolkit/plugin/tests/sync.test.ts
packages/toolkit/plugin/tests/waterfall.test.ts
pnpm-lock.yaml

Fork `farrow-pipeline` to remove tslib and reduce bundle size.
`@modern-js/plugin` is used by runtime, and it depends on `farrow-pipeline`, so `farrow-pipeline` will be bundled to runtime bundle.
`farrow-pipeline` is a great library, but it depends on `tslib`, causing the bundle size to rise.
This Pull Request forked `farrow-pipeline` and removed some unused code:
- dependencies: tslib
- files: compose.ts
- methods: usePipeline, assertContainer, assertContext, isContext, isContainer, pipeline.useLazy, context.assert
MWA bundle size: **reduced 10.5kb**

feat(plugin): fork farrow-pipeline, remove tslib and reduce bundle size

---

packages/generator/generators/base-generator/package.json
packages/generator/generators/bff-generator/package.json
packages/generator/generators/bff-refactor-generator/package.json
packages/generator/generators/changeset-generator/package.json
packages/generator/generators/cloud-deploy-generator/package.json
packages/generator/generators/dependence-generator/package.json
packages/generator/generators/docsite-generator/package.json
packages/generator/generators/electron-generator/package.json
packages/generator/generators/electron-independence-generator/package.json
packages/generator/generators/entry-generator/package.json
packages/generator/generators/eslint-generator/package.json
packages/generator/generators/generator-generator/package.json
packages/generator/generators/module-generator/package.json
packages/generator/generators/monorepo-generator/package.json
packages/generator/generators/mwa-generator/package.json
packages/generator/generators/repo-generator/package.json
packages/generator/generators/server-generator/package.json
packages/generator/generators/ssg-generator/package.json
packages/generator/generators/storybook-generator/package.json
packages/generator/generators/tailwindcss-generator/package.json
packages/generator/generators/test-generator/package.json
packages/generator/generators/unbundle-generator/package.json
packages/generator/plugins/generator-plugin/package.json
packages/toolkit/create/package.json

chore: build command should not cache main.js

---

.changeset/silly-bees-cheer.md
packages/generator/generators/module-generator/templates/base-template/package.json.handlebars
packages/generator/generators/monorepo-generator/templates/base-template/package.json.handlebars
packages/generator/generators/mwa-generator/templates/base-template/package.json.handlebars

feat: generator template add husky package

---

.changeset/loud-balloons-fry.md
packages/server/prod-server/src/server/modern-server.ts

feat: handle server context init error

---

.changeset/unlucky-parents-float.md
packages/toolkit/utils/package.json

fix missing browserslist exports

fix(utils): fix missing browserslist exports

---

.changeset/soft-weeks-smash.md
packages/toolkit/utils/package.json
packages/toolkit/utils/src/readTsConfig.ts
pnpm-lock.yaml

feat: use json5 instead typescript

---

.changeset/moody-coats-lick.md
packages/cli/babel-preset-lib/src/index.ts
packages/server/utils/tests/__snapshots__/babel.test.ts.snap

feat: enable helpers for es5

---

.changeset/ninety-horses-type.md
packages/cli/babel-preset-app/src/common.ts
packages/cli/babel-preset-base/src/plugins.ts

Enable babel runtime helpers for client bundles.
Reduce bundle size.
(The small amount of code in the template project makes the size difference insignificant).

feat(babel-preset-app): enable babel runtime helpers for client bundles

---

packages/cli/plugin-garfish/package.json

Release hotfix version for https://github.com/modern-js-dev/modern.js/pull/1057

chore: release @modern-js/plugin-garfish@1.4.12

---

website/docs/apis/config/tools/postcss.md

Improve tools.postcss document.

docs: improve tools.postcss

---

.changeset/silly-needles-notice.md
packages/cli/plugin-ssr/src/prefetch.tsx

fix: loadable with useloader in ssr faild in first render

---

.husky/commit-msg
.husky/pre-commit
package.json
pnpm-lock.yaml

chore: upgrade husky to 8

---

.changeset/eleven-bikes-work.md
packages/cli/webpack/src/config/node.ts

fix: enable globalVars in ssr bundles

---

.changeset/happy-mayflies-mate.md
packages/toolkit/utils/src/compiled.ts

fix: type export cause tsloader parse error

---

.changeset/rude-jeans-sin.md
packages/cli/core/src/config/types/index.ts
packages/cli/plugin-bff/package.json
packages/cli/plugin-bff/src/cli.ts
packages/cli/plugin-bff/tests/cli.test.ts
packages/cli/plugin-esbuild/src/index.ts
packages/cli/plugin-fast-refresh/src/cli.ts
packages/cli/plugin-garfish/src/cli/index.ts
packages/cli/plugin-less/src/cli.ts
packages/cli/plugin-sass/src/cli.ts
packages/cli/plugin-ssr/src/cli/index.ts
packages/cli/webpack/src/config/base.ts
packages/cli/webpack/src/config/client.ts
packages/cli/webpack/src/config/modern.ts
packages/cli/webpack/src/config/node.ts
packages/cli/webpack/src/config/shared.ts
packages/cli/webpack/src/index.ts
packages/cli/webpack/src/utils/createCSSRule.ts
packages/cli/webpack/tests/client.test.ts
pnpm-lock.yaml
website/docs/apis/config/tools/webpack-chain.md
website/docs/guides/tutorials/c07-app-entry/7.3-manage-entries-by-hand.md

Add `CHAIN_ID` constant to helper users to using `webpackChain`, and it allows us to manage chain ids better.
Modify `MiniCssExtractPlugin` options:
```js title="modern.config.js"
tools: {
webpackChain: (chain, { CHAIN_ID }) => {
chain.plugin(CHAIN_ID.PLUGIN.MINI_CSS_EXTRACT).tap(options => ({
...options,
ignoreOrder: false,
}));
},
},
});
```
Modify `css-loader` options:
```js title="modern.config.js"
tools: {
webpackChain: (chain, { CHAIN_ID }) => {
chain.module
.rule(CHAIN_ID.RULE.LOADERS)
.oneOf(CHAIN_ID.ONE_OF.CSS)
.use(CHAIN_ID.USE.CSS)
.tap(options => ({
...options,
sourceMap: false,
}));
},
},
});
```

feat(webpack): add CHAIN_ID constants for webpack chain

---

.changeset/few-dingos-sin.md
packages/server/utils/tests/__snapshots__/babel.test.ts.snap
packages/toolkit/babel-chain/src/preset.ts

fix: babel-chain preset option not woking

---

packages/cli/plugin-garfish/src/runtime/useModuleApps.ts

* feat(plugin-garfish): add path type

feat(plugin-garfish): add path type

---

.changeset/brave-socks-destroy.md
packages/cli/plugin-ssr/src/index.node.tsx

fix: return next in ssr-plugin's init hook

---

.changeset/dirty-camels-begin.md
packages/review/testing/src/config/testConfigOperator.ts
packages/review/testing/src/runJest.ts
packages/review/testing/tests/testConfigOperator.test.ts

Fix setting jest config with function.

fix(testing): fix setting jest config with function

---

.changeset/modern-deers-pull.md
packages/server/server/package.json
pnpm-lock.yaml

https://github.com/davewasmer/devcert/issues/83

fix: lock devcert version

---

.changeset/hungry-emus-dream.md
packages/cli/babel-preset-lib/package.json
packages/cli/babel-preset-module/package.json
packages/solutions/module-tools/package.json
pnpm-lock.yaml

1. Fix missing peer deps as following.
2. Remove unused `@babel/preset-typescript` and `@modern-js/babel-chain`.

fix: fix some missing peer dep issues

---

.changeset/fresh-ghosts-suffer.md
packages/cli/webpack/src/config/base.ts
packages/cli/webpack/src/config/node.ts

fix: use webpack chain to add target

---

.changeset/gentle-shrimps-doubt.md
packages/server/bff-utils/package.json
packages/server/bff-utils/src/server/api-handler-infos.ts
packages/toolkit/babel-chain/src/preset.ts

fix: prefix / not working

---

.github/workflows/release.yml

release workflow 修改拉取代码的 fetch-depth 为 1，加快拉代码速度，避免拉取仓库 tags 造成发版完成后获取到多余的版本信息

feat: change release branch depth

---

website/docs/apis/config/output/inject-by-entries.md
website/docs/apis/runtime/app/bootstrap.md
website/docs/apis/runtime/app/create-app.md
website/docs/apis/runtime/container/use-static-model.md
website/docs/apis/runtime/model/create-app.md
website/docs/apis/runtime/model/create-store.md
website/docs/apis/runtime/testing/renderApp.md
website/docs/apis/runtime/utility/loadable/loadable_.md
website/docs/guides/features/runtime/model/model-communicate.md
website/docs/guides/features/runtime/model/model-introduction.md
website/docs/guides/features/runtime/model/use-model.md
website/docs/guides/tutorials/c02-generator-and-studio/2.2-boilerplates.md
website/docs/guides/tutorials/c10-model/10.4-testing.md
website/docs/guides/tutorials/c11-container/11.4-testing.md

refer:  https://docusaurus.io/docs/markdown-features/links

docs: fix relative path without .md

---

website/docs/apis/config/source/env-vars.md
website/docs/apis/hooks/module/modern-config.md
website/docs/apis/hooks/mwa/modern-config.md
website/docs/apis/runtime/env.md

Update document of env vars and modern config file.

docs: update env vars and modern config file

---

.changeset/hot-worms-lie.md
.changeset/late-worms-sort.md
packages/server/create-request/package.json
packages/server/create-request/src/browser.ts
packages/server/create-request/src/node.ts
packages/server/create-request/tests/browser.test.ts
packages/server/create-request/tests/node.test.ts
packages/server/plugin-egg/src/cli/index.ts
packages/server/plugin-express/src/cli/index.ts
packages/server/plugin-express/src/registerRoutes.ts
packages/server/plugin-koa/src/cli/index.ts
packages/server/plugin-nest/src/cli/index.ts
tests/integration/api-service-koa/api/context/index.ts
tests/integration/api-service-koa/test/.eslintrc.js
tests/integration/api-service-koa/test/index.test.ts
tests/integration/api-service-koa/test/tsconfig.json
tests/integration/bff-express/api/context/index.ts
tests/integration/bff-express/test/.eslintrc.js
tests/integration/bff-express/test/index.test.ts
tests/integration/bff-express/test/tsconfig.json
tests/package.json

support params for bff schema

---

.changeset/modern-files-sleep.md
packages/cli/plugin-ssr/src/serverRender/type.ts
packages/cli/plugin-ssr/src/utils.ts
packages/toolkit/types/server/context.d.ts

fix: adjust ssr types

---

.changeset/clean-lions-argue.md
packages/cli/webpack/src/config/base.ts

ts checker skip api folder, it may block api server.

fix(webpack): ts checker skip api folder

---

.changeset/chilled-mails-add.md
packages/cli/webpack/src/config/shared.ts
packages/cli/webpack/tests/base.test.ts

Check argument type in webpack utils.

feat(webpack): check argument type in webpack utils

---

website/docs/guides/troubleshooting/compile.md

Add webpack compilation error faq.

docs: add webpack compilation error faq

---

.changeset/famous-monkeys-listen.md
packages/runtime/src/loader/loaderManager.ts
packages/runtime/src/loader/useLoader.ts

Support to disable `useLoader` cache  for  compatibility.

feat: support to disable `useLoader` cache

---

packages/cli/babel-preset-app/src/built-in/babel-plugin-ssr-loader-id.ts

fix: `babel-plugin-ssr-loader-id` types

---

.changeset/fresh-pots-count.md
packages/cli/plugin-ssg/src/index.ts
packages/cli/plugin-ssg/src/libs/util.ts
packages/cli/plugin-ssg/src/server/index.ts
packages/cli/plugin-ssg/tests/util.test.ts
packages/cli/plugin-ssr/src/cli/index.ts
packages/cli/webpack/src/config/node.ts

fix: optimize whether to do SSR bundle build

---

.changeset/new-ducks-matter.md
packages/server/adapter-helpers/src/utils.ts

fix: cannot find bff runtime file in Windows

---

.changeset/small-bottles-guess.md
packages/server/server/package.json
packages/server/server/src/dev-tools/dev-server-plugin.ts
packages/server/server/src/dev-tools/socket-server.ts
packages/server/server/src/server/dev-server.ts
packages/server/server/src/types.ts
packages/server/server/tests/dev.test.ts
packages/server/server/tests/server.test.ts
pnpm-lock.yaml

`@modern-js/server` should import `webpack` from `@modern-js/webpack` to ensure getting the correct webpack instance.

fix(server): using correct webpack instance

---

packages/server/server/src/dev-tools/socket-server.ts

fix(server): fix stats type

---

.changeset/kind-beans-mix.md
packages/runtime/src/compatible.tsx
packages/runtime/tests/bootstrap.test.tsx

bootstrap 函数在不传递 id 参数时返回 App 组件，支持用户自己进行 ReactDom 挂载

feat: bootstrap support return component

---

.changeset/silly-jokes-invent.md
packages/server/prod-server/src/server/modern-server.ts
packages/server/server/src/server/dev-server.ts

fix: remove cors for prod-server

---

.changeset/moody-games-teach.md
packages/cli/plugin-less/src/cli.ts
packages/cli/plugin-less/tests/index.test.ts
packages/cli/plugin-sass/src/cli.ts
packages/cli/plugin-sass/tests/index.test.ts
packages/cli/webpack/src/config/base.ts
packages/cli/webpack/src/config/shared.ts
packages/cli/webpack/src/utils/constants.ts
packages/cli/webpack/src/utils/createCSSRule.ts
packages/cli/webpack/tests/utils.test.ts
website/docs/apis/config/output/disable-css-module-extension.md

- Fix failed to compile CSS modules in node_modules.
- Improve rules order, move css module rules before normal css rules.
- Explain the detailed rules in document.

fix: failed to compile CSS modules in node_modules

---

.changeset/polite-dodos-eat.md
packages/cli/plugin-runtime/src/index.ts
packages/cli/plugin-state/src/runtime/plugin.tsx
packages/runtime/src/app-config.ts

Supply `AppConfig` type definition to get accurate type hints when calling `defineConfig` API.

feat: supply `AppConfig` type definition

---

.changeset/shy-clocks-glow.md
packages/cli/plugin-sass/src/cli.ts

Fix incorrect regexp for normal sass file.

fix(sass): incorrect regexp for normal sass file

---

.changeset/shaggy-ants-approve.md
packages/cli/plugin-ssr/package.json
packages/cli/plugin-ssr/src/serverRender/type.ts
packages/cli/plugin-ssr/src/utils.ts
packages/cli/plugin-ssr/tests/index.test.ts

fix: cookie and userAgent should not be optional

---

packages/cli/babel-preset-module/src/built-in/import-path.ts
packages/cli/babel-preset-module/src/index.ts
packages/cli/babel-preset-module/src/types.ts
packages/solutions/module-tools/src/features/build/bundless/copy-assets.ts
packages/solutions/module-tools/src/features/build/bundless/runBabel.ts
packages/solutions/module-tools/src/features/build/bundless/style.ts
packages/solutions/module-tools/src/features/build/normalize.ts
packages/solutions/module-tools/src/features/build/types.ts
packages/solutions/module-tools/src/utils/babel.ts

Refactor build catalog structure

---

.changeset/rude-poems-drop.md
packages/solutions/app-tools/src/utils/createCompiler.ts
packages/solutions/app-tools/src/utils/printInstructions.ts
website/docs/apis/commands/mwa/dev.md
website/docs/apis/config/dev/proxy.md
website/docs/apis/config/server/base-url.md
website/docs/guides/tutorials/c01-getting-started/1.3-dev-command.md
website/docs/guides/usages/debug/proxy-and-mock.md

Too much logs during `modern dev` may confuse users. vite and next.js outputs few logs during development. 
This PR remove some unnecessary logs during dev.
1. Remove repeated compile time log.
2. Remove build command tip, users know it.
4. No longer clear console after compile done, it may clear some useful logs during compile, such as bundle analyzer log.

fix(app-tools): remove some unnecessary logs during dev

---

.changeset/silver-ghosts-lay.md
.pnpmfile.cjs
packages/cli/webpack/src/config/base.ts
packages/cli/webpack/src/config/client.ts
pnpm-lock.yaml

- Remove `aggregateTimeout: 100`, the rebuild issue has been fixed in watchpack v2.4.0, see https://github.com/webpack/webpack/issues/15431
- Remove `wtfPath`, this configuration doesn't seem to take any effect.
- - Remove `esbuild` version rewrite in `.pnpmfile.cjs`
- Lazy require `node-libs-browser`, speed up bootstrap time.

feat(webpack): optimize webpack config

---

.changeset/empty-pillows-cough.md
packages/cli/core/src/config/mergeConfig.ts

fix: ignore dev server merge fn

---

.changeset/red-ears-laugh.md
packages/cli/webpack/src/config/client.ts

Keep the loaders order same as before, avoid breaking existed codes.

fix(webpack): fix loaders order

---

packages/solutions/module-tools/src/features/build/index.ts
packages/solutions/module-tools/src/types.ts
packages/solutions/module-tools/tests/generate-dts.test.ts
packages/solutions/module-tools/tests/generator-dts-utils.test.ts
packages/solutions/module-tools/tests/generator-dts.test.ts

fix: build and test error

---

packages/solutions/module-tools/src/features/build/bundless/generator-dts/index.ts

compatible logic for generate types

fix: compatible logic for generate types

---

.changeset/calm-hotels-wash.md
packages/solutions/module-tools/CHANGELOG.md
packages/solutions/module-tools/package.json
packages/solutions/module-tools/src/commands/build.ts
packages/solutions/module-tools/src/features/build/build.ts
packages/solutions/module-tools/src/types.ts
pnpm-lock.yaml
tests/integration/style-only-test/modern.config.js
tests/integration/style-only-test/package.json
tests/integration/style-only-test/src/index.js
tests/integration/style-only-test/test/index.test.js

Hotfix v1.4.0 style only

---

packages/solutions/module-tools/CHANGELOG.md
packages/solutions/module-tools/package.json
packages/solutions/module-tools/src/commands/build.ts
packages/solutions/module-tools/src/features/build/build.ts
packages/solutions/module-tools/src/types.ts
packages/toolkit/compiler/style/CHANGELOG.md
packages/toolkit/compiler/style/package.json
packages/toolkit/compiler/style/src/resolves/less.ts
pnpm-lock.yaml
tests/integration/style-only-test/modern.config.js
tests/integration/style-only-test/package.json
tests/integration/style-only-test/src/index.js
tests/integration/style-only-test/test/index.test.js

1. support `build --style-only`
2. set relativeUrls is true

Hotfix v1.4.0 relative urls

---

.changeset/gorgeous-avocados-walk.md
packages/cli/core/src/config/types/index.ts

修复 bffConfig 类型定义，使用 interface 代替 type 定义类型，允许进行类型覆盖

fix bff config type

---

.changeset/tender-buttons-tie.md
packages/toolkit/plugin/src/manager/async.ts
packages/toolkit/plugin/src/manager/shared.ts
packages/toolkit/plugin/src/manager/sync.ts
packages/toolkit/plugin/src/workflow/sync.ts

Extract same utils to shared, reduce duplicate code.

chore(plugin): extract same utils to shared

---

.changeset/curvy-dolls-exercise.md
packages/cli/webpack/src/config/base.ts

chore: fix tools.webpack type issue

---

.changeset/heavy-pens-burn.md
packages/cli/core/src/config/index.ts
packages/solutions/module-tools/src/features/build/bundle/runRollup.ts
packages/solutions/module-tools/src/features/build/bundle/runSpeedy.ts
packages/solutions/module-tools/src/features/build/bundless/runBabel.ts
packages/solutions/module-tools/src/features/build/constants.ts
packages/solutions/module-tools/src/features/build/index.ts
packages/solutions/module-tools/src/features/build/normalize.ts
packages/solutions/module-tools/src/features/build/types.ts
packages/solutions/module-tools/src/schema/build-config.ts
packages/solutions/module-tools/src/schema/index.ts
packages/solutions/module-tools/src/schema/output.ts
packages/solutions/module-tools/src/schema/tools.ts
packages/solutions/module-tools/src/schema/types.ts
packages/solutions/module-tools/src/types.ts
packages/solutions/module-tools/tests/generate-dts.test.ts
packages/solutions/module-tools/tests/generator-dts-utils.test.ts
packages/solutions/module-tools/tests/generator-dts.test.ts

[Module-tools]: review config

---

.changeset/selfish-moose-repair.md
packages/server/server/src/server/dev-server.ts

fix: support configure headers by devServer headers

---

.changeset/thirty-planes-visit.md
packages/cli/babel-preset-base/src/presets.ts

fix: node browserlist use 12

---

.changeset/large-avocados-greet.md
packages/cli/core/src/config/types/index.ts
packages/cli/core/src/config/types/ts-loader.ts
packages/cli/webpack/src/config/base.ts
packages/cli/webpack/tests/base.test.ts
website/docs/apis/config/tools/ts-loader.md

- support `addIncludes` and `addExcludes` in `tools.tsLoader`
- improve the typing of `tools.tsLoader`, add ts-loader options type and utils type.
- add document of `tools.tsLoader`

feat(webpack): support addIncludes and addExcludes in tools.tsLoader

---

.github/workflows/cypress-test.yml
packages/cli/plugin-garfish/package.json

workflow: fix cypress test error

workflow: fix cypress test error

---

.changeset/green-coats-prove.md
.changeset/perfect-avocados-hang.md
packages/generator/generators/module-generator/src/index.ts
packages/generator/generators/module-generator/src/locale/en.ts
packages/generator/generators/module-generator/src/locale/zh.ts
packages/generator/generators/monorepo-generator/src/index.ts
packages/generator/generators/monorepo-generator/src/locale/en.ts
packages/generator/generators/monorepo-generator/src/locale/zh.ts
packages/generator/generators/mwa-generator/src/index.ts
website/docs/apis/generator/config/introduce.md
website/docs/apis/generator/plugin/input/addInputAfter.md
website/docs/apis/generator/plugin/input/addInputBefore.md
website/docs/apis/generator/plugin/input/addOptionAfter.md
website/docs/apis/generator/plugin/input/addOptionBefore.md
website/docs/apis/generator/plugin/input/setInput.md
website/docs/apis/generator/plugin/input/setInputValue.md

fix: generator plugin doc

---

packages/solutions/module-tools/src/cli/build.ts
packages/solutions/module-tools/src/commands/build.ts
packages/solutions/module-tools/src/features/build/bundle/index.ts
packages/solutions/module-tools/src/features/build/bundle/runRollup.ts
packages/solutions/module-tools/src/features/build/bundle/runSpeedy.ts
packages/solutions/module-tools/src/features/build/bundless/copy-assets.ts
packages/solutions/module-tools/src/features/build/bundless/generator-dts/index.ts
packages/solutions/module-tools/src/features/build/bundless/index.ts
packages/solutions/module-tools/src/features/build/bundless/runBabel.ts
packages/solutions/module-tools/src/features/build/bundless/style.ts
packages/solutions/module-tools/src/features/build/constants.ts
packages/solutions/module-tools/src/features/build/index.ts
packages/solutions/module-tools/src/features/build/legacy-constants.ts
packages/solutions/module-tools/src/features/build/normalize.ts
packages/solutions/module-tools/src/features/build/types.ts
packages/solutions/module-tools/src/locale/en.ts
packages/solutions/module-tools/src/locale/zh.ts
packages/solutions/module-tools/src/schema/build-config.ts
packages/solutions/module-tools/src/schema/index.ts
packages/solutions/module-tools/src/schema/output.ts
packages/solutions/module-tools/src/schema/tools.ts
packages/solutions/module-tools/src/schema/types.ts
packages/solutions/module-tools/src/types.ts

refactor config and build logic.

Refactor build v2

---

tests/integration/garfish/main/src/App.tsx

chore: optimize plugin garfish e2e test

chore: optimize plugin garfish e2e test

---

.changeset/hot-rocks-arrive.md
packages/generator/generators/entry-generator/src/index.ts

fix: create entry not move .eslintrc.js file

---

.changeset/angry-onions-check.md
packages/server/bff-runtime/package.json
packages/server/bff-runtime/src/match.ts
packages/server/bff-runtime/src/request.ts
packages/server/bff-runtime/src/types.ts
pnpm-lock.yaml

Remove `farrow-http` from dependencies to reduce the size of node_modules.
`farrow-http` depend on a lot of packages:
```bash
➜  temp npm ls -a
temp@1.0.0 /Users/chenjiahan/Project/temp
└─┬ farrow-http@1.12.0
├─┬ accepts@1.3.8
│ ├── mime-types@2.1.35 deduped
│ └── negotiator@0.6.3
├── bytes@3.1.2
├─┬ chalk@4.1.2
│ ├─┬ ansi-styles@4.3.0
│ │ └─┬ color-convert@2.0.1
│ │   └── color-name@1.1.4
│ └─┬ supports-color@7.2.0
│   └── has-flag@4.0.0
├─┬ co-body@6.1.0
│ ├── inflation@2.0.0
│ ├── qs@6.10.5 deduped
│ ├─┬ raw-body@2.5.1
│ │ ├── bytes@3.1.2 deduped
│ │ ├─┬ http-errors@2.0.0
│ │ │ ├── depd@2.0.0 deduped
│ │ │ ├── inherits@2.0.4
│ │ │ ├── setprototypeof@1.2.0
│ │ │ ├── statuses@2.0.1 deduped
│ │ │ └── toidentifier@1.0.1
│ │ ├─┬ iconv-lite@0.4.24
│ │ │ └── safer-buffer@2.1.2
│ │ └── …
```

chore(bff-runtime): remove farrow-http from dependencies

---

.changeset/spicy-shirts-obey.md
packages/toolkit/utils/src/applyOptionsChain.ts

Fix applyOptionsChain type issue, maybe introduced in #1222 (the lock file has been re-generated).

fix(utils): applyOptionsChain argument type

---

tests/utils/modernTestUtils.js

Fix integration test of `compiled successfully` message.

chore: fix integration test of compiled successfully

---

website/docs/apis/config/output/disable-html-folder.md
website/docs/apis/config/output/html-path.md
website/docs/guides/usages/compile-speed.md

- add output.disableHtmlFolder description
- update output.htmlPath
- add dev browserslist guide

docs: add output.disableHtmlFolder description

---

.changeset/good-sloths-check.md
packages/cli/babel-preset-app/src/built-in/babel-plugin-lock-corejs-version.ts
packages/toolkit/utils/src/path.ts

fix babel-reset-app plugin. 
the soureFileName maybe null

fix(babel-reset-app): empty sourceFileName in babel-plugin-lock-corejs

---

.changeset/good-sloths-check.md

update changeset
update changeset

docs: update changeset

---

.changeset/cuddly-pots-itch.md
packages/cli/plugin-storybook/src/features/utils/webpackConfig.ts

Modify the webpack configuration of the running storybook to override the output configuration of the storybook with the webpackConfig.output configuration inside modern.js.

fix(storybook): change output config

---

.changeset/perfect-balloons-compare.md
packages/cli/core/src/config/types/index.ts
website/docs/guides/troubleshooting/compile.md

- Fix incorrect type of `tools.terser`.
- Add a FAQ of remove console.

fix(core): incorrect type of tools.terser

---

.changeset/sour-students-notice.md
packages/cli/plugin-changeset/src/index.ts

fix: changeset bump support ignore option

---

.changeset/sixty-starfishes-suffer.md
packages/cli/webpack/src/config/node.ts

```
sssByEntries: {
main: {}
}
```

fix: should bundle ssr when ssrByEntries[name] is exist

---

.changeset/forty-moons-jog.md
.changeset/lemon-fireants-yawn.md
.changeset/old-planes-walk.md
.changeset/smart-guests-pump.md
.changeset/weak-forks-raise.md
packages/cli/babel-preset-base/src/plugins.ts
packages/cli/plugin-runtime/src/cli/index.ts
packages/cli/plugin-tailwind/.eslintrc.js
packages/cli/plugin-tailwind/src/cli.ts
packages/cli/plugin-tailwind/src/utils.ts
packages/cli/plugin-tailwind/tests/__snapshots__/utils.test.ts.snap
packages/cli/plugin-tailwind/tests/cli.test.ts
packages/cli/plugin-tailwind/tests/fixtures/twin-macro/package.json
packages/cli/plugin-tailwind/tests/tsconfig.json
packages/cli/plugin-tailwind/tests/utils.test.ts
packages/cli/webpack/src/config/base.ts
packages/cli/webpack/tests/__snapshots__/utils.test.ts.snap
packages/server/utils/tests/__snapshots__/babel.test.ts.snap
packages/toolkit/load-config/src/index.ts
packages/toolkit/node-bundle-require/src/bundle.ts
packages/toolkit/node-bundle-require/src/index.ts
pnpm-lock.yaml
tests/integration/css/fixtures/twin.macro/modern.config.js
tests/integration/css/fixtures/twin.macro/package.json
tests/integration/css/fixtures/twin.macro/src/App.jsx
tests/integration/css/test/twin.macro.test.js
website/docs/guides/usages/css/tailwindcss.md

feat: support twin.macro

---

packages/server/plugin-egg/src/utils/registerRoutes.ts
packages/server/plugin-express/src/utils.ts
packages/server/plugin-nest/src/helpers.ts

remove ts-expect-error and modify types from some packages

chore: remove ts-expect-error

---

.changeset/rude-mirrors-retire.md
packages/generator/generators/entry-generator/templates/main.css

插件模板css文件中文错误
Microsoft YaHei就等于微软雅黑。
其中Microsoft YaHei兼容性更好，中文”微软雅黑“在某些版本的浏览器会失效。
当用户将模板css文件内容直接复制到.less中。在dev时，中文”微软雅黑“会导致less发生编译错误。

fix(@modern-js/entry-generator): Encoding error introduced in Chinese

---

packages/toolkit/freeze/src/index.ts

docs: add license

---

website/docs/apis/config/source/include.md
website/docs/guides/troubleshooting/compile.md
website/docs/guides/troubleshooting/dependencies.md

docs: add more faq about compile

---

website/docs/guides/usages/css/tailwindcss.md

fix broken link in tailwindcss.md.
https://github.com/modern-js-dev/modern.js/runs/7040585331?check_suite_focus=true

docs: fix broken link in tailwindcss

---

.changeset/small-dryers-relax.md
packages/cli/plugin-ssr/src/index.node.tsx
packages/cli/plugin-ssr/src/index.tsx
packages/cli/plugin-ssr/src/utils.ts
packages/runtime/src/runtime-context.ts
packages/server/prod-server/src/libs/render/ssr.ts
packages/toolkit/types/server/context.d.ts

feat: support set header and status

---

.changeset/spotty-comics-report.md
packages/cli/plugin-garfish/package.json
packages/server/bff-core/package.json
pnpm-lock.yaml

Upgrade `@babel/runtime` to `>= 7.18.0` to fix:
https://github.com/modern-js-dev/modern.js/runs/7069027737?check_suite_focus=true

fix: incorrect @babel/runtime version

---

tests/integration/ssr/fixtures/init/src/App.jsx

fix: intergartion test

---

packages/cli/plugin-changeset/package.json
packages/cli/plugin-changeset/src/commands/release-note.ts
pnpm-lock.yaml

优化 gen-release-note 自定义参数
- 支持计算 require 绝对路径
- 提供自定义函数校验
- 自定义函数支持返回 Promise

feat: optimize custom generator release note

---

website/docs/apis/config/output/favicon-by-entries.md
website/docs/apis/config/output/inject-by-entries.md
website/docs/apis/config/output/meta-by-entries.md
website/docs/apis/config/output/template-parameters-by-entires.md
website/docs/apis/config/output/template-parameters.md
website/docs/apis/config/output/title-by-entries.md
website/docs/apis/config/output/title.md
website/docs/components/entry-name.md
website/src/css/custom.css

- add `output.templateParameters` document.
- add `output.templateParametersByEntries` document.
- update all documents of `output.xxxByEntries`.
- keep menu font size same as jupiter.

docs: add output.templateParameters document

---

.changeset/spotty-walls-talk.md
.github/workflows/release-pull-request.yml
.github/workflows/release.yml
packages/cli/plugin-changeset/src/commands/release-note.ts

实现主要功能：
- 自动执行 pnpm run bump 升级版本号
- 自动提交代码
- 自动创建 Pull Request，Pull Request 内容为执行 pnpm run gen-release-note 的结果
触发方式：

feat: add release pull request workflow

---

.changeset/real-guests-perform.md
packages/cli/core/src/config/schema/server.ts
packages/cli/core/src/config/types/index.ts
packages/server/server/src/dev-tools/watcher/index.ts
packages/server/server/src/server/dev-server.ts
packages/server/server/tests/watcher.test.ts

feat: add watchOptions for server watcher

---

website/docs/apis/config/tools/minify-css.md
website/docs/apis/config/tools/terser.md

Fix mistakes in tools.minifyCss and tools.terser.

docs: fix mistakes in tools.minifyCss and tools.terser

---

.changeset/witty-islands-look.md
packages/generator/generator-plugin/src/utils/getPackageMeta.ts

fix: generator plugin no meta error

---

packages/server/bff-core/src/router/utils.ts

fix: type error in bff-core

---

.github/workflows/release-pull-request.yml
jest.config.js

Github 使用 secrets.GITHUB_TOKEN 默认不会触发 CI 流程，需要使用个人令牌 
https://github.com/peter-evans/create-pull-request/issues/48

feat: release pull request github token use repo scoped token

---

packages/server/bff-core/src/router/utils.ts

fix: esbuild-register not working

---

packages/solutions/module-tools/src/commands/build.ts
packages/solutions/module-tools/src/features/build/bundleless/runBabel.ts
packages/solutions/module-tools/src/features/build/bundleless/style.ts
packages/solutions/module-tools/src/utils/copy.ts
tests/integration/module-tools/bundle/index.test.js
tests/integration/module-tools/test/utils.js

fix: globby window path

---

packages/solutions/module-tools/package.json
packages/toolkit/compiler/style/CHANGELOG.md
packages/toolkit/compiler/style/package.json
pnpm-lock.yaml

chore: bump style-compiler

---

.github/workflows/check-changeset.yml
package.json
pnpm-lock.yaml
scripts/check-changeset/.eslintrc.js
scripts/check-changeset/package.json
scripts/check-changeset/src/index.ts
scripts/check-changeset/tsconfig.json

添加校验 changeset 的 workflow，避免开发者选择 Major 版本号，由 Modern.js 团队统一进行 Major 版本号升级决策

feat: add check changeset workflow

---

tests/integration/runtime/test/router.test.js

fix integration test runtime/router: [link](https://github.com/modern-js-dev/modern.js/runs/7176388308?check_suite_focus=true)

fix: page.$eval return null

---

tests/integration/runtime/test/router.test.js

fix: integration test runtime router

---

.changeset/four-camels-retire.md
packages/cli/webpack/src/config/features/minimizer.ts
website/docs/apis/config/tools/terser.md

- Remove `parse: { ecma: 8 }` because terser no longer provide this option: https://github.com/terser/terser#parse-options
- Remove `warnings`, `comparisons`, `inline` because these options are inherited from `create-react-app`, and the related issues are fixed by the latest terser, so we on longer need to config them, see https://github.com/facebook/create-react-app/blob/9802941ff049a28da2682801bc182a29761b71f4/packages/react-scripts/config/webpack.config.js#L272-L284.
This change can improve compress rate:

perf(webpack): optimize default terser options

---

.changeset/cyan-oranges-march.md
packages/cli/plugin-storybook/package.json
packages/cli/plugin-storybook/src/features/utils/webpackConfig.ts

change webpack `output.publicPath` for plugin-storybook

feat(plugin-storybook): change webpack output.publicPath

---

.changeset/gentle-gorillas-train.md
packages/solutions/module-tools/src/schema/build-config.ts
packages/solutions/module-tools/tests/__snapshots__/build-config.test.ts.snap
packages/solutions/module-tools/tests/schema.test.ts

Add `additionalProperties: false` to the schema of 'output.buildConfig'

fix: add additionalProperties

---

.changeset/early-garlics-melt.md
.changeset/wise-lions-care.md
packages/cli/plugin-ssg/src/server/process.ts

fix: ssg load plugin correctly

---

.changeset/cool-suits-marry.md
packages/runtime/src/compatible.tsx
packages/toolkit/types/server/context.d.ts
tests/integration/ssr/fixtures/init/package.json
tests/integration/ssr/fixtures/init/src/App.jsx

fix: use client init data priority

---

packages/toolkit/compiler/style/CHANGELOG.md
packages/toolkit/compiler/style/package.json

only bump version for style-compiler, trigger the correct version to be displayed on npm

chore: only bump style-compiler

---

.changeset/long-snakes-dream.md
packages/cli/plugin-changeset/src/commands/release-note.ts
packages/cli/plugin-changeset/tests/release-note.test.ts
website/docs/guides/features/changesets/release-note.md

优化 Release Note 展示格式
优化前：
优化后：

Feat optimize release note

---

packages/cli/plugin-storybook/CHANGELOG.md
packages/cli/plugin-storybook/package.json
packages/cli/plugin-storybook/src/features/utils/webpackConfig.ts

hotfix logic about storybook use client oneOf url

fix: storybook use client oneOf rule

---

.changeset/nasty-ads-destroy.md

fix: changeset

---

.changeset/many-candles-fetch.md
.changeset/popular-dancers-cough.md
packages/cli/plugin-nocode/package.json
packages/cli/plugin-nocode/src/cli.ts
packages/cli/plugin-storybook/package.json
packages/cli/plugin-storybook/src/index.ts
packages/solutions/module-tools/package.json
packages/solutions/module-tools/src/index.ts
pnpm-lock.yaml

remove plugin-analyze from module-tools and add plugin-analyze to plugin-storybook and plugin-nocode

feat: remove plugin-analyze

---

website/docs/guides/troubleshooting/compile.md
website/docs/guides/troubleshooting/dependencies.md

docs: add some faq

---

.changeset/afraid-gorillas-burn.md
packages/cli/webpack/src/config/features/bundle-analyzer.ts

fix(webpack): failed to analyze bundle

---

website/docs/apis/config/dev/https.md

Update https document, add ip address FAQ.

docs: update https document, add ip address FAQ

---

.changeset/funny-socks-clean.md
packages/cli/plugin-runtime/src/index.ts
packages/cli/plugin-storybook/src/runtime-addon/components/modern.tsx

added configuration file types about runtime.state and runtime.router.

feat: runtime config types

---

website/docs/apis/commands/module/gen-release-note.md
website/docs/apis/commands/monorepo/gen-release-note.md

修复 gen-release-note 文档 format 格式

fix: release note doc

---

pnpm-lock.yaml

feat: update lock file

---

.changeset/cuddly-boxes-carry.md
packages/cli/plugin-ssr/src/serverRender/helmet.ts
packages/cli/plugin-ssr/tests/helmet.test.ts

修复当开启SSR时，html 中的 <title> 标签将被空白内容替换。
@modern-js/plugin-ssr

fix(plugin-ssr): the tag in html template will replace by empty content

---

.changeset/honest-plums-train.md
.changeset/wise-geckos-train.md
packages/server/bff-core/src/errors/http.ts
packages/server/plugin-express/src/plugin.ts
packages/server/plugin-koa/src/plugin.ts

https://github.com/modern-js-dev/modern.js/issues/1376

fix: bff hot reload not works when has app.ts

---

.changeset/four-kings-decide.md
packages/cli/plugin-runtime/package.json
pnpm-lock.yaml

fix: ssr exports error

---

.changeset/olive-queens-melt.md
packages/cli/plugin-bff/package.json
packages/cli/plugin-bff/tests/fixtures/function/api/hello.ts
packages/cli/plugin-runtime/package.json
packages/cli/plugin-runtime/src/exports/server.ts
pnpm-lock.yaml

remove `@modern-js/bff-runtime` from `@modern-js/runtime` dependence

feat: remove @modern-js/bff-runtime from @modern-js/runtime dependence

---

.changeset/thin-cycles-double.md
packages/cli/webpack/src/config/features/html.ts

Additional compilation fields for templateParameters

fix: add compliation fields for templateParameters

---

.changeset/twenty-walls-bathe.md
packages/server/plugin-egg/src/utils/registerRoutes.ts
packages/server/plugin-express/src/utils.ts
packages/server/plugin-koa/src/utils.ts
packages/server/plugin-nest/src/helpers.ts

fix: allow BFF function to return void

---

.changeset/clean-cobras-type.md
packages/cli/plugin-runtime/src/ssr/cli/index.ts
packages/cli/webpack/src/config/node.ts
packages/cli/webpack/tests/node.test.ts

fix: ssg build error when multi entries

---

.changeset/metal-socks-beam.md
packages/cli/core/src/config/schema/source.ts
packages/cli/core/src/config/types/index.ts
packages/cli/webpack/src/config/base.ts
packages/cli/webpack/tests/base.test.ts
website/docs/apis/config/source/pre-entry.md

support source.preEntry config:
```js title="modern.config.js"
source: {
preEntry: './src/polyfill.ts',
},
});
```

feat(webpack): support source.preEntry config

---

.changeset/funny-pets-switch.md
packages/server/bff-core/src/operators/http.ts
packages/server/bff-core/src/types.ts
packages/server/plugin-express/src/registerRoutes.ts
packages/server/plugin-express/src/runtime.ts
packages/server/plugin-express/src/runtime/index.ts
packages/server/plugin-express/src/runtime/operators.ts
packages/server/plugin-express/src/utils.ts
packages/server/plugin-express/tests/api.test.ts
packages/server/plugin-express/tests/fixtures/operator/api/index.ts
packages/server/plugin-express/types.d.ts

feat: support Pipe and Middleware operators

---

.changeset/slimy-boxes-rule.md
packages/cli/plugin-runtime/src/common.ts
packages/cli/plugin-runtime/src/router/runtime/plugin.tsx
packages/cli/plugin-runtime/src/ssr/index.node.tsx
packages/cli/plugin-runtime/src/state/runtime/plugin.tsx
packages/runtime/src/compatible.tsx
packages/solutions/app-tools/src/analyze/templates.ts
packages/toolkit/utils/src/is/platform.ts

使用以下代码判断 window 环境，排除 jsdom 干扰
```
typeof window !== undefined && window.name !== 'nodejs';
```

fix: modify browser determine

---

.changeset/olive-pumpkins-rescue.md
packages/cli/plugin-runtime/src/exports/model.ts
packages/cli/plugin-runtime/src/exports/ssr.ts
packages/cli/plugin-testing/package.json

fix: runtime and testing package exports field

---

.changeset/slimy-boxes-rule.md

fix changeset container not exist package

docs: fix changeset

---

.changeset/slow-pears-share.md
packages/cli/webpack/src/config/node.ts

feat: 支持 externals

---

packages/cli/babel-preset-lib/package.json
packages/cli/babel-preset-module/package.json
packages/cli/core/package.json
packages/cli/plugin-jarvis/package.json
packages/generator/generator-plugin/package.json
packages/server/plugin-nest/package.json
pnpm-lock.yaml

chore: remove useless react dependencies

---

website/docs/guides/troubleshooting/compile.md

常见问题增加 「如何在编译过程中进行 ESLint 代码校验？」

docs: add eslint pugin faq

---

.changeset/four-points-doubt.md
packages/cli/plugin-runtime/types/model.d.ts
packages/cli/plugin-runtime/types/state.d.ts

Types for model effects are not working. This PR fix the issue.

fix: fix types for model effects

---

.changeset/angry-ways-rule.md
packages/solutions/app-tools/src/index.ts

fix: fix not found `analyze/cli` when change config

fix: analyze error

---

.changeset/grumpy-parrots-doubt.md
packages/server/plugin-egg/package.json
pnpm-lock.yaml

egg-ts-helper 新版本会启动一个新的进程，导致对于 fs 的 API 的 mock 失效。

chore: lock egg-ts-helper version

---

.changeset/angry-moose-reflect.md
packages/generator/generator-common/src/common/package-manager.ts

feat: package manager support isSubProject params

---

.changeset/angry-ways-rule.md
.changeset/famous-melons-return.md
packages/cli/plugin-garfish/package.json
packages/cli/plugin-runtime/CHANGELOG.md
packages/cli/plugin-runtime/package.json
packages/cli/plugin-storybook/package.json
packages/solutions/app-tools/CHANGELOG.md
packages/solutions/app-tools/package.json
pnpm-lock.yaml

- fix not found analyze/cli when change config
- fix  plugin runtime dependencies

Hotfix v1.7.1

---

.changeset/slimy-olives-float.md
packages/generator/generators/storybook-generator/src/index.ts

feat: storybook generator add `react-dom` dependence

---

packages/builder/web-builder/src/core/createBuilder.ts
packages/builder/web-builder/src/plugins/moment.ts
packages/builder/web-builder/src/types/config/performance.ts

Add moment plugin for web builder.

feat(web-builder): add moment plugin

---

packages/builder/web-builder/src/core/build.ts
packages/builder/web-builder/src/core/createBuilder.ts
packages/builder/web-builder/src/core/createCompiler.ts
packages/builder/web-builder/src/core/createContext.ts
packages/builder/web-builder/src/core/createPluginStore.ts
packages/builder/web-builder/src/core/initConfigs.ts
packages/builder/web-builder/src/core/initPlugins.ts
packages/builder/web-builder/src/core/webpackConfig.ts
packages/builder/web-builder/src/index.ts
packages/builder/web-builder/src/plugins/cache.ts
packages/builder/web-builder/src/plugins/cleanOutput.ts
packages/builder/web-builder/src/plugins/copy.ts
packages/builder/web-builder/src/plugins/devtool.ts
packages/builder/web-builder/src/plugins/minimize.ts
packages/builder/web-builder/src/plugins/mode.ts
packages/builder/web-builder/src/plugins/moment.ts
packages/builder/web-builder/src/plugins/progress.ts
packages/builder/web-builder/src/plugins/target.ts
packages/builder/web-builder/src/types/builder.ts
packages/builder/web-builder/src/types/config/dev.ts
packages/builder/web-builder/src/types/config/experiments.ts
packages/builder/web-builder/src/types/config/index.ts
packages/builder/web-builder/src/types/config/output.ts
packages/builder/web-builder/src/types/config/performance.ts
packages/builder/web-builder/src/types/config/security.ts
packages/builder/web-builder/src/types/config/source.ts
packages/builder/web-builder/src/types/config/tools.ts
packages/builder/web-builder/src/types/context.ts
packages/builder/web-builder/src/types/hooks.ts
packages/builder/web-builder/src/types/plugin.ts

Simplify type names of web builder

chore(web-builder): simplify type names

---

.changeset/fair-swans-rest.md
packages/cli/core/src/config/types/index.ts
packages/toolkit/utils/src/constants.ts

Revert schema of unbundle plugin.
Fix following errors:

fix(utils): revert schema of unbundle plugin

---

packages/builder/web-builder/package.json
packages/builder/web-builder/src/config/normalize/index.ts
packages/builder/web-builder/src/config/normalize/source.ts
packages/builder/web-builder/src/config/validate/index.ts
packages/builder/web-builder/src/config/validate/source.ts
packages/builder/web-builder/src/core/build.ts
packages/builder/web-builder/src/core/createBuilder.ts
packages/builder/web-builder/src/core/createContext.ts
packages/builder/web-builder/src/core/initConfigs.ts
packages/builder/web-builder/src/shared/utils.ts
packages/builder/web-builder/src/types/config/index.ts
packages/builder/web-builder/src/types/config/source.ts
packages/builder/web-builder/src/types/context.ts
pnpm-lock.yaml

- Compile and validate schema of config without blocking.
- Defining partial schemas with type annotations.

feat(web-builder): add ConfigValidator to ensure that the schema of config is correct

---

.changeset/eight-pandas-divide.md
packages/cli/plugin-runtime/package.json
packages/cli/plugin-runtime/src/index.ts
packages/cli/plugin-runtime/src/router/cli/index.ts
packages/cli/plugin-runtime/src/ssr/cli/index.ts
packages/cli/plugin-runtime/src/state/cli/index.ts

fix: runtime plugin module path

fix: runtime plugin module path

---

packages/cli/plugin-runtime/package.json
packages/cli/plugin-runtime/src/state/cli/index.ts

fix: state runtime path

---

.changeset/brave-donkeys-tan.md
.changeset/chilled-kangaroos-attack.md
.changeset/itchy-gifts-promise.md
.changeset/mighty-bottles-know.md
.changeset/neat-ducks-add.md
.changeset/three-masks-pump.md
packages/cli/plugin-changeset/package.json
packages/cli/plugin-esbuild/package.json
packages/cli/plugin-multiprocess/package.json
packages/cli/plugin-proxy/package.json
packages/solutions/app-tools/package.json
packages/toolkit/node-bundle-require/package.json

adjust packages export field with `output.packageMode: 'node-js'` config.
-  `@modern-js/plugin-multiprocess`
- `@modern-js/plugin-esbuild`
- `@modern-js/app-tools`
- `@modern-js/node-bundle-require`
- `@modern-js/plugin-proxy`
- `@modern-js/plugin-changeset`

fix:  packages export fields

---

.changeset/fifty-mirrors-kiss.md
.changeset/lucky-geckos-care.md
packages/generator/generators/mwa-generator/templates/ts-template/src/modern-app-env.d.ts.handlebars
packages/runtime/plugin-runtime/lib/types.d.ts
packages/runtime/plugin-runtime/package.json
packages/runtime/plugin-runtime/src/index.ts

feat: support runtime router and state type

feat: support runtime router and state type

---

.changeset/old-dodos-learn.md
packages/solutions/monorepo-tools/src/features/deploy/index.ts

Monorepo-tools 在执行命令时，应该复制 `lerna.json` 文件，否则 `output` 目录安装依赖时，不会作为一个 monorepo 仓库来安装。

fix: copy lerna.json

---

tests/integration/css/test/exclude.test.js

chore: fix integration test of css exclude

---

.changeset/selfish-lizards-hear.md
packages/runtime/plugin-garfish/type.d.ts

feat: support runtime masterApp type

feat: support runtime masterApp type

---

.changeset/new-chefs-cover.md
packages/cli/plugin-storybook/src/runtime-addon/typings.d.ts

fix: storybook type

---

packages/builder/web-builder/src/core/createBuilder.ts
packages/builder/web-builder/src/core/createContext.ts
packages/builder/web-builder/src/plugins/font.ts
packages/builder/web-builder/src/plugins/output.ts
packages/builder/web-builder/src/shared/constants.ts
packages/toolkit/utils/src/chainId.ts

Add font plugin for web builder.

feat(web-builder): add font plugin

---

.changeset/wild-shirts-sip.md

feat: add changeset for support zod transform

---

packages/builder/web-builder/src/core/createBuilder.ts
packages/builder/web-builder/src/plugins/hmr.ts
packages/builder/web-builder/src/types/config/tools.ts
packages/builder/web-builder/src/types/thirdParty/index.ts

- Add hmr plugin for web builder.

feat(web-builder): add hmr plugin

---

.changeset/friendly-peaches-compete.md
packages/runtime/plugin-runtime/src/router/runtime/utils.tsx

fix(runtime): router plugin replace error

---

website/src/theme/Navbar/styles.module.css

docs: update second nav style

---

jest.config.js
monorepo.code-workspace
packages/builder/web-builder/.eslintrc.js
packages/builder/web-builder/package.json
packages/builder/web-builder/tests/__snapshots__/createAsyncHook.test.ts.snap
packages/builder/web-builder/tests/createAsyncHook.test.ts
packages/builder/web-builder/vitest.config.ts
pnpm-lock.yaml
scripts/vitest-config/.eslintrc.js
scripts/vitest-config/index.ts
scripts/vitest-config/package.json
scripts/vitest-config/tsconfig.json

Use vitest instead of jest to run tests.

feat(web-builder): use vitest instead of jest

---

packages/builder/web-builder/package.json
packages/builder/web-builder/src/core/createBuilder.ts
packages/builder/web-builder/src/plugins/tsChecker.ts
packages/builder/web-builder/src/plugins/tsLoader.ts
packages/builder/web-builder/src/types/thirdParty/index.ts
pnpm-lock.yaml
tests/integration/web-builder/scripts/shared.ts
tests/integration/web-builder/tsconfig.json

feat: add ts loader & checker in web builder

---

packages/builder/web-builder/src/plugins/basic.ts
packages/builder/web-builder/src/plugins/cleanOutput.ts
packages/builder/web-builder/src/plugins/minimize.ts
packages/builder/web-builder/src/types/config/tools.ts

- fix `output.disableMinimize` not work
- fix `tools.tsChecker` typing
- add `context` to basic plugin

fix(web-builder): output.disableMinimize not work

---

packages/builder/web-builder/src/core/createBuilder.ts
packages/builder/web-builder/src/plugins/resolve.ts
packages/builder/web-builder/src/types/config/source.ts
tests/integration/web-builder/scripts/shared.ts

Add resolve plugin for web builder.

feat(web-builder): add resolve plugin

---

.changeset/slow-laws-give.md
packages/cli/plugin-tailwind/CHANGELOG.md
packages/cli/plugin-tailwind/package.json
packages/cli/plugin-tailwind/src/cli.ts
packages/cli/plugin-tailwind/src/design-token/cli/index.ts

fix: `@modern-js/plugin-tailwindcss` support `pluginName` params

---

packages/builder/web-builder/jest.config.js
packages/builder/web-builder/package.json
packages/builder/web-builder/src/core/createBuilder.ts
packages/builder/web-builder/src/core/createContext.ts
packages/builder/web-builder/src/core/createPluginStore.ts
packages/builder/web-builder/tests/__snapshots__/createAsyncHook.test.ts.snap
packages/builder/web-builder/tests/targetPlugin.test.ts
packages/builder/web-builder/tests/utils/builder.ts
packages/builder/web-builder/tests/utils/context.ts
pnpm-lock.yaml

add unwrap utils to stub builder

feat(web builder): add test utils

---

.changeset/spicy-roses-fly.md
packages/builder/web-builder/src/core/build.ts
packages/builder/web-builder/src/core/createCompiler.ts
packages/builder/web-builder/src/shared/format.ts
packages/builder/web-builder/src/shared/index.ts
packages/builder/web-builder/src/shared/logger.ts
packages/solutions/app-tools/src/utils/createCompiler.ts
packages/toolkit/utils/src/format.ts
tests/integration/web-builder/scripts/build.ts

Log more detailed error messages in `@modern-js/webpack` and `@modern-js/web-builder` to help users to debug compile issues.

feat(webpack): log more detailed error messages

---

packages/runtime/plugin-garfish/CHANGELOG.md
packages/runtime/plugin-garfish/package.json
packages/runtime/plugin-garfish/src/cli/index.ts

fix: `@modern-js/plugin-garfish` support `pluginName` params

---

.changeset/calm-hornets-think.md
.changeset/config.json
.changeset/dirty-fishes-agree.md

仓库包版本号统一
仓库包分为两类，生成器包和非生成器包，两类版本号版本保持一致

feat: unify version

---

.changeset/many-keys-prove.md
packages/server/bff-core/package.json

fix: modify bff-core types

---

.changeset/poor-adults-guess.md
packages/generator/generator-common/src/newAction/module/index.ts
packages/generator/generator-common/src/newAction/mwa/index.ts

move less、sass、tailwindcss、ssg、polyfill dependencies to devDependencies

feat: adjust new command dependencies position

---

packages/builder/web-builder/src/core/createBuilder.ts
packages/builder/web-builder/src/core/createContext.ts
packages/builder/web-builder/src/plugins/entry.ts
packages/builder/web-builder/src/plugins/tsChecker.ts
packages/builder/web-builder/src/types/builder.ts
packages/builder/web-builder/src/types/config/source.ts
packages/builder/web-builder/src/types/context.ts
packages/builder/web-builder/tests/__snapshots__/entryPlugin.test.ts.snap
packages/builder/web-builder/tests/entryPlugin.test.ts
tests/integration/web-builder/scripts/shared.ts

Add entry plugin for web builder.

feat(web-builder): add entry plugin

---

packages/builder/web-builder/package.json
packages/server/bff-core/src/index.ts
pnpm-lock.yaml

fix: build error

---

packages/builder/web-builder/src/plugins/css.ts
packages/builder/web-builder/src/plugins/less.ts
packages/builder/web-builder/src/plugins/sass.ts

chore: reuse css rules in sass and less

---

.changeset/happy-insects-shout.md
packages/runtime/plugin-runtime/src/ssr/utils.ts

fix: fix runtime context format bug

---

.changeset/cold-boxes-share.md
packages/server/plugin-egg/src/runtime/index.ts
packages/server/plugin-express/src/runtime/hook.ts
packages/server/plugin-express/src/runtime/index.ts
packages/server/plugin-koa/src/runtime.ts
packages/server/plugin-nest/src/runtime/index.ts

fix: add server hook and types

---

monorepo.code-workspace

feat: adjust monorepo workspace

---

.changeset/nice-garlics-call.md
packages/toolkit/types/package.json
packages/toolkit/types/server/utils.d.ts
packages/toolkit/utils/src/format.ts
pnpm-lock.yaml

fix bff.proxy and devServer.proxy types.
修复 bff.proxy 和 devServer.proxy 类型定义不完整的问题.

fix: bff.proxy and devServer.proxy types

---

.changeset/eleven-ducks-accept.md
packages/cli/webpack/src/config/node.ts
packages/cli/webpack/tests/node.test.ts

feat: generate ssr bundle sourcemap for node debugging

---

.changeset/rare-rockets-return.md
packages/server/prod-server/src/libs/context/context.ts
packages/server/prod-server/src/libs/render/measure.ts
packages/server/prod-server/src/utils.ts
packages/server/prod-server/tests/utils.test.ts

fix: remove cookie in error log

---

website/docs/apis/app/hooks/config/upload.md

fix: website build error

---

.changeset/neat-moons-enjoy.md
packages/runtime/plugin-runtime/src/ssr/serverRender/helmet.ts

fix: remove helmet regexp's global tag

---

packages/builder/web-builder/.eslintrc.js
packages/builder/web-builder/src/plugins/font.ts
packages/builder/web-builder/src/plugins/html.ts
packages/builder/web-builder/src/plugins/image.ts
packages/builder/web-builder/src/plugins/media.ts
packages/builder/web-builder/src/plugins/resolve.ts
packages/builder/web-builder/src/types/config/source.ts
packages/builder/web-builder/src/types/thirdParty/index.ts
packages/builder/web-builder/tests/plugins/resolve.test.ts

Support source.alias config in web builder.

feat(web-builder): support source.alias config

---

.github/workflows/check-changeset.yml
scripts/check-changeset/src/index.ts

check changeset should container two lines. one line is English info and other is Chinese info

feat: check changeset container english and chinese info

---

.github/workflows/release-pull-request.yml

When Create Release Pull Request, support auto calculate release version.
https://github.com/modern-js-dev/actions/pull/10

feat: release pull request workflow use auto version

---

packages/builder/web-builder/package.json
packages/builder/web-builder/src/core/createBuilder.ts
packages/builder/web-builder/src/plugins/babel.ts
packages/builder/web-builder/src/plugins/react.ts
packages/builder/web-builder/tests/plugins/__snapshots__/react.test.ts.snap
packages/builder/web-builder/tests/plugins/react.test.ts
pnpm-lock.yaml

feat: add react plugin in web builder

---

.changeset/popular-moles-try.md
packages/generator/generator-common/src/common/package-name.ts
packages/generator/generator-common/src/common/package-path.ts
packages/generator/generator-common/src/mwa/entry.ts

generator schema validate error info should use error field

fix: generator schema validate

---

.changeset/slimy-pumas-drive.md
packages/cli/plugin-bff/src/cli.ts
packages/cli/plugin-bff/src/loader.ts
packages/cli/plugin-bff/tests/loader.test.ts
packages/server/bff-core/src/router/index.ts

Support framework mode without lambda directory, when `api/app/` or `api/app.ts` exists, we also think of this as the framework mode.

feat: support framework mode without lambda directory

---

website/docs/apis/app/config/dev/asset-prefix.md
website/docs/apis/app/config/output/asset-prefix.md

Add tip for `dev.assetPrefix` with garfish.

docs: add tip for assetPrefix with garfish

---

packages/builder/web-builder/src/core/createBuilder.ts
packages/builder/web-builder/src/plugins/compatModern.ts
packages/builder/web-builder/src/plugins/moduleScopes.ts
packages/builder/web-builder/src/types/config/source.ts
packages/builder/web-builder/src/types/index.ts
packages/builder/web-builder/src/types/utils.ts
packages/builder/web-builder/src/webpackPlugins/ModuleScopePlugin.ts
packages/builder/web-builder/tests/plugins/__snapshots__/moduleScopes.test.ts.snap
packages/builder/web-builder/tests/plugins/moduleScopes.test.ts

Add moduleScope plugin for web builder, support `source.moduleScopes` config.

feat(web-builder): add moduleScope plugin

---

tests/cypress/e2e/1-garfish/whole-process.cy.js

fix: garfish cypress

---

.changeset/breezy-ghosts-press.md
packages/generator/generator-utils/src/index.ts
packages/generator/generators/module-generator/src/index.ts
packages/generator/generators/module-generator/templates/base-template/package.json.handlebars
packages/generator/generators/monorepo-generator/src/index.ts
packages/generator/generators/monorepo-generator/templates/base-template/package.json.handlebars
packages/generator/generators/mwa-generator/src/index.ts
packages/generator/generators/mwa-generator/templates/base-template/package.json.handlebars

npx @modern-js/create create project use modern current latest version

feat: create new project use modern current latest version

---

.changeset/warm-feet-bow.md
packages/generator/generator-plugin/src/context/new.ts

Fix event warning

---

.changeset/fresh-dolphins-promise.md
local-test-project/pnpm-workspace.yaml
packages/solutions/app-tools/src/analyze/index.ts
packages/solutions/app-tools/src/commands/start.ts
packages/toolkit/utils/src/analyzeProject.ts

fix: check apiOnly error while has source.entriesDir

---

.changeset/swift-onions-kick.md
packages/cli/plugin-changeset/CHANGELOG.md
packages/cli/plugin-changeset/package.json
packages/cli/plugin-changeset/src/commands/release.ts

Hotfix v1.16.0 changeset monorepo

---

.github/workflows/cypress-test.yml

cypress test support node14

---

packages/builder/webpack-builder/src/core/createPluginStore.ts
packages/builder/webpack-builder/src/types/plugin.ts
packages/builder/webpack-builder/tests/core/createPluginStore.test.ts

fix(web-builder): return plugins getter in createPluginStore

---

.changeset/dirty-shirts-melt.md
.changeset/selfish-scissors-work.md
packages/runtime/plugin-runtime/src/cli/index.ts
packages/toolkit/utils/src/runtimeExports.ts

feat: adjust runtime export

---

.changeset/shy-chairs-exercise.md
packages/runtime/plugin-runtime/src/common.ts
packages/runtime/plugin-runtime/src/core/app-config.ts
packages/runtime/plugin-runtime/src/core/index.ts
packages/runtime/plugin-runtime/src/core/loader/useLoader.ts
packages/runtime/plugin-runtime/src/index.ts
packages/runtime/plugin-runtime/src/ssr/type.d.ts
packages/runtime/plugin-runtime/src/state/runtime/plugin.tsx

feat: adjust runtime type define position

---

.changeset/empty-boats-search.md
packages/builder/webpack-builder/tests/plugins/__snapshots__/babel.test.ts.snap
packages/cli/babel-preset-app/package.json
packages/cli/babel-preset-app/src/common.ts
packages/cli/babel-preset-app/src/utils.ts
packages/cli/babel-preset-app/tests/utils.test.ts
packages/cli/webpack/package.json
pnpm-lock.yaml

Bump core-js version to support more polyfills, such as `array.prototype.at`

feat(babel-preset-app): bump core-js version to support more polyfills

---

website/docs/apis/app/runtime/model/auto-actions.md
website/docs/apis/app/runtime/model/create-app.md
website/docs/apis/app/runtime/model/create-store.md
website/docs/apis/app/runtime/model/get-store.md
website/docs/apis/app/runtime/model/handle-effect.md
website/docs/apis/app/runtime/model/use-store.md
website/docs/guides/features/model/faq.md
website/docs/guides/features/model/manage-effects.md
website/docs/guides/features/model/redux-integration.md
website/docs/guides/features/model/typescript-best-practice.md
website/docs/guides/features/model/use-model.md

Complement more Reduck guides.

docs: more reduck guides

---

tests/integration/css-modules/fixtures/global-module/src/index.module.css
tests/integration/css-modules/test/index.test.js

Fix an unstable integration test case.

chore: fix integration test of css modules

---

website/docs/apis/app/config/runtime/state.md
website/docs/guides/features/model/manage-effects.md
website/docs/guides/features/model/test-model.md
website/docs/guides/features/model/use-model.md
website/docs/guides/features/modules/test.md
website/docs/guides/tutorials/c10-model/10.4-testing.md
website/docs/start/admin.md

fix: fix website broken links

---

.changeset/tidy-jokes-glow.md
packages/cli/babel-preset-app/src/built-in/babel-plugin-ssr-loader-id.ts

fix: fix auto-generated `useloader` id

---

packages/builder/webpack-builder/src/core/mergeConfig.ts
packages/builder/webpack-builder/src/index.ts
packages/builder/webpack-builder/tests/mergeConfig.test.ts

Add `mergeBuilderConfig` method, this is a helper to merge multiple builder configs.

feat(builder): add mergeBuilderConfig helper

---

.changeset/tidy-jokes-glow.md
pnpm-lock.yaml
tests/integration/webpack-builder/package.json
tests/integration/webpack-builder/scripts/build.ts
tests/integration/webpack-builder/scripts/dev.ts
tests/integration/webpack-builder/scripts/inspect.ts
tests/integration/webpack-builder/scripts/shared.ts
tests/integration/webpack-builder/tsconfig.json
tests/integration/webpack-builder/tsconfig.scripts.json

- 更新 webpack-builder 集测工程，不再依赖 webpack-builder 源码，使其中的代码更接近真实场景下的接入代码。
- 移除了集测工程下的 `tsx`，避免 `tsx` 导致 `@modern-js/server` 中的 babel register 报错的问题。

chore(webpack-builder): update integration test codes

---

website/docs/apis/app/runtime/model/use-model.md

docs: fix `useModel` example

---

website/docs/guides/features/model/quick-start.md

docs: fix reduck quick start code example

---

website/docs/apis/app/config/source/include.md

Improve source.include usage guide.

docs: improve source.include usage guide

---

scripts/check-changeset/src/index.ts

fix: check changeset

---

packages/generator/generator-utils/src/index.ts
packages/generator/generators/upgrade-generator/src/index.ts
packages/toolkit/upgrade/modern.config.js
packages/toolkit/upgrade/package.json

feat: upgrade command add loading status

---

website/docs/apis/app/config/output/template-parameters.md
website/docs/guides/usages/html.md

Improve custom html template guide.

docs: improve custom html template guide

---

.changeset/config.json
packages/builder/plugin-esbuild/package.json
pnpm-lock.yaml
scripts/vitest-config/package.json

fix: utils version

---

.changeset/brown-seas-clap.md
packages/generator/generators/upgrade-generator/package.json
packages/generator/generators/upgrade-generator/src/index.ts

fix: upgrade generator error when not exist dependencies

---

.changeset/strong-brooms-tell.md
packages/generator/generators/upgrade-generator/src/index.ts
packages/generator/new-action/src/monorepo.ts

upgrade 工具支持在 monorepo 中自动升级子项目 Modern.js 相关依赖到最新版本

feat: upgrade support monorepo sub-project

---

jest.config.js
packages/generator/generators/repo-generator/src/index.ts
packages/generator/generators/upgrade-generator/src/index.ts
packages/generator/new-action/src/monorepo.ts

yarn upgrade only can update monorepo root package.json dependencies version.
When you need to upgrade sub-project dependencies, you can run `NoNeedInstall=true lerna exec npx @modern-js/upgrade`.

feat: remove yarn upgrade command

---

.changeset/proud-socks-live.md
packages/toolkit/upgrade/src/locale/zh.ts
website/docs/apis/app/commands/upgrade.md
website/docs/apis/module/commands/upgrade.md
website/docs/apis/monorepo/commands/upgrade.md

feat: upgrade doc

---

.changeset/shiny-jars-run.md
packages/builder/webpack-builder/src/types/config/dev.ts
packages/server/server/src/dev-tools/https/index.ts
packages/server/server/src/index.ts
packages/server/server/src/types.ts
website/docs/apis/app/config/dev/https.md

- export `DevServerHttpsOptions` type
- improve `dev.https` document

feat(server): export DevServerHttpsOptions type, improve doc

---

.changeset/old-moles-melt.md
website/docs/apis/app/config/server/routes.md

feat: add resHeaders docs

---

.changeset/poor-birds-carry.md
packages/generator/generators/upgrade-generator/src/index.ts
packages/generator/generators/upgrade-generator/src/locale/en.ts
packages/generator/generators/upgrade-generator/src/locale/zh.ts

feat: upgrade tools support prompting users to already have the latest version

feat: Optimize the prompt message of the `upgrade` command

---

website/docs/guides/troubleshooting/compile.md

Add faq of tree shaking and babel sourceType.

docs: add faq of tree shaking and babel sourceType

---

packages/cli/core/package.json

feat: upgrade core version

---

.changeset/slimy-berries-tell.md
packages/cli/core/src/config/schema/server.ts
packages/cli/core/src/config/types/index.ts
packages/server/utils/src/common/index.ts
tests/integration/bff-express/modern.config.ts

feat: add compiler option for server

---

.changeset/old-moles-melt.md
packages/builder/plugin-esbuild/package.json
scripts/vitest-config/package.json

fix: fix peerDependencies version for release

---

website/docs/guides/troubleshooting/compile.md
website/docs/guides/troubleshooting/dependencies.md

- add webpack cache faq
- add pnpm peer deps warning faq

docs: add webpack cache faq

---

.gitignore
website/main/docusaurus.config.js

Fix feishu group qrcode, close https://github.com/modern-js-dev/modern.js/issues/1683

docs: fix feishu qrcode

---

.github/workflows/build-main-website.yml

Fix build-main-website action failed.

chore: fix build-main-website action failed

---

.changeset/silver-drinks-kiss.md
packages/cli/core/src/config/types/index.ts
packages/cli/core/src/loadPlugins.ts
packages/cli/core/src/manager.ts
packages/solutions/module-tools-v2/src/config/defineConfig.ts
packages/solutions/module-tools-v2/src/config/normalize.ts
packages/solutions/module-tools-v2/src/config/schema.ts
packages/solutions/module-tools-v2/src/index.ts
packages/solutions/module-tools-v2/src/types/config/index.ts
packages/solutions/module-tools-v2/src/types/utils.ts

add tpe define and schema for config

feat: add type define and schema for config

---

packages/builder/builder-doc/en/config/dev/assetPrefix.md
packages/builder/builder-doc/en/config/output/assetPrefix.md
packages/builder/builder-doc/en/config/output/cleanDistPath.md
packages/builder/builder-doc/en/config/output/disableMinimize.md
packages/builder/builder-doc/en/config/output/disableSourceMap.md
packages/builder/builder-doc/en/config/source/alias.md
packages/builder/builder-doc/en/config/source/moduleScopes.md
packages/builder/builder-doc/en/config/source/preEntry.md
packages/builder/builder-doc/zh/config/dev/assetPrefix.md
packages/builder/builder-doc/zh/config/output/assetPrefix.md
packages/builder/builder-doc/zh/config/output/cleanDistPath.md
packages/builder/builder-doc/zh/config/output/disableMinimize.md
packages/builder/builder-doc/zh/config/output/disableSourceMap.md
packages/builder/builder-doc/zh/config/source/alias.md
packages/builder/builder-doc/zh/config/source/moduleScopes.md
packages/builder/builder-doc/zh/config/source/preEntry.md

add some documents of builder config:
- dev.assetPrefix
- output.assetPrefix
- output.disableMinimize
- output.disableSourcemap
- output.cleanDistPath
- source.alias
- source.moduleScopes
- source.preEntry

docs: add some documents of builder config

---

packages/builder/builder-doc/en/config/dev/hmr.md
packages/builder/builder-doc/en/config/source/resolveExtensionPrefix.md
packages/builder/builder-doc/zh/config/dev/hmr.md
packages/builder/builder-doc/zh/config/source/resolveExtensionPrefix.md
website/builder/src/.vuepress/config.ts

- Add document for `dev.hmr` and `source.resolveExtensionPrefix`
- Rename i18n helpers of document.

docs(builder): add hmr and resolveExtensionPrefix document

---

.changeset/sour-coats-love.md
packages/generator/generators/electron-generator/src/index.ts

chore: update electron template's plugin-electron version

---

packages/solutions/module-tools-v2/modern.config.js

chore: change build config

---

.changeset/tricky-tomatoes-draw.md
packages/server/server/src/dev-tools/dev-middleware/index.ts
packages/server/server/src/types.ts

fix: fix dev server type error

---

.changeset/polite-buttons-fix.md
.changeset/tender-trainers-tickle.md
packages/runtime/plugin-garfish/src/runtime/loadable.tsx
packages/runtime/plugin-garfish/src/runtime/utils/MApp.tsx

fix: fix MApp can not pass props to microapp and fix closure causes loadable invalid

fix: fix MApp can not pass props to microapp and fix closure causes loadable invalid

---

.changeset/rotten-news-dress.md
packages/server/server/src/dev-tools/register/index.ts

fix: ssr bundle should not be compiled by ts-node

---

.changeset/nasty-experts-allow.md
packages/server/server/src/dev-tools/dev-middleware/index.ts
packages/server/server/src/server/dev-server.ts

fix: invoke next() in dev-middleware directly if only api

---

.changeset/little-moons-fix.md
packages/toolkit/plugin/src/manager/sync.ts

Fix incorrect createManager type in TS 4.8.

fix(plugin): incorrect createManager type in TS 4.8

---

packages/builder/builder-doc/en/config/html/appIcon.md
packages/builder/builder-doc/en/config/html/crossorigin.md
packages/builder/builder-doc/en/config/html/disableHtmlFolder.md
packages/builder/builder-doc/zh/config/html/appIcon.md
packages/builder/builder-doc/zh/config/html/crossorigin.md
packages/builder/builder-doc/zh/config/html/disableHtmlFolder.md
website/main/docs/apis/app/config/output/disable-html-folder.md

add document of some html configs:
- html.appIcon
- html.crossorigin
- html.disableHtmlFolder

docs(builder): add document of some html configs

---

packages/builder/builder-doc/en/config/tools/babel.md
packages/builder/builder-doc/zh/config/tools/babel.md

feat: add builder babel doc

---

.changeset/khaki-hounds-juggle.md
packages/generator/generators/electron-generator/templates/init-template/ts/electron.config.js.handlebars
packages/generator/generators/electron-generator/templates/init-template/ts/modern.config.ts.handlebars

chore: electron ts template use electron.config.js

---

packages/builder/builder-doc/en/config/tools/babel.md
packages/builder/builder-doc/en/config/tools/tsChecker.md
packages/builder/builder-doc/en/config/tools/tsLoader.md
packages/builder/builder-doc/zh/config/tools/tsChecker.md
packages/builder/builder-doc/zh/config/tools/tsLoader.md

feat: add tsLoader and tsChecker doc

---

.changeset/empty-birds-itch.md
packages/builder/webpack-builder/package.json
packages/builder/webpack-builder/src/types/config/dev.ts
packages/builder/webpack-builder/src/types/config/tools.ts
packages/cli/core/package.json
packages/cli/core/src/config/types/index.ts
packages/server/server/package.json
packages/server/server/src/index.ts
packages/server/server/src/types.ts
packages/toolkit/types/server/devServer.d.ts
packages/toolkit/types/server/index.d.ts
pnpm-lock.yaml

Fix tools.devServer type missing some properties.
Move `DevServerOptions` to `@modern-js/types`, so it can be shared by `@modern-js/core` and `@modern-js/server`.

fix: tools.devServer type missing some properties

---

.changeset/metal-books-compare.md
packages/server/server/src/dev-tools/dev-middleware/dev-server-plugin.ts
packages/server/server/src/dev-tools/dev-middleware/socket-server.ts
packages/toolkit/types/server/devServer.d.ts

fix: dev server config should be optional

---

.changeset/twelve-taxis-act.md
packages/solutions/module-tools-v2/src/builder/platform.ts
packages/solutions/module-tools-v2/src/constants/colors.ts
packages/solutions/module-tools-v2/src/types/color.ts

feat: add platform build log

---

.changeset/tidy-turtles-scream.md
packages/solutions/module-tools-v2/lib/types.d.ts
packages/solutions/module-tools-v2/src/cli.ts
packages/solutions/module-tools-v2/src/command.ts
packages/solutions/module-tools-v2/src/utils/language.ts
packages/solutions/module-tools-v2/src/utils/valide.ts

feat: add new and upgrade command

---

packages/builder/builder-doc/en/config/output/polyfill.md
packages/builder/builder-doc/en/config/performance/bundleAnalyze.md
packages/builder/builder-doc/en/config/tools/inspector.md
packages/builder/builder-doc/en/config/tools/styledComponents.md
packages/builder/builder-doc/zh/config/output/polyfill.md
packages/builder/builder-doc/zh/config/performance/bundleAnalyze.md
packages/builder/builder-doc/zh/config/tools/inspector.md
packages/builder/builder-doc/zh/config/tools/less.md
packages/builder/builder-doc/zh/config/tools/sass.md
packages/builder/builder-doc/zh/config/tools/styledComponents.md
packages/builder/builder-doc/zh/config/tools/tsChecker.md
packages/builder/builder-doc/zh/config/tools/tsLoader.md

feat: add inspector builder doc

---

packages/builder/builder-doc/en/config/dev/progressBar.md
packages/builder/builder-doc/zh/config/dev/progressBar.md
packages/builder/webpack-builder/src/config/defaults.ts
packages/builder/webpack-builder/src/plugins/progress.ts
packages/builder/webpack-builder/src/types/config/dev.ts
packages/builder/webpack-builder/tests/plugins/progress.test.ts
website/builder/src/.vuepress/styles/index.styl
website/builder/src/en/api/config-dev.md
website/builder/src/zh/api/config-dev.md

- add dev.progressBar config, allow to disable default progress bar.
- fix incorrect anchor position of document

feat(builder): add dev.progressBar config

---

.changeset/popular-poets-work.md
packages/cli/plugin-storybook/src/index.ts
packages/solutions/module-tools-v2/src/dev.ts

feat: change dev menu log

---

packages/builder/builder-doc/en/config/output/legalComments.md
packages/builder/builder-doc/zh/config/output/legalComments.md
packages/builder/plugin-esbuild/src/index.ts
packages/builder/plugin-esbuild/tests/__snapshots__/index.test.ts.snap
packages/builder/plugin-esbuild/tests/index.test.ts
packages/builder/webpack-builder/src/config/defaults.ts
packages/builder/webpack-builder/src/plugins/minimize.ts
packages/builder/webpack-builder/src/types/config/output.ts
packages/builder/webpack-builder/tests/plugins/__snapshots__/minimize.test.ts.snap
packages/builder/webpack-builder/tests/plugins/minimize.test.ts
website/builder/src/en/api/config-dev.md
website/builder/src/en/api/config-html.md
website/builder/src/en/api/config-output.md
website/builder/src/en/api/config-performance.md
website/builder/src/en/api/config-security.md
website/builder/src/en/api/config-source.md
website/builder/src/en/api/config-tools.md
website/builder/src/zh/api/config-dev.md
website/builder/src/zh/api/config-html.md
website/builder/src/zh/api/config-output.md
website/builder/src/zh/api/config-performance.md
website/builder/src/zh/api/config-security.md
website/builder/src/zh/api/config-source.md

Added new `output.legalComments` config, same as esbuild's legalComments option: https://esbuild.github.io/api/#legal-comments

feat(builder): add output.legalComments config

---

packages/solutions/module-tools-v2/src/types/config/index.ts

Next build task

---

packages/builder/builder-doc/en/config/output/assetsRetry.md
packages/builder/builder-doc/en/config/output/svgDefaultExport.md
packages/builder/builder-doc/en/config/performance/chunkSplit.md
packages/builder/builder-doc/zh/config/output/assetsRetry.md
packages/builder/builder-doc/zh/config/output/svgDefaultExport.md
packages/builder/builder-doc/zh/config/performance/chunkSplit.md

feat: add some builder docs

---

.github/workflows/build-builder-website.yml
.github/workflows/build-main-website.yml
.github/workflows/check-changeset.yml
.github/workflows/integration-test-Windows.yml
.github/workflows/integration-test-macOS.yml
.github/workflows/lint-Linux.yml
.github/workflows/reset-prepare.yml
.github/workflows/test-Windows.yml
.github/workflows/test-macOS.yml
.github/workflows/type-check.yml
CONTRIBUTING.md
package.json
packages/generator/generators/upgrade-generator/src/index.ts

feat: lock github workflow pnpm version to v7

---

packages/solutions/module-tools-v2/src/types/config/index.ts

feat: add path config

---

packages/solutions/module-tools-v2/package.json
packages/solutions/module-tools-v2/src/builder/build.ts
packages/solutions/module-tools-v2/src/builder/dts/index.ts
packages/solutions/module-tools-v2/src/builder/dts/rollup.ts
packages/solutions/module-tools-v2/src/builder/index.ts
packages/solutions/module-tools-v2/src/command.ts
packages/solutions/module-tools-v2/src/types/config/index.ts
pnpm-lock.yaml

feat: add runBuildTask

---

.changeset/chilly-hounds-sparkle.md
packages/generator/generator-common/src/common/solution.ts

feat: support custom solution list

---

packages/builder/webpack-builder/package.json

fix: peer dependencies version

---

.changeset/lazy-shrimps-admire.md
packages/generator/generators/upgrade-generator/src/index.ts
packages/runtime/plugin-testing/tests/bff/index.test.ts
pnpm-lock.yaml

- 修复升级工具添加 pnpm 配置添加多份问题
- 修复 pull request workflow 导致 lock 文件回退到 pnpm v6 的问题

feat: update lock file and fix test

---

packages/builder/webpack-builder/src/plugins/define.ts
packages/builder/webpack-builder/tests/plugins/define.test.ts

fix(builder): define plugin will add prefix `process.env` for vars

---

packages/builder/builder-doc/en/config/output/enableCssModuleTSDeclaration.md
packages/builder/builder-doc/en/config/tools/webpack.md
packages/builder/builder-doc/en/config/tools/webpackChain.md
packages/builder/builder-doc/zh/config/output/enableCssModuleTSDeclaration.md
packages/builder/builder-doc/zh/config/tools/webpack.md
packages/builder/builder-doc/zh/config/tools/webpackChain.md

chore: add builder doc

---

.github/workflows/release.yml

reset release workflow action version

feat: reset action version

---

.changeset/change-my-builder.md
packages/builder/builder-doc/en/config/html/templateParameters.md
packages/builder/builder-doc/zh/config/html/templateParameters.md
packages/builder/webpack-builder/src/plugins/html.ts
packages/builder/webpack-builder/src/types/config/html.ts

feat: support templateParameters function

---

packages/builder/webpack-builder/src/shared/utils.ts
packages/builder/webpack-builder/tests/mergeConfig.test.ts

mergeBuilderConfig not effect source params

fix: mergeBuilderConfig not effect source params

---

.github/workflows/check-changeset.yml
.github/workflows/cypress-test.yml
.github/workflows/integration-test-Windows.yml
.github/workflows/integration-test-macOS.yml
.github/workflows/lint-Linux.yml
.github/workflows/test-Windows.yml
.github/workflows/test-macOS.yml
.github/workflows/type-check.yml
packages/solutions/module-tools-v2/tests/normalize-config.test.ts
scripts/skip-docs-change.js

feat: github action workflow add next branch

---

packages/builder/builder-webpack-provider/src/webpackPlugins/AutoSetRootFontSizePlugin.ts
tests/e2e/webpack-builder/basic/plugin.test.ts

fix plugin-rem insert runtime code error and add e2e test case

fix(builder): plugin-rem insert runtime code error

---

packages/builder/builder-doc/en/config/tools/minifyCss.md
packages/builder/builder-doc/en/config/tools/pug.md
packages/builder/builder-doc/en/config/tools/terser.md
packages/builder/builder-doc/zh/config/tools/minifyCss.md
packages/builder/builder-doc/zh/config/tools/pug.md
packages/builder/builder-doc/zh/config/tools/terser.md
packages/builder/builder-webpack-provider/src/plugins/pug.ts
packages/builder/builder-webpack-provider/src/types/config/tools.ts
website/builder/src/en/guide/glossary.md
website/builder/src/zh/guide/glossary.md
website/main/docs/apis/app/config/tools/terser.md

Add document of some configs:
- tools.pug
- tools.terser
- tools.minifyCss
Allow `tools.pug` config to be `true`.

docs(builder): add terser/minifyCss/pug document

---

.changeset/neat-wombats-notice.md
packages/runtime/plugin-runtime/src/ssr/index.node.tsx
packages/runtime/plugin-runtime/src/ssr/serverRender/entry.ts
packages/runtime/plugin-runtime/src/ssr/serverRender/index.ts
packages/runtime/plugin-runtime/src/ssr/serverRender/loadable.ts
packages/runtime/plugin-runtime/src/ssr/serverRender/type.ts
packages/runtime/plugin-runtime/src/ssr/utils.ts
packages/runtime/plugin-runtime/tests/ssr/index.test.ts

ssr runtime plugin accept crossorigin config
The value passed in is determined by the ssr cli plugin, pass through `html.crossorigin` in 2.0

feat: support loadable add crossorigin props

---

.changeset/rare-pants-run.md
packages/cli/plugin-storybook/template/main.tmpl

We disabled the managerWebpack configuration earlier and now allow users to configure it.

feat: use user managerWebpack config

---

packages/server/plugin-express/types.d.ts
packages/server/plugin-koa/types.d.ts
tests/integration/api-service-koa/api/context/index.ts
tests/integration/api-service-koa/api/tests/context.test.ts
tests/integration/bff-express/api/_app.ts
tests/integration/bff-express/src/base/App.tsx

fix: change '/server' to '/express' in test

---

.changeset/change-my-builder.md
.changeset/few-moose-bathe.md

fix: delete unused changeset

---

.changeset/lucky-points-arrive.md
packages/builder/builder-shared/package.json
packages/builder/builder-shared/src/types/provider.ts
packages/builder/builder-webpack-provider/src/core/startDevServer.ts
pnpm-lock.yaml
website/builder/src/en/api/builder-instance.md
website/builder/src/zh/api/builder-instance.md

Allow to close the dev server:
```js
const { server } = await builder.startDevServer();
// Close the Dev Server
await server.close();
```

feat(builder): allow to close dev server

---

.changeset/moody-spies-dream.md
packages/builder/builder-doc/en/config/performance/bundleAnalyze.md
packages/builder/builder-doc/zh/config/performance/bundleAnalyze.md
packages/builder/builder-shared/package.json
packages/builder/builder-webpack-provider/package.json
packages/builder/plugin-node-polyfill/package.json
packages/cli/core/package.json
packages/cli/plugin-bff/package.json
packages/cli/plugin-esbuild/package.json
packages/cli/plugin-less/package.json
packages/cli/plugin-sass/package.json
packages/cli/plugin-storybook/package.json
packages/cli/webpack/package.json
packages/server/server/package.json
packages/toolkit/utils/package.json
pnpm-lock.yaml
scripts/prebundle/package.json
website/builder/package.json
website/main/package.json

- Bump webpack to 5.74.0, unlocked the version because lock version may cause some type conflcts.
- Fix a mistake in bundleAnalyze document.

chore(builder): bump webpack to 5.74.0

---

packages/server/server/src/constants.ts
packages/server/server/src/dev-tools/dev-middleware/socket-server.ts
packages/server/server/tests/dev.test.ts
packages/toolkit/types/server/devServer.d.ts

remove useless devServer options

chore(DevServer): remove useless devServer options

---

.changeset/mighty-starfishes-listen.md
packages/runtime/plugin-runtime/src/ssr/index.node.tsx
packages/runtime/plugin-runtime/src/ssr/index.tsx
packages/runtime/plugin-runtime/src/ssr/serverRender/loadable.ts

fix: ssr config need default value

---

.changeset/lovely-trees-march.md
packages/solutions/app-tools/src/commands/dev.ts

~~fix type error in packages/solutions/app-tools/src/commands/dev.ts#82~~
~~the added type is ref to: https://github.com/webpack/webpack-dev-server/blob/master/lib/options.json#L82~~
remove unused `logging` option which caused type error

fix(app-tools): remove useless logging option

---

packages/builder/builder-doc/en/config/tools/devServer.md
packages/builder/builder-doc/zh/config/tools/devServer.md

docs(devServer): add devServer.proxy

docs(devServer): add devServer.proxy

---

.github/workflows/build-builder-website.yml
.github/workflows/build-main-website.yml
.github/workflows/cypress-test.yml
.github/workflows/integration-test-macOS.yml
.github/workflows/reset-prepare.yml
.github/workflows/test-Windows.yml
.github/workflows/test-macOS.yml
.github/workflows/type-check.yml
packages/builder/builder-doc/zh/config/html/faviconByEntries.md
packages/builder/builder-webpack-provider/src/types/context.ts

- Reduce CI usage, avoid queued CI.
- Using ubuntu instead of macOS because it is cheaper.
Unit Test - Before: 
- 14.x Mac
- 16.x Mac
- 14.x Windows
- 16.x Windows
Unit Test -After: 
- 14.x Mac
- 16.x Windows

chore: reduce CI usage, avoid queued

---

.changeset/weak-points-smash.md
packages/cli/plugin-changeset/src/commands/release.ts
packages/cli/plugin-changeset/src/utils/index.ts
packages/cli/plugin-changeset/src/utils/pnpm.ts
packages/solutions/monorepo-tools/src/features/deploy/index.ts
packages/toolkit/utils/src/index.ts
packages/toolkit/utils/src/version.ts

fix: support monorepo deploy in pnpm 7

---

packages/builder/builder-shared/tests/.eslintrc.js
packages/builder/builder-webpack-provider/package.json
packages/builder/builder-webpack-provider/src/plugins/progress.ts
packages/builder/builder-webpack-provider/src/progress/bar.ts
packages/builder/builder-webpack-provider/src/progress/bus.ts
packages/builder/builder-webpack-provider/src/progress/index.ts
packages/builder/builder-webpack-provider/src/progress/log.ts
packages/builder/builder-webpack-provider/src/progress/type.ts
packages/builder/builder-webpack-provider/src/progress/utils.ts
packages/builder/builder-webpack-provider/src/types/config/dev.ts
packages/builder/builder-webpack-provider/src/webpackPlugins/ProgressPlugin.ts
packages/builder/builder-webpack-provider/tests/plugins/progress.test.ts
packages/builder/builder-webpack-provider/tests/setup.ts
pnpm-lock.yaml

* create a new progress bar based on the progress of webpack reading the file

feat(builder): add new webpack progress bar

---

website/main/docs/guides/tutorials/c01-getting-started/1.2-minimal-mwa.md
website/main/docs/guides/tutorials/c01-getting-started/1.4-enable-ssr.md

docs: add guide details for config file

docs: add guide details for config file

---

packages/builder/builder-shared/package.json
packages/builder/builder-shared/src/createPublicContext.ts
packages/builder/builder-shared/src/index.ts
packages/builder/builder-shared/src/utils.ts
packages/builder/builder-webpack-provider/src/core/initConfigs.ts
packages/builder/builder-webpack-provider/tests/core/initConfigs.test.ts
pnpm-lock.yaml

feat(builder): protect final config

---

packages/runtime/plugin-router-legacy/lib/types.d.ts
packages/runtime/plugin-router-legacy/package.json
packages/runtime/plugin-router-legacy/tsconfig.json
packages/runtime/plugin-router-legacy/type.d.ts
packages/runtime/plugin-runtime/lib/types.d.ts

fix(next): runtime router types

---

.changeset/chilly-gifts-worry.md
packages/builder/builder-doc/en/config/performance/profile.md
packages/builder/builder-doc/zh/config/performance/profile.md
packages/builder/builder-webpack-provider/src/plugins/performance.ts
packages/builder/builder-webpack-provider/src/shared/plugin.ts
packages/builder/builder-webpack-provider/src/types/config/performance.ts
packages/builder/builder-webpack-provider/tests/plugins/performance.test.ts
website/builder/src/en/api/config-performance.md
website/builder/src/zh/api/config-performance.md

feat: support webpack profile configuration

feat: support webpack profile configuration

---

.changeset/clever-jokes-smile.md
packages/builder/builder-doc/en/config/output/disableInlineRuntimeChunk.md
packages/builder/builder-doc/en/config/output/enableInlineScripts.md
packages/builder/builder-doc/en/config/output/enableInlineStyles.md
packages/builder/builder-doc/zh/config/output/disableInlineRuntimeChunk.md
packages/builder/builder-doc/zh/config/output/enableInlineScripts.md
packages/builder/builder-doc/zh/config/output/enableInlineStyles.md

Add docs for `disableInlineRuntimeChunk`, `enableInlineScripts`, `enableInlineStyles`.

docs(builder): add docs for inline chunks

---

.changeset/real-radios-sing.md
packages/toolkit/utils/src/logger.ts
packages/toolkit/utils/tests/logger.test.ts

Fix failed to call logger.success method.

fix(utils): failed to call logger.success method

---

.changeset/chilled-maps-cry.md
packages/server/plugin-express/types.d.ts
packages/server/plugin-koa/package.json
packages/server/plugin-koa/types.d.ts
pnpm-lock.yaml

fix: compat hook in /server namespace

---

.changeset/witty-forks-develop.md
packages/solutions/module-tools-v2/src/builder/build.ts
packages/solutions/module-tools-v2/src/builder/clear.ts
packages/solutions/module-tools-v2/src/builder/dts/tsc.ts
packages/solutions/module-tools-v2/src/builder/index.ts
packages/solutions/module-tools-v2/src/constants/dts.ts
packages/solutions/module-tools-v2/src/constants/file.ts
packages/solutions/module-tools-v2/src/utils/dts.ts
packages/solutions/module-tools-v2/src/utils/tspaths-transform.ts
packages/solutions/module-tools-v2/todo.md

feat: add dts alias logic

---

.github/workflows/release.yml

feat: support next branch release

---

.changeset/flat-lamps-draw.md
packages/solutions/module-tools-v2/package.json
packages/solutions/module-tools-v2/src/builder/build.ts
packages/solutions/module-tools-v2/src/builder/dts/rollup.ts
packages/solutions/module-tools-v2/src/builder/dts/tsc.ts
packages/solutions/module-tools-v2/src/builder/index.ts
packages/solutions/module-tools-v2/src/constants/log.ts
packages/solutions/module-tools-v2/src/utils/libuild-plugins.ts

feat: add log logic

---

.changeset/pink-wasps-joke.md
packages/toolkit/plugin/src/workflow/sync.ts
packages/toolkit/plugin/tests/workflow.test.ts

Fix the return type of `Workflow` in `@modern-js/plugin`.

fix(plugin): fix return type of workflow

---

.changeset/cyan-boats-impress.md
packages/generator/generator-utils/src/index.ts

fix: new action

---

packages/generator/generator-plugin/src/context/index.ts
packages/generator/generators/monorepo-generator/src/index.ts
packages/generator/generators/mwa-generator/src/index.ts

fix: generator input

---

.changeset/two-llamas-cheer.md
packages/builder/builder-webpack-provider/src/webpackPlugins/ProgressPlugin/helpers/bus.ts

Fix failed to write stderr messages when using progress plugin.
```js
console.error('some error'); // this message is not displayed in the shell
```

fix(builder): failed to write stderr messages

---

.changeset/nine-glasses-divide.md
packages/solutions/module-tools-v2/src/builder/build.ts
packages/solutions/module-tools-v2/src/types/config/index.ts
packages/solutions/module-tools-v2/src/utils/builder.ts
packages/solutions/module-tools-v2/src/utils/libuild-plugins.ts

feat: add skipDeps config

---

packages/builder/builder-doc/en/config/tools/cssExtract.md
packages/builder/builder-doc/zh/config/tools/cssExtract.md
packages/builder/builder-webpack-provider/src/plugins/css.ts
packages/builder/builder-webpack-provider/src/plugins/output.ts
packages/builder/builder-webpack-provider/src/types/config/tools.ts
packages/builder/builder-webpack-provider/tests/plugins/css.test.ts

- Support disable mini-css-extract-plugin by setting `tools.cssExtract: false`

feat(builder): support disable css extract plugin

---

package.json
packages/builder/builder-shared/package.json
packages/builder/builder-webpack-provider/package.json
packages/builder/builder/package.json
packages/builder/plugin-esbuild/package.json
packages/builder/plugin-node-polyfill/package.json
pnpm-lock.yaml
scripts/vitest-config/package.json

build: remove `vitest` & `@vitest/ui` from sub-packages

---

packages/builder/builder-doc/en/config/source/globalVars.md
packages/builder/builder-doc/zh/config/source/globalVars.md

docs(builder): fix wrong describes of `globalVars`

---

packages/cli/plugin-storybook/package.json
packages/cli/plugin-storybook/src/runtime-addon/components/modern.tsx
packages/generator/generators/entry-generator/templates/router/App.handlebars
packages/runtime/plugin-runtime/src/router/cli/index.ts
packages/runtime/plugin-runtime/src/state/runtime/plugin.tsx
pnpm-lock.yaml

fix: router path and storybook

---

packages/builder/builder-doc/en/config/tools/webpackChain.md
packages/builder/builder-doc/zh/config/tools/webpackChain.md

chore: update webpack builder docs

---

packages/generator/generator-cases/tests/index.test.ts
packages/generator/generator-common/src/locale/en.ts
packages/generator/generator-common/src/locale/zh.ts
packages/generator/generator-common/src/newAction/common/index.ts
packages/generator/generator-common/src/newAction/mwa/index.ts
packages/generator/generators/entry-generator/src/index.ts
packages/generator/generators/entry-generator/templates/main.handlebars
packages/generator/generators/mwa-generator/templates/ts-template/src/modern-app-env.d.ts.handlebars
packages/generator/generators/router-legacy-generator/.eslintrc.js
packages/generator/generators/router-legacy-generator/LICENSE
packages/generator/generators/router-legacy-generator/README.md
packages/generator/generators/router-legacy-generator/jest.config.js
packages/generator/generators/router-legacy-generator/modern.config.js
packages/generator/generators/router-legacy-generator/package.json
packages/generator/generators/router-legacy-generator/src/index.ts
packages/generator/generators/router-legacy-generator/src/locale/en.ts
packages/generator/generators/router-legacy-generator/src/locale/index.ts
packages/generator/generators/router-legacy-generator/src/locale/zh.ts
packages/generator/generators/router-legacy-generator/tsconfig.json
packages/generator/new-action/src/mwa.ts
packages/generator/new-action/src/utils/index.ts
pnpm-lock.yaml

feat: add refactor router generator

---

.changeset/nine-mugs-obey.md
packages/cli/core/src/config/types/index.ts

Fix dev.https missing object type, close https://github.com/modern-js-dev/modern.js/issues/1913

fix(core): dev.https missing object type

---

packages/builder/builder-webpack-provider/package.json

build(builder): export `package.json`

---

packages/runtime/plugin-runtime/package.json

feat: add runtime-router export

---

.changeset/thick-walls-grow.md
packages/runtime/plugin-runtime/src/ssr/index.tsx
packages/runtime/plugin-runtime/src/ssr/serverRender/renderToStream/loadable.ts

fix: remove overmuch '@modernjs/utils' dependency import in ssr runtime

fix: remove overmuch '@modernjs/utils' dependency import in ssr runtime

---

packages/builder/builder-doc/en/config/html/templateParametersByEntries.md
packages/builder/builder-doc/zh/config/html/templateParametersByEntries.md
packages/builder/builder-webpack-provider/src/core/startDevServer.ts

dev.https enable in startDevServer

fix(builder): dev.https enable in startDevServer

---

tests/integration/mwa-app/src/modern-app-env.d.ts
tests/integration/ssg/test/index.test.js

fix: fix integration test

---

.changeset/cool-lemons-mix.md
packages/runtime/plugin-runtime/src/ssr/prefetch.tsx
packages/runtime/plugin-runtime/src/ssr/serverRender/entry.ts
packages/runtime/plugin-runtime/src/ssr/serverRender/loadable.ts
packages/runtime/plugin-runtime/src/ssr/serverRender/template.ts
packages/runtime/plugin-runtime/src/ssr/serverRender/type.ts
packages/runtime/plugin-runtime/src/ssr/type.d.ts
packages/server/plugin-koa/src/plugin.ts
packages/server/prod-server/src/libs/render/index.ts
packages/server/prod-server/src/libs/render/ssr.ts
packages/server/server/src/server/dev-server.ts
packages/toolkit/types/server/context.d.ts

feat: remove node internal package which import by ssr runtime

---

.changeset/old-zebras-design.md
packages/runtime/plugin-runtime/src/ssr/index.node.tsx

fix: miss ssr export in node

---

.changeset/cool-lemons-mix.md
.changeset/late-ghosts-grin.md
.changeset/nine-mugs-obey.md
.changeset/purple-suns-beam.md
.changeset/swift-teachers-exercise.md
packages/builder/builder-doc/en/config/html/templateParametersByEntries.md
packages/builder/builder-doc/en/config/tools/webpackChain.md
packages/builder/builder-doc/zh/config/html/templateParametersByEntries.md
packages/builder/builder-doc/zh/config/tools/webpackChain.md
packages/builder/builder-webpack-provider/src/core/startDevServer.ts
packages/cli/core/package.json
packages/cli/core/src/config/types/index.ts
packages/cli/plugin-storybook/src/features/utils/webpackConfig.ts
packages/cli/webpack/src/config/base.ts
packages/runtime/plugin-runtime/src/ssr/prefetch.tsx
packages/runtime/plugin-runtime/src/ssr/serverRender/renderToStream/loadable.ts
packages/runtime/plugin-runtime/src/ssr/serverRender/renderToString/entry.ts
packages/runtime/plugin-runtime/src/ssr/serverRender/renderToString/loadable.ts
packages/runtime/plugin-runtime/src/ssr/serverRender/renderToString/template.ts
packages/runtime/plugin-runtime/src/ssr/serverRender/renderToString/type.ts
packages/runtime/plugin-runtime/src/ssr/type.d.ts
packages/server/prod-server/src/libs/render/index.ts
packages/server/prod-server/src/libs/render/ssr.ts
packages/server/prod-server/src/server/modern-server.ts
packages/server/server/src/server/dev-server.ts
packages/toolkit/types/server/context.d.ts
pnpm-lock.yaml

chore: sync main

---

.changeset/clever-taxis-protect.md
packages/builder/plugin-swc/.npmignore
packages/builder/plugin-swc/package.json
packages/builder/plugin-swc/src/config.ts
packages/builder/plugin-swc/src/index.ts
packages/builder/plugin-swc/src/loader.ts
packages/builder/plugin-swc/src/plugin.ts
packages/builder/plugin-swc/tests/__snapshots__/index.test.ts.snap
packages/builder/plugin-swc/tests/__snapshots__/plugin.test.ts.snap
packages/builder/plugin-swc/tests/plugin.test.ts
pnpm-lock.yaml
tests/integration/webpack-builder/package.json
tests/integration/webpack-builder/scripts/shared.ts

- Fix failed to remove babel-loader, `module.rule(xxx).delete` should be `module.rules.delete(xxx)`
- Add default value of browserslist.
- Rename `SwcPlugin` to `PluginSwc`, consistent with other build plugins.

fix(plugin-swc): failed to remove babel-loader

---

.github/workflows/test-macOS.yml

fix: codecover branch

---

packages/generator/generators/router-legacy-generator/src/locale/en.ts
packages/generator/generators/router-legacy-generator/src/locale/zh.ts
packages/runtime/plugin-router-legacy/.npmignore
packages/runtime/plugin-router-legacy/package.json
packages/runtime/plugin-router-legacy/src/cli/index.ts
packages/runtime/plugin-router-legacy/types/index.d.ts
packages/runtime/plugin-runtime/package.json
packages/runtime/plugin-runtime/src/router/cli/index.ts
packages/runtime/plugin-runtime/types/router.d.ts

Fix router path

---

packages/runtime/plugin-router-legacy/src/cli/index.ts
packages/runtime/plugin-runtime/src/router/cli/index.ts

fix: router name

---

.changeset/orange-lamps-watch.md
packages/runtime/plugin-router-legacy/src/cli/index.ts
packages/runtime/plugin-runtime/package.json
packages/runtime/plugin-runtime/src/router/cli/index.ts
packages/runtime/plugin-runtime/src/router/runtime/index.ts
packages/runtime/plugin-runtime/src/router/runtime/plugin.node.tsx
packages/runtime/plugin-runtime/src/router/runtime/plugin.tsx
packages/runtime/plugin-runtime/src/router/runtime/types.ts
packages/runtime/plugin-runtime/src/router/runtime/utils.tsx
packages/runtime/plugin-runtime/src/ssr/cli/index.ts
packages/runtime/plugin-runtime/src/ssr/serverRender/renderToStream/index.ts
packages/runtime/plugin-runtime/tests/router/router.test.tsx
packages/solutions/app-tools/src/analyze/getBundleEntry.ts
pnpm-lock.yaml

Refactor router with react-router 6.4.

feat: refactor router with react-router 6.4

---

.changeset/nice-tools-bow.md
packages/generator/generators/entry-generator/templates/main.css
packages/generator/generators/entry-generator/templates/main.handlebars

fix: entry generator template

---

.changeset/serious-pants-beam.md
packages/server/prod-server/src/libs/render/ssr.ts
packages/toolkit/types/server/context.d.ts

Add `req` and `res` to SSR server context.

feat(server): add `req` and `res` to SSR context

---

.pnpmfile.cjs
packages/cli/plugin-storybook/package.json
packages/generator/generators/module-generator/src/index.ts
packages/generator/generators/mwa-generator/src/index.ts
packages/runtime/plugin-runtime/package.json
pnpm-lock.yaml
tests/e2e/webpack-builder/css-modules/package.json
tests/e2e/webpack-builder/externals/package.json
tests/e2e/webpack-builder/ignore-css/package.json
tests/e2e/webpack-builder/inspect-config/package.json

fix: generator and test's react version

---

.changeset/slimy-spiders-burn.md
packages/runtime/plugin-garfish/src/runtime/loadable.tsx

fix(garfish): remove useless mount check ref

fix(garfish): remove useless mount check ref

---

.github/workflows/build-builder-website.yml

Disable build-builder-website action in main branch, only build the document in next branch.

chore: disable build-builder-website action in main branch

---

.pnpmfile.cjs
pnpm-lock.yaml

Fix failed to build builder website by adding correct peer dependencies to `vue-server-renderer`

docs: fix failed to build builder website

---

website/main/blog/2022-11.01-release.md
website/main/docs/components/command-tip.md

feat: update doc(9~10)
